### ISSUE TITLE
How does this apply to ds460c shelves?

### ISSUE THREAD

**Issue by rikv-1** [NetAppDocs/ontap#1001]
### Page URL

https://docs.netapp.com/us-en/ontap/disks-aggregates/manual-assign-ownership-partitioned-disks-task.html

### Page title

Manually assign ownership of partitioned disks overview

### Summary

I have the impression that the current documentation applies to shelves with 24 drives, not to the 60 drive ds460c that has 5 drawers with 12 drives each.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
@rikv-1 , we've confirmed that your impression is correct. We'll be working on updating this documentation. If you are a NetApp team member, please let me know and I'll add you to our internal tracking system for this update.

**Comment by netapp-aherbin** [comment]
Move this to Jira for internal tracking.  Added Rik as a watcher to the issue: ONTAPDOC 1681.
