### ISSUE TITLE
Missing S3 actions

### ISSUE THREAD

**Issue by johnlantz** [NetAppDocs/ontap#1002]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-config/ontap-s3-supported-actions-reference.html

### Page title

ONTAP S3 supported actions

### Summary

My understanding is that the following are supported as well:

ListBucketVersioning (9.11.1)
ListObjectVersions (9.11.1)
GetBucketLocation (9.10.1)

Hope this helps,

John

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Thanks @johnlantz !
Maria, let's publish this update at the nearest opportunity.
Ed

**Comment by netapp-mdavidson** [comment]
Added these supported actions to the page - closing out.
