### ISSUE TITLE
Page Change Request

### ISSUE THREAD

**Issue by csa72** [NetAppDocs/ontap#1003]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

### Page title

What version of ONTAP can I upgrade to?

### Summary

The right hand column for ONTAP 9.8 upgrade paths the "Attention Metrocluster Configurations:" text should not just be for ONTAP 9.10.1, it should also be for all newer versions of ONTAP.
It can also be noted that ONTAP 9.8P12 and newer P releases are not affected by the upgrade issues and do not require the ONTAP 9.9.1 workaround.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Here is the BOL:  [https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1455547]

If the issue is correct, the BOL needs to also be updated.

**Comment by netapp-aherbin** [comment]
@csa72 can you provide more details regarding your request?  The BOL you referenced specifies 9.8 to 9.10.1.  
Are you internal to NetApp? If so can you send me your userid so we can discuss further over email?

**Comment by netapp-aherbin** [comment]
Thanks for the discussion.  Updated text for 9.10 or later.
