### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ace-en** [NetAppDocs/ontap#1005]
### Page URL

https://docs.netapp.com/us-en/ontap/system-admin/commands-manage-feature-licenses-reference.html

### Page title

Commands for managing licenses

### Summary

Could we have some examples of how to add licenses. The command is obvious but it is not intuitive how to upload the NLF file. A link to the KB or section on how to download the NLF would also be very helpful.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thank you for the feedback. The page has been updated with several examples and with additional links to more information at the end of the topic.
