### ISSUE TITLE
Missing net int migrate-all and -option allow-version-mismatch required for 9.7, 9.8, 9.9.1 upgrades

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/ontap#1008]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/task_updating_a_four_or_eight_node_mcc.html?q=tiebreaker#updating-the-second-dr-pair-in-a-metrocluster-dr-group

### Page title

Manual nondisruptive upgrade of a four- or eight-node MetroCluster configuration using the CLI

### Summary

#1 - Before performing a storage failover takeover, the command 'net int migrate-all -node <node to be upgraded>' should be run to move the LIFs to the partner.  This is step #9 on the non-metro cluster manual upgrade guide
https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_nondisruptive_manual_cli.html#updating-the-first-node-in-an-ha-pair

#2 - When performing the takeover on the 2nd DR Pair in a metrocluster, the option:
-option allow-version-mismatch
is required for all new Ontap versions from at least 9.7 - 9.12.1, and possibly 9.3 / 9.5 as well.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@jhubert-netapp I've add step 1 as outlined.  In #2 the  allow-version-mismatch option is already there and noted: The allow-version-mismatch option is not required for upgrades from ONTAP 9.0 to ONTAP 9.1 or for any patch upgrades.  

Any further comment?

**Comment by netapp-aherbin** [comment]
@jhubert-netapp if there are further comments or questions feel free to reopen this issue.  Thanks!
