### ISSUE TITLE
Service policies for external key managers

### ISSUE THREAD

**Issue by joecaruso** [NetAppDocs/ontap#1014]
### Page URL

https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html

### Page title

LIFs and service policies in ONTAP 9.6 and later

### Summary

There currently isn't any documentation for how KMIP/external key manager traffic is handled with service policies.  There isn't a specific service policy that handles that currently, so it should be documented which services are required to pass KMIP traffic properly. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Discussing with engineering

**Comment by netapp-barbe** [comment]
The decision is to make the statement generic to cover any applications or features that are not bound by specific service policies. The statement is: "Features that are not bound to a specific service will use a system-defined behavior to select LIFs for outbound connections.

**Comment by netapp-barbe** [comment]
Documentation update published: https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html
