### ISSUE TITLE
Orphan page

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#1015]
### Page URL

https://docs.netapp.com/us-en/ontap/flexgroup/aggregate-space-requirements-concept.html

### Page title

Guidelines for aggregate space when provisioning a FlexGroup volume

### Summary

This page doesn't show up in the sidebar. I believe it should be removed. It looks like the contents of the page match what's under "About this task" on the "Create a FlexGroup volume" page:

https://docs.netapp.com/us-en/ontap/flexgroup/create-task.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Also, this page is linked to from the "Create a FlexGroup volume" page so that link should be removed.

**Comment by netapp-lenida** [comment]
You're correct, Ben. I'll remove the topic.

**Comment by netapp-lenida** [comment]
This topic has been removed.
