### ISSUE TITLE
Adding ONTAP S3

### ISSUE THREAD

**Issue by MikePalicNTAP** [NetAppDocs/ontap#1019]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-concept.html

### Page title

About SnapMirror SVM replication

### Summary

Just to add clarification to this matrix,  can we add ONTAP S3 along with the other protocals?   

Thank you. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for the suggestion. The topic has been updated to include ONTAP S3 as not supported with SVM DR.
