### ISSUE TITLE
Remove Related Infromation Links 

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#1020]
### Page URL

https://docs.netapp.com/us-en/ontap/antivirus/index.html

### Page title

Antivirus configuration overview

### Summary

Please remove the related information links on this page and redirect users to this Page within the docs 'https://docs.netapp.com/us-en/ontap/antivirus/vscan-partner-solutions.html' for more information

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
The  link has been updated.
