### ISSUE TITLE
FabricPool with SnapLock Enterprise is only possible via fepvr

### ISSUE THREAD

**Issue by johnlantz** [NetAppDocs/ontap#1023]
### Page URL

https://docs.netapp.com/us-en/ontap/fabricpool/requirements-concept.html

### Page title

Considerations and requirements for using FabricPool

### Summary

You must be running ONTAP 9.8 or later for the following FabricPool functionality:
...
FabricPool with SnapLock Enterprise
...

This became technically possible as of 9.8 … but it requires fpvr approval and and issuing a secret key to make it work. 

Please consider removing this bullet point, or updating it with a note along the lines of:

"FabricPool with SnapLock Enterprise requires a Feature Product Variance Request (FPVR). To create an FPVR, please contact your sales team."

Thanks,

John

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
The updates have been completed.
