### ISSUE TITLE
ASA can be up to 12-node clusters - not just 2-node, plus TR-4515 is replaced by TR-4968

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#1024]
### Page URL

https://docs.netapp.com/us-en/ontap/asa/overview.html

### Page title

All SAN Array software configuration overview

### Summary

This sentence needs an update, given that you can have up to 12 ASA nodes in a cluster.

_The ASA platforms are available in two-node switched or switchless clusters, can be configured for FC or iSCSI, and use symmetric active-active for multipathing._

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by andris-ntap** [comment]
Also, the TR-4515 link is broken.

[NetApp Technical Report 4515: ONTAP AFF All SAN Array Systems](http://www.netapp.com/us/media/tr-4515.pdf)

This looks like a www.netapp.com content/link error, though...

**Comment by netapp-aherbin** [comment]
@andris-ntap I've added a table to the topic that lists protocol and max cluster support.  I've also updated the TR link and searched for other references in the ONTAP library.
