### ISSUE TITLE
Terminology updates

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#1028]
### Page URL

https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html

### Page title

SnapMirror Cloud backups to object storage

### Summary

Please update the following terms:

- "BlueXP and Cloud Backup" to "BlueXP backup and recovery"
- "AWS S3" to "Amazon S3"
- "Google Cloud Storage Platform" to "Google Cloud Storage"

Also "StoragGRID" should be "StorageGRID"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
@netapp-lenida , can you do a global search across ontap for other instances of these terms as well?
@netapp-aherbin, FYI
