### ISSUE TITLE
Flexcache Support for NFSv4 - source requirements

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/ontap#1029]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

### Page title

Supported and unsupported features for FlexCache volumes

### Summary

Hi,

We got this info from engineering on support case #2009628388:

"In order to access cache volume using NFSv4.x protocol, both origin and cache clusters must be at least the ONTAP 9.10.1 version. The original and flexcached cluster can be a different ONTAP version. Both should be 9.10.1 and later versions, like the original 9.10.1, flexcached 9.11.1"

In the docs, no minimum version is mentioned on the source side for NFSv4.

Thx
Holger

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
The topic has been updated.
