### ISSUE TITLE
Review "Your ANDU upgrade path is…" column and make changes as required.

### ISSUE THREAD

**Issue by raju-aravind** [NetAppDocs/ontap#1030]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

### Page title

What version of ONTAP can I upgrade to?

### Summary

From the examples below, I would like to confirm the correct upgrade paths. 
Please correct the document if the provided path is incorrect where ever applicable.

Example 1. 
Upgrade path from 9.7 to 9.13 is multi-stage
9.7 → 9.8 (direct)
**9.8 → 9.13.1 (direct)**

If the current release is ONTAP 9.8, as per the table the upgrade path from 9.8 to 9.13.1 is **direct multi hop (requires images for 9.12.1 & 9.13.1)**

This could be interpretated as **Direct**, however our understanding is that upgrade from 9.8 to 9.13.1 is **direct multi hop.****

Example 2:
upgrade path from 9.2 to 9.11 is multi-stage
9.2 → 9.3
9.3 → 9.7 (direct multi-hop, requires images for 9.5 & 9.7)
**9.7 → 9.9.1 (direct multi-hop, requires images for 9.8 & 9.9.1)**
9.9.1 → 9.11.1

If the current release is ONTAP 9.7, as per the table the upgrade path from 9.7 to 9.9.1 is **direct**

This could be interpretated as **Direct multi-hop**, however our understanding is that upgrade from 9.7 to 9.9.1 is **direct****

Example 3:
upgrade path from 9.2 to 9.6 is multi-stage
9.2 → 9.3
9.3 → 9.6 (direct multi-hop, requires images for 9.5 & 9.6)

If the current release is ONTAP 9.3, as per the table the upgrade path from 9.3 to 9.6 is **multi-stage**
9.3 → 9.5
9.5 → 9.6

This could be interpretated as **Direct multi-hop**, however our understanding is that upgrade from 9.3 to 9.6 is **multi-stage****

Example 4:
upgrade path from 9.1 to 9.12 is multi-stage
9.1 → 9.3
9.3 → 9.7 (direct multi-hop, requires images for 9.5 & 9.7)
**9.7 → 9.12.1 (direct multi-hop, requires images for 9.8 & 9.12.1)**

If the current release is ONTAP 9.7, as per the table the upgrade path from 9.7 to 9.12 is **multi-stage**
9.7 → 9.8
9.8 → 9.12.1

This could be interpretated as **Direct multi-hop**, however our understanding is that upgrade from 9.7 to 9.12.1 is **multi-stage****

Please update the document with correct upgrade path that is consistent across all section.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you for pointing this out.  I'm verifying these paths with our engineering team.  Update forthcoming.

**Comment by netapp-aherbin** [comment]
We've corrected the inconsistencies.  Thank you for pointing these out.  Updates as described in your comments.
