### ISSUE TITLE
PDF Collections?

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#1036]
### Page URL

https://docs.netapp.com/us-en/ontap/index.html

### Page title

ONTAP 9 Documentation

### Summary

The option to select a collection of PDF's isn't working for this page. The only functional option seems to be downloading a 2300 page PDF. The problem appears to be widespread, affecting other documentation pages as well.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @jfsinmsp . We are aware of this. There is a separate issue reporting the same problem, and the tools team is working on a solution https://github.com/NetAppDocs/ontap/issues/1009

FYI @ntap-bmegan

**Comment by netapp-ahibbard** [comment]
Thanks Megan. @jfsinmsp  - this issue has been resolved.
