### ISSUE TITLE
Have to reverse the order of the commands.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#1039]
### Page URL

https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-self-encrypting-disks-keys-not-available-task.html

### Page title

Return a FIPS drive or SED to service when authentication keys are lost

### Summary

![image](https://github.com/NetAppDocs/ontap/assets/68621663/b829fb98-633f-4279-a336-106abba64360)

The description I attached the command must reverse the order of commands to be executed.

First, unfail.
Second, disk assign

Example;
SR-A400-01::*> storage disk assign -owner SR-A400-01-01 -disk 1.5.17

Error: command failed: Failed to assign disks. Reason: Assign request failed
       for disk 1.5.17. Reason:Disk is in broken pool.

SR-A400-01::*> storage disk unfail -spare true -disk 1.5.17

Warning: Failed disk "1.5.17" might have aggregate labels and file system data
         present. Releasing this disk as a spare disk will lead to permanent
         loss of file system data that might be on this disk, and it might
         prevent recovery of a failed aggregate. Are you sure you want to
         continue with disk unfail? {y|n}: y

SR-A400-01::*> disk assign -owner SR-A400-01-01 -disk 1.5.17

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @kanitani. We've updated the document
