### ISSUE TITLE
Update SM-C license page for ONTAP One license model

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#1041]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/install-snapmirror-cloud-license-task.html

### Page title

Install a SnapMirror Cloud license

### Summary

The license for SM-C is not included with ONTAP One. This page should reflect that licensing model as the license would already be installed for new clusters and will be installed as part of the ONTAP One upgrade to older clusters.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention, Tony. I'm going to close this issue, but I amcontinuing to track it internally in Jira as part of the overall licensing updates I'm making now.

**Comment by tansley-netapp** [comment]
> Thanks for bringing this to our attention, Tony. I'm going to close this issue, but I amcontinuing to track it internally in Jira as part of the overall licensing updates I'm making now.

I just realized there was a typo in my original email...

"The license for SM-C is not included with ONTAP One. " should read "The license for SM-C is NOW included with ONTAP One. "

Just want to be clear.

Thanks for the update Lenida!
