### ISSUE TITLE
ARP: Unsupported system configurations

### ISSUE THREAD

**Issue by seijitanabe** [NetAppDocs/ontap#1043]
### Page URL

https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html

### Page title

Autonomous Ransomware Protection use cases and considerations

### Summary

The doc lists "VMDKs on NFS" as unsupported system configurations of ARP, however this can be misleading.
Actually, if VMDKs itself were encrypted by intrusions like EASiArgs and file extentions were changed, then ONTAP could potentially detect that. 
But if the files inside the VMDK are encrypted at the OS layer, ARP would not be able to detect that.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @seijitanabe . The documentation has been updated to help clarify ARP support with VMDKs
