### ISSUE TITLE
Please replace old TR-4515 link with link to TR-4968

### ISSUE THREAD

**Issue by liamp-sys** [NetAppDocs/ontap#1051]
### Page URL

https://docs.netapp.com/us-en/ontap/asa/overview.html

### Page title

All SAN Array software configuration overview

### Summary

The link and description "[NetApp Technical Report 4515: ONTAP AFF All SAN Array Systems](http://www.netapp.com/us/media/tr-4515.pdf)" is outdated.
Please replace with https://www.netapp.com/pdf.html?item=/media/85671-tr-4968.pdf "NetApp All-SAN Array
Data Availability and Integrity".

Thank you!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @liamp-sys . The documentation has been updated
