### ISSUE TITLE
Needs new NFS v4.2 features added

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/ontap#1052]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html

### Page title

ONTAP support for NFSv4.2

### Summary

ONTAP now supports Sparse Files and Space Reservations, which themselves include several sub-commands.

We need to add these to the supported capabilities.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Chance, thanks as always for your help here. We're reviewing...

**Comment by netapp-ehoffman** [comment]
@netapp-aherbin Please update topic in question as shown in https://netapp-my.sharepoint.com/:w:/r/personal/ehoffman_netapp_com/Documents/[NFSv2support.eh.docx](https://netapp-my.sharepoint.com/:w:/r/personal/ehoffman_netapp_com/Documents/NFSv2support.eh.docx?
d=wfd7d314dd107480282eec1440336b250&csf=1&web=1&e=1Qecd1)?d=wfd7d314dd107480282eec1440336b250&csf=1&web=1&e=1Qecd1

**Comment by netapp-ehoffman** [comment]
Further updates may be required, so please reassign to me after initial updates

**Comment by netapp-aherbin** [comment]
Initial updates complete.

**Comment by netapp-aherbin** [comment]
No further updates at this time.  Per Ed, closing.
