### ISSUE TITLE
impact to IO during upgrade

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap#1054]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/index.html

### Page title

Upgrade ONTAP overview

### Summary

I can't seem to find it but is there a section in the Upgrade documentation that can talk about the I/O impact to an upgrade.   As well as discuss how it impacts particular I/O based on the protocols used?  (ex. CIFS, ISCSI, etc..)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Information needed was found in [Considerations for session-oriented protcols|https://docs.netapp.com/us-en/ontap/upgrade/concept_considerations_for_session_oriented_protocols.html].  Using Eric's feedback to improve SEO on this topic.  Tracking internally in Jira 1275.  Closing this issue.
