### ISSUE TITLE
SMB ODX (copy offload) is supported at the origin

### ISSUE THREAD

**Issue by elliottecton** [NetAppDocs/ontap#1055]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

### Page title

Supported and unsupported features for FlexCache volumes

### Summary

The feature matrix currently says that SMB ODX is not supported at the origin. This is wrong. It is supported at the origin.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
@elliottecton, thanks for bringing this to our attention. I'll update the information as soon as possible.

**Comment by netapp-lenida** [comment]
The table in this topic has been updated to indicate that SMB ODX is supported on the origin volume.
