### ISSUE TITLE
skipping ONTAP 9.10.1

### ISSUE THREAD

**Issue by Brandon12345678901** [NetAppDocs/ontap#1056]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

### Page title

What version of ONTAP can I upgrade to?

### Summary

Hi 
Can we confirm and verify skipping ONTAP 9.10.1 is ok in particualr for FCP ? Going from 9.9.1 - 9.11.1 for exmple . I am sure I have seen documentation or courses say 9.10.1 should be a jump code to 9.12 for example . 

Kind regards,

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@Brandon12345678901 I'm confirming your question with our engineering team.

**Comment by netapp-aherbin** [comment]
@Brandon12345678901 upgrade from 9.9.1 to 9.11.1 is supported for FCP.
