### ISSUE TITLE
Will enabling or disabling CIFS signing and sealing incur an outage

### ISSUE THREAD

**Issue by justuw** [NetAppDocs/ontap#1059]
### Page URL

https://docs.netapp.com/us-en/ontap/smb-admin/configure-required-encryption-concept.html

### Page title

SMB encryption overview

### Summary

It would be very helpful if you could state which commands will cause an outage or disconnect to current CIFS sessions.  

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you @justuw. We will research this as soon as possible.  Let us know if you are an internal NetApp team memeber.

**Comment by netapp-ehoffman** [comment]
Public issue closed, tracking in https://jira.ngage.netapp.com/browse/ONTAPDOC-1360

**Comment by netapp-maireadn** [comment]
This doc update is now complete.
Details tracked in jira ontapdoc 1360
