### ISSUE TITLE
Add new video

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap#1061]
### Page URL

https://docs.netapp.com/us-en/ontap/update/index.html

### Page title

Firmware and system updates overview

### Summary

New video added to KBtv channel, https://youtu.be/GoABILT85hQ?si=sCBRbtcl1gSZ9nww. 

should consider adding a link to it. 

thank you

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Hi @loganbaez.  This is a great addition.  I've added the video to the topic.
