### ISSUE TITLE
Confusion at feature availability matrix.

### ISSUE THREAD

**Issue by yiwai14** [NetAppDocs/ontap#1064]
### Page URL

https://docs.netapp.com/us-en/ontap/concept_nas_file_system_analytics_overview.html

### Page title

File System Analytics overview

### Summary

In the feature availability matrix, I assume the ”X" refers to a "Yes", which is super confusing. I recommend this to be changed to a "✓" or "〇".

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks for the comment @yiwai14 . The page has been updated.
