### ISSUE TITLE
Add sentence about 9.13.1 primary public key authentication does not make use of AD authentication

### ISSUE THREAD

**Issue by tulledge** [NetAppDocs/ontap#1065]
### Page URL

https://docs.netapp.com/us-en/ontap/authentication/grant-access-active-directory-users-groups-task.html

### Page title

Enable Active Directory account access

### Summary

Under About this task:

Change this bullet:

Beginning with ONTAP 9.13.1, you can use an SSH public key as either your primary or secondary authentication method with an AD user password.

To this:
Beginning with ONTAP 9.13.1, you can use an SSH public key as either your primary or secondary authentication method with an AD user password. When doing primary SSH public key authentication, no AD authentication takes place.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Hi @tulledge the topic is updated. Thank you for the feedback.
