### ISSUE TITLE
Confusing title

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#1066]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/split-flexclone-from-parent-task.html

### Page title

Split a FlexClone volume from its parent volume

### Summary

This document is still causing confusion. The first sentence just isn't correct. Splitting a clone results in the volume having it's own space reservation, but it's still a space-efficient operation and it's still using the same blocks as the parent after the split. This needs correction because it's causing headaches with customers.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for working with me on this and reviewing my changes, @jfsinmsp. The topic has been updated.
