### ISSUE TITLE
SSE Feedback for ONTAP Release notes

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#1067]
### Page URL

https://docs.netapp.com/us-en/ontap/index.html

### Page title

ONTAP 9 Documentation

### Summary

This is feedback for the "Known problems and limitations in ONTAP 9 releases" in Release Notes.  These are the "issues" in the tables.

- Instability of ONTAP during a virus scan: Affecting should be ONTAP 9.7 through 9.7P14 and 9.8 through 9.8P4
- XDP SnapMirror transfers can cause long running consistency points:  Affecting should be ONTAP 9.7 through 9.7P11 and 9.8 through 9.8P3 and 9.5 and 9.6
- A large CCMA file might cause system controller disruption: Affecting should be ONTAP 9.5 through 9.5P13
- Adding ATTO FibreBridge for inband monitoring fails in two-node MetroCluster fabric attached configurations: Affecting should be ONTAP 9.5 through 9.5P15 and 9.6 through 9.6P11 and 9.7 through 9.7P8
- Snapshot copy restore of read-only volumes to ONTAP 9.3 or earlier might cause controller disruption:  Affecting should be ONTAP 9.8 through 9.8P4
- AFF A400 systems with NS224 storage fail to boot after upgrade to ONTAP 9.8:   Affecting should be ONTAP 9.8 through 9.8P1
- A250 e0a/e0b ports might randomly negotiate 1GB speed when connected to a switch: Affecting should be ONTAP 9.8 and later
- Controller disruption might occur after upgrading to ONTAP 9.8:  Affecting should be ONTAP 9.8 through 9.8P5
- The security key-manager restore or security key-manager external restore command might cause controller disruption to kmip2_client process:  So this bug is fixed in 9.9.1 and newer.  There are only 4 cases attached to the bug itself.  There is no detail in the bug description as to what a customer can do to check if they are vulnerable to this issue.  How did this issue get added to the release notes?  Can we consider removing it based upon that detail?
- File system metadata corruption might cause system controller disruption: Affecting should be ONTAP 9.7 through 9.7P13 and 9.8 through 9.8P4
- Changing LIF home port might cause an outage:  There is only a single case associated with the bug.  Should this be in release notes?  The customer admitted in the BURT they made the change in error.
- ONTAP RPCs facing significant slowdown in speed due to external DNS server unresponsiveness:  Affecting should be ONTAP 9.5 and 9.6 and 9.7 through 9.7P14 and 9.8 through 9.8P6
- Cluster peering in ONTAP 9.5 requires PSK cipher suites for TLS:  This is first fixed in 9.5P3.  Consider either removing from release notes changing Affecting to just 9.5 through 9.5P2.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Hi @TimMcGue, we'll get this assigned and address the points as soon as possible.

**Comment by netapp-ehoffman** [comment]
Updates published 8/31/2023
