### ISSUE TITLE
Volume size 

### ISSUE THREAD

**Issue by kjntap** [NetAppDocs/ontap#1069]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/create-snaplock-volume-task.html

### Page title

Create and mount SnapLock volumes

### Summary

Is the volume size not required in the volume create command?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
@kjntap, according to the man page, the volume size is optional when creating a volume:

https://docs.netapp.com/us-en/ontap-cli-9131/volume-create.html#parameters

Excerpt:
[-size {<integer>[KB|MB|GB|TB|PB]}] - Volume Size

    This optionally specifies the size of the volume. The size is specified as a number followed by a unit designation: k (kilobytes), m (megabytes), g (gigabytes), or t (terabytes). If the unit designation is not specified, bytes are used as the unit, and the specified number is rounded up to the nearest 4 KB. The minimum size for a FlexVol volume is 20 MB. The minimum size for a volume guaranteed FlexGroup is 20 MB per constituent. The minimum size for a none guaranteed FlexGroup is 200 MB per constituent. However, the recommended size for all FlexGroups is a minimum of 100 GB per constituent. For all volumes, the default size is set to the minimum size. The volume’s maximum size is limited by the platform maximum. If the volume’s guarantee is set to volume , the volume’s maximum size can also be limited by the available space in the hosting aggregates. Volumes can be increased and decreased in size with the [volume modify](https://docs.netapp.com/us-en/ontap-cli-9131/volume-modify.html) command. The maximum number of files a volume is configured for is listed under "Total Files" when running the command [volume show](https://docs.netapp.com/us-en/ontap-cli-9131/volume-show.html)-instance .

**Comment by netapp-lenida** [comment]
Closing this issue. Please reopen if you still feel an update is necessary.
