### ISSUE TITLE
Igroup Create-LUN Map-Host Rescan :: Request to include Destination cluster as well in the task scope.

### ISSUE THREAD

**Issue by carun-netapp** [NetAppDocs/ontap#107]
Page: [Mapping LUNs to the application hosts](https://docs.netapp.com/us-en/ontap/smbc/smbc_install_mapping_luns_to_the_application_hosts.html)

All the steps mentioned in this page equally apply on the destination cluster, once the CG relationship is created & resynced.
However this page is targeted in the context of 'source cluster' only. While the steps mentioned are fine, need to set the correct scope of the steps for both source & destination cluster. 

Refer to NetApp BURT: 1355713

**Comment by netapp-lenida** [comment]
Thanks, Arun. I've updated the topic to indicate that this task should be performed on both the source and destination clusters. Update will be live Friday afternoon.

**Comment by carun-netapp** [comment]
Thanks lenida. I confirm closure of this issue.
