### ISSUE TITLE
max-file-size

### ISSUE THREAD

**Issue by kjntap** [NetAppDocs/ontap#1070]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/create-audit-log-task.html

### Page title

Create an audit log

### Summary

Looks like this is actually max-log-size

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @kjntap. I'll look into this.

**Comment by netapp-lenida** [comment]
@kjntap, thanks for bringing this to our attention. The topic has been updated.
