### ISSUE TITLE
Update HPUX Limitation Content

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#1077]
### Page URL

https://docs.netapp.com/us-en/ontap/smbc/supported-configurations-reference.html

### Page title

Supported configurations and features

### Summary

Please replace the HPUX Limitation content with the below content

An AUFO event on the isolated master cluster which is caused by dual event failure when the connection between the primary and the secondary cluster is lost and the connection between the primary cluster and the mediator is also lost. This is considered a rare event, unlike other AUFO events. 
- In this scenario, it might take more than 120 seconds for I/O to resume on the HP-UX host. Depending on the applications that are running, this might not lead to any I/O disruption or error messages. 
- To remediate, you must restart applications on the HP-UX host that have a disruption tolerance of less than 120 seconds.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks Nikhita. This has been updated.
