### ISSUE TITLE
Please use cluster commands not blade commands

### ISSUE THREAD

**Issue by wolftales** [NetAppDocs/ontap#1079]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/display-file-inode-usage-task.html

### Page title

Display file or inode usage

### Summary

This example is using dialed commands to illustrate how to check file count.

All command examples should use documented commands, which are the cluster commands. Shouldn't this be something to the affect:

volume show -volume *volume_name* -fields files

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank @wolftales ! We'll get this updated.

**Comment by netapp-aherbin** [comment]
Updated.  Thank you for your feedback
