### ISSUE TITLE
Addition for Unsupported feature

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#1080]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html

### Page title

Lock a Snapshot copy for protection against ransomware attacks

### Summary

Under "Unsupported features" we should add Long-Term Retention Snapshots. I think we're getting support soon, but currently it's not supported with Tamperproof Snapshots and it's opened at least one case.

Long-Term Retention Snapshots isn't a well-known term, so maybe the bullet can be something like:
- SnapMirror Policy rules using the `-schedule` parameter

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
@netapp-ahibbard  FYI as well. Lenida please share the update with Andrew in case there's impact on ARP docs

**Comment by netapp-lenida** [comment]
Thanks for letting us know, @netapp-joey. I'll update this topic ASAP.

**Comment by netapp-lenida** [comment]
Thanks, @netapp-joey. The topic has been updated.
