### ISSUE TITLE
FlexVol to FlexGroup conversion - retroactive file move feature discrepancy

### ISSUE THREAD

**Issue by jmcmx** [NetAppDocs/ontap#1082]
### Page URL

https://docs.netapp.com/us-en/ontap/flexgroup/manage-flexgroup-rebalance-task.html

### Page title

Rebalance FlexGroup volumes

### Summary

Under "FlexVol to FlexGroup conversion" we see the retroactive file move feature described first as disruptive and then as non-disruptive.

Is this feature disruptive or not? Please fix this section to provide clarity. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @jmcmx. I'll update the topic ASAP.

**Comment by netapp-lenida** [comment]
Thanks for the feedback. The topic has been updated.
