### ISSUE TITLE
Enable Activity Tracking for multiple volumes - System Manager only?

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap#1085]
### Page URL

https://docs.netapp.com/us-en/ontap/file-system-analytics/activity-tracking-task.html

### Page title

Enable Activity Tracking

### Summary

Intro text mentions System Manager, but steps include System Manager and CLI.

![image](https://github.com/NetAppDocs/ontap/assets/36739591/a3e866d5-db41-4f7d-b339-7a3c62733f25)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks Adam. This has been updated.
