### ISSUE TITLE
Add link to configuration

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/ontap#1086]
### Page URL

https://docs.netapp.com/us-en/ontap/nas-audit/enable-disable-auditing-svms-task.html

### Page title

Enable and disable auditing on SVMs

### Summary

In this section:

What you’ll need
Before you can enable auditing on the SVM, the SVM’s auditing configuration must already exist.

Would be nice to have a link to https://docs.netapp.com/us-en/ontap/nas-audit/create-auditing-config-task.html that describes how to create the configuration that must already exist.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you for the suggestion.  The link has been added.
