### ISSUE TITLE
SSE Feedback for ONTAP Release notes - Part #2

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#1088]
### Page URL

https://docs.netapp.com/us-en/ontap/index.html

### Page title

ONTAP 9 Documentation

### Summary

This is feedback for the "Known problems and limitations in ONTAP 9 releases" in Release Notes. These are the "issues" in the tables.  This is a continuation of request #1067.  We might have one more follow up after this (looking through the remainder that don't have bugs associated with them last).  Thanks as always for your hard work!

- Platform controller disruption might occur during SnapMirror transfers: Affecting should be ONTAP 9.5 through 9.5P16 and 9.6 through 9.6P13 and 9.7 through 9.7P11 and 9.8 through 9.8P1
- Low memory platform controller disruption during heavy write traffic:  Affecting should be ONTAP 9.6 and 9.7 through 9.7P12 and 9.8 through 9.8P2
- Slow aggregate online processes during upgrade to ONTAP 9.7: Affecting should be ONTAP 9.7 through 9.7P12 and 9.8 through 9.8P4
- Counter manager threads might run longer than expected while collecting statistics which might cause controller disruption:  Affecting should be ONTAP 9.7 through 9.7P15 and 9.8 through 9.8P4
- Kernel controller disruption might occur if the system removes an object store server configuration:  Affecting should be ONTAP 9.6 and ONTAP 9.7 and ONTAP 9.8 through 9.8P6
- Directories are converted for use in FlexGroups:  This is an extremely rare scenario with only one case ever added to the BURT.  Can we remove this one? 
- Volume move issue with FabricPools: On the Affecting the 9.7 versions are correct but the 9.6 should be ONTAP 9.6 through 9.6P8
- Quota rule deletion by using REST API might cause a disruption:  This bug was fixed in ONTAP 9.6P2 and all future versions.  The exposure is very limited.  Can this one be removed?
- Unchanged initiators are removed from SAN initiator group during edit:  Affecting should be ONTAP 9.7 through 9.7P2
- Upgrading a cluster with a local software image upload from System Manager:  Affecting should be ONTAP 9.5 through 9.5P10 and ONTAP 9.6 through 9.6P6
- Users with a custom role cannot log in to System Manager:  Affecting should only be ONTAP 9.7 (not later)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Thank you again, @TimMcGue . We'll process these next week.

**Comment by netapp-sumathi** [comment]
The feedback was incorporated and updated Release Notes was published. We have removed all instances of ONTAP 9.7 and earlier releases per the discussion with the release management.
