### ISSUE TITLE
SSE Feedback - link

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#1089]
### Page URL

https://docs.netapp.com/us-en/ontap/insights-system-optimization-task.html

### Page title

Gain insights to help optimize your system

### Summary

In the "About this task" section this part:
Based on best practices, these insights are displayed on one page from which you can initiate immediate actions to optimize your system. For more detail about each insight, see [System Manager insights](https://docs.netapp.com/us-en/concepts/insights-system-optimization-concept.html).

The link looks like it should be this instead:
https://docs.netapp.com/us-en/ontap/concepts/insights-system-optimization-concept.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-thomi** [comment]
This comment is being tracked in JIRA ticket ONTAPDOC-1342.

**Comment by netapp-ehoffman** [comment]
Closing GitHub issue. Tracking now only via https://jira.ngage.netapp.com/browse/ONTAPDOC-1342
