### ISSUE TITLE
Change Cloud Manager to BlueXP

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#1090]
### Page URL

https://docs.netapp.com/us-en/ontap/concepts/introducing-data-management-software-concept.html

### Page title

ONTAP platforms

### Summary

In the graphic, "Cloud Manager" should be changed to "BlueXP"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thanks Ben! We'll get this updated as soon as possible.

**Comment by netapp-aherbin** [comment]
The graphic is updated with BlueXP.  Thanks for bringing this to our attention.
