### ISSUE TITLE
Page is duplicated in sidebar

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#1091]
### Page URL

https://docs.netapp.com/us-en/ontap/task_dp_recover_snapshot.html

### Page title

Recover from Snapshot copies

### Summary

This page appears twice in the sidebar.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thanks Ben.  We'll get this updated as soon as possible.

**Comment by netapp-aherbin** [comment]
Duplication removed. Closing.
