### ISSUE TITLE
Clarify the examples to indicate the volume and or destination need to exist

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/ontap#1092]
### Page URL

https://docs.netapp.com/us-en/ontap/nas-audit/create-auditing-config-task.html

### Page title

Create the auditing configuration

### Summary

Good afternoon Team,
Somewhere on this page, could we please help clarify the examples.

for the parameter: -destination /audit_log

1. It does not have to be audit_log  you can set it to whatever value works for your environment.
2. The volume / destination needs to exist / be valid.

Many thanks!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you for your feedback.  We'll look into this as soon as  possible.

**Comment by netapp-ehoffman** [comment]
Barb, please assign as appropriate.

**Comment by netapp-barbe** [comment]
Mairead, please work with Thom if you have questions.

**Comment by netapp-maireadn** [comment]
Hi Barb,
 I will link in with Thom if I have any questions on this one.
Thanks,
Mairead

**Comment by netapp-maireadn** [comment]
I have created a jira issue to track progress on this GitHub issue.

**Comment by netapp-maireadn** [comment]
Hi @louvipi 
Thanks again for your feedback.
I have liaised with a subject matter expert and updated the topic according to your suggestion.
Kind Regards
Mairead
