### ISSUE TITLE
Update ONTAP S3 information

### ISSUE THREAD

**Issue by ace-en** [NetAppDocs/ontap#1094]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-config/index.html

### Page title

S3 configuration overview

### Summary

The 300TB restriction for ONTAP S3 has been lifted. Please remove the reference here. Suggested edit.  From "For deployments larger than 300TB, NetApp StorageGRID software continues..." to " However, NetApp StorageGRID software continues..."

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Amanda, I was aware of this issue. Ace-en's recommended suggestion is a good immediate update to the topic: can you implement with the next build?

**Comment by netapp-aherbin** [comment]
The update has been implemented.
