### ISSUE TITLE
Clarifications on metrocluster configs

### ISSUE THREAD

**Issue by francesco-paolini** [NetAppDocs/ontap#1096]
### Page URL

https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nve-task.html

### Page title

Enable onboard key management in ONTAP 9.6 and later (NVE)

### Summary

"If you have a MetroCluster configuration, you must run security key-manager onboard enable on the local cluster first, then run security key-manager onboard sync on the remote cluster, using the same passphrase on each." is the current content.
Should be added "Only one cycle is needed. When running the command on site A and syncronizing on site B, it's not needed to run enable on site B"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you for the feedback.  We've made the update.
