### ISSUE TITLE
Object Store Bucket Removal

### ISSUE THREAD

**Issue by KalinTM** [NetAppDocs/ontap#1097]
### Page URL

https://docs.netapp.com/us-en/ontap/fabricpool/requirements-concept.html

### Page title

Considerations and requirements for using FabricPool

### Summary

I think we may need more granularity on the following line of this document:

You cannot detach an object store bucket from the FabricPool configuration after it is attached.

I had a client that understood that the OBS/bucket could not be removed after attaching it to an aggregate, however was not aware that in order to remove his temp license he would need to remove the OBS from the ONTAP cluster, which requires the attached aggregate to be deleted. Client is pointing to this documentation and is claiming this is not sufficient. More information on the removal process in this documentation would have been helpful in my case and may have forced the client to create a temporary aggregate for use with his temp license rather than attaching the OBS to a prod aggregate

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for the feedback. I've updated the topic to include the following additional information:

You cannot detach a cloud tier from a local tier after it is attached; however, you can use FabricPool mirror to attach a local tier to a different cloud tier.
