### ISSUE TITLE
Default value is now 1 hr not 24 starting in ONTAP 9.10.1

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/ontap#1098]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-admin/configure-time-to-live-cached-user-credentials-task.html

### Page title

Configure the time-to-live for cached NFS user credentials

### Summary

Hi,
 Starting with ONTAP 9.10.1, the default value has been changed from 24h to 1h.
Could we please update this page to reflect this change.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Update complete.  Thank you!
