### ISSUE TITLE
SMBC: Clarify how to add a new volume to the CG

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/ontap#110]
Page: [Adding and removing volumes in a consistency group](https://docs.netapp.com/us-en/ontap/smbc/smbc_admin_add_and_remove_volumes_in_consistency_groups.html)

This page mentions briefly "The new volume you add to expand the consistency group must have a pair of common Snapshot copies between the source and destination volumes."

This should be more explicit. You need to create a regular snapmirror, initialize it, then delete the regular snapmirror relationship and release it (with `-relationship-info-only true`) before you can begin with step 1 on that page.

It would be good to have these steps also mentioned in the guide, BEFORE step 1

**Comment by netapp-lenida** [comment]
Thank you for your feedback. I have added additional steps to this topic to describe how determine if common Snapshot copies are available and how to create common Snapshot copies if they do not already exist. I hope this helps make the task clearer.
