### ISSUE TITLE
Correct the examples for different security levels

### ISSUE THREAD

**Issue by gmogil** [NetAppDocs/ontap#1102]
### Page URL

https://docs.netapp.com/us-en/ontap/networking/configure_snmpv3_users_in_a_cluster.html

### Page title

Configure SNMPv3 users in a cluster

### Summary

The cluster in the FIPS mode doesn't support authNoPriv security level. 

The SNMP user can't be created without privacy protocol when the ONTAP is in FIPS mode:
```
security login create -username snmpv3user -application snmp -authmethod usm
Enter the authoritative entity's EngineID [local EngineID]:
Which authentication protocol do you want to choose (sha, sha2-256) [sha]: sha
Enter authentication protocol password (minimum 8 characters long):
Enter authentication protocol password again:
Which privacy protocol do you want to choose  (**des**) [des]: des
Enter privacy protocol password (minimum 8 characters long):
Enter privacy protocol password again:
```

Please correct the information for the authNoPriv security level and the example for authPriv when the ONTAP is in FIPS mode.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Please assign as needed

**Comment by netapp-barbe** [comment]
Aoife, please work on this GH issue. Thank you!

**Comment by netapp-cgoff** [comment]
Hi, thanks again for raising this issue. This issue is now being tracked internally with Jira (ONTAPDOC-1674).
