### ISSUE TITLE
Change to Rebalance FlexGroup volumes docs page

### ISSUE THREAD

**Issue by sdowling03** [NetAppDocs/ontap#1105]
### Page URL

https://docs.netapp.com/us-en/ontap/flexgroup/manage-flexgroup-rebalance-task.html

### Page title

Rebalance FlexGroup volumes

### Summary

Hi Docs Team,

I'm just wondering if it would be possible to put a disclaimer that this operation is unsupported in ONTAP S3 buckets which use FlexGroups as the underlying storage. I had a customer who updated to do this only to get the following response:

koloapina01::*> volume rebalance start -vserver svm_ontaps3 -volume fg_oss_1634725223

Error: command failed: Failed to start volume capacity rebalancing for volume "fg_oss_1634725223" in Vserver "svm_ontaps3".
       Reason: Volume capacity rebalancing is not supported on object store volumes.

I don't see this mentioned in our documentation anywhere. Perhaps it could also be added in the next revision of the FlexGroup TR available here too:
https://www.netapp.com/media/12385-tr4571.pdf 

Thanks in advance!
Sean

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thank you for your feedback. The FlexGroup rebalancing topic has been updated.
