### ISSUE TITLE
There is an error in the upgrade path

### ISSUE THREAD

**Issue by toshihiro-hirate** [NetAppDocs/ontap#1110]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

### Page title

Supported ONTAP upgrade paths

### Summary

I think there is an error in the following items.
"Supported upgrade paths" > "Manual paths, ONTAP 9"

"9.7 | 9.13.1 | multi-stage -9.7 → 9.8 -9.8 → 9.12.1 -9.8 → 9.13.1"

Isn't this the following error?
"9.7 | 9.13.1 | multi-stage -9.7 → 9.8 -9.8 → 9.12.1 -**9.12.1** → 9.13.1"
Or maybe the following is correct?
"9.7 | 9.13.1 | multi-stage -9.7 → **9.9.1 -9.9.1** → 9.13.1

Please confirm it is.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@toshihiro-hirate thank you for bringing this to our attention.  You can upgrade from 9.7->9.9.1 and then 9.9.1 -> 9.13.1.  However the preferred path (based on testing) is -9.7 → 9.8 -9.8 → 9.12.1 -9.12.1 → 9.13.1.

**Comment by toshihiro-hirate** [comment]
I understand.
thank you.

**Comment by netapp-aherbin** [comment]
The topic is updated.  Thanks again for the feedback
