### ISSUE TITLE
Page doesn't appear in sidebar

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#1111]
### Page URL

https://docs.netapp.com/us-en/ontap/encryption-at-rest/manage-external-key-managers-sm-task.html

### Page title

Manage external key managers

### Summary

I came across this page through search. It doesn't appear in the sidebar.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks Ben. This has been updated.
