### ISSUE TITLE
Manage external key managers with System Manager topic - Condense and simplify opening paragraphs

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap#1114]
### Page URL

https://docs.netapp.com/us-en/ontap/encryption-at-rest/manage-external-key-managers-sm-task.html

### Page title

Manage external key managers with System Manager

### Summary

Recommended re-write follows:

> Beginning with ONTAP 9.7, you can store and manage authentication and encryption keys with the Onboard Key Manager. Beginning with ONTAP 9.13.1, you can also use external key managers to store and manage these keys.

> The Onboard Key Manager stores and manages keys in a secure database that is internal to the cluster. Its scope is the cluster. An external key manager stores and manages keys outside the cluster. Its scope can be the cluster or the storage VM. One or more external key managers can be used. The following conditions apply:

> •	If the Onboard Key Manager is enabled, an external key manager cannot be enabled at the cluster level, but it can be enabled at the storage VM level. 
> •	If an external key manager is enabled at the cluster level, the Onboard Key Manager cannot be enabled.

> When using external key managers, you can register up to four primary key servers per storage VM and cluster. Each primary key server can be clustered with up to three secondary key servers.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Update is posted.  Thank you!
