### ISSUE TITLE
Confusing version support

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#1120]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-snapmirror/index.html

### Page title

S3 SnapMirror overview

### Summary

This doc says CVO for Azure is supported "(beginning with ONTAP 9.9.0)", but the overall feature of S3 SnapMirror is only supported in 9.10.1 and later. Where's this ONTAP 9.9.0 version coming from, as it seems to be inaccurate?
Are the other versions accurate in this table?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-joey** [comment]
I think I found where these versions came from. They're the versions when S3 was first supported on those CVO platforms, per this TR: https://www.netapp.com/media/17219-tr4814.pdf

So these versions are not accurate for when S3 SnapMirror support starts for CVO. I'm not sure when that is, or if it's even the case that CVO is supported.

**Comment by netapp-ehoffman** [comment]
@johnlantz , would you be able to take a look at Joey's comments and advise?

**Comment by johnlantz** [comment]
I think Joey figured it out. The releases under the various platforms are when those platforms started supporting ONTAP S3.

The feature, S3 SnapMirriror, didn't exist until 9.10, 

All of this might be a bit superfluous for CVO as they use a SaaS model and are always on the the latest version. Given where we are today (9.13.1) I'd recommend removing the various CVO release numbers from the page. (I'd keep the 9.10.1 call out for the feature itself. That still matters for customers who are on older versions of ONTAP.)

**Comment by netapp-ehoffman** [comment]
Thank you very much, John, and Joey for raising this. We'll address in short order.
Ed

**Comment by netapp-aherbin** [comment]
Thank you for the feedback.  Updated based on changes in Word doc from @netapp-ehoffman. Closing.
