### ISSUE TITLE
SSE Feedback - Maximum supported volumes per SVM

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#1121]
### Page URL

https://docs.netapp.com/us-en/ontap/svm-migrate/index.html

### Page title

SVM data mobility overview

### Summary

This is from a recent conversation - I will forward the ticket to the other participants who will have more input.

So this chart breaks down the requirements for AFF and FAS platforms.  The question came up what if the cluster is mixed between both?  Is this limited to only the HA pair?  Then what if the SVM contains volumes that reside on both the FAS and AFF HA pairs in the cluster - does that change the requirement?  

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Hi Tim, I looked at the email thread and added Tony's response in a note before the table:

Note: If you are migrating from one cluster type to another (from a FAS cluster to an AFF cluster, for example), the maximum number of volumes supported is based on the HA pair that is hosting the source SVM.

**Comment by netapp-lenida** [comment]
I've updated the topic to match the FAQ that Tony pointed to.
