### ISSUE TITLE
Add NVMe protocols for vsadmin / vsadmin-volume / vsadmin-protocol roles

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap#1123]
### Page URL

https://docs.netapp.com/us-en/ontap/authentication/predefined-roles-svm-administrators-concept.html

### Page title

Predefined roles for SVM administrators

### Summary

The vsadmin / vsadmin-volume / vsadmin-protocol roles current has the following Capability.

- Configuring protocols: NFS, SMB, iSCSI, and FC, including FCoE

This request is to add the new NVMe/FC and NVMe/TCP protocols to the list.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you for your feedback.  We are researching the issue.

**Comment by netapp-aherbin** [comment]
Moved to internal tracking (ONTAPDOC 1645)
