### ISSUE TITLE
Broken link on https://docs.netapp.com/us-en/ontap/cluster-admin/index.html

### ISSUE THREAD

**Issue by Grantglass** [NetAppDocs/ontap#1124]
### Summary

       
Broken link on https://docs.netapp.com/us-en/ontap/cluster-admin/index.html
The yml file in Cluster Nodes (https://github.com/NetAppDocs/ontap/blob/main/cluster-admin/_index.yml)  references a document that doesn't exist. 
Line 35-36
 - title: Shut down a node
          url: /../system-admin/shut-down-node-task.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thanks Grant!

@ntap-bmegan the link under "Shut down a node" in the "Cluster nodes" tile on this landing page is being redirected from /system-admin/manage-node-boot-menu-task.html  to /system-admin/shut-down-node-task.html, which is giving a 404.  

We have  not created this redirect in the ontap repo.  Also when I put the link (https://docs.netapp.com/us-en/ontap/system-admin/manage-node-boot-menu-task.html) directly in the web browser it is resolving.  Any insight here?

**Comment by ntap-bmegan** [comment]
I honestly can't trace what's being redirected from where. 

@Grantglass reported that this landing page entry 

![image](https://github.com/NetAppDocs/ontap/assets/56453501/e116a616-a120-40d2-9dc5-fa1cbeb69530)

Which has this URL: 

`https://docs.netapp.com/us-en/ontap/system-admin/shut-down-node-task.html`

Which loads as the same URL: 

`https://docs.netapp.com/us-en/ontap/system-admin/shut-down-node-task.html`

Returns a 404, which it does. 

There is no Adoc source file named `system-admin/shut-down-node-task`:

![image](https://github.com/NetAppDocs/ontap/assets/56453501/b2dcbf28-8e8e-4bdb-b185-809c721b118f)

Nothing @Grantglass mentioned deals with a second file. What does `system-admin/manage-node-boot-menu-task` have to do with it?

**Comment by netapp-aherbin** [comment]
@ntap-bmegan  @Grantglass I think I misread the file first time around.  I've removed the broken link.
