### ISSUE TITLE
ARP snapshot copies are not locked 

### ISSUE THREAD

**Issue by tsohst** [NetAppDocs/ontap#1127]
### Page URL

https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html

### Page title

Autonomous Ransomware Protection overview

### Summary

* We've found that when a low attack happend, ARP created a snapshot with no "snaplock-expiry-time", means that there is no lock in the snapshot.
* The doc said:
> When an attack is suspected, the system takes a volume Snapshot copy at that point in time and locks that copy.

* Enable ARP does not reference it either
https://docs.netapp.com/us-en/ontap/anti-ransomware/enable-task.html

* I can't verify it on a technical basis, but:
  * either the snapshot is not locked because it is a low attack, 
  * or tamperproof snapshot requirements are not met (like ComplianceClock is not initialized)

https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html#enable-snapshot-copy-locking-when-creating-a-volume

* Please reference in the doc what is needed to lock a "Anti_ransomware_backup" snapshot.

```
vserver volume   snapshot                               snaplock-expiry-time
------- -------- -------------------------------------- --------------------
VSERVER  VOLUME Anti_ransomware_backup.2023-10-02_1316 -
```

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
@tsohst , thank you for sharing your experience with NetApp documentation. Can I ask you to send an email to ng-doccomments@netapp.com, referencing this GitHub issue, so that we can follow up with further questions if needed?

**Comment by tsohst** [comment]
> @tsohst , thank you for sharing your experience with NetApp documentation. Can I ask you to send an email to [ng-doccomments@netapp.com](mailto:ng-doccomments@netapp.com), referencing this GitHub issue, so that we can follow up with further questions if needed?

E-Mail has been send, do you have an update for this topic?

**Comment by netapp-ehoffman** [comment]
@netapp-chandaj , have you seen this email? I'm not sure we received it.

**Comment by netapp-ahibbard** [comment]
Thanks @tsohst - Closing this as we've clarified that ARP Snapshots are locked, albeit with a different locking mechanism.
