### ISSUE TITLE
Misleading "recommended" section

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#1128]
### Page URL

https://docs.netapp.com/us-en/ontap/consistency-groups/limits.html

### Page title

Consistency group limits

### Summary

Hello,
The new section of this doc at the bottom is called "Recommended limits", but the limit mentioned is a supported limit, meaning using a lower value is not a supported configuration. As-is, this isn't clear and a customer might think they can use a lower value and still be supported, even if it's not "recommended".

Suggest we change the name of the section to "Unenforced limits", which more closely follows the top section of "Enforced limits". And the text could read:
"
The minimum supported Snapshot copy schedule for consistency groups is 30 minutes. This is based on the minimum supported schedules on [FlexGroups](https://www.netapp.com/media/12385-tr4571.pdf) which share the same Snapshot infrastructure as consistency groups.
"

Thanks!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-joey** [comment]
Any questions about this ask?

**Comment by netapp-ahibbard** [comment]
Thanks Joey. This has been updated
