### ISSUE TITLE
missed step in system manager instructions

### ISSUE THREAD

**Issue by bdeloure** [NetAppDocs/ontap#1129]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/set-efficiency-mode-task.html

### Page title

Set storage efficiency mode during volume creation

### Summary

For the System Manager steps to set storage efficiency, step 3 is missing one step.  The user must click edit and select volume before they can get to the edit volume settings and scroll to the storage efficiency section.

3. Click Edit, and scroll to Storage Efficiency.

would be more accurate to read:

3. Click Edit > Volumes, and scroll to Storage Efficiency.

![image](https://github.com/NetAppDocs/ontap/assets/122458706/0dda1bed-ade7-4916-865a-1a96bcc34840)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@bdeloure thank you for bringing this to our attention.  The content has been updated.
