### ISSUE TITLE
Add an additional link for Sentinel 1

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#1132]
### Page URL

https://docs.netapp.com/us-en/ontap/antivirus/vscan-partner-solutions.html

### Page title

Vscan partner solutions

### Summary

Update the Sentinel 1 section to add the additional link that is publicly available 

Sentinel One - 
https://www.sentinelone.com/platform/singularity-cloud-data-security/ (No Login required)
https://support.sentinelone.com/hc/en-us/categories/360002507673-Knowledge-Base-and-Documents (This link requires a user log-in. You can request access from Sentinel One.)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
The link has been added.  Thank  you.
