### ISSUE TITLE
This page is not in the table of contents

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#1135]
### Page URL

https://docs.netapp.com/us-en/ontap/cloud-install-fabricpool-task.html

### Page title

Install a FabricPool license

### Summary

Seems to be a duplicate of this page?
https://docs.netapp.com/us-en/ontap/fabricpool/install-license-aws-azure-ibm-task.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @netapp-bcammett. I'll take a look.

**Comment by netapp-lenida** [comment]
Thanks @netapp-bcammett. The duplicate page has been removed.
