### ISSUE TITLE
Tamper-Proof Snapshot Platform Limitations

### ISSUE THREAD

**Issue by jleafnapp** [NetAppDocs/ontap#1136]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html

### Page title

Lock a Snapshot copy for protection against ransomware attacks

### Summary

Please note in Unsupported that CVO, ONTAP Select is unsupported

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for the information. We'll update this topic as soon as possible.

**Comment by netapp-lenida** [comment]
Thanks @jleafnapp. The topic has been updated.
