### ISSUE TITLE
Procedure to enable Active Directory authentication of cluster administrators doesn't work without CIFS license

### ISSUE THREAD

**Issue by nadgb** [NetAppDocs/ontap#1138]
### Page URL

https://docs.netapp.com/us-en/ontap/authentication/enable-ad-users-groups-access-cluster-svm-task.html

### Page title

Configure Active Directory domain controller access overview

### Summary

The 'vserver active-directory create -vserver SVM_name" only accepts data SVM names and can not be used to create a computer account for the cluster SVM on the AD domain.

So how do you configure the admin SVM to authenticate administrators using Active Directory when the CIFS feature license is not present?

The question is probably moot. The answer is likely to install the ONTAP ONE license and create a SMB data SVM that is used exclusively as tunnel to the AD server.

Let me know if there is an alternate method to installing CIFS feature license.

Thanks, Derek
NetApp Learning Services

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Thanks Derek. We'll need to reach out to the appropriate ENG to request their consult on this. Will CC you.

**Comment by netapp-aherbin** [comment]
@nadgb I've verified with engineering. Your assumptions above are correct.

- The 'vserver active-directory create -vserver SVM_name" only accepts data SVM names and can not be used to create a computer account for the cluster SVM on the AD domain. (**Correct**)

- How do you configure the admin SVM to authenticate administrators using Active Directory when the CIFS feature license is not present? (**Without the CIFS license, it is not possible to configure the admin SVM to authenticate users.**)

- The question is probably moot. The answer is likely to install the ONTAP ONE license and create a SMB data SVM that is used exclusively as tunnel to the AD server. (**Correct**)

- Let me know if there is an alternate method to installing CIFS feature license. (**Presently, there is no alternative method.**)

Feel free to reopen the issue if you have additional questions or reach out to me internally on Teams.
