### ISSUE TITLE
Does Solaris support thin provisioning LUN ?

### ISSUE THREAD

**Issue by yanw113** [NetAppDocs/ontap#1139]
### Page URL

https://docs.netapp.com/us-en/ontap/san-admin/host-support-scsi-thin-provisioning-reference.html

### Page title

Host support for SCSI thin provisioning

### Summary

According to the document, it only lists below host OS:

1. VMware ESX 5.0 and later
2. Red Hat Enterprise Linux 6.2 and later
3. Citrix XenServer 6.5 and later
4. Microsoft Windows 2012
5. Microsoft Windows 2016

Does Solaris support thin provisioning LUN ? Does not being on this list mean it is not supported?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@yanw113 we'll research this issue and let you know.

**Comment by yanw113** [comment]
Oracle Linux doesn't list on the page too, Do we only support the five OS type? This caused a lot of confusion for our customers

**Comment by yanw113** [comment]
Any update? our customer is waiting for official reply

**Comment by netapp-aherbin** [comment]
@yanw113 SCSI thin provisioning is supported for Solaris beginning with Solaris 11.1.  We are in the process of researching other OS types and will update the content once we make further confirmations.

**Comment by yanw113** [comment]
@netapp-aherbin  Thank you for the update, so Oracle Linux is unsupported, or non-qualified, is it correct?

**Comment by netapp-dawsona** [comment]
Oracle Enterprise Linux and Solaris are two very different OSes. 

Oracle Enterprise Linux is supported for iSCSI - in terms of LUN thin provisioning, the OS doesn't know it's thin. Thin provisioning is only recommended when the OS can SCSI UNMAP, and Oracle Linux can UNMAP - https://support.oracle.com/knowledge/Oracle%20Linux%20and%20Virtualization/2809910_1.html

**Comment by netapp-aherbin** [comment]
The updated list is posted.  Thank you for bringing this to our attention.
