### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by antoine-netapp** [NetAppDocs/ontap#1142]
### Page URL

https://docs.netapp.com/us-en/ontap/san-admin/asa-iscsi-lif-fo-task.html#about-enabling-iscsi-lif-failover

### Page title

iSCSI LIF failover for ASA platforms

### Summary

If the steps mentioned in this kb are followed for pre-existing failover groups, the group ends up with ports from one node only.
A step needs to be added to specifically add ports from the partner node.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Moving to Jira for internal discussion and tracking (ONTAPDOC-1457)
