### ISSUE TITLE
Replication of service policies

### ISSUE THREAD

**Issue by wrobinson-ntap** [NetAppDocs/ontap#1147]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-concept.html

### Page title

About SnapMirror SVM replication

### Summary

Since firewall policies have been deprecated and replaced by service policies, this document should reference both firewall policies and service policies as being replicated when identity preserve is set to true. Currently, the document only mentions firewall policies.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for making us aware of this change. We'll update the the documentation as soon as possible.
