### ISSUE TITLE
Batch upgrade process is wrong in this document

### ISSUE THREAD

**Issue by taddingt** [NetAppDocs/ontap#1149]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html

### Page title

ONTAP software upgrade methods

### Summary

In the document it states:

ONTAP batch upgrades
In the batch upgrade process, the cluster is divided into several batches, each of which contains multiple HA pairs. In the first batch, half of the nodes are upgraded, followed by their HA partners.

This says that half of the nodes in a cluster are upgraded in a Batch Upgrade. This is misleading.   It does upgrade half of the HA pairs at a time, but only a single node in the HA pair will upgrade simultaneously.  So technically only 25% of the nodes in a cluster are upgraded at a time.    We had a customer complaining that they expected 4 nodes of their 8 node cluster to upgrade at the same time based on this.    

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@taddingt thank you for the clarification.  We will update as soon as possible.

**Comment by netapp-aherbin** [comment]
@taddingt I've updated as following:
In the batch upgrade process, the cluster is divided into several batches, each of which contains multiple HA pairs. In the first batch, one node of each HA pair is upgraded, followed by their HA partners. The process is then repeated sequentially for the remaining batches

Any further comment?

**Comment by netapp-aherbin** [comment]
Verified changed with @taddingt via Teams.  Closing.
