### ISSUE TITLE
Adding/removing Vol mapping:  Pre-work for original CG relationship needs to be called out before Step#5.

### ISSUE THREAD

**Issue by carun-netapp** [NetAppDocs/ontap#115]
Page: [Adding and removing volumes in a consistency group](https://docs.netapp.com/us-en/ontap/smbc/smbc_admin_add_and_remove_volumes_in_consistency_groups.html)

Comment on Step #5.
Need extra pre-step or note about how to delete original CG relationship, before making expansion/reduction operation on volume mapping. 

ie.. original CG relationship requires full delete or using release-info-only

**Comment by netapp-lenida** [comment]
Would you please provide the step that needs to be added before Step 5?

**Comment by carun-netapp** [comment]
Copy + pasting offline discussion, for the purpose of tracking the changes on this issue: 

-----------------------------Email start-------------------------------------

From: Kumar, Arun <Arun.C@netapp.com> 
Sent: Tuesday, January 5, 2021 9:30 PM
To: Somasundaram, Sathish <Sathish.Somasundaram@netapp.com>
Cc: Gandham, Satish Kumar <SatishKumar.Gandham@netapp.com>; Sethuraman, Venkatesan <Venkatesan.Sethuraman@netapp.com>; Vorwerk, Lenida <Lenida.Vorwerk@netapp.com>
Subject: RE: [NetAppDocs/ontap] Adding/removing Vol mapping: Pre-work for original CG relationship needs to be called out before Step#5. (#115)

Hello Sathish

Hope you are doing well. 
Reaching out to you for your guidance on SMBC documentation.

I find some issue with the steps mentioned at below documentation: 
https://docs.netapp.com/us-en/ontap/smbc/smbc_admin_add_and_remove_volumes_in_consistency_groups.html

I raised a github request to clarify the gap.
https://github.com/NetAppDocs/ontap/issues/115

As per my understanding, given below is the missing gap (step 4)  that needs to be addressed in documentation: 
------------------------------------------------------------

Pre-Requisites:
Assuming the current CG relationship has vol_src1:@vol_dst1 vol_src2:@vol_dst2 as volume mapping before expansion. Workflow shall append vol_src3:@vol_dst3 to the relationship.

Step 4:   Unmap the luns, Delete the existing cg relationship with release-info-only flag, before adding/deleting volume mapping. 
destination::> snapmirror delete -destination-path vs1_dst:/cg/cg_dst 
source        ::> snapmirror release -destination-path vs1_dst:/cg/cg_dst -relationship-info-only true

Step 5:
Destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1, vol_src2:@vol_dst2, vol_src3:@vol_dst3

------------------------------------------------------------

Could you please share your thoughts on this (or) correct me ?

arun


-----------------------------Email End------------------------------------

**Comment by netapp-lenida** [comment]
Hi Arun, the topic has been updated. Please verify that it is correct now. Thanks

**Comment by carun-netapp** [comment]
Lenida
I looked into the updated doc & below are my observations. 

Excerpt #1: 
"If you want to change the composition of the consistency group by adding or removing a volume, you must first delete the original relationship and then create the consistency group again with the new composition. "

carun comments:  " .....you must first delete the original relationship, followed by a release with "-release-info-only" flag......."

Excerpt #2: 
"About this task:
The composition change is not allowed when the consistency group is in the “InSync” state. "

carun comments: " I am not sure about the correctness of the above statement. Please get this line reviewed by SMBC Engineering team. "

**Comment by carun-netapp** [comment]
Pre-work steps are addressed. Looks good to me.
