### ISSUE TITLE
version missing 

### ISSUE THREAD

**Issue by merdos** [NetAppDocs/ontap#1150]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html

### Page title

Storage limits

### Summary

This article has old numbers and does not mention what version it is for. Confusing. Maybe just take it down? 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Moved to internally tracking (ONTAPDOC 1644)
