### ISSUE TITLE
Please explicitly state that the snapmirror and ICMP ports need to be bi-directional

### ISSUE THREAD

**Issue by rbaetz** [NetAppDocs/ontap#1152]
### Page URL

https://docs.netapp.com/us-en/ontap/peering/prerequisites-cluster-peering-reference.html

### Page title

Prerequisites for cluster peering

### Summary

Customer's firewall engineer will not open the ports 11104, 11105 and ICMP as bi-directional without the documentation explicitly stating that they are bi-directional.  Please update.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
This request is being researched.

**Comment by netapp-barbe** [comment]
The documentation has been updated. Thank you very much for raising this issue. Please see the changes here:

- https://docs.netapp.com/us-en/ontap/peering/prerequisites-cluster-peering-reference.html#connectivity-requirements 
- https://docs.netapp.com/us-en/ontap/networking/ontap_port_usage_on_a_storage_system_overview.html
