### ISSUE TITLE
Update table to include options 10 and 11

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap#1154]
### Page URL

https://docs.netapp.com/us-en/ontap/system-admin/manage-node-boot-menu-task.html

### Page title

Manage a node by using the boot menu

### Summary

boot menu now include options 10 and 11

**refer to:**

-option 10 -   https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html#ontap-9-8-and-later-with-encrypted-root-volume
- option 11 - https://kb.netapp.com/onprem/ontap/os/Supplied_passphrase_and_backup_data_are_not_able_to_successfully_import_keys_during_maintenance

thank you

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thanks Logan, we'll get this updated as soon as possible.
