### ISSUE TITLE
Supported object storage for FabricPool and Cloud Tiering

### ISSUE THREAD

**Issue by seijitanabe** [NetAppDocs/ontap#1155]
### Page URL

https://docs.netapp.com/us-en/ontap/fabricpool/index.html

### Page title

FabricPool tier management overview

### Summary

I understand FabricPool and Cloud Tiering use the same technology. However there are defferences in supported object storage between the following two docs.
https://docs.netapp.com/us-en/ontap/fabricpool/index.html
https://docs.netapp.com/us-en/bluexp-tiering/concept-cloud-tiering.html#supported-object-storage-providers

Is it correct that there are differences? or is one of them incorrect?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
@seijitanabe, thanks for bringing this to our attention. I've verified that the FabricPool information is still accurate, but I need to check with the BlueXP writer or someone on the BlueXP team to find out about the difference on their end. I'm closing this public issue and will open an internal issue. I'll email you the details.
