### ISSUE TITLE
Change wording for clarity?

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap#1156]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/create-load-sharing-mirror-task.html

### Page title

Create and initializing load-sharing mirror relationships

### Summary

The 2nd line of the document page:

LSM is not suitable for single HA clusters, and it should be configured for multiple HA pair clusters, configuring the LSM between the node with the root volume and another node from a different HA pair.

Looking at "single HA clusters", should that not be "single HA **pair** cluster" to be consistent with the rest of the line?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @estarz, I'll look into this.

**Comment by netapp-lenida** [comment]
@estarz, thank you for your feedback. The sentence has been updated.
