### ISSUE TITLE
Misleading "Unenforced limits" section

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#1159]
### Page URL

https://docs.netapp.com/us-en/ontap/consistency-groups/limits.html

### Page title

Consistency group limits

### Summary

I had asked for some changes to this page in this request: https://github.com/NetAppDocs/ontap/issues/1128
But seems like we only made some of those changes, so I am asking again.

The "Unenforced limits" section text is misleading because it mentions "recommended", which is wrong. This isn't a recommended limit, it's a supported limit. Can we please change the current text under "Unenforced limits" to this:
"
The minimum supported Snapshot copy schedule for consistency groups is 30 minutes. This is based on the minimum supported schedules on [FlexGroups](https://www.netapp.com/media/12385-tr4571.pdf) which share the same Snapshot infrastructure as consistency groups.
"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-joey** [comment]
Hello, can we make this change, please? Thanks

**Comment by netapp-ahibbard** [comment]
Thanks Joey. This has been updated.
