### ISSUE TITLE
Non-support for CG creation across different ONTAP persona needs call out.

### ISSUE THREAD

**Issue by carun-netapp** [NetAppDocs/ontap#116]
Page: [Creating a consistency group relationship](https://docs.netapp.com/us-en/ontap/smbc/smbc_install_creating_a_consistency_group_relationship.html)

Good to have the following oneliner under "Before you begin"
- smbc CG relationship can not be established across clusters with ASA & NON-ASA persona.

**Comment by netapp-lenida** [comment]
This has now been added. Can you verify that it's correct?

**Comment by carun-netapp** [comment]
looks good.
