### ISSUE TITLE
S3 Glacier support confusion

### ISSUE THREAD

**Issue by kevinh-netapp** [NetAppDocs/ontap#1162]
### Page URL

https://docs.netapp.com/us-en/ontap/fabricpool/setup-aws-s3-cloud-tier-task.html

### Page title

Set up Amazon S3 as the cloud tier

### Summary

S3 Glacier is listed as supported in the CVO data tiering docs, which also uses FabricPool:
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html#data-tiering-in-aws

Is this intentionally omitted (not supported) in ONTAP docs, or does it just need to be added? Thanks!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @kevinh-netapp. I've confirmed that FabricPool supports Amazon S3 Glacier Instant Retrieval. I'll update the FabricPool documentation shortly.

**Comment by netapp-lenida** [comment]
The topic has been updated.
