### ISSUE TITLE
Changes in TR - 4568 should reflect here for ODX requirements

### ISSUE THREAD

**Issue by AickeB** [NetAppDocs/ontap#1165]
### Page URL

https://docs.netapp.com/us-en/ontap/san-admin/microsoft-offloaded-data-transfer-odx-concept.html

### Page title

Microsoft Offloaded Data Transfer (ODX)

### Summary

[19751-tr-4568.pdf (netapp.com)](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.netapp.com%2Fmedia%2F19751-tr-4568.pdf&data=05%7C01%7CAicke.Barthel%40netapp.com%7Cf0d9a3572dec47a134b008dbe02da12e%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638350258798094162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G7N24n8ge8gLKmvRFbQxfZzlAaeaUql30hq907R01Os%3D&reserved=0)
 
Replace:
>> ODX increases performance significantly with faster copying, reduced utilization of CPU and memory on the client, and reduced network I/O bandwidth utilization
 
With:
ODX can potentially improve performance of copies within same volume, reduce utilization of CPU and memory on the client, and reduce network I/O bandwidth utilization.
 
With ODX, it is faster and efficient to copy files within the SMB shares, within the LUNs, and between the 
SMB shares and LUNs in same volume. This approach is more helpful in a scenario for which multiple copies of the 
golden image of an OS (VHD/VHDX) are required within same volume. Several copies of the same golden image can be 
made in significantly less time if copies are within same volume. ODX is also applied in Hyper-V storage live migration
for moving VM storage.
 
If copy is across volumes, there may not be significant performance gains compared to host-based copies.
 
 
[Microsoft Offloaded Data Transfer (ODX) (netapp.com)](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Fontap%2Fsan-admin%2Fmicrosoft-offloaded-data-transfer-odx-concept.html&data=05%7C01%7CAicke.Barthel%40netapp.com%7Cf0d9a3572dec47a134b008dbe02da12e%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638350258798094162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KNy9msXPE9ccufNBdqN7w1Q1o32E9scIQ7wDBZYeEjI%3D&reserved=0)
 
Replace:
>>Because ODX offloaded copies are performed directly between the source and destination, significant performance benefits are realized, including faster copy time, reduced utilization of CPU and memory on the client, and reduced network I/O bandwidth utilization.
 
With:
 
Because ODX offloaded copies are performed directly between the source and destination, significant performance benefits are realized (if copies are within same volume), including faster copy time (for same volume copies), reduced utilization of CPU and memory on the client, and reduced network I/O bandwidth utilization. If copy is across volumes, there may not be significant performance gains compared to host-based copies.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
The update to [Microsoft Offloaded Data Transfer (ODX) (netapp.com)](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Fontap%2Fsan-admin%2Fmicrosoft-offloaded-data-transfer-odx-concept.html&data=05%7C01%7CAicke.Barthel%40netapp.com%7Cf0d9a3572dec47a134b008dbe02da12e%7C4b0911a0929b4715944bc03745165b3a%7C0%7C0%7C638350258798094162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KNy9msXPE9ccufNBdqN7w1Q1o32E9scIQ7wDBZYeEjI%3D&reserved=0) is complete.  The TR update will be handled separately as discussed in internal email thread.  Thank you for the feedback.
