### ISSUE TITLE
ONTAP S3 and FlexCache

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#1169]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

### Page title

Supported and unsupported features for FlexCache volumes

### Summary

I would like this manual to state whether it is possible to access data using the SMB/NFS/S3 protocol on the origin and access the data using the S3 protocol on the cache volume.
S3 is supported in the origin, but S3 is not supported in the cache volume.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @kanitani. I'll take a look.
