### ISSUE TITLE
SMBC upgrade/revert closure notes

### ISSUE THREAD

**Issue by carun-netapp** [NetAppDocs/ontap#117]
Page: [SM-BC upgrade and revert considerations](https://docs.netapp.com/us-en/ontap/smbc/smbc_admin_upgrade_and_revert_considerations.html)

Comments to Engineering owner:

Presentation of the doc content looks incomplete. Did we miss on the closure note of this topic ??
are there any further recommendations to complete the upgrade/revert, after performing revert check-only ??

**Comment by netapp-lenida** [comment]
Hi Arun,
What additional information is required? Can you tell me who to contact for missing details?

**Comment by carun-netapp** [comment]
I didn't see any specific note/step/precautions on revert procedure in the context of SMBC feature. If there is any specific step to be taken care by customer outside of default ONTAP revert procedure, pls call out. 

More explanation: 
--------------------
There is only 1 step defined here.  Its a dry run command (doesn't actually perform the revert) that is listing a check list of items to address before performing actual revert.  There should be further steps defined here to complete the workflow [ may be step2 with sample command reference for revert operation (or) at least say "follow normal ONTAP revert workflow" ].

I do not know the engineering author for this topic.  "SatishKumar.Gandham@netapp.com" might be able to help here.

**Comment by netapp-lenida** [comment]
I understand what you're asking. I can provide a link to our upgrade and revert documentation. I think that should be sufficient.

**Comment by netapp-lenida** [comment]
Links are now added to our documentation for upgrade and revert. Please verify.

**Comment by carun-netapp** [comment]
looks good now.
