### ISSUE TITLE
Include that VAAI and NFSv4.2 are not supported on Cache volumes

### ISSUE THREAD

**Issue by augustritchie** [NetAppDocs/ontap#1171]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

### Page title

Supported and unsupported features for FlexCache volumes

### Summary

Neither NFSv4.2 or VAAI are supported on FlexCache volumes

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thank you for bringing this to our attention. The table has been updated to show that VAAI and NFSv4.2 are not supported on the cache volume.
