### ISSUE TITLE
Incorrect LUN maps per cluster and node

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#1173]
### Page URL

https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html

### Page title

Object limits for SnapMirror Business Continuity

### Summary

Please correct the LUN Maps Numbers per cluster and per node as follows:

LUN maps per node | 4096
LUN maps per cluster | 8192

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
@Nikhita-13 , are these changes the result of an update in a particular ONTAP version?

**Comment by netapp-aherbin** [comment]
@Nikhita-13 verified that updated limits apply to 9.10.1 and later.  Update complete.
