### ISSUE TITLE
Regarding the compatible ONTAP versions for SVM-DR

### ISSUE THREAD

**Issue by Wyu-2023** [NetAppDocs/ontap#1176]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html

### Page title

Compatible ONTAP versions for SnapMirror relationships

### Summary

We have received the following feedback from the customer and would like to request your confirmation and assistance with the necessary modifications:

Regarding the SnapMirror SVM disaster recovery relationships, 
the documentation states, "The ONTAP version on the target cluster must be no more than two versions newer, as shown in the table below."

However, upon reviewing the contents of the table, we have noticed the following:

For ONTAP versions 9.3-9.6 on the source, the destination version can be counted up to three versions each.

But for ONTAP versions 9.7 and above (excluding cloud), the destination version can only be counted up to two versions, excluding the asterisk (*).

Shouldn't the destination version for ONTAP versions 9.7 and above (excluding cloud) also be counted up to three versions, similar to ONTAP versions 9.3-9.6 on the source?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
@Wyu-2023, I have sent you a message directly in email.

**Comment by netapp-lenida** [comment]
The topic has been updated.
