### ISSUE TITLE
Request to remove unwanted review comments in the content. 

### ISSUE THREAD

**Issue by carun-netapp** [NetAppDocs/ontap#118]
Page: [Mediator not reachable or Mediator quorum status is false](https://docs.netapp.com/us-en/ontap/smbc/smbc_troubleshoot_mediator_not_reachable_or_quorum_false.html)

Review comments are published in the content. 
Please remove the "(I WILL ADD LINK TO COMMAND ONCE TOPIC IS IN GITHUB)" from the section "SOLUTION"

**Comment by netapp-lenida** [comment]
Removed comment.

**Comment by carun-netapp** [comment]
looks good.
