### ISSUE TITLE
Unnecessary repetition of words

### ISSUE THREAD

**Issue by adamn-netapp** [NetAppDocs/ontap#1180]
In the following excerpt from this page, the words "for upgrades from" are not necessary:

> The upgrade paths for upgrades from ONTAP 9.4, 9.3, 9.2, 9.1 and 9.0 might vary based upon whether you are performing an automated upgrade or a manual upgrade.

This would be easier to read/parse as follows:

> The upgrade paths from ONTAP 9.4, 9.3, 9.2, 9.1 and 9.0 might vary based upon whether you are performing an automated upgrade or a manual upgrade.

**Comment by netapp-aherbin** [comment]
Updated.  Thank you.
