### ISSUE TITLE
The expression "with a single NFS mount" is ambiguous and the text cannot be understood correctly.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#1181]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv41-concept.html

### Page title

ONTAP support for NFSv4.1

### Summary

![image](https://github.com/NetAppDocs/ontap/assets/68621663/f071dae4-5586-4b90-9cdb-5c98d8dff2ae)

When performing NFS mounting, I can have multiple access route IPs even if there is only one NFS export.
If multiple LIFs for NFS access are created in ONTAP, NFS mounting can be performed via any IP.

When performing NFS mounting, I can access using multiple IPs even one NFS export.
(If multiple LIFs for NFS are created in ONTAP, NFS mounting can be performed via any IP.)

When resolving the NFS server name using DNS, multiple IPs may be returned, but does nConnect use multiple IPs to mount the NFS export? Or does nConnect only use one IP and use that one IP to establish multiple TCP Connections?

Could you please be a little more specific about the expression "with a single NFS mount"?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Tracking internally with ONTAPDOC 1673 
@kanitani are you internal to NetApp.  If so, what is your id so we can add you to the issue.

**Comment by kanitani** [comment]
ID: kan.itani@netapp.com

**Comment by kanitani** [comment]
Please do not close this issue.

**Comment by netapp-ehoffman** [comment]
@kanitani , we're now tracking this via Jira. I've sent an email asking for your access to be granted to that Jira project.

**Comment by netapp-dbagwell** [comment]
Change is live: https://github.com/NetAppDocs/ontap/pull/1617
