### ISSUE TITLE
Update the pointers under Bucket operations.

### ISSUE THREAD

**Issue by harshitmarwah1** [NetAppDocs/ontap#1182]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-config/ontap-s3-supported-actions-reference.html

### Page title

ONTAP S3 supported actions

### Summary

Hi Team,

Need to update the page as the following line no longer valid. Please reach out to me.

Bucket operations
The following operations are supported using ONTAP REST APIs in ONTAP releases where AWS S3 REST API support is not available:

bucket creation and deletion

bucket policy creation, modification, and deletion

Regards,
Harshit Marwah

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
The updates based on our email exchanged are posted.  Thank you!
