### ISSUE TITLE
Do not use time-bound words 

### ISSUE THREAD

**Issue by adamn-netapp** [NetAppDocs/ontap#1184]
### Page URL

https://docs.netapp.com/us-en/ontap/disks-aggregates/default-raid-policies-aggregates-concept.html

### Page title

Default RAID policies for local tiers (aggregates)

### Summary

In the following passage in this topic, the word "new" begs the questions - new as of when? 

> A new RAID policy called RAID-TEC is available. RAID-TEC is supported on all disk types and all platforms, including AFF. Local tiers that contain larger disks have a higher possibility of concurrent disk failures. RAID-TEC helps to mitigate this risk by providing triple-parity protection so that your data can survive up to three simultaneous disk failures. RAID-TEC is the default RAID policy for capacity HDD local tiers with disks that are 6 TB or larger.

Avoid using this word. It is unhelpful. Instead of using "new," specify when the feature was introduced by referencing the release/version in which it first became available.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
The use of time-bound words in the ONTAP documentation has been corrected. Closing this comment.
