### ISSUE TITLE
Dedupe policy changes by default incorrect

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/ontap#1185]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/automatic-deduplication-schedule-aff-concept.html

### Page title

Manage automatic volume-level background deduplication on AFF systems

### Summary

I don't believe this statement is correct: 
If a volume moves from a non-AFF system to an AFF system, the auto policy is enabled on the destination node by default. If a volume moves from an AFF node to a non-AFF node, the auto policy on the destination node is replaced by the inline-only policy by default.

I have never seen the auto policy enabled on the destination AFF system when migrating non-AFF to AFF.  Similarly, it does not make sense that the policy would be set to inline-only when moving from AFF to non-AFF, as inline is only supported on AFF.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Investigating this issue.

**Comment by netapp-aherbin** [comment]
Moved to internally tracking (Jira ONTAPDOC-1643)
