### ISSUE TITLE
Minor correction to "What happens" section

### ISSUE THREAD

**Issue by johnlantz** [NetAppDocs/ontap#1188]
### Page URL

https://docs.netapp.com/us-en/ontap/fabricpool/tiering-policies-concept.html

### Page title

About FabricPool tiering policies

### Summary

Second bullet in "What happens" section reads: "Changing the tiering policy to all from another policy causes ONTAP to move all user blocks in the active file system and in the Snapshot copies to the cloud tier as the next time the tiering scan runs."

This was changed in 9.8. Can we update the text to read something along the lines of:

"Changing the tiering policy to all from another policy causes ONTAP to move all user blocks in the active file system and in the Snapshot copies to the cloud tier as soon as possible. Prior to ONTAP 9.8, blocks needed to wait until the next tiering scan ran."

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention, John. I'll update the topic ASAP.
