### ISSUE TITLE
external HA interconnect

### ISSUE THREAD

**Issue by Nat-Netapp** [NetAppDocs/ontap#1189]
### Page URL

https://docs.netapp.com/us-en/ontap/concepts/high-availability-pairs-concept.html

### Page title

High-availability pairs

### Summary

Hello, 
It's written "An internal HA interconnect", but some controllers have an external HA interconnect cabling, it should be mentioned to let customer understand why they have to wire this cables. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you for the feedback!

Generally most single chassis HA systems have communicated over the backplane.  But on A700s, A800, and now A250 systems you have an external HA connection.  So node to node communication doesn’t occur over the backplane.  The nice thing about the A250 is cluster interconnects and HA are combined on the same physical port.  

We've reworded the definition of HA as the best option here.  HA simply means fault tolerant nodes that can communicate with each other in different ways.
