### ISSUE TITLE
typo: remove "- style" for "-rootvolume-security"

### ISSUE THREAD

**Issue by sakaia** [NetAppDocs/ontap#119]
Page: [Create SVMs](https://docs.netapp.com/us-en/ontap/networking-app/create_svms.html)

I am trying to execute the command. from the experience, following changes are needed.

```
- `vserver create -vserver vs1 -aggregate aggr3 -rootvolume vs1_root ‑rootvolume-security- style ntfs -ipspace ipspace1 -language en_US.UTF-8`
+ `vserver create -vserver vs1 -aggregate aggr3 -rootvolume vs1_root ‑rootvolume-security ntfs -ipspace ipspace1 -language en_US.UTF-8`
```

**Comment by netapp-barbe** [comment]
HI Atsushi, thank you for catching this, I'll make this update.

**Comment by netapp-barbe** [comment]
There is a typo on this page, the command should be **-rootvolume-security-style <_security style_>** (no space between security and -style) where <_security style_> can be _unix_, _ntfs_, or _mixed_.

See the following Command MAN page for more information: [vserver create commands](https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-980/vserver__create.html)
