### ISSUE TITLE
Storage Limits Page appears to need updating

### ISSUE THREAD

**Issue by bryan-britesky** [NetAppDocs/ontap#1192]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html

### Page title

Storage limits

### Summary

Some of the limits listed have been increased since 9.12.1 (Max. LUN Size = 16TB on page, but was increased to 100TB in 9.12.1)
Also, max. volume size is not mentioned.  Might be good to review all values and update accordingly as this page is ranked first when searching for ONTAP limits...

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @bryan-britesky . This page has been updated to reflect the change.
