### ISSUE TITLE
Update doc

### ISSUE THREAD

**Issue by bradvondanford** [NetAppDocs/ontap#1193]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-admin/configure-number-group-ids-allowed-nfs-users-task.html

### Page title

Configure the number of group IDs allowed for NFS users

### Summary

Can we add a warning that enabling this option, prior to making changes as seen in the following list, can cause impact?

There is a number of prerequisites that will need to be configured prior to enabling extended authentication 
If the prerequisites are not met, any supplemental group(s) will not be used and access to data may be impacted
Prerequisites:
LDAD or NIS must be configured and functional for the NFS server in question
The LDAP or NIS server must have all users configured with associated groups
[NSSWITCH](https://docs.netapp.com/us-en/ontap-cli-9141//vserver-services-name-service-ns-switch-modify.html) must be configured to include LDAP or NIS for the Vserver in question

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Tracking internally with JIRA issue ONTAPDOC-1632.  Closing this GitHub issue.
