### ISSUE TITLE
Correction Request: Outgoing throttle values

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#1194]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-global-throttling-concept.html

### Page title

Use SnapMirror global throttling

### Summary

Based on discussions with engineering, this documentation's reference below should be updated to reflect no maximum limit.
Please change 

> KBps is the maximum transfer rate in kilobytes per second. Valid transfer rate values are 1 to 125000. The default value for this option is unlimited

To 

> The recommended minimum throttle bandwidth is 4 KBps and the maximum is up to 2 TBps. The default value for this option is unlimited, which means there is no limit on the total bandwidth used. Parameter values are in KBps.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
The topic has been updated. Thank again, Tony.
