### ISSUE TITLE
inconsistent info in the table rg. max file size considering 9.12.1P2 and 9.13.0P2

### ISSUE THREAD

**Issue by lescar** [NetAppDocs/ontap#1196]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html

### Page title

Storage limits

### Summary

Note max file size (incl. LUNs): 
https://docs.netapp.com/us-en/ontap/volumes/enable-large-vol-file-support-task.html#create-a-new-volume

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @lescar . This has been updated.
