### ISSUE TITLE
Add ASA to scalability table.

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#1197]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html

### Page title

SnapMirror Synchronous disaster recovery basics

### Summary

Currently, the table showing max relationships does not show ASA platforms. Can we add a row specifically to call out ASA and set it to the same values as AFF?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, @tansley-netapp, the topic has been updated to include the ASA information.
