### ISSUE TITLE
If the documentation for the features supported by FlexCache is correct, the description on this page is misleading to users.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#1199]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/audit-flexcache-volumes-concept.html

### Page title

Considerations for auditing FlexCache volumes

### Summary

In this document below, AntiVirus is not available on the cache side.
https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html#supported-protocols
![image](https://github.com/NetAppDocs/ontap/assets/68621663/8f246852-a5b5-4e94-a27d-8b8b9da9ff82)

However, it is written that the ONTAP FPolicy function used by AntiVirus operates on the cache side.
![image](https://github.com/NetAppDocs/ontap/assets/68621663/a87363b1-5aa0-4176-8a21-b9b7a0f9901a)

Please tell me what is correct.
Please correct the wording so that users do not misunderstand it.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Checked with the engineering team and verified that the information is correct, however, I changed antivirus support on the FlexCache volume from "not applicable" to "No" so there is no doubt that antivirus is not supported on the cache volume.

**Comment by kanitani** [comment]
I think that change alone is not enough.
Please add information on how users can perform virus scanning in FlexCache configurations.

**Comment by netapp-ehoffman** [comment]
Hi @kanitani , thanks for your request. Can you take a look at the FlexCache Best Practices technical report (https://www.netapp.com/media/7336-tr4743.pdf) and let us know if the virus scanning information in that document helps provide clarity?

**Comment by kanitani** [comment]
![image](https://github.com/NetAppDocs/ontap/assets/68621663/ed815ead-c933-40b7-9a2f-6291f743c079)

Yes, this description is useful to me.
However, please include important information like this in the manual. The TR should only be a supplementary document, and important information should be included in the manual.

**Comment by netapp-ehoffman** [comment]
@kanitani, thank you: this is valuable feedback. In the short term, we will add a link to the TR for information on virus-scanning on FlexCache, and we'll open an internal issue to track the effort to migrate this content to the core documentation.

**Comment by kanitani** [comment]
![image](https://github.com/NetAppDocs/ontap/assets/68621663/00b8fa0b-3454-48fb-9f1c-e07d295f75a5)
By the way, I don't think people who read this description will get correct information.

How about changing "No" to "Not Applicable" and adding the following as a supplement?
"If you scan for viruses at the origin, no settings are required on the cache side. The origin vscan will also detect files infected with viruses that are written to the cache."

**Comment by netapp-lenida** [comment]
Thank you for the helpful feedback. I'll follow up with the Product Manager to find out if your information is correct and update the topic appropriately.

**Comment by netapp-lenida** [comment]
I checked with the product manager and the TME who both provided feedback. I've updated the antivirus statement with their feedback and included a link to the TR. Thanks again for the suggestions.
