### ISSUE TITLE
Unsupported list update

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#1202]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html

### Page title

SnapMirror Synchronous disaster recovery basics

### Summary

The following items need to be removed from the unsupported list and moved to the supported list:

•	LUN clone/file clone : We support it since 9.5.  Clones of ACS backed LUN is supported since 9.7
•	Tape based restore to the source volume – we support it since 9.13.1

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, Tony. The topic was updated.
