### ISSUE TITLE
Add IMT link 

### ISSUE THREAD

**Issue by Brandon12345678901** [NetAppDocs/ontap#1204]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

### Page title

Supported ONTAP upgrade paths

### Summary

Hi 
Can we add a link to the IMT   for example 

The version of ONTAP that you can upgrade to depends on 

1. Your hardware platform and the version of ONTAP currently running on your cluster’s nodes. See [NetApp Hardware Universe](https://hwu.netapp.com/) to verify that your platform is supported for the target upgrade release. 
2. NetApp interoperability Matrix Tool report see https://imt.netapp.com/matrix/#welcome 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Update is complete.  Thank you.
