### ISSUE TITLE
Rebalancing should mention this helps capacity issues not performance in a clear warning.

### ISSUE THREAD

**Issue by MrObvious** [NetAppDocs/ontap#1208]
### Page URL

https://docs.netapp.com/us-en/ontap/flexgroup/manage-flexgroup-rebalance-task.html

### Page title

Rebalance FlexGroup volumes

### Summary

Hello team. This page is a great page. One thing that isn't clear unless you read very carefully is that FG Rebalance is a feature that only fixes capacity issues, not performance. There should be a clear warning that this will degrade performance.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @MrObvious. We'll update this topic ASAP.

**Comment by netapp-lenida** [comment]
I've added a note at the beginning of the topic to make it clearer that performance can be impacted when using the FlexGroup rebalance feature.
