### ISSUE TITLE
Contradicting information

### ISSUE THREAD

**Issue by cpickens85** [NetAppDocs/ontap#1214]
### Page URL

https://docs.netapp.com/us-en/ontap/svm-migrate/index.html

### Page title

SVM data mobility overview

### Summary

It says Flexgroups are not supported with SVM Data Mobility but it is starting in 9.12

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @cpickens85, I'll look into this.

**Comment by netapp-lenida** [comment]
SVM data mobility has been removed from the features supported by FlexGroup volumes in ONTAP 9.12.1. Thanks again.
