### ISSUE TITLE
Correction for ONTAP 9.12.1 list

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#1215]
### Page URL

https://docs.netapp.com/us-en/ontap/flexgroup/supported-unsupported-config-concept.html

### Page title

Supported and unsupported configurations for FlexGroup volumes

### Summary

SVM Migrate does not currently support FlexGroups. Please remove this bullet from the 9.12.1 list.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks Tony. I'm updating this now as part of issue# 1214.

**Comment by netapp-lenida** [comment]
The topic has been updated. Thanks Tony.
