### ISSUE TITLE
Missing  details about upgrades

### ISSUE THREAD

**Issue by Ludicious** [NetAppDocs/ontap#1217]
### Page URL

https://docs.netapp.com/us-en/ontap/smbc/smbc_admin_upgrade_and_revert_considerations.html

### Page title

Upgrade and revert ONTAP with SM-BC

### Summary

Page makes no reference to ONTAP upgrades in general. What pre-reqs or checks should be performed before upgrading clusters with SMBC relationship. Can it be done with relationship in sync, or does it need broken?  Could there be some simple validation steps?  
1. Relationship is in-sync and no event log errors about snapmirror
2. Mediator is onilne and healthy from both clusters
3. All hosts can see all paths properly to protected luns

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @Ludicious . We've updated the doc accordingly.
