### ISSUE TITLE
Remove "ONTAP Select" from "Unsupported Features"

### ISSUE THREAD

**Issue by tulledge** [NetAppDocs/ontap#1221]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html

### Page title

Lock a Snapshot copy for protection against ransomware attacks

### Summary

Remove "ONTAP Select" from "Unsupported Features"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Thanks @tulledge . Was this a change in a particular release of ONTAP/ONTAP Select?

**Comment by netapp-lenida** [comment]
Thanks @tulledge. ONTAP Select has been removed from the list of unsupported features.
