### ISSUE TITLE
How frequently does ONTAP check for firmware updates after enabling automatic updates?

### ISSUE THREAD

**Issue by neilmaldy** [NetAppDocs/ontap#1224]
### Page URL

https://docs.netapp.com/us-en/ontap/update/how-auto-updates-scheduled.html

### Page title

How automatic updates are scheduled for installation

### Summary

How frequently does ONTAP check for firmware updates after enabling automatic updates?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Neil's question has been answered internally.  Checking with team to verify if we need to additional detail in the topic

**Comment by netapp-aherbin** [comment]
Neil's query has been address internally through email.  As a result of the conversation we have added clarification to the documentation regarding how nodes/clusters are grouped for scheduling.  Closing this issue.
