### ISSUE TITLE
 Error when adding service to policy applied to Data iSCSI LIF

### ISSUE THREAD

**Issue by Brandon12345678901** [NetAppDocs/ontap#1227]
### Page URL

https://docs.netapp.com/us-en/ontap/networking/configure_lif_service_policies.html

### Page title

Configure LIF service policies

### Summary

I am hitting an error when adding a service to a policy applied to a data LIF in ONTAP 9.13   . I do not see the error in 9.11 

cluster2::*> net int service-policy add-service -vserver svm_linux_iscsi_lifs -policy bs_test_9_13 -service data-iscsi
  (network interface service-policy add-service)

Warning: Adding service "data-iscsi" to service policy "bs_test_9_13" on Vserver "svm_linux_iscsi_lifs" will result in changes to the failover policies
         for 1 LIFs on that Vserver. Impacted LIFs: "iscsi_lif_1".
Do you want to continue? {y|n}: y

Warning: Adding service "data-iscsi" to service policy "bs_test_9_13" on Vserver "svm_linux_iscsi_lifs" will require 1 LIFs on that Vserver to be
         temporarily disabled for changes in protocol registration to be applied. All current network connections on these LIFs will be reset. Impacted
         LIFs: "iscsi_lif_1".
Do you want to continue? {y|n}: y

Error: command failed: Modifying service policy "bs_test_9_13" on Vserver "svm_linux_iscsi_lifs" is not allowed while the service policy is currently
       referenced by a LIF.

-----------####-------
#################
>>I found a workaround to change the LIF policy to default-data-iscsi then add the service to the custom policy then reapply it to the LIF .
>>Alternatively add the service before applying the custom policy to the LIF 

#Change vserver and iscsi data LIF’s policy to iscsi default 
net int modify -vserver svm_linux_iscsi_lifs -lif iscsi_lif_1 -service-policy default-data-iscsi

#Add additional service to policy 
net int service-policy add-service -vserver svm_linux_iscsi_lifs -policy bs_test_9_13 -service data-iscsi

#Add policy back to svm / iscsi lifs 
net int modify -vserver svm_linux_iscsi_lifs -lif iscsi_lif_1 -service-policy bs_test_9_13

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@Brandon12345678901 has resolved issue with ENG.  Thank you!
