### ISSUE TITLE
step 18 on this page is wrong

### ISSUE THREAD

**Issue by zhuolin-shen** [NetAppDocs/ontap#1229]
### Page URL

https://docs.netapp.com/us-en/ontap/revert/task_reverting_an_ontap_cluster.html

### Page title

Revert an ONTAP cluster

### Summary

Basically, system node upgrade-revert show command can only display info if upgrades occur.
Revert only will not display anything by it
======
fas2520-2n-dal-1::*> system node upgrade-revert show -node fas2520-dal-1a
There are no entries matching your query.
 
fas2520-2n-dal-1::*> system node upgrade-revert show -node fas2520-dal-1b
There are no entries matching your query.
======

And not-needed status can also occur if there are staged updates that were ever performed:
https://kb.netapp.com/onprem/ontap/os/After_ONTAP_revert%2C_system_node_upgrade-revert_show_command_displays_%22Status%3Anot-needed%22

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@zhuolin-shen thanks for reporting this issue.  In your example above, the revert was **successful** but the system node upgrade-revert command **did not** display the status as successful.  Instead, the command returned: "There are no entries matching your query."  Is that correct?

**Comment by netapp-aherbin** [comment]
Updated based on email discussion with ENG and @zhuolin-shen.
