### ISSUE TITLE
Aligning doc page with KB by adding step for snapmirror release

### ISSUE THREAD

**Issue by jdsmith-21** [NetAppDocs/ontap#1230]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/convert-snapmirror-version-flexible-task.html

### Page title

Convert an existing DP-type relationship to XDP

### Summary

Customer was confused because our KB article about the DP to XDP conversion process for SVM DR includes "snapmirror release" as a step, but the doc page for the DP to XDP conversion process for volume-level snapmirror does not.

Step 3 of the "[convert existing SVM DR relationship from DP to XDP](https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_to_convert_existing_SVM_DR_relationship_from_DP_to_XDP)" article is equivalent to step 6 of the [doc page](https://docs.netapp.com/us-en/ontap/data-protection/convert-snapmirror-version-flexible-task.html).
 
Step 4 of the SVM DR article is snapmirror release with the -relationship-info-only true option.  The -relationship-info-only true prevents in-common snapshots from being deleted.  The snapshots are critical for the resync and conversion process to work.
 
To make the doc page consistent with the procedure in the KB article, a snapmirror release step should be inserted between steps 6 and 7.  The new step 7 on the doc page should be snapmirror release with the -relationship-info-only true option.
 
The "create the new XDP-type relationship" step will become step 8.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @jdsmith-21. I'll look into this issue.

**Comment by netapp-lenida** [comment]
The missing step has been added.
