### ISSUE TITLE
SnapMirror Copy to Cloud and SnapMirror Asynchronous Copy-to-Cloud

### ISSUE THREAD

**Issue by jleafnapp** [NetAppDocs/ontap#1232]
### Page URL

https://docs.netapp.com/us-en/ontap/svm-migrate/index.html

### Page title

SVM data mobility overview

### Summary

Remove internal branding for SnapMirror Copy to Cloud  and SnapMirror Asynchronous Copy to Cloud.

The public facing documentation should refer to this as SnapMirror Cloud

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
@jleafnapp, thanks for bringing this to our attention. I'll take a look ASAP.

**Comment by netapp-lenida** [comment]
The topic has been updated.
