### ISSUE TITLE
Add 'snapshot copies take up no space at the time of first creation'.

### ISSUE THREAD

**Issue by randobrando46** [NetAppDocs/ontap#1237]
### Page URL

https://docs.netapp.com/us-en/ontap/concepts/snapshot-copies-concept.html

### Page title

Snapshot copies

### Summary

Hi, I think it would be valuable to add that the first SnapShot of a volume consumes no space because it is just pointers to blocks.  Similar to this older page: https://library.netapp.com/ecmdocs/ECMP1196991/html/GUID-CF9E77A6-BDD9-4138-A281-FC0E7BEA4C6D.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for the suggestion, @randobrando46. I'll look into this.

**Comment by netapp-lenida** [comment]
Thanks again @randobrando46. I added information you suggested in the second paragraph of the topic. Closing this issue.
