### ISSUE TITLE
Add Deep Instinct to the Partner Solution Page

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#1243]
### Page URL

https://docs.netapp.com/us-en/ontap/antivirus/vscan-partner-solutions.html

### Page title

Vscan partner solutions

### Summary

We have recently onboarded Deep Instinct. So please add a row in the table to add Deep Instinct and in the description. 

Add a row for Deep Instinct (that would look similar to Sentienl 1):

Solution Name: Deep Instinct Prevention for Storage 

Links:
Documentation and Interop: https://portal.deepinstinct.com/pages/dikb (Requires login)
Data Sheet: https://www.deepinstinct.com/pdf/datasheet-deep-instinct-prevention-for-storage-netapp (Doesn’t require login

No IMT for this partner. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Update complete.
