### ISSUE TITLE
Changing LIF data protocols

### ISSUE THREAD

**Issue by tespinoz-netapp** [NetAppDocs/ontap#1244]
### Page URL

https://docs.netapp.com/us-en/ontap/smb-config/create-lif-task.html

### Page title

Create a LIF

### Summary

The page currently suggests that it's not possible to change LIF data protocols after the LIF has been created. While this may be true for ONTAP 9.5 and earlier (I'm not certain but I would imagine so), it's definitely not true for ONTAP 9.6 and later where service policies can be modified at virtually any time and the data protocols for a LIF are derived from the allowed services in the service policy. 

For example, I created a LIF in 9.13.1 using the "-data-protocol nfs" option, at which point a new custom nfs-only service policy was automatically created for that LIF. After adding the 'data-cifs' service to that custom service policy, the LIF now shows both NFS and CIFS as allowed data protocols via "network interface show -fields data-protocol"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for reporting this issue, I will investigate and follow up here.

**Comment by netapp-barbe** [comment]
This issue has been corrected: https://docs.netapp.com/us-en/ontap/smb-config/create-lif-task.html
