### ISSUE TITLE
Remove 9.8 from the XDP table for 9.14.1

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#1245]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html

### Page title

Compatible ONTAP versions for SnapMirror relationships

### Summary

Lenida,

I mistakenly put 9.8 as supported for 9.14.1 on the XDP table.  Can we change that value to "no" please?

Thanks
Tony

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for letting me know, Tony. I'll get this updated.

**Comment by netapp-lenida** [comment]
Thank you, Tony. The topic has been updated.
