### ISSUE TITLE
Page is duplicated in the sidebar

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#1249]
### Page URL

https://docs.netapp.com/us-en/ontap/concepts/aggregates-raid-groups-concept.html

### Page title

Local tiers (aggregates) and RAID groups

### Summary

I was in the disk and tier management section, but somehow ended up in the concepts section because this page is used twice in the sidebar.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Update complete - See Jira ONTAPDOC 1720 for details on update.
