### ISSUE TITLE
Update supported MAV commands

### ISSUE THREAD

**Issue by ntapmattt** [NetAppDocs/ontap#1251]
### Page URL

https://docs.netapp.com/us-en/ontap/multi-admin-verify/index.html

### Page title

Multi-admin verification overview

### Summary

AS of 9.14.1 these commands are also supported.

vserver modify

volume recovery-query modify

volume recovery-query purge

volume recovery-query purge-all

This should be added to the doc.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@ntapmattt public doc site has been updated with the changes you requested. Thanks!
