### ISSUE TITLE
The table of "File operations" at the end of this doc is unclear

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#1253]
### Page URL

https://docs.netapp.com/us-en/ontap/svm-migrate/index.html

### Page title

SVM data mobility overview

### Summary

The table at the end of this document implies that end users will not be able create, move, or modify files during a migration operation. I'm pretty sure that table is actually referring to API-based operations, not end users. As written, it sounds like the SVM-Migrate feature would be highly disruptive and barely usable.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, @jfsinmsp. I'll contact the SMEs I worked with on this table to make this information clearer.

**Comment by netapp-lenida** [comment]
I've moved this issue to Jira to track internally: https://jira.ngage.netapp.com/browse/ONTAPDOC-1651. Closing this issue.

**Comment by ntap-bmegan** [comment]
@netapp-lenida - Don't post internal URLs in public issues. It's okay to cite the item number (as I've edited above).
