### ISSUE TITLE
MetroCluster Support needs to be updated

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#1254]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-concept.html

### Page title

About SnapMirror SVM replication

### Summary

In the Support Details table, the metrocluster row needs to be updated.

The first bullet  "A MetroCluster configuration cannot be the destination of an SVM disaster recovery relationship" needs to be updated to the following:

1) update the bullet to say "Prior to ONTAP 9.10, A MetroCluster configuration cannot be the destination of an SVM disaster recovery relationship.
2) new bullet: "Starting with ONTAP 9.10.1 and later, A MetroCluster configuration may be the destination of an SVM disaster recovery relationship for migration purposes only and must meet all requirements specified in [TR-4966: Migrating a SVM into a MetroCluster solution ](https://www.netapp.com/pdf.html?item=/media/83785-tr-4966.pdf)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, Tony. The topic has been updated.
