### ISSUE TITLE
Possible incorrect info

### ISSUE THREAD

**Issue by kevinh-netapp** [NetAppDocs/ontap#1256]
### Page URL

https://docs.netapp.com/us-en/ontap/system-admin/access-system-console-node-task.html

### Page title

Access the system console of a node

### Summary

The following may be incorrect:

"From the cluster, you can access the system console of any node in the cluster."

From a lab system, if I ssh into the cluster lif, I cannot access the local node using the "system node run-console" command with the following error:

"Error: command failed: You are already on the console of node "nodea""

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
ENG is verifying this.  Moving to Jira 1898 to record internal conversation and progress.
