### ISSUE TITLE
Error in step 1 command

### ISSUE THREAD

**Issue by pelijaro** [NetAppDocs/ontap#1258]
### Page URL

https://docs.netapp.com/us-en/ontap/ndmp/enable-svm-scoped-ndmp-cluster-task.html

### Page title

Enable SVM-scoped NDMP on the cluster

### Summary

Hello,

This document needs to be revised in this part:

<img width="430" alt="image" src="https://github.com/NetAppDocs/ontap/assets/11003546/1b3a2f1a-a0b8-47a4-8224-ddae9fde534d">

It should be off

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
For future reference, @pelijaro is correct.  The command turns node-scope-mode off which is what enables SVM-scoped NDMP as noted in the topic.
