### ISSUE TITLE
Virtual vs Physical Machine

### ISSUE THREAD

**Issue by patrickr0636** [NetAppDocs/ontap#1259]
### Page URL

https://docs.netapp.com/us-en/ontap/antivirus/install-ontap-antivirus-connector-task.html

### Page title

Install ONTAP Antivirus Connector

### Summary

In the section About this task it states 'The ONTAP Antivirus Connector can run on a virtual machine. However, for best performance, NetApp recommends using a dedicated **virtual** machine for antivirus scanning.' 

The section should read The ONTAP Antivirus Connector can run on a virtual machine. However, for best performance, NetApp recommends using a dedicated **physical** machine for antivirus scanning.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you for the feedback.  The update is live.
