### ISSUE TITLE
Wrong description?

### ISSUE THREAD

**Issue by okrause** [NetAppDocs/ontap#1260]
### Page URL

https://docs.netapp.com/us-en/ontap/smb-admin/commands-manage-computer-account-passwords-concept.html

### Page title

Commands for managing SMB servers computer account passwords

### Summary

The page says:

Change or reset the domain account password and you know the password | vserver cifs domain password change
Reset the domain account password and you do not know the password | vserver cifs domain password reset

IMHO this is wrong. Correct would be:

Change or reset the domain account password and ONTAP knows the machine account password (machine account password in sync with AD) | vserver cifs domain password change
Reset the domain account password and ONTAP does not know the machine account password (machine account password out of sync with AD)| vserver cifs domain password reset

Of course I recommend to describe it differently. Please ask the experts for these commands.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Thanks @okrause for alerting us to this issue.  We'll investigate and update here with what we find.

**Comment by netapp-barbe** [comment]
Thank you for your feedback, this have been fixed
