### ISSUE TITLE
Deep Instinct Update

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#1265]
### Page URL

https://docs.netapp.com/us-en/ontap/antivirus/vscan-partner-solutions.html

### Page title

Vscan partner solutions

### Summary

Hi All, 

Partner is requesting in the first column instead of 'Deep Instinct Prevention for Storage' we say -> 'Deep Instinct'. 

In the second column - Can we write it as follows: 
Deep Instinct Prevention for Storage 
- Documentation and Interop (This link requires a user log-in. You can request access from Deep Instinct.) 
- Data Sheet 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
The update is posted.
