### ISSUE TITLE
Correct subject-verb disagreement

### ISSUE THREAD

**Issue by adamn-netapp** [NetAppDocs/ontap#1269]
### Page URL

https://docs.netapp.com/us-en/ontap/release-notes/index.html

### Page title

ONTAP 9 release highlights

### Summary

In the following excerpt, the words I've highlighted in bold indicate a subject/verb disagreement:

> Add metadata **tags** to volumes and clusters, which **follows** the data as it moves from on-premises to the cloud and reverse.

It should say:

Add metadata tags to volumes and clusters, which **follow** the data as it moves from on-premises to the cloud and reverse.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Update posted.  Thank you for your feedback.
