### ISSUE TITLE
Recommend re-write for first three paragraphs

### ISSUE THREAD

**Issue by adamn-netapp** [NetAppDocs/ontap#1270]
### Page URL

https://docs.netapp.com/us-en/ontap/release-notes/index.html

### Page title

ONTAP 9 release highlights

### Summary

The first three paragraphs:

> Each release of the ONTAP 9 data management software delivers new and enhanced features that improve the capabilities, manageability, performance, and security offerings in ONTAP.
> 
> You can find the highlighted new features for recent ONTAP 9 releases on this page or use the sidebar to navigate to a specific ONTAP 9 version to learn about all the enhancements in recent ONTAP releases.
> 
> For details about earlier ONTAP 9 releases, hardware platform and switch support, known issues, and limitations, refer to the [ONTAP 9 Release Notes](https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508). You must sign in with your NetApp account or create a NetApp account to access the ONTAP 9 Release Notes.

Can be tightened as follows:

> Each release of the ONTAP 9 data management software delivers new and enhanced features that improve the capabilities, manageability, performance, and security offerings in ONTAP.
> 
> In addition to these highlights, you can find comprehensive, per-version coverage of all the new and enhanced features introduced in recent ONTAP releases.
> 
> For details about hardware platform and switch support, known issues, and limitations in all ONTAP 9 versions, or for features introduced in releases prior to ONTAP 9.9.1, refer to the [ONTAP 9 Release Notes](https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508). You must sign in with your NetApp account or create an account to access the Release Notes.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you for your feedback.  Update posted.
