### ISSUE TITLE
Networking content not properly indexed

### ISSUE THREAD

**Issue by saroojain** [NetAppDocs/ontap#1275]
### Page URL

https://docs.netapp.com/us-en/ontap/networking/configure_vlans_over_physical_ports.html

### Page title

Configure VLANs over physical ports

### Summary

The VLAN and IFGRP content in ONTAP doc is not properly indexed. It is difficult to search for. Even search on doc does not give the desired page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@saroojain we are researching this issue.  Can you share what search terms you used and what search mechanism you used (Google, Coveo, Elasticsearch)?

**Comment by netapp-aherbin** [comment]
SEO updates complete based on @netapp-pavanrk recommendations. Thank you for your feedback.
Opened Jira 1850 and added internal email discussion /decisions for reference.
