### ISSUE TITLE
Please call out that a SnapLock license is required to use S3 object lock

### ISSUE THREAD

**Issue by johnlantz** [NetAppDocs/ontap#1276]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-config/create-bucket-task.html

### Page title

Create a bucket

### Summary

S3 object lock requires a standard SnapLock License. This license is included in ONTAP One. 

Prior to ONTAP One, the SnapLock license was included in the Security and Compliance bundle. The Security and Compliance bundle is no longer offered, but customers can upgrade to ONTAP One.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
The topic has been updated to include SnapLock license information.
