### ISSUE TITLE
Clarify the SnapMirror section

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#1279]
### Page URL

https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html

### Page title

Autonomous Ransomware Protection use cases and considerations

### Summary

Section: Supported configurations
Table Row 2: "SVMs protected with Asynchronous Snapmirror" change to add "(SVM DR)" at the end.  
This is what a lot of customers (and NetApp field) use when searching documentation.

Table Row 3: "SVMs enabled for data migration"... change to "SVM data mobility (vserver migrate)". SVMs are not "enabled" for data migration...the are simply migrated.

This should make this page more discoverable.

Thanks.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks. These changes have been applied.
