### ISSUE TITLE
DNS Zone configuration step should be removed since it is not neccessary for this configuration

### ISSUE THREAD

**Issue by mpittman-netapp** [NetAppDocs/ontap#1281]
### Page URL

https://docs.netapp.com/us-en/ontap/networking/configure_dns_for_host-name_resolution.html

### Page title

 Configure DNS for host-name resolution

### Summary

Under the section "Configure an SVM and data LIFs for host-name resolution using an external DNS server", step 2 ("Enable DNS on LIFs owned by the SVM") is modifying the LIFs to use a DNS Zone, and that parameter is used with a different ONTAP feature than standard host-name resolution that is being discussed in this section.  With this, this step should be removed.  I am not sure if the intent of this step was to advise users about service policies since those control what LIF is used for DNS communications, so it may be useful to at least link to the section that discusses them - [LIFs and service policies (ONTAP 9.6 and later)](https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for reporting this issue. I will investigate and follow up here.

**Comment by netapp-barbe** [comment]
This has been corrected: https://docs.netapp.com/us-en/ontap/networking/configure_dns_for_host-name_resolution.html
