### ISSUE TITLE
Missing information about the Certificate for Mediator.

### ISSUE THREAD

**Issue by sgalla-netapp** [NetAppDocs/ontap#1282]
### Page URL

https://docs.netapp.com/us-en/ontap/smbc/smbc_install_confirm_ontap_cluster.html

### Page title

Configure the ONTAP Mediator and clusters for SnapMirror Business Continuity

### Summary

For the document, it needs to be mentioned that the certificate can be found on the mediator server at _/opt/netapp/lib/ontap_mediator/ontap_mediator/server_config/ca.crt_.   In addition, for the CLI, the certificate needs to be installed first with the command _security certificate install -type server-ca -vserver <vserver>_. where vserver is the vserver for the cluster.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @sgalla-netapp . This has been updated.
