### ISSUE TITLE
Align NFS/SMB instructions to UI

### ISSUE THREAD

**Issue by juliantap** [NetAppDocs/ontap#1283]
### Page URL

https://docs.netapp.com/us-en/ontap/task_nas_provision_nfs_and_smb.html

### Page title

Provision NAS storage for both Windows and Linux using both NFS and SMB

### Summary

**Comments from user testing**
1. The docs don't align with the UI dialog. Here's a screenshot of the discrepancy. The line should instead say "Export via NFS". 

![image](https://github.com/NetAppDocs/ontap/assets/83591660/d7fe3c68-f277-4228-8042-702686a8a525)

2. In looking docs, there is also a mismatch for the "Share with SMB" line. The UI says "Share via SMB/CIFS".
3. Users were unsure which option applied to Linux and which applied to Windows. They suggest that Linux be mentioned for NFS and Windows for SMB to reduce reliance on preexisting industry knowledge.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Update complete.  Thank you for the feedback
