### ISSUE TITLE
NFS trunking needs greater detail around failover

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/ontap#1285]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-trunking/prepare-network-task.html

### Page title

Prepare your network for trunking

### Summary

The documentation is clear about the requirement to use ports on the same node for NFS v4.1 trunking - however if all ports in the failover group are on the same node, then a controller failover will cause the LIF to go offline.  Documentations needs a section on how to maintain redundancy to keep the LIF online or list limitations. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Moved to internal issue: ONTAPDOC-2577
