### ISSUE TITLE
Page doesn't include any links

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#1290]
### Page URL

https://docs.netapp.com/us-en/ontap/task_cp_monitor_cluster_performance_ci.html

### Page title

Monitor cluster performance with Cloud Insights

### Summary

This page should include links to learn more about Cloud Insights, including how to get started with it.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Added related links to Learn more about Cloud Insights and How to get started.  Thank you for your feedback.
