### ISSUE TITLE
Page doesn't tell me why

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#1291]
### Page URL

https://docs.netapp.com/us-en/ontap/task_admin_download_cluster_config.html

### Page title

Download a cluster configuration

### Summary

Why would I want to download a cluster configuration? What would I do with? We need to address motivation and intent.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
The reasons to download configuration data have been added - thank you for the feedback.
