### ISSUE TITLE
Need to update the features relased in recent releases 9.13.1, 9.14.1

### ISSUE THREAD

**Issue by harshitmarwah1** [NetAppDocs/ontap#1293]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-config/ontap-s3-interoperability-concept.html

### Page title

ONTAP S3 interoperability

### Summary

Features like WORM, Snaplock(Objectlock) are now supported from 9.14.1 onwards. 

### Public issues must not contain sensitive information

- [X] #1294

**Comment by netapp-lenida** [comment]
Thank you @harshitmarwah1. The supported features list has been updated.
