### ISSUE TITLE
typo in SeSecurity priveldege row description

### ISSUE THREAD

**Issue by SuperJT** [NetAppDocs/ontap#1295]
### Page URL

https://github.com/NetAppDocs/ontap/blob/main/smb-admin/list-supported-privileges-reference.adoc

### Page title

List of supported privileges

### Summary

`
SeSecurityPrivilege | BUILTIN\Administrators | Manage auditingThis includes viewing, dumping, and clearing the security log.
-- | -- | --

SeChangeNotifyPrivilege | BUILTIN\Administrators, BUILTIN\Backup Operators, BUILTIN\Power Users, BUILTIN\Users, Everyone | Bypass traverse checkingUsers with this privilege are not required to have traverse (x) permissions to traverse folders, symlinks, or junctions.
-- | -- | --

`

There should be some sort of punctuation after auditing, and after checking in the next row

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Update posted.  Thank you for the feedback.
