### ISSUE TITLE
Limits have changed

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/ontap#1296]
### Page URL

https://docs.netapp.com/us-en/ontap/san-admin/configure-nvme-lif-task.html

### Page title

Configure an NVMe LIF

### Summary

The LIF/node limits changed in ONTAP 9.12.1 but are not reflected in this page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@netapp-bingen I've updated the topic with the 9.12.1 node limit change:

Beginning in ONTAP 9.12.1 and later, you can configure two NVMe LIFs per node on a maximum of 12 nodes. In ONTAP 9.11.1 and earlier, you can configure two NVMe LIFs per node on a maximum of two nodes.
