### ISSUE TITLE
Missing DNS and NTP info

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#1298]
### Page URL

https://docs.netapp.com/us-en/ontap/task_configure_ontap.html

### Page title

Configure ONTAP on a new cluster with System Manager

### Summary

This page should mention if (or where) DNS server and NTP server information is entered. These two items are also usually part for cluster setup.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Update complete.
