### ISSUE TITLE
Question over SVM

### ISSUE THREAD

**Issue by dirvine24** [NetAppDocs/ontap#1299]
### Page URL

https://docs.netapp.com/us-en/ontap/peering/configure-intercluster-lifs-share-data-ports-task.html

### Page title

Configure intercluster LIFs on shared data ports

### Summary

I would usually created inter-cluster LIF's in the admin SVM not the system SVM. Not sure if this page is correct.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Interesting question! I have done some research and have a question out to engineering.

**Comment by netapp-barbe** [comment]
This issue has been corrected: https://docs.netapp.com/us-en/ontap/peering/configure-intercluster-lifs-share-data-ports-task.html
