### ISSUE TITLE
Remove or modify statement about "No other clients should be configured on it"

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/ontap#1305]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-trunking/create-server-task.html

### Page title

Create a trunking-enabled NFS server

### Summary

This statement may no longer be accurate: 
"dedicated to NFS trunking. No other clients should be configured on it"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Thanks @netapp-bingen , we'll check with ENG on this. Would they be the authority on the requirement?

**Comment by netapp-ahibbard** [comment]
Thanks @netapp-bingen . The documentation has been updated with a recommendation from engineering.
