### ISSUE TITLE
Remove ownership from a disk

### ISSUE THREAD

**Issue by bejoegcv** [NetAppDocs/ontap#1307]
### Page URL

https://docs.netapp.com/us-en/ontap/disks-aggregates/remove-ownership-disk-task.html

### Page title

Remove ownership from a disk

### Summary

**_Currently_**
4. If the disk is partitioned for root-data partitioning, remove ownership from the partitions:

a. For ONTAP 9.10.1 and later, enter:

storage disk removeowner -disk disk_name

This command did not for ONTAP 9.10.1P12 & had the error as shown in 
[KB: https://kb.netapp.com/onprem/ontap/hardware/Error%3A_command_failed%3A_Failed_to_remove_the_owner_of_disk]

**_Recommended changes_**:
4. If the disk is partitioned for root-data partitioning, remove ownership from the partitions:

a. For ONTAP 9.10.1 and later, remove the ownership of the partitions from the nodeshell
Example:
Cluster::> storage disk option modify -node * -autoassign off
Cluster::> node run -node nodename
Node> priv set advanced
Node*> disk remove_ownership 0a.00.16P2 <------- example disk
Node*> exit
Cluster::> storage disk option modify -node * -autoassign on

Ref: https://kb.netapp.com/onprem/ontap/hardware/Error%3A_command_failed%3A_Failed_to_remove_the_owner_of_disk

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
The commands listed above are diag level commands which we don't document in the customer facing content.  However, I've added a note to the topic that to remove ownership for disk using root-data partitioning in 9.10.1 or later, customers should contact tech support.  I've also added the KB link for reference.  Update will be posted shortly.

**Comment by netapp-aherbin** [comment]
Update posted.
