### ISSUE TITLE
Should be supported the Autonomous Ransomware Protection with FlexGroup origin volume.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#1316]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

### Page title

Supported and unsupported features for FlexCache volumes

### Summary

![image](https://github.com/NetAppDocs/ontap/assets/68621663/9b8e43bc-0c0b-4cf9-adc6-f4b80ead343c)

It states that ARS is not supported if the origin is a FlexGroup volume.
However, with ONTAP 9.13.1, the combination of ARS and FlexGroup is now OK.
https://docs.netapp.com/ja-jp/ontap/flexgroup/supported-unsupported-config-concept.html
Therefore, I believe that ARS and FlexGroup can be used together on FlexCache origin volumes, but could you please confirm the correct information?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @kanitani. I'm working with the FlexCache TME to get this answered for you.

**Comment by netapp-lenida** [comment]
The FlexCache supported features table has been updated to include support for ARP on the FlexGroup origin volumes beginning with ONTAP 9.13.1.

**Comment by kanitani** [comment]
I've been waiting a long time for your reply (exactly 4 months!)
I expect a speedy response.
If the response from engineering is slow, please keep pushing.

**Comment by netapp-ehoffman** [comment]
@kanitani , thank you for raising this issue. As @netapp-lenida noted above, the docs were updated in late June with this correction. Lenida was delayed in closing the issue until this week.

**Comment by kanitani** [comment]
Aren't both she and the engineering team responding too slowly?
Our business and the customer's business moves fast, and we need a response within a week for such a simple check.

If you don't get a response from the engineering within three days, please push it. If there's still no response after a week, please push again and again.
And if you get a response, please respond it to the questioner (=me) right away.

It's okay to update the documentation later.
