### ISSUE TITLE
Wanna know how lon would it takes

### ISSUE THREAD

**Issue by easy061** [NetAppDocs/ontap#1319]
### Page URL

https://docs.netapp.com/us-en/ontap/flexgroup/convert-flexvol-snapmirror-relationship-task.html

### Page title

Convert a FlexVol volume SnapMirror relationship to a FlexGroup volume SnapMirror relationship

### Summary

Hello Vorwerk,

Could you add information about the time consumption of the conversion?
Does the capacity matter? How long does it take in your environment ?

Thank you and best regards,
Randy

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
@easy061, thank you for contacting us. I checked with one of our FlexGroup experts, and he explained that there are too many variables for determining the amount of time any given conversion will take. Some of the factors that affect the conversion time include:

- CPU of the controller
- Utilization of CPU by other applications
- Amount of data in the initial Snapshot
- Network bandwidth
- Utilization of bandwidth by other applications

I have added this information to the documentation, however, there is nothing specific that I can add about the amount of time it takes for a conversion.
