### ISSUE TITLE
Unrelated link to E Series

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap#1321]
### Page URL

https://docs.netapp.com/us-en/ontap/concepts/rdma-concept.html

### Page title

RDMA overview

### Summary

Hi,
at the very bottom of the page there is a link named "Configure storage array NVMe over RoCE connections" - leading to https://docs.netapp.com/us-en/e-series/config-linux/nvme-roce-configure-storage-connections-task.html.
That is E Series documentation and iunrelated to ONTAP 9 and its RDMA and NVMe functionality.
This link should be removed.
Cheers, Niels

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
Linked removed. Changes are live.
