### ISSUE TITLE
Missing instructions for creating or deleting snapshots in System Manager

### ISSUE THREAD

**Issue by binder1234** [NetAppDocs/ontap#1326]
### Page URL

https://docs.netapp.com/us-en/ontap/task_dp_configure_snapshot.html

### Page title

Configure Snapshot copies

### Summary

The documentation covers setting a local policy for a volume in System Manager but doesn't cover steps for either manually creating or deleting snapshots in System Manager.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by binder1234** [comment]
Most of the documentation for creating or deleting snapshots seems to be limited to cli examples.

**Comment by netapp-lenida** [comment]
Thanks @binder1234. I'll look into this.

**Comment by netapp-lenida** [comment]
Thanks again @binder1234. The topic has been added here: https://docs.netapp.com/us-en/ontap/data-protection/create-delete-snapshot-manually-task.html.
