### ISSUE TITLE
URL broken

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/ontap#1329]
### Page URL

https://docs.netapp.com/us-en/ontap/release-notes/9121-reference.html

### Page title

What's new in ONTAP 9.12.1

### Summary

In the below parapgraph the URL is broken. have highlighted it in bold.

Beginning with ONTAP 9.12.1, System Manager is integrated with BlueXP. With BlueXP, administrators can manage the hybrid multicloud infrastructure from a single control plane while retaining the familiar System Manager dashboard. When signing into System Manager, administrators are given the option of accessing the System Manager interface in BlueXP or accessing System Manager directly. Learn more about [System Manager integration with BlueXP](**https://docs.netapp.com/us-en/ontap/ontap/sysmgr-integration-bluexp-concept.html**).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@sabarig84 thanks for reporting this. We'll take care of it in our next doc update.
