### ISSUE TITLE
Fix bad info about extended groups and client interoperability

### ISSUE THREAD

**Issue by elliottecton** [NetAppDocs/ontap#1330]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-admin/configure-number-group-ids-allowed-nfs-users-task.html

### Page title

Configure the number of group IDs allowed for NFS users

### Summary

This information callout is incorrect:

Some older NFS clients might not be compatible with AUTH_SYS extended groups.

The client has nothing to do with extended groups when using AUTH_SYS. An RPC header is an RPC header, which is where the limitation exists.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@elliottecton thanks. The note has been removed.
