### ISSUE TITLE
Clarify that multipath routing is not ECMP

### ISSUE THREAD

**Issue by matthewjmiller1** [NetAppDocs/ontap#1331]
### Page URL

https://docs.netapp.com/us-en/ontap/networking/enable_multipath_routing.html

### Page title

Enable multipath routing

### Summary

> If multiple routes have the same metric for a destination, only one of the routes is picked for outgoing traffic. This leads to other routes being unutilized for sending outgoing traffic. You can enable multipath routing to load balance and utilize all the available routes.

May want to clarify, since the first sentence mentions the same metric, that multipath routing will load balance across all available routes of all metrics. I.e., to clarify that this is not ECMP where it load balances across available routes of the same metric.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for raising this issue, I will investigate and update shortly.

**Comment by netapp-barbe** [comment]
Corrected, thank you: https://docs.netapp.com/us-en/ontap/networking/enable_multipath_routing.html
