### ISSUE TITLE
Move Flash Pool comment to FAS systems as it does not make sense for AFF

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap#1335]
### Page URL

https://docs.netapp.com/us-en/ontap/fabricpool/requirements-concept.html

### Page title

Considerations and requirements for using FabricPool

### Summary

In the list of supported aggregate types, non-support for Flash Pool is mentioned under AFF but not under FAS.

As an AFF can't have spinning disks in the first place it doesn't make sense to have it under AFF.

FAS can have Flash Pool but don't have the limitation listed so suggest moving it there.

<img width="715" alt="Screenshot 2024-04-22 at 12 01 24" src="https://github.com/NetAppDocs/ontap/assets/2291693/82484b15-a5d0-46ee-b004-2ff980e169d5">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @estarz. I'll look into this.

**Comment by netapp-lenida** [comment]
Thanks @estarz, the topic has been updated.
