### ISSUE TITLE
Suggestion for root volume load-sharing mirrors document.

### ISSUE THREAD

**Issue by jogeorg2** [NetAppDocs/ontap#1336]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/create-load-sharing-mirror-task.html

### Page title

Create and initializing load-sharing mirror relationships

### Summary

Near the bottom, the document states that initializing a load-sharing mirror can be time-consuming, but this is not true because this is a 1GB volume. Initialization takes very little time and it is not necessary to do this during off-peak hours.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
@jogeorg2, thanks for contacting us. This statement is probably old, referring to a time when load-sharing mirrors were not just for root volume data protection and could potentially contain more data. I have verified this with a subject matter expert, and I will remove the statement.

**Comment by netapp-lenida** [comment]
This issue has been fixed. The statement was removed.
