### ISSUE TITLE
Request to add descrition of arw snapshot options 'arw.snap.new.extns.interval.hours'

### ISSUE THREAD

**Issue by PolarLiu12** [NetAppDocs/ontap#1337]
### Page URL

https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-shapshot-options-task.html

### Page title

Modify options for automatic Snapshot copies

### Summary

Hi Team,

Here is Polar from JP language Team.
Our partner requires for adding the description of a new arw snapshot options 'arw.snap.new.extns.interval.hours' on this page:

https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-shapshot-options-task.html

arw.snap.new.extns.interval.hours

    This option specifies the interval (in hours) between the Anti-ransomware generated snapshot copies for the new extension based detection.
    A new Anti-ransomware snapshot copy will be created when a new file extension is observed, and the previous snapshot created upon
    observing a new file extension is older than this specified interval. On a workload that frequently creates new file extensions, this
    interval helps in controlling the frequency of the snapshot copies created by Anti-ransomware. There is another option
    arw.snap.create.interval.hours which specifies the interval between the Anti-ransomware generated snapshot copies for the data entropy
    based detection.

    The supported values for the -option-value parameter include integers from 24 to 8760. The default value of this option is 48.

Could you help to review?

Thanks,
Polar.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by PolarLiu12** [comment]
Hi Team,

May I ask for update on this?

Thanks,
Polar.

**Comment by netapp-ahibbard** [comment]
This has been updated. Thanks @PolarLiu12
