### ISSUE TITLE
How do we trigger a plan when Autosupports are disabled?

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap#1339]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html

### Page title

Create an ONTAP upgrade plan

### Summary

we should add a note about 
Note: Upgrade Advisor requires a full AutoSupport bundle to create the report. 

then link them to - [How to manually upload AutoSupport messages to NetApp in ONTAP 9](https://kb.netapp.com/onprem/ontap/os/How_to_manually_upload_AutoSupport_messages_to_NetApp_in_ONTAP_9)

thank you

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@loganbaez thanks. Added the note and related link.

**Comment by netapp-dbagwell** [comment]
@loganbaez after closing this issue, we've had a question about what's meant by a "full AutoSupport bundle" and the phrasing of the note. Here's the comment:
What is a reader expected to know and do based on this statement? For example, do they need to create the bundle and do something with it? Or does AutoSupport create bundles on some recurring basis? If so, where would that bundle be and under what circumstances would it be sufficient vs the customer having to manually build the bundle.

Can you give some extra clarity behind your requested addition of the note?

**Comment by loganbaez** [comment]
hello Dave, 
might be eaiser to talk thru this one together

the kb explains this further, not sure if you want to add more scenarios in the docs itself?

this kb is also related - https://kb.netapp.com/on-prem/ontap/DM/System_Manager/SM-KBs/Upgrade_Advisor_fails_to_generate_upgrade_plan_in_Active_IQ_Digital_Advisor

**all scenarios are as follows**

- Asup enabled - you can use upgrade advisor
- Asup disabled - you can't , you either walk thru the manual upgrade process or you can upload a manual autosupport to run a tailored upgrade advisor. 

perhaps we can improve the INFO:

- **from** -Upgrade Advisor requires a full AutoSupport bundle to create the report.
- **to** - Upgrade Advisor requires AutoSupport logs to create the report
or
Upgrade Advisor builds a tailored report based on your AutoSupport.
