### ISSUE TITLE
When saying hardware configuration, include the FAS/AFF.

### ISSUE THREAD

**Issue by MrObvious** [NetAppDocs/ontap#1340]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/confirm-configuration.html

### Page title

Confirm ONTAP support for your hardware configuration

### Summary

https://docs.netapp.com/us-en/ontap/upgrade/prepare.html step 4 links to this, and it is a slight gap that it doesn't say explicitly that ONTAP versions may not be compatible. For example, please see case 2009927286.

Thanks,

Paul

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@MrObvious thank you for your feedback.  Could you provide a bit more clarity?  Do you mean the current ONTAP version might not be compatible for a direct upgrade to the target ONTAP version?  The [upgrade paths](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html) cover how a customer gets from any version of ONTAP 9 to any other version.  Or do you mean the current hardware might not support the target ONTAP version?  The topic in question advises the user to check HWU to confirm that the hardware platform is supported in the target ONTAP release.  I'm not sure how to access the case for additional details.  Thank you.

**Comment by netapp-aherbin** [comment]
@MrObvious I **think** what you want to point out is the following:

NOTE:  The version of ONTAP that you can upgrade to might be limited based upon your hardware configuration. If your hardware doesn't support the version of ONTAP software that you want to upgrade to, will to first add new nodes to your cluster, migrate your data, remove the older nodes and then upgrade your ONTAP software.  Follow the procedure to [Add new nodes to an ONTAP cluster](https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html#adding-new-nodes-to-an-ontap-cluster).

**Comment by netapp-aherbin** [comment]
The stated changed has been made.  Closing this issue.  Please feel free to reopen if something else is needed.  Thank you.
