### ISSUE TITLE
management-ntp-server was added in ONTAP 9.10.1 - not ONTAP 9.11.1

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#1344]
### Page URL

https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html

### Page title

LIFs and service policies (ONTAP 9.6 and later)

### Summary

management-ntp-server

Introduced in ONTAP 9.11.1.  <<<< Should be 9.10.1
Services for NTP server management access

I checked source code to verify this is incorrect.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Thank you, @andris-ntap! We'll update the content to reflect and search for other impacted topics. It's possible this was retroactively added to a patch of 9.10.1 after it was introduced in 9.1.1.1, so we can check with the networking team to make sure we have clarity on that.

**Comment by netapp-barbe** [comment]
Thank you again, this fix has been made
