### ISSUE TITLE
Correct UNC path

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/ontap#1345]
### Page URL

https://docs.netapp.com/us-en/ontap/task_nas_provision_home_directories.html

### Page title

Provision NAS storage for home directories

### Summary

Hi,
The following line should be more like
In Windows Explorer, map a drive to the share in the following format: \\_SMB_Server_Name__Share_Name_

In Windows Explorer, map a drive to the share in the following format: \\SMB_Server_Name\Share_Name

Thanks

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@louvipi Thanks, John. We'll get that update into one of our coming doc hot fixes. Appreciate the feedback!

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention. The topic has been updated.
