### ISSUE TITLE
SMB3 Support?

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/ontap#1347]
### Page URL

https://docs.netapp.com/us-en/ontap/flexgroup/index.html

### Page title

FlexGroup volumes management overview with the CLI

### Summary

Hi, I would think ONTAP supports SMB3 as well, just figured I should ask and clarify.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks John. I'll update this topic. Support for SMB 3 is listed here:
https://docs.netapp.com/us-en/ontap/flexgroup/supported-unsupported-config-concept.html

**Comment by netapp-lenida** [comment]
I added a link to the supported and unsupported configurations topic to find additional details.
