### ISSUE TITLE
NFS over RDMA support is (not) limited to node-local traffic only

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/ontap#1348]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html

### Page title

NFS over RDMA

### Summary

> NFS over RDMA support is limited to node-local traffic only. Standard FlexVols or FlexGroups where all constituents are on the same node are supported and must be accessed from a LIF on the same node

That seems incorrect.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @scaleoutsean . The topic has been corrected
