### ISSUE TITLE
Add link to the firmware download

### ISSUE THREAD

**Issue by Wittionary** [NetAppDocs/ontap#135]
Page: [Update ONTAP](https://docs.netapp.com/us-en/ontap/task_admin_upgrade_ontap.html)

Please provide a link to the actual download or page of downloads.

**Comment by netapp-barbe** [comment]
Hi Witt, 
Thank you for the good idea. We are looking into it!
Barb

**Comment by netapp-aherbin** [comment]
Hi Witt, 

In the Upgrade ONTAP, topic that you referenced, there is already a link in step 1 to the download page for the software image.

If you are doing an upgrade, the firmware is updated automatically.  Documented here: https://docs.netapp.com/us-en/ontap/upgrade/concept_how_firmware_is_updated_during_upgrade.html

Outside of the upgrade workflow the link to download/update the firmware is actually inside the UI.  It's documented here: https://docs.netapp.com/us-en/ontap/task_admin_update_firmware.html

Thanks for the feedback.
Amanda
