### ISSUE TITLE
Redundant and incomplete (can something be both...) comment regarding MetroCluster IP

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap#1352]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

### Page title

Supported ONTAP upgrade paths

### Summary

Section "From ONTAP 9.8" has 2 similar lines regarding MetroCluster on certain platforms.

If you are upgrading a MetroCluster IP configuration from 9.8 to 9.10.1 or later on any of the following platforms, you must upgrade to 9.9.1 before you upgrade to 9.10.1 or later.

and 

Clusters in MetroCluster IP configurations on these platforms cannot be upgraded directly 9.8 to 9.10.1 or later. The listed direct upgrade paths can be used for all other platforms.

The second mentioning is vaguer as it does not mention 9.9.1 and also the word "from" is missing before the 9.8.

Had to read through this section a couple of times before I understanding what it said.
I feel it should be changed in some way to make it easier to read and understand.

Maybe we can create a separate table for the mentioned platforms?

"If you have controllers X, Y or Z with MetroCluster IP"
"<new table including the 9.9.1 intermediate step>"
"All other platforms"
"<existing table>"

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@estarz thanks for bringing this to our attention. We'll take a look at it and make clarifications to the content. Will keep you posted in this issue.

**Comment by netapp-dbagwell** [comment]
Updated note: https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#from-ontap-9-8
Thanks again for your feedback.
