### ISSUE TITLE
List of supported systems and adapters seems to be incomplete

### ISSUE THREAD

**Issue by campbj70** [NetAppDocs/ontap#1353]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html

### Page title

NFS over RDMA

### Summary

This article does not mention the X1152 adapter as being RDMA/RoCE compatible. HWU says otherwise (see PNG). 
<img width="836" alt="x1152" src="https://github.com/NetAppDocs/ontap/assets/99951397/e6033a7b-b0c2-467b-9c98-2ae5c0d0d358">
This adapter can be installed in the following systems i.e. A250 etc.
<img width="476" alt="other systems" src="https://github.com/NetAppDocs/ontap/assets/99951397/76ea1874-a509-4690-8a65-4632ded543ef">

Please update this document and other ONTAP documents which do not acknowledge that the X1152 25Gb adapter is RDMA/RoCE capable. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
@campbj70 , thanks for making us aware of this. We'll address soon.

**Comment by netapp-ahibbard** [comment]
This has been updated. Thanks.
