### ISSUE TITLE
Old brand name

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/ontap#1354]
### Page URL

https://docs.netapp.com/us-en/ontap/performance-admin/index.html

### Page title

Performance monitoring and management overview

### Summary

VSC is now known as ONTAP tools for VMware vSphere, or just ONTAP tools for short.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@netapp-bingen thanks for reporting this! We're tracking this issue internally now. I've added you as a watcher for the internal issue. Closing this issue as it's public facing.
