### ISSUE TITLE
Mention need to create aggregate using -disklist

### ISSUE THREAD

**Issue by Florian7843** [NetAppDocs/ontap#1361]
### Page URL

https://docs.netapp.com/us-en/ontap/concepts/root-data-partitioning-concept.html

### Page title

Root-data partitioning

### Summary

Hello,

I was recently trying to create a new unmirrored aggregate on my root-data-data partitioned metrocluster. 

Creating always failed when only specifiying -diskcount, because not enough matching disks are available. I could only circumvent this by specifying -disklist.

I think it would be benefitical if there was a mention of this behaviour on the advanced data partitioning and the storage aggregate create page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for your feedback, I will investigate and reply here.

**Comment by netapp-barbe** [comment]
Assigning to Aoife to the ontap-metrocluster repo. Consider making an update or adding a note to this topic:
https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_create_unmirrored_data_aggregates_mcc.html

**Comment by netapp-aoife** [comment]
Hi there, thanks again for raising this issue. We've made an update here to address your feedback: https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_create_unmirrored_data_aggregates_mcc.html
