### ISSUE TITLE
Correction: Volume->Snapshot autodelete not supported by SVM-DR

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#1364]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-concept.html

### Page title

About SnapMirror SVM replication

### Summary

Section: Configurations replicated in SVM disaster recovery relationships

Please correct the following table entry:

Volume
   Snapshot copies, Snapshot policy, and autodelete policy
            Remove "autodelete policy"...this is not currently replicated.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks again, Tony. This topic has been fixed.
