### ISSUE TITLE
Make this document actually useful

### ISSUE THREAD

**Issue by weeglos** [NetAppDocs/ontap#1365]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/automatic-deduplication-schedule-aff-concept.html

### Page title

Manage automatic volume-level background deduplication on AFF systems

### Summary

This document is completely useless if it describes a feature available but neglects to demonstrate how to actually use that feature.  

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
This issue has been fixed and merged.  The guidance has been improved and the concept topic now reads like a concept topic, with links to the actual task topics for using the feature. Thanks for bringing this to our attention, @weeglos.
