### ISSUE TITLE
-object-store-name instead of -name

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/ontap#1369]
### Page URL

https://docs.netapp.com/us-en/ontap/fabricpool/replace-existing-object-store-mirror-task.html

### Page title

Replace an existing object store using a FabricPool mirror

### Summary

Tested on 9.14.1
Here it was cluster1::> storage aggregate object-store mirror -aggregate aggr1 -object-store-name my-AZURE-store 
instead of -name

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
@kholger, thank you for bringing this to our attention. The command has been updated.
