### ISSUE TITLE
Protection level for SnapLock compliance and enterprise modes

### ISSUE THREAD

**Issue by y-halim** [NetAppDocs/ontap#1370]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/index.html

### Page title

What SnapLock is

### Summary

The protection level for compliance and enterprise modes must be reversed in the table under the section "SnapLock Compliance and Enterprise Modes": 
- Compliance mode: at the disk level (instead of file level).
- Enterprise mode: at the file level (instead of disk level).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @y-halim. The protection level in the table has been updated.
