### ISSUE TITLE
Mediator 1.8 Whats New

### ISSUE THREAD

**Issue by chjones45** [NetAppDocs/ontap#1374]
### Page URL

https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html

### Page title

What's new with the ONTAP Mediator

### Summary

Can we please get the 1.8 details added to this page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ranuk** [comment]
We are working on this content. Thank you!

**Comment by netapp-ranuk** [comment]
Hi @chjones45,

The ONTAP Mediator 1.8 details have been added to the "What's New" page. Please see https://docs.netapp.com/us-en/ontap/mediator/whats-new-concept.html.

Thanks!
