### ISSUE TITLE
Enabling space allocation does not require offlining the LUN

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#1376]
### Page URL

https://docs.netapp.com/us-en/ontap/san-admin/enable-space-allocation.html

### Page title

Enable space allocation for SAN

### Summary

The statement "You must take the LUN offline to enable space allocation" is incorrect. You'll probably need to restart the host to make the changes take effect, but I see no reason to offline the LUN and ONTAP does not impose this restriction.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@jfsinmsp thanks for the feedback. We'll look into this and make needed corrections in a coming doc update.

**Comment by netapp-dbagwell** [comment]
@jfsinmsp the changes we worked out together are now live. Thanks!
