### ISSUE TITLE
This statement seems to be wrong and we need to re-phrase it

### ISSUE THREAD

**Issue by jdaecher** [NetAppDocs/ontap#1379]
### Page URL

https://docs.netapp.com/us-en/ontap/high-availability/ha_how_automatic_takeover_and_giveback_works.html

### Page title

How automatic takeover and giveback works

### Summary

We have this statement on the page:
[Quote]
Due to the nature of the SMB protocol, all SMB sessions are disrupted (except for SMB 3.0 sessions connected to shares with the Continuous Availability property set). SMB 1.0 and SMB 2.x sessions cannot reconnect after a takeover event; therefore, takeover is disruptive and some data loss could occur. 
[/Quote]

But technically this is wrong. SMB 1.0 and SMB 2.x session will automatically reconnect after the takeover event.
Though, they cannot reclaim their file-handles which makes it disruptive to these clients.
Regarding the "data loss could occur", we need to think if that is the right wording.
I believe, there is a chance of data loss if there currently is data in-flight, which is not cached by the client and the application crashes. But this should be a very rare situation.

The general statement above sounds pretty scary. A customer might think that every takeover can cause a data loss if they are using CIFS/SMB. Which basically is NOT the case.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@jdaecher thanks for your feedback. We'll look into improving the statement and keep you posted on progress.

**Comment by netapp-dbagwell** [comment]
Changes are live: https://github.com/NetAppDocs/ontap/pull/1409
Only minor changes were recommended by the team. The recommendation was to retain the "data loss" language.
