### ISSUE TITLE
Note for Snapmirror policy creation on both original source SVM and original DR SVM

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/ontap#1380]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/exclude-lifs-svm-replication-task.html

### Page title

Exclude LIFs and related network settings from SVM replication

### Summary

Please add a note or make it very clear that creating a custom policy excluding LIFs (Step 4) needs to be created on both the original source SVM and original DR SVM.

I ran into an issue while testing SVMDR for Azure CVO HA:  While reactivating the original source SVM, the resync errors/fails due to a port probe issue.  The cause was due to not having a snapmirror policy excluding LIFs on the original source side.

While it does state in step 1: "From the original source SVM or the original source cluster, create a reverse SVM DR relationship using the same configuration, policy, and identity-preserve setting as the original SVM DR relationship:" in reactivating the source SVM steps located here: https://docs.netapp.com/us-en/ontap/data-protection/reactivate-original-source-svm-task.html.  It is not very clear for a non data protection person.

In my opinion, in step 1 of the reactivate original source SVM steps, you should add the snapmirror policy create commands prior to the snapmirror create commands so that it is more clear.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by virtualhawk** [comment]
to add to the last sentence:

Or in step 4 of this page, make it clear that the custom policy needs to be created on both sides and provide the examples.

**Comment by netapp-lenida** [comment]
Thanks @virtualhawk. I've added the following note to the "Exclude LIFs and related network settings from SVM replication" topic:
Note: Consider creating the same custom SnapMirror policy on the source cluster for future failover and failback scenarios.
