### ISSUE TITLE
Add verbage about caveat for creating flexcache of a snapmirrored destination

### ISSUE THREAD

**Issue by dstauba** [NetAppDocs/ontap#1381]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

### Page title

Supported and unsupported features for FlexCache volumes

### Summary

I checked this page and found that as of 9.8, ONTAP supports creating a Flexcache volume of a snapmirrored destination, however, I discovered that it will fail if the snapmirror is actively being updated.  Once the snapmirror was "Idle" the flexcache volume creation was successful.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @dstauba. I'm looking into to this.

**Comment by netapp-lenida** [comment]
Thanks @dstauba. The topic has been updated.
