### ISSUE TITLE
Clarify namespace limitations

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/ontap#1388]
### Page URL

https://docs.netapp.com/us-en/ontap/nvme/support-limitations.html

### Page title

NVMe configuration, support, and limitations

### Summary

I think this part could use some additional clarifications:

> When working with NVMe namespaces, you should be aware of the following:
>
> * If you lose data in a LUN, it cannot be restored from a namespace, or vice versa.

What type of "restore" does this refer to? I think it refers to SnapRestore (single-file? volume?) and that LUNs and namespaces are different things that cannot be "single-file snap-restored" to each other. But as it is written it sounds a bit ambiguous (e.g. you can always do a client-side restore of the data *in* a LUN, but not the LUN itself).
Maybe rewrite it something like this: "You cannot use SnapRestore to restore a namespace from a LUN or vice-versa"

> You cannot create a namespace on a volume transition from Data ONTAP operating in 7-mode.

Grammar error. Should be: "...on a volume **transitioned** from..."

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@darkstar thank you for your feedback.  by "SnapRestore" I think you are referring to the snapmirror restore command.  And you are correct that snapmirror restore can't be used.  I think the general intent of the statement is to say, regardless of method (CLI or SM), you cant' restore a namespace from a snapshot of a LUN.  Making the update to read:  "You cannot restore a namespace from a snapshot of a LUN and vice versa."  

Please comment if you feel additional clarity is needed.

**Comment by netapp-aherbin** [comment]
No additional comments received.  Closing.
