### ISSUE TITLE
9.12.1 and above release notes need to warn about Users cannot access CIFS shares after ONTAP upgrade to 9.12.1 and later

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/ontap#1389]
### Page URL

https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9121.html

### Page title

What's new in ONTAP 9.12.1

### Summary

Hi,

It seems that there have been some changes made in 9.12.1 which was causing disruption to CIFS.
https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/Many_secd.rpc.authRequest.blocked_alerts_after_upgrading_to_9.12

https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/Users_cannot_access_CIFS_shares_after_ONTAP_upgrade_to_9.12.1_and_later

check the KBs and add it under upgrade warning or new feature.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@sabarig84 thanks for alerting us about the issue. We're assessing the content change and will keep you posted on progress.

**Comment by netapp-sumathi** [comment]
The "Caution Note" is added to the release notes - https://library.netapp.com/ecm/ecm_get_file/ECMLP2492508
**Topic:** Upgrade caution
**Functionality:** CIFS shares cannot be accessed after upgrade

**Comment by netapp-sumathi** [comment]
Update is published. 
https://library.netapp.com/ecm/ecm_get_file/ECMLP2492508
