### ISSUE TITLE
Poor choice of link in "Storage efficiency" section

### ISSUE THREAD

**Issue by adamn-netapp** [NetAppDocs/ontap#1390]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/index.html

### Page title

What SnapLock is

### Summary

In the "Storage efficiency" section on this page, we include the following:

> For more information about storage efficiency, see [Logical storage management overview with the CLI](https://docs.netapp.com/us-en/ontap/volumes/index.html).

I cannot understand why we use this link to refer the reader to a section that discusses storage efficiency. What is the logic? Wouldn't it be better to link to this topic - https://docs.netapp.com/us-en/ontap/concepts/storage-efficiency-overview.html? Or, if this section is describing new SnapLock functionality that is configurable, it would be even better to link to a topic that talks about how to configure these features with SnapLock.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for the suggestion @adamn-netapp. The topic has been updated with the new link.
