### ISSUE TITLE
Typo on page 15 of PDF version of this document shows 'xref:./releasenotes' metadata

### ISSUE THREAD

**Issue by StorageDan** [NetAppDocs/ontap#1391]
### Page URL

https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9151.html

### Page title

What's new in ONTAP 9.15.1

### Summary

There is a typo on page 15 of PDF version of this document.

The very last link on the page shows the metadata right before the actual link to the online NetApp documentation (which does work):
xref:./releasenotes

![Typo in NetApp PDF document - What's new in ONTAP 9 15 1](https://github.com/NetAppDocs/ontap/assets/154554621/d09d128a-0911-4b7c-9ce5-cc3cea140676)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@StorageDan thanks. We'll address this in the next doc rev.
