### ISSUE TITLE
Can it be converting online?

### ISSUE THREAD

**Issue by easy061** [NetAppDocs/ontap#1393]
### Page URL

https://docs.netapp.com/us-en/ontap/disks-aggregates/convert-raid-dp-tec-task.html

### Page title

Convert from RAID-DP to RAID-TEC

### Summary

Kindly add information about if it can be converting without service disruption.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Hi @easy061, we're in the process of updating the documentation in this area to point to the manual pages for the "storage aggregate modify" command, which give more detail about converting between RAID types.  To answer your above question, there is no service disruption for converting from RAID-DP to RAID-TEC.  The aggregate group remains online, although a reconstruction is triggered so there might be slightly degraded performance. You can see more information here: 
https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameters  (see the -t parameter)

Thank you,
Michael

**Comment by netapp-mwallis** [comment]
Hi @easy061, this change is now public.  Thanks!
