### ISSUE TITLE
missing info in release notes or upgrade cautions for 9.12.1

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/ontap#1395]
### Page URL

https://docs.netapp.com/us-en/ontap/release-notes/whats-new-9121.html

### Page title

What's new in ONTAP 9.12.1

### Summary

please check the KB provided here.
https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/S3_SnapMirror_fails_to_create_due_to_missing_licenses.

Add the changes around this in necessary sections/release notes.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thank you @sabarig84. The details have been added to the Upgrade Cautions in the Release Notes.
