### ISSUE TITLE
System Manager method to create an interface group or LAG needs update

### ISSUE THREAD

**Issue by kaminis85** [NetAppDocs/ontap#1399]
### Page URL

https://docs.netapp.com/us-en/ontap/networking/combine_physical_ports_to_create_interface_groups.html

### Page title

Combine physical ports to create interface groups

### Summary

Topic - Create an interface group or LAG
System Manager method is showing the option of Broadcast domain as below-

Choose from the following:
ONTAP to Automatically select broadcast domain (recommended).
To manually select a broadcast domain.

But this option will only show up in System Mgr if those data ports are already part of some broadcast domain. If the data ports are not part of any broadcast-domain, then the option of broadcast-domain does not show up during ifgrp creation.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aoife** [comment]
Hi @kaminis85, thanks for raising this issue! We'll verify and update the documentation accordingly.

**Comment by netapp-barbe** [comment]
According to our product team, the current instructions are correct. I am going to close this issue, but if you have further information to share, please reach out.
