### ISSUE TITLE
Adding SnapMirror to data protection section

### ISSUE THREAD

**Issue by pdiddens** [NetAppDocs/ontap#1400]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-config/ontap-s3-interoperability-concept.html

### Page title

ONTAP S3 interoperability

### Summary

I think SnapMirror should be listed in the "not supported" section for data protection. Emphasizing that S3 SnapMirror is supported might not be sufficient.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention. SnapMirror has been added to the list of unsupported data protection functionality list.
