### ISSUE TITLE
Chnage to RSH/Telnet docs

### ISSUE THREAD

**Issue by sdowling03** [NetAppDocs/ontap#1401]
### Page URL

https://docs.netapp.com/us-en/ontap/system-admin/enable-telnet-rsh-access-cluster-task.html

### Page title

Enable Telnet or RSH access to the cluster

### Summary

Also for correction:
https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-rsh-task.html

Can we improve this RSH documentation as ONTAP no longer uses the firewall commands and the command in step 2 is misleading. I have updated the following KB with the correct steps:
https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_enable_RSH_or_Telnet_access_to_cluster

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for the feedback, I will look into this issue.

**Comment by netapp-barbe** [comment]
Thank you again for the feedback, this issue has been fixed.
