### ISSUE TITLE
Edit Restore from the cloud with system manager section

### ISSUE THREAD

**Issue by oliviermasson** [NetAppDocs/ontap#1407]
### Page URL

https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html

### Page title

Back up data to the cloud using SnapMirror

### Summary

In the Restore from the cloud section, could you please indicate this:

1.     From the source Cluster of a Snapmirror to Cloud relationship
2.     Click Storage > Volumes.
3.     Click the volume you want to restore
4.     Select the Back Up to Cloud tab.
5.     Click Menu Options next to the source volume you want to restore, and select Restore.
6.     Under Source, select a storage VM and then enter the name of the volume to which you want the data restored.
7.     Under Destination, select the Snapshot copy you want to restore.
8.     Click Save.

Because the Backup Up to Cloud tab is only displayed after clicking on the source volume and not only by clicking on Storage > Volume

Regards

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @oliviermasson. I'm in the process of updating the restore task with the updated step.

**Comment by netapp-lenida** [comment]
Thanks @oliviermasson for bringing this to our attention. The missing step has been added.
