### ISSUE TITLE
Please update with correct Zero Trust TR number  TR-4829

### ISSUE THREAD

**Issue by netapp-chrisgeb** [NetAppDocs/ontap#1408]
### Page URL

https://docs.netapp.com/us-en/ontap/zero-trust/zero-trust-overview.html

### Page title

NetApp and Zero Trust

### Summary

https://www.netapp.com/pdf.html?item=/media/19756-tr-4829.pdf

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
Thanks @netapp-chrisgeb. I'll fix that today along with other doc fixes.

**Comment by netapp-dbagwell** [comment]
Changes are live: https://github.com/NetAppDocs/ontap/pull/1409
