### ISSUE TITLE
Information on this page is referencing Cloud Insights vs FabricPool setup.

### ISSUE THREAD

**Issue by virtualhawk** [NetAppDocs/ontap#1410]
### Page URL

https://docs.netapp.com/us-en/ontap/fabricpool/add-connection-to-cloud-task.html

### Page title

Add a connection to the cloud

### Summary

Information on this page is referencing Cloud Insights collector setup vs FabricPool setup.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @virtualhawk. I'll check with our SMEs, but it looks like this topic needs to be removed from the FabricPool section.

**Comment by virtualhawk** [comment]
Hi Lenida,

     After digging deeper into it, the CI collector is not longer available.  Thank you!

**Comment by netapp-lenida** [comment]
Thanks for the additional info!

**Comment by netapp-lenida** [comment]
Thanks again for bringing this to our attention. The topic has been removed.

**Comment by virtualhawk** [comment]
Thank you so much! I appreciate the fast response!


Thanks,



David Hawkins

Professional Services Consultant

Global Services Solutions Center



NetApp

3308927057 -  Direct Phone

***@***.******@***.***>



Upcoming Out of the office: None

________________________________
