### ISSUE TITLE
The default of Space allocation value

### ISSUE THREAD

**Issue by netapptakayuki** [NetAppDocs/ontap#1411]
### Page URL

https://docs.netapp.com/us-en/ontap/release-notes/defaults-limits.html

### Page title

Changes to ONTAP limits and defaults

### Summary

The space allocation is enabled by default for any OS type in the ONTAP 9.15.1 GA now. Is this correct the space allocation enabled by default only newly created VMware LUNs and Hyper-V LUNs ? 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@netapptakayuki you are correct. The statement needs to be modified as follows:
_Space allocation is enabled by default for newly created LUNs. Space allocation had been disabled by default in previous versions of ONTAP (9.14.1 and earlier)._
I will roll the change into a coming doc fix. Thanks!

**Comment by netapp-dbagwell** [comment]
Changes are live: https://github.com/NetAppDocs/ontap-internal/pull/1944
