### ISSUE TITLE
Need to add 2 steps (run 2 commands to complete the LDAP setting)

### ISSUE THREAD

**Issue by desmondpane** [NetAppDocs/ontap#1412]
### Page URL

https://docs.netapp.com/us-en/ontap/authentication/grant-access-nis-ldap-user-accounts-task.html

### Page title

Enable LDAP or NIS account access

### Summary

We followed the steps in the document, but it didn't work. After we ran the following two commands, it worked.

ns-switch modify -vserver <vserver_name> -database passwd -sources files,ldap
ns-switch modify -vserver <vserver_name> -database group -sources files,ldap

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for the feedback - we will investigate and reply here

**Comment by netapp-barbe** [comment]
@desmondpane when you complete the tasks on this page:
https://docs.netapp.com/us-en/ontap/authentication/grant-access-nis-ldap-user-accounts-task.html
There is a section named **After you finish**, which includes a link to this page:
https://docs.netapp.com/us-en/ontap/authentication/enable-nis-ldap-users-access-cluster-task.html#configure-nis-server-access
On that page, the commands you mention are documented in the **Create a name service switch** section. 

Does that solve your issue?
