### ISSUE TITLE
Laundry list of over 30 links begs the question

### ISSUE THREAD

**Issue by adamn-netapp** [NetAppDocs/ontap#1419]
### Page URL

https://docs.netapp.com/us-en/ontap/zero-trust/zero-trust-learn-more.html

### Page title

Learn more about ONTAP Zero Trust content

### Summary

Why do we present the end user with a list of over 30 links in this topic? 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@adamn-netapp thanks. I'll consult the author. We can reassess the value of the links as presented.

**Comment by netapp-ehoffman** [comment]
@adamn-netapp , this is something I should have dealt with before we published, I don't think we'll get much pushback on removing this list from Dan Tulledge. (Many of the links could be presented inline earlier in the doc.)

**Comment by netapp-dbagwell** [comment]
@adamn-netapp the list topic has been removed. Relevant links were inline already in other topics or added inline where relevant. I'll create an internal issue to think about the broader use of a _Related information_ section throughout ONTAP.
