### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by svitakj** [NetAppDocs/ontap#1421]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/replicate-entire-svm-config-task.html

### Page title

Replicate an entire SVM configuration

### Summary

At The point 5 is in example used svm dvs1. In other examples is used svm_backup. I think, it should be consistent.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @svitakj for bringing this to our attention. I'm in the process of making additional updates to this topic, so I'll make this change at the same time.

**Comment by netapp-lenida** [comment]
Thanks again @svitakj. Step 5 has been updated to make it consistent with the other step examples.
