### ISSUE TITLE
should the title be 'manage access ...'?

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/ontap#1423]
### Page URL

https://docs.netapp.com/us-en/ontap/smb-admin/manage-accessibility-users-home-directories-task.html

### Page title

Manage accessibility to users' home directories

### Summary

The term _accessibility_ has [specific connotations](https://en.wikipedia.org/wiki/Accessibility#:~:text=Accessibility%20is%20the%20design%20of,usable%20by%20people%20with%20disabilities.), and I've never seen it used in the context of user access to a system, folder, or permission. I came across the article searching for accessibility information for docs.netapp.com.

https://github.com/search?q=repo%3ANetAppDocs%2Fontap%20accessibility&type=code

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@ntap-bmegan thanks. I'll take a look at where it's used and substitute an appropriate replacement.

**Comment by ntap-bmegan** [comment]
Actually hold on this a little bit, at least for changes? It looks a bit more widespread than I originally realized. Research would be good tho. :)

**Comment by ntap-bmegan** [comment]
@netapp-dbagwell - I spoke with @netapp-myronw, who agrees in principle that we should not use _accessibility_ where we mean _access_. However, we don't have a content standard. I've requested an organization-wide search for the term to provide to the architects. 

You are free to proceed with this issue if the solution is clear or to consider it blocked and wait on a content standard.

**Comment by ntap-bmegan** [comment]
@netapp-dbagwell - I've asked for content standards to weigh in, so I'm closing this issue as not planned. If there will be a standard, they'll alert authors to it and of any necessary actions. Sorry for the runaround.
