### ISSUE TITLE
FlexCache documentation does not show compatibility between versions

### ISSUE THREAD

**Issue by cwaltham** [NetAppDocs/ontap#1425]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

### Page title

Supported and unsupported features for FlexCache volumes

### Summary

Today, there is a great SnapMirror document which describes what versions are supported for use in a relationship: https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html

However, there is not a FlexCache equivalent. The closest thing I can find is this: https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

That document calls out which features are supported in which versions, but not what versions are allowed in a relationship. Can I have an ONTAP 9.6 file system be the source for a 9.14 FlexCache?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for your feedback @cwaltham. After checking with the TME, I've added the following information at the top of the page:

Cache volumes and origin volumes can interoperate as long as both are running on a supported version of ONTAP. Keep in mind that features are supported only when both the cache and the origin are running at least the ONTAP version where support was introduced or a later ONTAP version.
