### ISSUE TITLE
incorrect description about Resync 

### ISSUE THREAD

**Issue by zhuolin-shen** [NetAppDocs/ontap#1426]
### Page URL

https://docs.netapp.com/us-en/ontap/task_dp_restore_from_destination.html

### Page title

Resynchronize a protection relationship

### Summary

currently doc's description below is incorrect
>This procedure replaces the data in the original source volume in an asynchronous relationship so that you can start serving data from the original source volume again and resume the original protection relationship.

because this action via OCSM equal to command below:
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst

so there is no data replace in source volume.
after resycn via OCSM, source volume will overwrite dest volume so dest volume will lose all new data written during the RW period.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Awaiting review feedback from @zhuolin-shen.

**Comment by netapp-lenida** [comment]
The topic has been updated, however I have not received feedback from @zhuolin-shen. I'm closing this issue, but please reopen and add any additional changes if the topic is still incorrect.
