### ISSUE TITLE
No update since Aug 2022: TR-4743: FlexCache in ONTAP

### ISSUE THREAD

**Issue by Khalidnetappps** [NetAppDocs/ontap#1428]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/index.html

### Page title

FlexCache overview

### Summary

Hi Team,
TR-4743: FlexCache in ONTAP has not been updated since Aug 2022. Is there any plan to update it in line with latest ONTAP releases?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@Khalidnetappps thanks for your inquiry. I will respond shortly via email rather than in this public forum. Closing this issue and we can correspond via that thread.
