### ISSUE TITLE
Tamperproof Snapshot Support by CVO (Cloud Volumes ONTAP)

### ISSUE THREAD

**Issue by kmakoto-at-netapp** [NetAppDocs/ontap#1429]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html

### Page title

Lock a Snapshot copy for protection against ransomware attacks

### Summary

Good day!

According with this page, Cloud Volumes ONTAP(CVO) is unsupported.

> Unsupported features
> The following features currently are not supported with tamperproof Snapshot copies:
> 
> Cloud Volumes ONTAP

However, the CVO documentation page states that this feature is supported.
https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-worm-snaplock.html

> You can create tamperproof Snapshot copies of write once, read many (WORM) files on a Cloud Volumes ONTAP system and retain the snapshots in unmodified form for a specific retention period. This functionality is powered by the SnapLock technology, and provides an additional layer of data protection and compliance.

Which one is correct?
If this (ONTAP's page) has not been updated, please update it to the latest status.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @kmakoto-at-netapp. I've removed CVO from the unsupported features list and added it to the supported features, with a link to the CVO topic.
