### ISSUE TITLE
Updating for 9.11.1

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#1430]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/task_verifying_the_san_configuration.html

### Page title

Verify SAN host configuration before an ONTAP upgrade

### Summary

Cross reference this document:
https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html#view-manage-san-igroups

With this:
The columns display various information about the igroups. Beginning with 9.11.1, the connection status of the igroup is also displayed. Hover over status alerts to view details.

So for this doc.... if the current running version of ONTAP is 9.11.1 or newer, use System Manager to view the Connection Status and resolve any issues.  It gives a much clearer display than the CLI options required for the previous ONTAP versions.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@TimMcGue thanks for your feedback. We'll look to address in a coming doc fix.

**Comment by netapp-dbagwell** [comment]
@TimMcGue added a tabbed block to emphasize the SM option for https://docs.netapp.com/us-en/ontap/upgrade/task_verifying_the_san_configuration.html. Change also made to near identical section in https://docs.netapp.com/us-en/ontap/upgrade/task_verifying_the_san_configuration_after_an_upgrade.html
If you need us to provide any additional info, let us know! Thanks again.

**Comment by TimMcGue** [comment]
Looks perfect - thank you!

Tim McGue
Americas Solution Support Engineer
NetApp
314-680-6117 Mobile Phone
***@***.******@***.***>
Activate AI-Powered predictive analytics and proactive support by enabling AutoSupport<https://kb.netapp.com/onprem/ontap/os/How_to_set_up_or__modify_AutoSupport_in_ONTAP_9>
Collection of PowerShell Scripts<https://www.powershellgallery.com/profiles/timmcgue>
Upcoming Time Off:
None Scheduled

**Comment by TimMcGue** [comment]
Looks perfect - thank you!
