### ISSUE TITLE
Missing dash in front of -failover-policy attribute in examples

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#1435]
### Page URL

https://docs.netapp.com/us-en/ontap/networking/configure_failover_settings_on_a_lif.html

### Page title

Configure failover settings on a LIF

### Summary

The CLI examples omit the "dash" character in "-failover-policy" in two places on this page. 
Please correct them with -failover-policy.

Also, remove the space between "-" and "failover-group" in "- failover-group fg3"
Should be: -failover-group fg3

---------------------
Examples of configuring failover settings and disabling failover

The following command sets the failover policy to broadcast-domain-wide and uses the ports in failover group fg3 as failover targets for LIF data1 on SVM vs3:

```
network interface modify -vserver vs3 -lif data1 **failover-policy** broadcast-domain-wide - failover-group fg3

network interface show -vserver vs3 -lif * -fields failover-group,failover-policy

```
```
vserver lif             failover-policy       failover-group
------- -------------- ---------------        --------------
vs3     data1          broadcast-domain-wide  fg3
```

The following command disables failover for LIF data1 on SVM vs3:

`network interface modify -vserver vs3 -lif data1 **failover-policy** disabled`

------------

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@andris-ntap thanks for reporting this. We'll make the updates as part of a coming doc fix.
