### ISSUE TITLE
there are some missing steps here that should be added

### ISSUE THREAD

**Issue by raunEstes** [NetAppDocs/ontap#1438]
### Page URL

https://docs.netapp.com/us-en/ontap/peering/remove-snapmirror-encryption-existing-relationship-task.html

### Page title

Remove cluster peering encryption from an existing peer relationship

### Summary

The procedure to Remove cluster peering encryption from an existing peer relationship is missing steps.
After the 1st command option, you will be prompted for the existing passphrase or it will not allow you to proceed....that should be added to the procedure in public documentation.

  cluster peer modify <source_cluster> -auth-status-admin use-authentication -encryption-protocol-proposed none
           Enter Passphrase:
           Re-enter Passphrase:

The other issue is that ONTAP will not allow you to disable authentication unless you first change the peering policy to allow unauthenticated access

need to add this step...
Modify cluster peering policy to allow unauthenticated access
  cluster peer policy modify -is-unauthenticated-access-permitted true

Then the below command will work
 cluster peer modify <source_cluster> -auth-status no-authentication

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
The missing steps have been added to the topic. Thank you for verifying that the steps are correct @raunEstes. Closing this issue.
