### ISSUE TITLE
https port missing?

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap#1439]
### Page URL

https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/mediator-install-task.html

### Page title

Configure the ONTAP Mediator and clusters for SnapMirror active sync

### Summary

The documentation only mentions port 31784 to be open between the ONTAP controllers and the mediator. IIRC this is solely for the REST API calls and not the mailbox disks. For Mailbox disk communication ONTAP uses https and as such I would expect port 443 must be opened, too.
Can you please verify and have this information added if indeed missing.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for your feedback, I am investigating this issue and will reply here.

**Comment by nlsntap** [comment]
There is a similar section describing Mediator port and firewall requirements for MetroCluster:
[https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html#firewall-requirements-for-ontap-mediator](url)
I suggest to have the section on Mediator with SnapMirror active sync to be like this one - with the difference that the iSCSI port tcp 3260 with MetroCluster would be the https port tcp 443(?) with SnapMirror active sync.

**Comment by netapp-barbe** [comment]
Thank you again for your feedback, however this does not seem to be accurate. 

According to our engineering team, the ONTAP clusters should be communicating via the REST API with the VM that has Mediator server installed and listening on port 31784. The Mediator server running on the VM does not bind to port 443 to avoid a conflict with something else likely installed on the host machine.

I hope this helps.
