### ISSUE TITLE
Italics missing on reference to TR-4743: FlexCache in ONTAP 9.11.1

### ISSUE THREAD

**Issue by adamn-netapp** [NetAppDocs/ontap#1441]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache-writeback/flexcache-write-back-overview.html

### Page title

FlexCache write-back overview

### Summary

I believe the standard for notes like this is for the titles of former TRs to be italicized.

For example, see the note in this article -- https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-overview.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
Thanks for catching @adamn-netapp. I'll fix that in a coming doc hot fix.

**Comment by netapp-aaron-holt** [comment]
Hi @adamn-netapp, thanks again for spotting this. The change is now live.

**Comment by netapp-aaron-holt** [comment]
Closing this issue.
