### ISSUE TITLE
Step 2 is not entirely clear at the moment

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/ontap#1449]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-snapmirror/create-remote-mirror-existing-bucket-task.html

### Page title

Create a mirror relationship for an existing bucket (remote cluster)

### Summary

Good afternoon Team,
 It's entirely possible I just don't have enough exposure to S3 for this set of instructions to make sense to me, but step 2 under System Manager is not clear enough to me at the moment.

>>  Verify that user and group access is correct in both the source and destination storage VMs:

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, John. I'll take a look and see if I can make this information clearer.

**Comment by netapp-lenida** [comment]
The updated step is available now. I went through the steps on a lab system, and I hope I've made Step 2 clearer. You can reopen this issue if you feel it hasn't been resolved.
