### ISSUE TITLE
No mention of support for PRESIGN API

### ISSUE THREAD

**Issue by ntap-leeray** [NetAppDocs/ontap#1454]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-config/ontap-s3-supported-actions-reference.html

### Page title

ONTAP S3 supported actions

### Summary

In this kb: https://community.netapp.com/t5/ONTAP-Discussions/S3-buckets-and-presigned-URLs/m-p/443292, it was mentioned that an S3 API PRESIGN is supported as long as V4 signature is enabled. But nowhere in the ONTAP doc can I find a reference to this.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for your feedback. Presigned URLs are now listed under S3 actions by release under ONTAP 9.11.1.
