### ISSUE TITLE
I cannot understand the text because I don't know what "The ONTAP security documentation" refers to.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#1456]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache-writeback/flexcache-write-back-overview.html

### Page title

FlexCache write-back overview

### Summary

![image](https://github.com/user-attachments/assets/42a623c2-3db0-49ec-a902-83b536f1cb5d)

I cannot understand the text because I don't know what "The ONTAP security documentation" refers to.
Please provide a link to the specific document you are referring to.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@kanitani thanks for the feedback. We can clear that up in coming doc hot fix.

**Comment by netapp-dbagwell** [comment]
@kanitani thanks. There were two problems with the note. The first is that the security section mentioned should have been the volume section (parent section). The second is that older content associated with the KB has not yet been migrated. While the new content has been migrated, the note is misleading. We have removed the note for the time being. Updates to the live site are in progress.
