### ISSUE TITLE
revert_to with -d takes days - possible warning addition

### ISSUE THREAD

**Issue by antoine-netapp** [NetAppDocs/ontap#1466]
### Page URL

https://docs.netapp.com/us-en/ontap/revert/task_reverting_an_ontap_cluster.html

### Page title

Revert an ONTAP cluster

### Summary

One of my customer came across this message when going through a revert procedure:

> revert_to 9.13
There is a backlog of asynchronous deletes that must complete before
the revert_to operation can proceed. If you want the revert_to command
to wait, use the "-d" parameter. With "-d" the command will wait for
the deletes to complete and then proceed with the revert.

Address the above condition, then try "revert_to" again.

After running the same command with -d, it took days because of the amount of asynchronous deletes to perform.
Would it be possible to add a warning in the doc stating that if prompted, using the -d option can take a VERY long time and should be used with caution ?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@antoine-netapp as part of this request, we added language to https://docs.netapp.com/us-en/ontap/revert/task_reverting_an_ontap_cluster.html emphasizing engagement with support before a revert. I know the long email thread internally led to a CONTAP issue where it sounds like your concerns are being addressed with the system messaging. If you need anything else from us in regards to the user doc set, please feel free to reopen this issue.
