### ISSUE TITLE
What is the impact of enabling and disabling this option while a volume is already mounted by an ESXi host?

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/ontap#1467]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-vmware-vstorage-over-nfs-task.html

### Page title

Enable or disable VMware vStorage over NFS

### Summary

What is the impact of enabling and disabling this option while a volume is already mounted by an ESXi host? Please document this behavior. Specific questions that need to be included in the answer: Do you have to unmount and remount the volume after being enabled? What about after being disabled? What happens if you install the VAAI VIB and the volume is already mounted?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
Closed public issue. Tracking internally in ONTAPDOC-2576
