### ISSUE TITLE
Please clarify the vstorage fact.

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/ontap#1468]
### Page URL

https://docs.netapp.com/us-en/ontap/svm-migrate/index.html

### Page title

SVM data mobility overview

### Summary

This page says that SVM migration doesn't support the vstorage option. Please clarify what that means. For example: Must the option always be disabled? Or can you have the option turned on during normal operations, but disable it during a migration event and turn it back on after the migration cutover is done? 

If is is permitted, please document why it is unsupported.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
I've reached out to engineering and TME for more information. Still awaiting a response.

**Comment by netapp-lenida** [comment]
Thanks @netapp-bingen. I've added a note to the topic that suggests disabling the vstorage option before a migration and then reenabling it when the migration is finished.
