### ISSUE TITLE
Lack of Space Reclamation in NVMe Namespaces not mentioned as current limitation

### ISSUE THREAD

**Issue by krazy43d** [NetAppDocs/ontap#1470]
### Page URL

https://docs.netapp.com/us-en/ontap/nvme/support-limitations.html

### Page title

NVMe configuration, support, and limitations

### Summary

Current versions of ONTAP do not yet support space reclamation (NVMe DataSet Management (`deallocate`) command) in NVMe Namespaces.  [Associated NetApp KB](https://kb.netapp.com/on-prem/ontap/da/SAN/SAN-KBs/ONTAP_namespace_space_reclamation_on_NVMe_datastore_does_not_work).
This has serious implications for volume and aggregate usage on the ONTAP backend and is therefore worth mentioning as a limitation on this page.
This limitation should be added to the *Namespaces* section on this page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
This has been corrected, thank you for the excellent feedback!
