### ISSUE TITLE
Default share permissions are listed incorrectly

### ISSUE THREAD

**Issue by tespinoz-netapp** [NetAppDocs/ontap#1473]
### Page URL

https://docs.netapp.com/us-en/ontap/smb-admin/manage-smb-level-acls-concept.html

### Page title

Guidelines for managing SMB share-level ACLs

### Summary

This page lists the default share permissions are "Read-only" for Everyone, but in fact it's "Full Control" for Everyone. This can be proven quite easily by creating a new share and checking the permissions on it
![image](https://github.com/user-attachments/assets/a243ca4a-f123-49bc-8ed1-e2a24d7af2f8)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@tespinoz-netapp thanks. We're looking into this and will update the docs accordingly.

**Comment by netapp-dbagwell** [comment]
@tespinoz-netapp thanks for pointing out the error. The revised language including the full control default is now live.
