### ISSUE TITLE
Default SMB Share-Lvels ACL's are full control for Everyone, not "read only" as Documented

### ISSUE THREAD

**Issue by jason43017** [NetAppDocs/ontap#1474]
### Page URL

https://docs.netapp.com/us-en/ontap/smb-admin/manage-smb-level-acls-concept.html

### Page title

Guidelines for managing SMB share-level ACLs

### Summary

I'm an ATS with NetApp and have verified with several NetApp SME's, that default is full control as documented here: https://learn.microsoft.com/en-us/azure/azure-netapp-files/network-attached-storage-permissions#smb-share-acls

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@jason43017 thanks. Can you confirm your short name with NetApp (not full email alias). I'd like to discuss this internally. Thanks.

**Comment by jason43017** [comment]
Short name is jpierson

**Comment by netapp-dbagwell** [comment]
@jason43017 thanks for pointing out the error. The revised language including the full control default is now live.

**Comment by jason43017** [comment]
Good deal. Thanks Dave!

From: Dave Bagwell ***@***.***>
Date: Wednesday, September 18, 2024 at 12:08 PM
To: NetAppDocs/ontap ***@***.***>
Cc: Pierson, Jason ***@***.***>, Mention ***@***.***>
Subject: Re: [NetAppDocs/ontap] Default SMB Share-Lvels ACL's are full control for Everyone, not "read only" as Documented (Issue #1474)
EXTERNAL EMAIL - USE CAUTION when clicking links or attachments



@jason43017<https://github.com/jason43017> thanks for pointing out the error. The revised language including the full control default is now live.
