### ISSUE TITLE
Add link to doccomments ng on GitHub 

### ISSUE THREAD

**Issue by jenatnetapp** [NetAppDocs/ontap#148]
Some users don't have (or want) a GitHub ID. Can we add a link to the doccomments ng?

![image](https://user-images.githubusercontent.com/48109805/118042572-1b6b9b00-b329-11eb-936f-38d7a453c180.png)

Something like... "No GitHub ID? Contact us via [email]( @doccommnts@netapp.com)

**Comment by netapp-aherbin** [comment]
@netapp-forry @netapp-ehoffman, please respond.

**Comment by jenatnetapp** [comment]
@adamn-ntap returning to this... use case is that a customer doesn't have a GitHub ID and wants to send an email to doccomments instead. Should  we offer a link?

**Comment by netapp-forry** [comment]
@jenatnetapp @adamn-ntap; isn't this a general doc site issue, not specific to ONTAP? Can you move it elsewhere? Thx.
