### ISSUE TITLE
Instructions for using UEFI Secure Boot Enable

### ISSUE THREAD

**Issue by rbaetz** [NetAppDocs/ontap#1480]
### Page URL

https://docs.netapp.com/us-en/ontap/mediator/index.html

### Page title

Prepare to install or upgrade the ONTAP Mediator service

### Summary

Can you provide instructions on how to use mediator with UEFI Secure Boot enabled?  Does NetApp have an official security key to add this manually to UEFI Secure Boot?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-sarajane** [comment]
This was addressed as part of the ONTAP Mediator 1.9 release work as part of 9.16.1, due for release 7th November. 
https://review.docs.netapp.com/us-en/ontap_sarajane-mediator-9161/mediator/index.html#register-a-security-key-when-uefi-secure-boot-is-enabled
