### ISSUE TITLE
Mistaken command parameters

### ISSUE THREAD

**Issue by seijitanabe** [NetAppDocs/ontap#1482]
### Page URL

https://docs.netapp.com/us-en/ontap/authentication/configure-dynamic-authorization.html

### Page title

Customize dynamic authorization

### Summary

In the command _**“security dynamic-authorization group create”**_, the arguments _**"-group-name”**_ and **_"-exclude-users"_** are invalid. 
_**"-name"**_ and _**"-excluded-usernames"**_ are correct as the following command reference.
https://docs.netapp.com/us-en/ontap-cli/security-dynamic-authorization-group-create.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@seijitanabe thanks for catching this. We'll fix this in a coming doc update.

**Comment by netapp-dbagwell** [comment]
The issue has been corrected. Thanks again, @seijitanabe
