### ISSUE TITLE
Clarification needed on default accounts vs built-in accounts

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap#1485]
### Page URL

https://docs.netapp.com/us-en/ontap/ontap-security-hardening/default-admin-accounts.html

### Page title

Default administrative accounts

### Summary

Never understood there is a difference between built-in accounts and default accounts but apparently there is.

I've always thought the admin account was a built-in, that could be locked but not deleted.
I read:
There are two default administrative accounts: admin and diag.
and
"ONTAP cannot remove or rename built-in accounts."

But still a few sections down we delete the admin account.
Can we add a list of the built-in account so it's clear which ones cannot be deleted?
Just tested deleting admin in one of my lab clusters so now I know admin can be done, some 13 years after starting to work on cDOT as it were :-)

Then we should probably also list autosupport in the default (and built-in) accounts because it's there on all clusters.

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dtulledg** [comment]
If you delete it, it will work.  But after reboot, the accounts will reappear.  You should lock it to disable access.

**Comment by estarz** [comment]
Interesting. Just rebooted both nodes in my lab cluster and after logging in again I see the admin account has reappeared.

Then I believe this section in the hardening guide should be change and recommend only locking the admin account.
I mean, why provide the commands to delete it if we know it will come back?

**Comment by netapp-dtulledg** [comment]
Hi Dave,

You can delete that part.

We're trying to keep customers from locking themselves out by keeping admin.

Thanks,
Dan
________________________________

**Comment by netapp-dbagwell** [comment]
Sorry for the delay. Section has been deleted and revisions should be live next week.
