### ISSUE TITLE
Typo in CLI command for doc page titled "View existing tags on a volume"

### ISSUE THREAD

**Issue by StorageDan** [NetAppDocs/ontap#1488]
### Page URL

https://docs.netapp.com/us-en/ontap/fabricpool/view-existing-tags-volume-task.html

### Page title

View existing tags on a volume

### Summary

I believe that there is a typographical error in the CLI command shown below.  The current CLI command shown is:
**volume show [ -vserver <vserver name> ] -volume <volume_name> -fields -tiering-object-tags**

However, the '-fields' parameter  takes a list of field names without a leading "-".  I believe the correct syntax of the CLI command is: 
**volume show [ -vserver <vserver name> ] -volume <volume_name> -fields tiering-object-tags**

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @StorageDan, I'll look into this.

**Comment by netapp-lenida** [comment]
Thanks again for bringing this to our attention. The issue has been fixed.
