### ISSUE TITLE
Add "async-delete" to the categories of events to audit

### ISSUE THREAD

**Issue by mcanate** [NetAppDocs/ontap#1489]
### Page URL

https://docs.netapp.com/us-en/ontap/nas-audit/plan-auditing-config-concept.html

### Page title

Plan the auditing configuration

### Summary

"Async-delete" is not included on the event categories to audit on the parameters table. I would like to suggest adding the following description on the "Type of information" section for "Categories of events to audit":

Record/audit instances of directories being deleted asynchronously. Async-delete is an ONTAP file operation that can be done from the cluster CLI or via System Manager. For more information about this file operation/task, please refer to: [Delete directories rapidly on the cluster (netapp.com)](https://docs.netapp.com/us-en/ontap/flexgroup/fast-directory-delete-asynchronous-task.html)

And adding the "async-delete" event on the "Option" section:

-events {file-ops|cifs-logon-logoff|cap-staging|file-share|audit-policy-change|user-account|security-group|authorization-policy-change|async-delete}

Thanks!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for the feedback. I'll investigate and reply in this issue

**Comment by netapp-barbe** [comment]
The documentation has been updated - thanks again!
