### ISSUE TITLE
Change the Virus scanning workflow

### ISSUE THREAD

**Issue by Nat-Netapp** [NetAppDocs/ontap#1491]
### Page URL

https://docs.netapp.com/us-en/ontap/antivirus/workflow-concept.html

### Page title

Virus scanning workflow

### Summary

it said in the documentation pages after that On-access policy should be created to create on-demand task , but the workflow diagram seems that we can choose On-demand without configuring and enabling On-access policy first , then activating vscan on the SVM. So On-demand task can only be created AFTER the "on access" path.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
@Nat-Netapp this is true, however, since you can use the default on-access policy, you might not have to create an on-access policy before creating an on-demand task. 

> To create an on-demand task, there must be at least one on-access policy enabled. It can be the default policy or a user created on-access policy.
