### ISSUE TITLE
"ONTAP 9.6 or later" and "ONTAP 9.5 or earlier" is not correct description

### ISSUE THREAD

**Issue by zhuolin-shen** [NetAppDocs/ontap#1492]
### Page URL

https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-rsh-task.html

### Page title

Access the cluster by using RSH

### Summary

1) Based on lab, management-rsh-server also doesn't exist on ONTAP 9.8. 

cluster1::*> version
NetApp Release Dirtwolf__9.8.0: Wed Dec 09 01:07:39 UTC 2020

cluster1::*> network interface service-policy add-service -vserver cluster1 -policy default-management -service ?
 intercluster-core
  management-bgp
 management-portmap

2) According to the doc below, it is supposed to be from 9.10.1 or later, management-rsh-server is added.

https://docs.netapp.com/us-en/ontap/networking/configure_firewall_policies_for_lifs.html

Beginning with ONTAP 9.10.1:

Firewall policies are deprecated and are replaced by LIF service policies. Previously, the onboard firewall was managed using firewall policies. This functionality is now accomplished using a LIF service policy.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-barbe** [comment]
Thank you for the feedback. I'll investigate and reply in this issue.
