### ISSUE TITLE
Presigned URL documentation missing

### ISSUE THREAD

**Issue by james-netapp** [NetAppDocs/ontap#1494]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-config/ontap-s3-supported-actions-reference.html

### Page title

ONTAP S3 supported actions

### Summary

Maybe I missed it, but I'm not seeing pre-signed URLs (v4) in our docs, which were added to ONTAP S3 in 9.11.1.

It doesn't have to go on this page necessarily, but somewhere within the ONTAP S3 docs would be ideal.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, James. I've added a new section to the topic called S3 actions by release that includes presigned URLs.
