### ISSUE TITLE
Change link from blog to docs.

### ISSUE THREAD

**Issue by netapp-chrisgeb** [NetAppDocs/ontap#1495]
### Page URL

https://docs.netapp.com/us-en/ontap/ransomware-solutions/ransomware-cyber-vaulting.html

### Page title

Air-gapped WORM protection with cyber vaulting

### Summary

Could you, when you get a chance, replace the link to the blog with this link.

https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@netapp-chrisgeb will do!
