### ISSUE TITLE
A70/A90/A1K

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#1496]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/enable-temperature-sensitive-efficiency-concept.html

### Page title

Temperature-sensitive storage efficiency overview

### Summary

Can we add the detail from here:  https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html

Of this information:
Temperature-sensitive storage efficiency is not applied on AFF A70, AFF A90, and AFF A1K platforms. Compression is not based on hot or cold data on these platforms, so compression begins without waiting for data to become cold.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Tim, Thank you for the feedback.  The update is posted.
