### ISSUE TITLE
Command syntax to validate write-back enablement is incorrect

### ISSUE THREAD

**Issue by tespinoz-netapp** [NetAppDocs/ontap#1498]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache-writeback/flexcache-writeback-enable-task.html

### Page title

Enable and manage FlexCache write-back

### Summary

Under the header for "Check if FlexCache writeback is enabled", the command to validate write-back enablement is shown as:

volume flexcache config show -volume cache -fields is-writeback-enabled

However, the "-volume cache" parameter specification is incorrect in any environment where the volume modified is not also named "cache". Looking at the syntax used in the previous enablement command under "Enable FlexCache write-back on an existing FlexCache volume", this should be modified to the following to reflect the volume that was modified:

volume flexcache config show -volume <cache_flexgroup_name> -fields is-writeback-enabled

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, Tyler. I'll look into this.

**Comment by netapp-lenida** [comment]
Thanks again, Tyler. The topic has been updated.
