### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#1499]
### Page URL

https://docs.netapp.com/us-en/ontap/element-replication/index.html

### Page title

Replication between NetApp Element software and ONTAP overview

### Summary

The link on this page is a 404. Not sure if this is still supported or where the link may have moved to, but we should address it.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
Thanks @netapp-joey. These pages were recently migrated to the [SolidFire Element repo](https://docs.netapp.com/us-en/element-software/storage/concept_snapmirror_overview.html) and are still current. I'll correct that link.

**Comment by netapp-dbagwell** [comment]
Link has been fixed. Thanks again for reporting.
