### ISSUE TITLE
Add text to call attention to PDF options

### ISSUE THREAD

**Issue by jenatnetapp** [NetAppDocs/ontap#150]
While we wait for a bigger UI fix, can we add some text or a graphic or anything at all that calls attention to the PDF options? Customers are overlooking the subtle offering in the left nav drop down menu and think we are not providing PDF any more. 

![image](https://user-images.githubusercontent.com/48109805/118050746-b7e76a80-b334-11eb-8f43-addfbea3c74b.png)

**Comment by netapp-aherbin** [comment]
@netapp-forry @netapp-ehoffman please respond

**Comment by jenatnetapp** [comment]
This will be resolved by changes to PDF download redesign issue 487. We can close this.

**Comment by netapp-forry** [comment]
Closing per Jen's comment.
