### ISSUE TITLE
Correct outdated info on sm-s cascades

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#1505]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/supported-deployment-config-concept.html

### Page title

Fan-out and cascade data protection deployments

### Summary

The first paragraph mentions that SM-S isn't supported in a cascade: "...however, SnapMirror synchronous relationships (supported beginning with ONTAP 9.5) support only fan-out deployments with one or more SnapMirror asynchronous relationships and do not support cascade deployments. ..."

This is not true anymore. As of 9.6, cascades with SM-S are supported. See: https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html#supported-features

Can we please up this doc with the correct info?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, Joey. The topic has been updated.
