### ISSUE TITLE
Unclear if replication between A Series and C Series is supported

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap#1509]
### Page URL

https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/index.html

### Page title

SnapMirror active sync overview

### Summary

Hi,

I got asked if replication between A Series and Series is supported. While the documentation states SMas is only supported between like families (i.e. ASA to ASA and AFF to AFF), it does not mentioned replication between A and C at all.

The following information should be added - either here or another place talking about SMas concepts and architectures.

#####
For _asymmetric_ active/active access, i.e. the SnapMirror policy "AutomatedFailover", replication from A Series to C Series is supported. This is because there is a clear definition of what the primary copy and what the DR copy is. An asymmetric performance profile of the two copies is acceptable. In case of a failover to the DR copy, a reduced IO performance is accepted by the application or workload.

For _symmetric_ active/active access, i.e. the SnapMirror policy "AutomatedFailoverDuplex", a symmetric performance profile is expected from both copies, as IO access can occur to either copy at any given time. There is no concept of "primary copy" and "DR copy". As such both copies have to either reside on A Series controllers *or* C Series controllers.
#####

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @nlsntap. The doc has been updated.

**Comment by nlsntap** [comment]
I don't know what has actually been changedhere, but it does not address what I want it to say - meaning the support of replication from an A-Series system/controller/cluster to a C-Series system/controller/cluster when the policy "AutomatedFailover" is uses (i.e. asymmetric a/a access).

**Comment by nlsntap** [comment]
I found it being mentioned here:
[https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/prerequisites-reference.html#hardware](https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/prerequisites-reference.html#hardware)
But it's too generic.
Replication between A and C should only be supported for asymmetric active/active access (i.e. policy AutomatedFailover) and not symmetric active/active access (i.e. AutomatedFailoverDuplex).
It should be clarified as otherwise a performance case could easily arise.

**Comment by netapp-ahibbard** [comment]
@nlsntap - SnapMirror active sync engineering has confirmed that replication between A and C is supported for symmetric active/active. If you can share your NetApp ID, I can share more resources with you.

**Comment by nlsntap** [comment]
Thanks – I wasn’t even aware of that.
I’d love to get more details on it. ***@***.******@***.***>)

Cheers, Niels
