### ISSUE TITLE
Add information that Persistent Reservations for NVMe_oF is not supported

### ISSUE THREAD

**Issue by Myer** [NetAppDocs/ontap#1513]
### Page URL

https://docs.netapp.com/us-en/ontap/nvme/support-limitations.html

### Page title

NVMe configuration, support, and limitations

### Summary

Currently it's only visible in IMT:
![grafik](https://github.com/user-attachments/assets/7c0be66d-7153-49b5-9f34-9ccd6b1cac89)

It's also mentioned here (https://docs.netapp.com/us-en/ontap-sanhost/nvme_windows_2022.html) but that's about NVMe_oF into the Windows guest OS. I was looking for support for implementing a CAB (cluster-across-box) virtualized solution for WSFC on ESXi using Clustered VMDKs on NVMe_oF datastores (which needs persistent reservations support).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you for the feedback and HWU verification.  We've added persistent reservations to the list of NVMe limitations.
