### ISSUE TITLE
Operations "ObjectVersion" not supported?

### ISSUE THREAD

**Issue by kalex2001** [NetAppDocs/ontap#1514]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-config/ontap-s3-supported-actions-reference.html

### Page title

ONTAP S3 supported actions

### Summary

In documentation not clear is these operations supported?
"s3:GetObjectVersion"
"s3:DeleteObjectVersion"

And these also? According TR-4814 S3 in ONTAP best practices - page 29, these operations not supported, right?
"s3:GetObjectLegalHold"
"s3:PutObjectLegalHold"

S3 Object Lock
Beginning in ONTAP 9.14.1, data in ONTAP S3 buckets can be protected using S3 Object Lock to
commit data to nonerasable, nonrewritable, write once, read many (WORM) storage.
Commonly used in Compliance mode to meet regulatory requirements Object Lock is also frequently
used in Governance mode to protect objects from accidental—or intentional—alteration or deletion.
Note: **Legal hold operations (**locks without defined retention times) are not supported.

Anyway, need updated this page and specify if these operations supported/not supported

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
@kalex2001, the topic has been updated to include a note saying that legal hold operations are note supported. 

For the GetObject and DeleteObject actions, these are supported as documented in the topic. "Version" is a parameter of these supported actions as described in the Amazon S3 API Reference: https://docs.aws.amazon.com/AmazonS3/latest/API/Type_API_Reference.html. A link to to this reference is also included at the topic of the topic.
