### ISSUE TITLE
RDMA support - need to add latest gen AFF

### ISSUE THREAD

**Issue by spruch305** [NetAppDocs/ontap#1517]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html

### Page title

NFS over RDMA

### Summary

Need to include A70, A90, A1K 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@spruch305 are you internal to NetApp?

**Comment by netapp-aherbin** [comment]
This is a duplicate request for issue 1520. Closing and adding info here to track in Issue 1520.

**Comment by spruch305** [comment]
I am a netapp employee but somehow my github uses my personal email.
