### ISSUE TITLE
"-option-name" needs to show option settings

### ISSUE THREAD

**Issue by raccoony** [NetAppDocs/ontap#1518]
### Page URL

https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-snapshot-options-task.html

### Page title

Modify options for automatic Snapshot copies

### Summary

To show all current ARP Snapshot copy settings, enter:
- vserver options -vserver svm_name arw*
+ vserver options -vserver svm_name -option-name arw*

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@raccoony thanks for reporting this. We'll get the docs updated.
