### ISSUE TITLE
Missing ONTAP Ports

### ISSUE THREAD

**Issue by scottkntap** [NetAppDocs/ontap#1519]
### Page URL

https://docs.netapp.com/us-en/ontap/networking/ontap_internal_ports.html

### Page title

ONTAP internal ports

### Summary

While our PS consultant was troubleshooting a CVO problem for the customer, they detected some additional ports they needed to open for a CVO M-AZ configuration that are not listed in the ONTAP port list. They are in the existing defined ranges so I'm assuming they are both NetApp Cluster RPC ports.  Can these please be updated and defined in the list of ports in the documentation?  Thank you!

930
975
7700
7836/37
7846/47
10006 (I found this in the MCC docs as a Metrocluster ICL port, but CVO is probably using this for a different purpose).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Raised BLUEXPDOC-166 from this issue, closing this one.
