### ISSUE TITLE
NFS over RDMA topic needs the table updated to add new platform models as needed

### ISSUE THREAD

**Issue by netapp-lisa** [NetAppDocs/ontap#1520]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-rdma/index.html

### Page title

NFS over RDMA

### Summary

Steven Pruchniewski contacted me to say that platforms models are missing from the table in this page. The way it's worded, all platforms that use the CX-6 card need to be listed. Sounds like Vino platforms use this card and Gizo, when it releases, will also use this card. Seems that it is tricky to keep this topic up to date. Here's the table Steve is referring to: 
<img width="332" alt="image" src="https://github.com/user-attachments/assets/fb00302d-4dc7-4ec4-87ef-47c4f001f541">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Issue 1517 was for same request, specifically to include A70, A90, A1K.  @netapp-ahibbard please address these as well.  Thanks!

**Comment by netapp-bhouser** [comment]
This was resolved in a separate issue. Table is updated with A70, A90, A1K, A50, A30 & A20 as of Nov 27, 2024.
