### ISSUE TITLE
IP address seems to be required in SAN but is not documented as required.

### ISSUE THREAD

**Issue by arndt-netapp** [NetAppDocs/ontap#1521]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-admin/tls-nfs-strong-security-concept.html

### Page title

Overview of using TLS with NFS for strong security

### Summary

Our NFS over TLS docs state:
 
“Each certificate must be configured with the IP address or FQDN of the NFS server (or both) as the Subject Alternative Name (SAN). If both IP address and FQDN are configured, NFS clients can connect using either the IP address or FQDN.”
 
However, if I try to use a certificate without an IP address SAN, I get an error that includes “For TLS certificate, LIF IP address as subject alternate name is mandatory.”  It seems that the LIF IP is mandatory in the SAN, but the FQDN is optional, and our documentation needs to be updated to reflect this.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
This has been fixed and will be merged into the main documentation shortly.  Thanks, @arndt-netapp for letting us know about this issue!
