### ISSUE TITLE
Similar FC to CNA doc request

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#1523]
### Page URL

https://docs.netapp.com/us-en/ontap/san-config/change-uta2-port-cna-mode-fc-task.html

### Page title

Change the UTA2 port from CNA mode to FC mode

### Summary

Any chance we could get the flipside of this doc for a FC to CNA conversion?  

Maybe under this:
Network management - Network ports - Configure network ports

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Sure Tim.  We would need assistance with the steps.  Would it follow the same procedure with the exception of step 2 where the mode would be changed to 'cna' instead of 'fcp'?

**Comment by TimMcGue** [comment]
Pretty similar at least.

Step 1 is the same.

Step 2 changes to cna for mode.

Step 3 still needs reboot but doesn't need the command. 

Step 4 would be OK to remove all together. 

Step 5 would be just about the same, just remove the command.

**Comment by netapp-aherbin** [comment]
Thanks Tim! I'll get this updated.

**Comment by netapp-aherbin** [comment]
@TimMcGue I've updated the topic to include both conversions.  Thank you!
https://docs.netapp.com/us-en/ontap/networking/convert-uta2-port-cna-fc.html
