### ISSUE TITLE
Counter name change

### ISSUE THREAD

**Issue by MikePalicNTAP** [NetAppDocs/ontap#1525]
### Page URL

https://docs.netapp.com/us-en/ontap/nfs-admin/display-ldap-statistics-task.html

### Page title

Display LDAP statistics

### Summary

secd_external_service_op no longer exists and is now external_service_op

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@MikePalicNTAP thank you for the update.  Does this change apply to a specific ONTAP version (ie Beginning in ONTAP 9.15.1) or does it apply to all ONTAP 9 versions?

**Comment by netapp-aherbin** [comment]
The man page for the statistics show command does not list all the valid object names. Mike responded in email that the change may have occurred in 9.3 or 9.5 but was unsure.  To, mitigate uncertainty, I've replaced the previous example with the most recent one used in the 9.15.1 man page.
