### ISSUE TITLE
Please change language in doc for TOTP

### ISSUE THREAD

**Issue by netapp-chrisgeb** [NetAppDocs/ontap#1527]
### Page URL

https://docs.netapp.com/us-en/ontap/authentication/configure-local-account-mfa-totp-task.html

### Page title

Configure local user account for MFA with TOTP

### Summary

Please change this: "TOTP is supported by various authenticator apps such as Google Authenticator."

To this: "Any TOTP-compatible authenticator such as Microsoft Authenticator, Google Authenticator and Authy are supported."

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Thank you for the suggestion.  We've reworded for better clarity.
