### ISSUE TITLE
Wrong CLI command to delete bucket event selector

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#1528]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-audit/select-buckets-task.html

### Page title

Select buckets for S3 auditing

### Summary

I'm pretty sure this CLI is wrong.

Auditing configurations persist for buckets until removed by the vserver object-store-server audit object-select delete command.

The correct command is: vserver object-store-server audit event-selector delete

Ref: https://docs.netapp.com/us-en/ontap-cli/vserver-object-store-server-audit-event-selector-delete.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @andris-ntap. I'll look into this.

**Comment by netapp-lenida** [comment]
Thanks again for bringing this to our attention. The command has been corrected.
