### ISSUE TITLE
Question - is the reference to the CLI command the best reference?

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap#153]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

In the first paragraph, we tell the user they can determine the current version of ONTAP running on each node by using the system image show command.

I assume this information is available in System Manager. If that's true, why don't we direct the user to that UI first and then secondarily refer to the CLI command?

**Comment by netapp-aherbin** [comment]
Hi Adam,

Great catch.  This content was originally CLI based and merged with the System Manger content when migrated to GitHub.  Let me check with the System Manager team for the steps to verify there; then we can update.

Amanda

**Comment by netapp-aherbin** [comment]
Adam, 

This content has been updated to include instructions for determining your ONTAP version first from System Manager or the CLI.

Thank you,
Amanda
