### ISSUE TITLE
mirror-vault requirement

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#1533]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html#modify-an-existing-policy-to-apply-long-term-retention

### Page title

Lock a Snapshot copy for protection against ransomware attacks

### Summary

Earlier in the document it is mentioned:

In a SnapMirror relationship, you can set a retention period on a mirror-vault policy rule

It would be good to mention that same requirement in the modify an existing policy section too.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks @TimMcGue. I'll look into this.

**Comment by netapp-lenida** [comment]
Thanks again, Tim. I've added the mirror-vault information to the "Modify an existing policy" section.
