### ISSUE TITLE
the WAFL reserve for aggregates for FAS platform

### ISSUE THREAD

**Issue by toshiki-mukaeda** [NetAppDocs/ontap#1543]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/determine-space-usage-volume-aggregate-concept.html

### Page title

Determine space usage in a volume or aggregate

### Summary

I have responded from Fusion team;
"right now, WAFL 5% changes were implemented for AFF/ASA platforms only. We have a roadmap to implement 5% WAFL changes on FAS platforms in our future release and we are working on the timeline."

So please update this in the doc?
**Beginning in ONTAP 9.14.1, this same reduction applies to aggregates on all FAS platforms, resulting in 5% more usable space in the aggregates.**

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Confirmed with WAFL team that the current documentation is correct.  Shared results via email with @toshiki-mukaeda who will share with Fusion team.
