### ISSUE TITLE
"S3 SnapMirror" or "SnapMirror S3" - which one is it

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap#1544]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-snapmirror/index.html

### Page title

SnapMirror S3 overview

### Summary

We're mixing S3 SnapMirror and SnapMirror S3 in the docs.
Would be great if we called this feature one thing only as it's confusing enough with all the other SnapMirror variants.

<img width="1429" alt="Screenshot 2024-11-18 at 21 22 11" src="https://github.com/user-attachments/assets/845f663c-0b33-4dbd-990a-008345b7f75b">

Also the license looks like this:
<img width="583" alt="Screenshot 2024-11-18 at 21 24 46" src="https://github.com/user-attachments/assets/ace78048-1e3b-4f87-af2f-276ce719ed48">

Thanks,
Erik

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Hi Erik, thanks for bringing this to our attention. It should be SnapMirror S3. I can't change the license information that shows up in the CLI, but I can change any stray references to S3 SnapMirror that weren't updated. I make sure this is included in an upcoming doc hotfix.

**Comment by netapp-lenida** [comment]
I have updated remaining references to "S3 SnapMirror" to "SnapMirror S3" where possible. Thanks again.
