### ISSUE TITLE
Feedback from case 2010156561

### ISSUE THREAD

**Issue by simon-craig-netapp** [NetAppDocs/ontap#1550]
### Page URL

https://docs.netapp.com/us-en/ontap/system-admin/restore-cluster-config-from-existing-task.html

### Page title

Restore a cluster configuration from an existing configuration

### Summary

Customer used this doc page to restore cluster config on a test cluster before creating support case 2010156561.
They found that some of the configuration was missing such ifgrps. LIF names were also different.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@simon-craig-netapp thanks. We'll create an internal issue and reach out to you about this.
