### ISSUE TITLE
"System Manager does not support cascading relationships in ONTAP 9.9.1" is an incorrect description

### ISSUE THREAD

**Issue by zhuolin-shen** [NetAppDocs/ontap#1553]
### Page URL

https://docs.netapp.com/us-en/ontap/flexgroup/create-snapmirror-cascade-fanout-reference.html#considerations-for-creating-cascading-relationships

### Page title

Considerations for creating SnapMirror cascade and fanout relationships for FlexGroups

### Summary

Documentation mentioned that System Manager does not support cascading relationships in ONTAP 9.9.1, but it is for FlexGroup volumes. There is no limitation described for non-FlexGroup volumes.
[https://docs.netapp.com/us-en/ontap/flexgroup/create-snapmirror-cascade-fanout-reference.html]

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by zhuolin-shen** [comment]
Revision:
Please correct the documentation due to the following reasons:
- System Manager does not support cascading relationships regardless ONTAP version.
- Not only for FlexGroup volumes but also non-FlexGroup volumes.

Reference: https://kb.netapp.com/on-prem/ontap/DM/System_Manager/SM-KBs/Unable_to_configure_cascade_SnapMirror_for_non-FlexGroup_volumes_in_System_Manager

**Comment by zhuolin-shen** [comment]
The following description is also wrong. Please also correct it as well.
It is not system manager's enhancement but ONTAP 9.9.1's enhancement.
In other words, SnapMirror cascade can only be configured for flexgroup volume via CLI after ONTAP 9.9.1

https://docs.netapp.com/us-en/ontap-whatsnew/ontap991fo_system_manager_enhancements.html#other-system-manager-9-9-1-enhancements
SnapMirror cascade and fan-out support for FlexGroup volumes

ONTAP 9.11 below: (vol fg_dst is DP type)
![image](https://github.com/user-attachments/assets/c898f59f-8464-4d55-b6d5-9eb04f5da447)

**Comment by netapp-ehoffman** [comment]
Thank you @zhuolin-shen! We'll look to get these updates made in the first week of December.

**Comment by netapp-ehoffman** [comment]
Moving this to an internal issue: ONTAPDOC-2582
