### ISSUE TITLE
Provision NVMe storage - Volume step missing

### ISSUE THREAD

**Issue by tintop2k** [NetAppDocs/ontap#1555]
### Page URL

https://docs.netapp.com/us-en/ontap/san-admin/create-nvme-namespace-subsystem-task.html

### Page title

Provision NVMe storage

### Summary

It is not clear that when creating a new namespace via the CLI, that the volume referenced in the -path command needs to either already exist or needs to be created as an additional step. Coming from the GUI, the provision namespace workflow automatically creates the containing volume, so this isn't clear when moving to the CLI.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@tintop2k thanks for this feedback! We'll add some clarifying details about this in a coming doc update.
