### ISSUE TITLE
Please be specific that customer need to set -mail-hosts to ensure their  internal support organization receive mail.

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/ontap#1559]
### Page URL

https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html

### Page title

Set up AutoSupport

### Summary

Customer complain that the doc can't easily understand what's the required setting is to receive mail notification with body.7z ASUP.
Please be specified in step 5 or somewhere else that "In order to receive mail notification with ASUP attachment, need to set -mail-hosts and recipients in step 4"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@Xinwei-Wang thanks. We'll take a look at the topic and see if we can make clarifications.

**Comment by netapp-dbagwell** [comment]
@Xinwei-Wang we made a minor change based on your request to step 5: **If you configured the recipient addresses for your internal support organization in the previous step** or you chose SMTP transport for messages to technical support, configure SMTP by setting the following parameters of the system node autosupport modify command...

If you feel we need additional clarity, please feel free to reopen this issue.
