### ISSUE TITLE
amending the Ontap9 upgrade stages

### ISSUE THREAD

**Issue by st4cy001** [NetAppDocs/ontap#1565]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

### Page title

Supported ONTAP upgrade paths

### Summary

when upgrading Ontap9, you are merely providing a simple cookie cutter process. version A to B to C to ...
You also need to mention the required updates to firmware, hardware and BIOS loaders,  
otherwise this can cause extended service outage issues.  Same goes for RCF requirement
if using intercluster switches

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@st4cy001 The overview topic you mention above gives a brief synapsis of the upgrade process, but you need to follow the links for details.  If you do not have an active SupportEdge contract for Digital Advisor, you should follow the procedure to [prepare for your upgrade without Upgrade Advisor](https://docs.netapp.com/us-en/ontap/upgrade/prepare.html).  The content you mention above is already part of that documentation.  It includes: 

- [Rebooting the SP or BMC for firmware updates](https://docs.netapp.com/us-en/ontap/upgrade/reboot-sp-bmc.html).  Note:  You do not need to manually update your firmware prior to an ONTAP upgrade. The firmware for your cluster (including BIOS) is included with the ONTAP upgrade package and is copied to each node's boot device. The new firmware is then installed as part of the upgrade process.
- [Confirming support for your hardware configuration](https://docs.netapp.com/us-en/ontap/upgrade/confirm-configuration.html) (including the RCF).

If you have access to Upgrade Advisor, you should use it to generate an upgrade plan, which will also cover the items mentioned above.  

Thank you for your feedback.  Please feel free to reopen this issue if you have additional questions.
