### ISSUE TITLE
Remove inaccurate statement

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#1569]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html

### Page title

Commit Snapshot copies to WORM on a vault destination

### Summary

Hello,
In the initial summary text for this page, we need to remove this part: "; therefore, creating scheduled Snapshot copies on the destination volume using SnapMirror policies is not supported."
This is no longer true in 9.14.1 and later.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks again for bringing this to our attention. The topic has been updated.

**Comment by netapp-joey** [comment]
Thanks!
