### ISSUE TITLE
ONTAP ARP/AI Clarification

### ISSUE THREAD

**Issue by ACSantos47** [NetAppDocs/ontap#1579]
### Page URL

https://docs.netapp.com/us-en/ontap/anti-ransomware/enable-arp-ai-with-au.html

### Page title

Enable ARP/AI with automatic updating

### Summary

Hello guys, I have downloaded the "ONTAP 9.15.1 Technical Overview.pptx" at Field Portal site, and this document has information about ARP/AI. My question is: ARP/AI is only available in ONTAP version 9.16.1 and later or in ONTAP 9.15.1 too? If this resource is available only in ONTAP 9.16.1 NetApp needs to adjust the Technical documentation at Field Porta. Thanks in advance!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-dbagwell** [comment]
@ACSantos47 thanks. I'll reach out to the author for clarity.

**Comment by netapp-dbagwell** [comment]
@ACSantos47 ARP/AI was released as a tech preview in 9.15.1. There's a pink Tech Preview bubble in the upper right corner of the ARP/AI page in the PPTX you cited. Feel free to reopen the ticket if you need any more guidance/clarifications.

**Comment by ACSantos47** [comment]
@netapp-dbagwell I appreciate your attention, but I don´t know what 'Tech Preview' means. Could you explain me? My question is: ARP/AI is available in ONTAP 9.15.1 or no?

**Comment by ACSantos47** [comment]
@netapp-dbagwell its an amazing notice! How can I enable this on bootarg?

**Comment by netapp-ehoffman** [comment]
@ACSantos47 , thanks very much for your interest. NetApp docs does not document how to change bootargs, as that's not an expected customer activity. You'll need to contact support to ask if it's possible for you to do so. We'd recommend upgrading to ONTAP 9.16.1 as soon as possible to be able to take advantage of this feature.

**Comment by ACSantos47** [comment]
@Bagwell, Dave ***@***.***> Thank you for your patience and
attention. As version 9.16.1 will be available I´l install it on the
customer.

Have a good day!




Em qua., 18 de dez. de 2024 às 12:25, Ed Hoffman ***@***.***>
escreveu:
