### ISSUE TITLE
Download Link does not work, Version 1.3 is the current one

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap#162]
Page: [Installing the ONTAP Mediator](https://docs.netapp.com/us-en/ontap/smbc/smbc_install_installing_the_ontap_mediator.html)

Correct DL Link: https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab

And as mentioned in the Subject: Current version is 1.**3**

**Comment by netapp-forry** [comment]
Thanks SPGoetze -- we're investigating and will fix ASAP.

**Comment by netapp-lenida** [comment]
Thanks SPGoetze. The link has been updated and should be pointing to the correct page.
