### ISSUE TITLE
Typo on manual update command 1.b

### ISSUE THREAD

**Issue by vkumbar** [NetAppDocs/ontap#169]
Page: [Download and install the ONTAP software image](https://docs.netapp.com/us-en/ontap/upgrade/task_download_and_install_ontap_software_image.html)

Seems like the below command has a Typo error
manual update section  1.b.
system node image update -node * -package location -replace-package **true true** -background true -setdefault false

**Comment by netapp-aherbin** [comment]
Thank you for the feedback.  I've updated the typo.
