### ISSUE TITLE
Change upgrade path from ONTAP 9.5 to 9.6, 9.7 and 9.9.1 to be 9.6, 9.7 and 9.8, since 9.9.1 is still in release candidate. Should be closer to how 9.6 shows it.

### ISSUE THREAD

**Issue by csteiner52** [NetAppDocs/ontap#171]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we're investigating.

**Comment by netapp-aherbin** [comment]
@csteiner52 upgrade the current published paths are correct.  Upgrade from 9.5 directly to 9.8 is not supported.  9.9.1 is in RC, but all our content has been updated to support 9.9.1 RC .

**Comment by csteiner52** [comment]
Amanda,

If it isn’t supported from 9.5 to 9.8 it should not be supported to 9.9.1 either. 9.9.1 isn’t even GA yet. Also, you cannot create an upgrade plan from 9.5 to 9.9.1 either with upgrade planning tool.

Regards,

Chris
