### ISSUE TITLE
Feedback on "Updating the second DR pair in a MetroCluster DR group" documentation

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap#173]
From: Hubert, Jeff <Jeff.Hubert@netapp.com> 
Sent: Saturday, June 5, 2021 8:16 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: docs_feedback: https://docs.netapp.com/us-en/ontap/upgrade/task_updating_a_four_or_eight_node_mcc.html#updating-the-second-dr-pair-in-a-metrocluster-dr-group

docs_feedback: https://docs.netapp.com/us-en/ontap/upgrade/task_updating_a_four_or_eight_node_mcc.html#updating-the-second-dr-pair-in-a-metrocluster-dr-group

When upgrading the second DR pair, -allow-version-mismatch true is required for 9.5 => 9.7. 

I believe the statement of >9.1 not requiring the -allow-version mismatch is incorrect. 

—
Jeff Hubert
Professional Services Consultant
NetApp
703-447-9732

**Comment by netapp-aherbin** [comment]
@netapp-martyh I've already researched this issue with ENG and updated the content.

The -allow-version-mismatch true option is not required for upgrades from 9.0 to 9.1 but is required for all others.
