### ISSUE TITLE
Feedback on: Configure an SVM and data LIFs for host-name resolution using an external DNS server

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap#187]
Page: [Configure DNS for host-name resolution](https://docs.netapp.com/us-en/ontap/networking/configure_dns_for_host-name_resolution.html)
------------------------
From: Hunsur Eswara, Jeevan <Jeevan.HunsurEswara@netapp.com> 
Sent: Thursday, June 24, 2021 10:44 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Subject: docs_feedback: https://docs.netapp.com/us-en/ontap/networking/configure_dns_for_host-name_resolution.html#configure-an-svm-and-data-lifs-for-host-name-resolution-using-an-external-dns-server

Hi,

An example section 2 “Enable DNS on LIFs owned by the SVM:” CLI commands are overlapping.

1.	vserver services name-service dns create -vserver <vs1> -domains <example.com> -name-servers <192.0.2.201, 192.0.2.202> -state <enabled>  >>> This might not be needed here.
2.	network interface modify -lif <datalif1> -dns-zone <zonename.whatever.com>

Please check with the right DEV team and fix this.
Ignore if the doc is not relevant.

Thanks,
Jeevan

**Comment by netapp-barbe** [comment]
This has been fixed and can now be closed - thank you so much for the excellent feedback and helping to improve our documentation!
