### ISSUE TITLE
No documentation about Add disk to aggregates (local tiers) in 9.9.1

### ISSUE THREAD

**Issue by UweRoos** [NetAppDocs/ontap#192]
Page: [Add disks to a local tier (Add capacity to aggregate)](https://docs.netapp.com/us-en/ontap/task_admin_add_disks_to_local_tier.html)

I heard it is possible now to decide raidgroups etc. in 9.9.1. As I have no spares to try, I search for the documentation. But this talks about the classic version which is gone since 9.8.

**Comment by netapp-forry** [comment]
BURT 1414740.

**Comment by netapp-thomi** [comment]
Hello, UweRoos,
Thanks again for your feedback.  The topic has been updated to include the procedure for ONTAP 9.8 and later.  
Here's the link:
https://docs.netapp.com/us-en/ontap/task_admin_add_disks_to_local_tier.html
Thanks,
Thom
