### ISSUE TITLE
Video isn't documentation

### ISSUE THREAD

**Issue by kclarkr** [NetAppDocs/ontap#193]
Page: [Provision NAS storage for large file systems using FlexGroup volumes](https://docs.netapp.com/us-en/ontap/task_nas_provision_flexgroup.html)

Please stop substituting video for actual documentation with searchable text.  Watching marketing filled videos to find a technical answer is a waste of everyone's time.  And NetApp has a bad habit of letting the "documentation" videos get old and outdated, probably because they are time consuming to maintain.  All around bad idea as the formal documentation.  Perfectly fine as supplemental information.

**Comment by netapp-forry** [comment]
Thanks for the input. We're just back from vacation, will consider and get back to you.

**Comment by netapp-forry** [comment]
Thanks for taking the time to contact us.

Our intent is not to substitute marketing for technical content, but rather to connect marketing content to technical content for the benefit of those unfamiliar with the technology. 

Customers often use product documentation to learn about the product, so we sometimes offer different types of content alongside our technical documentation to enable learning. 

Was the technical content provided for FlexGroup volumes insufficient? If so, please let us know, we would like to address any content gaps.

Thanks again.
