### ISSUE TITLE
Rename page to something more descriptive.

### ISSUE THREAD

**Issue by netapp-norbertt** [NetAppDocs/ontap#195]
Page: [Verify status](https://docs.netapp.com/us-en/ontap/upgrade/task_verify_status.html) is standing out from the list of check that should be done before the upgrade. It is not descriptive on what should be checked. On the sidebar on left it is called "Status" only. Suggesting to rename it to something like "Verifying HA, LDAP and DNS server status".  This can be done after implementing issue #194 .

**Comment by netapp-aherbin** [comment]
Thank you for your feedback.  

"Status" has been renamed in the sidebar to "Status (HA, LDAP, DNS, MCC networking and storage)" It is is listed under the heading "What should I verify before I upgrade?" so no need to include "Verify" before.  

Amanda
