### ISSUE TITLE
there is no information on the page 

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap#197]
Page: [Configure IPspaces (cluster administrators only)](https://docs.netapp.com/us-en/ontap/networking/configure_ipspaces_@cluster_administrators_only@.html)

**Comment by netapp-forry** [comment]
Thanks Logan, we'll look into this.  Question: how did you get to this page? Was it via Search?

**Comment by loganbaez** [comment]
Hey Mark,

Adding my colleague Ryan. He informed me  about it.


Ryan, can you answer Mark. How you came to the link / page. Was it you searching or the customer etc.

Thanks


Logan Baez
Escalation Engineer
Technical Support Center
***@***.******@***.***>
Work hours: Monday-Friday, 7AM to 3:30PM EST (GMT -4)
***@***.***D778C1.52BDCA30]

**Comment by loganbaez** [comment]
One of our Cloud Solution Architects brought it up. However if you Google for “netapp configure ip spaces” it’s like the 3rd result:

***@***.***D778C1.B1F8C1D0]

Regards,

Ryan Urice
Escalation Engineer Cloud | NetApp A-Team

NetApp
984-209-7218 Direct Phone
***@***.******@***.***>

[A picture containing bird  Description automatically generated]<http://netapp.com/>


***@***.***D778C1.B1F8C1D0]<https://www.facebook.com/NetApp>   ***@***.***D778C1.B1F8C1D0] <https://www.instagram.com/netapp/>    ***@***.***D778C1.B1F8C1D0] <https://www.youtube.com/netapp>    ***@***.***D778C1.B1F8C1D0] <https://www.linkedin.com/company/netapp/>    ***@***.***D778C1.B1F8C1D0] <https://twitter.com/NetApp>

***@***.***D778C1.B1F8C1D0][NetApp Certified Technology Associate]

From: Baez, Logan ***@***.***>
Sent: Wednesday, July 14, 2021 3:03 PM
To: NetAppDocs/ontap ***@***.***>; NetAppDocs/ontap ***@***.***>
Cc: Author ***@***.***>; Urice, Ryan ***@***.***>
Subject: RE: [NetAppDocs/ontap] there is no information on the page (#197)

Hey Mark,

Adding my colleague Ryan. He informed me  about it.


Ryan, can you answer Mark. How you came to the link / page. Was it you searching or the customer etc.

Thanks


Logan Baez
Escalation Engineer
Technical Support Center
***@***.******@***.***>
Work hours: Monday-Friday, 7AM to 3:30PM EST (GMT -4)
***@***.***D778C1.B1F8C1D0]

**Comment by netapp-forry** [comment]
Thanks guys, that helps. We should be able to commission this and other empty pages in the next day or so.

**Comment by loganbaez** [comment]
As always , THANK YOU

-logan

**Comment by netapp-aherbin** [comment]
Logan,

We've removed this and other empty pages.  

Amanda
