### ISSUE TITLE
Giveback Expectations

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap#201]
Page: [Automatic giveback commands](https://docs.netapp.com/us-en/ontap/high-availability/ha_automatic_giveback_commands.html)

From: McGue, Tim <Timothy.McGue@netapp.com> 
Sent: Wednesday, July 21, 2021 8:09 PM
To: ng-doccomments <ng-doccomments@netapp.com>
Cc: Davis, Eric <Eric.Davis@netapp.com>; McGue, Tim <Timothy.McGue@netapp.com>
Subject: Giveback Expectations

Hello doccomments team…..

This document:
https://docs.netapp.com/us-en/ontap/high-availability/ha_automatic_giveback_commands.html#the-effects-of-automatic-giveback-parameter-combinations-that-apply-to-panic-situations

Eric and I had a recent case where the system had a takeover from a loss of a heartbeat and the automatic giveback was unexpected.  We don't call out that combination specifically in this document and wondered if we should.  It feels like it behaves the same was as the onreboot table calls out (but that's just a gut feeling from what we saw, probably need engineering to explain more).

However, diving in more I looked back at BURT 1105680.  For the table at the bottom of the page linked above.  I think the first two rows can be removed since the final row in the table states the same thing.  The fourth row (true/true/false) I believe should be a yes for automatic giveback.  

Thanks as always for your help!

Tim McGue

**Comment by netapp-jsnyder** [comment]
I reached out to our SME **Chethan Hublikar** for clarification. He validated the table as follows:

> Rows 1 and 2 say what last row is saying.  So we can remove the rows 1 and 2.  The current row 4 remains same (No).
> 
> A note about panic packet/information getting lost might help to clarify some situations.  Mainly, if a node panics and the panic packet doesn’t make it across to the partner, the partner might do a heartbeat loss takeover.  This is controlled by ’onfailure’ parameter.  And so the giveback is not controlled by auto-giveback-after-panic setting.

**Resolution**: I removed the first two rows, kept the 4th row the same and added the following note: Takeover could occur for other reasons during node panic.  In such cases giveback is not controlled by auto-giveback-after-panic setting

**Comment by TimMcGue** [comment]
That's fantastic thank you!  Love how fast you can turn this around in Github!

**Comment by netapp-jsnyder** [comment]
Issue resolved.
