### ISSUE TITLE
Just a minor tweak...

### ISSUE THREAD

**Issue by simonhazell** [NetAppDocs/ontap#204]
Page: [Creating a consistency group relationship](https://docs.netapp.com/us-en/ontap/smbc/smbc_install_creating_a_consistency_group_relationship.html)

The syntax for have AutomatedFailOver as the policy name where **O**ver has a capital letter

cluster2::> snapmirror create -source-path svm1_cluster1:/cg/cg_sql2 -destination-path svm1_cluster2:/cg/cg_sm_sql2 -cg-item-mappings sql2_db1:@sm_sql2_db1,sql2_logs1:@sm_sql2_logs1 -policy ?  
  **AutomatedFailOver**

The documentation has it as lowercase

**Comment by netapp-forry** [comment]
Thanks Simon -- we'll look into this immediately.

**Comment by netapp-lenida** [comment]
Thanks for the feedback Simon. I've updated the documentation so that the sample command output shows **AutomateFailOver**. The fix should be merged soon.

**Comment by netapp-lenida** [comment]
This issue has been resolved. Thanks again for the feedback.

**Comment by simonhazell** [comment]
Hi - I think if you search the documentation that it is a problem on other pages. I noticed it elsewhere, so should be corrected for completeness/accuracy

Simon
