### ISSUE TITLE
Please clarify this. Can you change MTU on vlan ifgrp indepedent of changing the physical ports or untagged interfaces?

### ISSUE THREAD

**Issue by siggins1** [NetAppDocs/ontap#206]
Page: [Modify MTU setting for interface group ports](https://docs.netapp.com/us-en/ontap/networking/modify_mtu_setting_for_interface_group_ports.html)

**Comment by netapp-barbe** [comment]
Hi siggins1 - I'm following up on my initial research and it is taking a bit longer than expected. Thanks for asking, I'll get back to you as soon as I hear more.

**Comment by netapp-barbe** [comment]
Hi again, the following change has been committed and will appear in the next build:
"VLAN MTU size should match the broadcast domain MTU of the underlying interface groups and physical ports. If a different VLAN setting is needed for a VLAN, it must not exceed the size specified by the underlying broadcast domain."
