### ISSUE TITLE
Step 2: Is the destination path incorrect?

### ISSUE THREAD

**Issue by chjones45** [NetAppDocs/ontap#218]
Page: [Adding and removing volumes in a consistency group](https://docs.netapp.com/us-en/ontap/smbc/smbc_admin_add_and_remove_volumes_in_consistency_groups.html)

Should the destination-path in Step 2 actually be "destination-path vs1_dst:vol_dst3" instead of vol_dst2?

**Comment by netapp-ahibbard** [comment]
Thanks for flagging this @chjones45 ; This has been updated
