### ISSUE TITLE
Modifying/adding FSx ONTAP compatibility

### ISSUE THREAD

**Issue by jsuarezs** [NetAppDocs/ontap#233]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

Hello team.

Could we modify the phrase: "For SnapMirror relationships of type “XDP”, using on premises or Cloud Volumes ONTAP releases:" specifying also the new service in AWS or create a new table for FSxN if necessary but I guess we can adjust this phrase to work with FSxN too.

Many thanks.

**Comment by netapp-forry** [comment]
Thanks Javier -- good idea. We'll see about getting this into the library ASAP.

**Comment by netapp-lenida** [comment]
Hi Javier, thanks again for your suggestion. FSx has been added to the table for SnapMirror relationships of type XDP.
