### ISSUE TITLE
Make current step 14 the new step 10

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#238]
Page: [Reactivate the original source SVM (FlexGroup volumes only)](https://docs.netapp.com/us-en/ontap/data-protection/reactivate-original-source-svm-flexgroup-task.html)

Can we please make the current step 14 (vserver start) the new step 10? The current steps 10-13 can be made 11-14. Vserver start is needed to allow client access; the steps as-written imply client access has to remain down until these snapmirror steps are complete but that's not the case. This change will make that more clear.

**Comment by netapp-forry** [comment]
Thanks Joey -- we'll look into clarifying this ASAP.

**Comment by netapp-lenida** [comment]
Hi Joey, I'll make this update today. Thanks!

**Comment by netapp-lenida** [comment]
Thanks again, Joey. The steps have been updated.
