### ISSUE TITLE
Clicking new chapter headings on left nav refreshes entire page

### ISSUE THREAD

**Issue by dclaybrook** [NetAppDocs/ontap#240]
Page: [ONTAP 9 Documentation](https://docs.netapp.com/us-en/ontap/index.html)
I'm opening this ticket on behalf of a few partners I've heard mention this behavior...

Using ONTAP as the example, when clicking on a chapter heading on the left menu nav, the entire page refreshes to take the user to the chapter's home page. This is seen at the 1-2 second mark in the attached video. On a slower connection, this transaction is more pronounced and seems to be frustrating some users. You can also see this at the 5-6 second mark and several other points in the video.

I think the worst part of the user experience is that the entire nav menu appears to expand and then collapses. It's a jarring visual for some.

I'm a NetApper, so feel free to contact me internally if you'd prefer.

Sorry the video is short and the timings are so quick. GitHub limits them to 10 MB.
[Demo Recording](https://user-images.githubusercontent.com/14077814/140589666-9410973e-b006-4536-bb7d-6af9d279258f.mov)

**Comment by netapp-forry** [comment]
Thanks Drew -- I've noticed this too. I *think* it's a known issue with our Tools team, but I'll check.

**Comment by netapp-forry** [comment]
Drew, apologies for the delay. It _has_ been identified as an issue with our Tools team and it's in the queue for a fix, being tracked internally here: NetAppDocs/jekyll#659

If you like, I'll keep this issue open until it's fixed, or I'll close it with this note. Please let me know. Thanks again for contacting us.

**Comment by netapp-forry** [comment]
This issue is being tracked separately by the IE Tools Team and will be scheduled for a fix ASAP.
