### ISSUE TITLE
typo in ONTAP 9.10.1 docs

### ISSUE THREAD

**Issue by pgbachman** [NetAppDocs/ontap#242]
Page: [LIFs and service policies in ONTAP 9.6 and later](https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html)

Missing space 

![image](https://user-images.githubusercontent.com/3339516/140778916-697b05c9-3f02-4de7-a46c-e47a164a8815.png)

**Comment by netapp-ahibbard** [comment]
Thanks for catching this @pgbachman . Documentation has been corrected.
