### ISSUE TITLE
Can this document be updated for ONTAP 9.10.1, now that it is in RC1 status?

### ISSUE THREAD

**Issue by jgartrell-missional** [NetAppDocs/ontap#244]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

**Comment by netapp-forry** [comment]
Thanks John -- you're right, of course, this needs to be updated. We'll do so ASAP.

**Comment by netapp-aherbin** [comment]
Updated.
