### ISSUE TITLE
Add NetApp Support Link?

### ISSUE THREAD

**Issue by dclaybrook** [NetAppDocs/ontap#246]
Page: [Introduction and concepts](https://docs.netapp.com/us-en/ontap/introduction-concepts/index.html)

Would it be possible (and logical) to add links to the [NetApp Knowledge Base](https://kb.netapp.com) and to the [NetApp Discord](https://discord.gg/NetApp) in the sidebar or header/footer areas?

The [How to Contribute](https://docs.netapp.com/us-en/contribute/) page might be a good spot too.

**Comment by netapp-forry** [comment]
Thanks Drew -- good idea. I'll look into this and see about adding the links you suggested.

**Comment by netapp-forry** [comment]
Hi Drew -- Sorry for the slow response.

We already have a KB link in the More resources tile, which is our standard location for most doc sites.

I *think* the Communities and blogs tile might be a good location for Discord link. Am I understanding correctly that we are now offering a Discord community for NetApp customers, partners, and employees? This sounds like a good idea. I'll also check with my colleagues; it might already be included in other NetApp product doc sites.

My inclination for the How to contribute page is that we want to keep it focused on contributions to NetApp product doc and solutions.

Thanks again!

**Comment by netapp-forry** [comment]
Confirmed the NetApp Discord link on the Introduction and concepts page. Thanks again!

**Comment by dclaybrook** [comment]
Thanks Mark!
