### ISSUE TITLE
Conflicting information on NVMe support in MCC environments

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/ontap#247]
Page: [Considerations for SAN configurations in a MetroCluster environment](https://docs.netapp.com/us-en/ontap/san-config/san-config-mcc-concept.html)

This page says that NVMe (I assume this means both NVMe/FC and NVMe/TCP) is not supported on MetroCluster configurations.

However, the NVMe/FC Technical Report, [TR-4684](https://www.netapp.com/media/10681-tr4684.pdf) (newest version from June 2021) explicitly states that it is supported (Table 3 on page 21)

Which one is correct?

**Comment by netapp-aherbin** [comment]
The TR is correct. NVMe is supported on MetroCluster configurations. We've updated the documentation.
