### ISSUE TITLE
SnapLock no longer requires dedicated aggregates

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/ontap#248]
Page: [SnapLock workflow](https://docs.netapp.com/us-en/ontap/snaplock/workflow-concept.html)

This page (and subsequent pages) should be updated to reflect the fact that SnapLock no longer requires dedicated aggregates, i.e. the steps "create SnapLock compliance aggregate" and "create SnapLock enterprise aggregate" should be removed.

If there are any other conflicting features, these should also be mentioned (e.g. is this new "SnapLock without dedicated aggregate" supported on MCC systems? MCC is often a showstopper for new features)

**Comment by netapp-forry** [comment]
Thanks Michael -- we'll look into this and get back to you ASAP.

**Comment by netapp-lenida** [comment]
Thanks, Michael. The documentation has been updated. The information regarding MCC was reviewed when the documentation for updated, so it should be correct.
