### ISSUE TITLE
Question about FSA Restriction

### ISSUE THREAD

**Issue by rafaelo-ntap** [NetAppDocs/ontap#251]
Page: [File System Analytics overview](https://docs.netapp.com/us-en/ontap/concept_nas_file_system_analytics_overview.html)

Hello,

I'm the NetApp OPM for Fujitsu, I received a question about this page's content. Specifically the customer points out there's no inclusion of Fabric Pool in the restriction list of volume types. Could some mention of this be added to the document description to clear this up, is it supported or not?

Regards,
RO

**Comment by netapp-ahibbard** [comment]
Hi @rafaelo-ntap, there are no restrictions on using File System Analytics with a FabricPool-enabled volume. As the list of restrictions with File System Analytics is exhaustive, the implication is that anything outside the list will work with File System Analytics. Documentation does not typically identify single cases where a feature is supported. That said, FabricPool documentation has been updated to note compatibility with FSA: https://docs.netapp.com/us-en/ontap/cloud/fabricpool-concept.html
