### ISSUE TITLE
Question about Ransomware Support 

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/ontap#255]
Page: [Anti-ransomware use cases and restrictions](https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html)

At Unsupported system configurations section, ONTAP Select is supported or not?
Could you please clarify about his?

Best regards,

**Comment by netapp-forry** [comment]
Thanks for the question. I'll look into this and get back to you.

**Comment by netapp-forry** [comment]
The topic has been updated and published -- thanks again for letting us know.
