### ISSUE TITLE
Unsupported system configurations for the ONTAP Select.

### ISSUE THREAD

**Issue by netapptakayuki** [NetAppDocs/ontap#257]
Page: [Anti-ransomware use cases and restrictions](https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html)

The ONTAP Select is not supported anti-ransomware now and should be added to this "Unsupported system configuration" section.

**Comment by netapp-forry** [comment]
Thank you, Takayuki-san -- we'll update this content ASAP.

**Comment by netapp-forry** [comment]
The topic has been updated and published -- thanks again for letting us know.
