### ISSUE TITLE
XDP SnapMirror should support data transfer between CVO ONTAP 9.9.0 and FSxN 9.10.0, so please correct the documentation.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#262]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

XDP SnapMirror should support data transfer between CVO ONTAP 9.9.0 and FSxN 9.10.0, so please correct the documentation.

**Comment by netapp-forry** [comment]
Thanks for letting us know, we'll look into this right away.

**Comment by netapp-lenida** [comment]
I apologize for the delay. I'm following up with one of our SMEs to verify that CVO ONTAP 9.9.0 and FSxN 9.10.0 are supported. I will make the appropriate change to the documentation as soon as possible.

**Comment by netapp-forry** [comment]
This issue is on hold pending resolution of FSx content strategy questions.
@netapp-ehoffman, @jenatnetapp - FYI

**Comment by kanitani** [comment]
It should also support On-prem ONTAP instead of FSxN, so please correct the documentation.
![image](https://user-images.githubusercontent.com/68621663/172326384-7b5d9d41-2c9e-4b33-b417-c320f3210f91.png)

**Comment by kanitani** [comment]
How about this relation between CVO9.9.0 and ONTAP9.10.1?

**Comment by netapp-lenida** [comment]
@kanitani, the table indicates that these releases do not interoperate.
![CVO support_2](https://user-images.githubusercontent.com/54081920/172950131-444ad4fb-6d2f-4240-b21d-122344bd90f8.jpg)

**Comment by kanitani** [comment]
Why do you mention different items?
(1) You mention 9.10.0 and 9.10.0
(2) You mention 9.10.1 and 9.9.0
(3) You mention 9.11.0 and 9.11.0

What I'm pointing out is that this "No" is wrong.
![image](https://user-images.githubusercontent.com/68621663/173005166-37bdd6cd-3e75-493e-9e0f-c11efaaffd2c.png)

**Comment by kanitani** [comment]
Are the following combinations not supported?
If for any reason, please state that in the documentation.

9.9.0  --XDP SnapMirror--->  9.10.0
9.9.0  --XDP SnapMirror--> 9.10.1
9.9.0  --XDP SnapMirror--->  9.11.0
9.9.0  --XDP SnapMirror--->  9.11.1

9.10.0  --XDP SnapMirror--->  9.9.0
9.10.1  --XDP SnapMirror--->  9.9.0
9.11.0  --XDP SnapMirror--->  9.9.0
9.11.1  --XDP SnapMirror--->  9.9.0

**Comment by kanitani** [comment]
There was no such unsupported configuration in ONTAP in the past. If the combination is not supported, please state the reason in the manual.

**Comment by netapp-lenida** [comment]
@kanitani, I'm going to close this issue, but I wanted to let you know that we've been working on ways to improve this topic and the tables within it. Some improvements have already been implemented, but we are researching additional ways to make it easier to locate which ONTAP releases are supported with SnapMirror. Thank you for contacting us about the issues you found. I hope some our current or improvements will help you.
