### ISSUE TITLE
cluster_src should be cluster_dst for snapmirror quiesce command

### ISSUE THREAD

**Issue by orb71** [NetAppDocs/ontap#263]
Page: [Delete a volume replication relationship](https://docs.netapp.com/us-en/ontap/data-protection/delete-volume-replication-relationship-task.html])

A quiesce operation can be executed only on the cluster_dst

```
cluster_src::> snapmirror quiesce -destination-path svm_backup:volA_dst
```

should be in fact

```
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
```

Also on the same page.

`If you have SnapMirror Synchronous relationships (supported starting with ONTAP 9.5), quiesce the replication relationship:`

The quiescing operation has always been a step in the workflow, having a mention about SnapMirror Synchronous is misleading.

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll look into this right away.
