### ISSUE TITLE
404 file not found

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#264]
Page: [Configure audit policies on NTFS security-style files and directories](https://docs.netapp.com/us-en/ontap/nas-audit/configur-policies-ntfs-security-concept.html)

There are two dead links.
Please see below.
![image](https://user-images.githubusercontent.com/68621663/143816817-dcd8be45-c679-44a9-8a87-8dbe39574382.png)
![image](https://user-images.githubusercontent.com/68621663/143817128-7c34a9b9-b344-4a54-baa7-c55fc8c1c8e1.png)

I cannot access these URLs below that are linked from "https://docs.netapp.com/us-en/ontap/nas-audit/configur-policies-ntfs-security-concept.html"
  https://docs.netapp.com/us-en/ontap/nas-audit/configure-ntfs-audit-policies-windows-security-tab-task.html
  https://docs.netapp.com/us-en/ontap/nas-audit/configure-ntfs-audit-policies-concept.html

**Comment by netapp-ahibbard** [comment]
@kanitani Thanks for catching these dead links. We have updated the content to remove them.
