### ISSUE TITLE
Managing certs is a dead link

### ISSUE THREAD

**Issue by aknetapp** [NetAppDocs/ontap#268]
Page: [[Event and performance monitoring](https://docs.netapp.com/us-en/ontap/event-performance-monitoring/index.html)](https://docs.netapp.com/us-en/ontap/event-performance-monitoring/index.html#)

manage certs links to https://docs.netapp.com/us-en/ontap/manage-certificates-sm-task.html which is a dead link.

**Comment by netapp-forry** [comment]
Thanks AK -- we'll look into this right away.
