### ISSUE TITLE
Support details needs to indicate MetroCluster support starting in 9.8 for SVM scoped key servers

### ISSUE THREAD

**Issue by tulledge** [NetAppDocs/ontap#270]
Page: [Configure NetApp Volume Encryption overview](https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html)

In the section Support details change:

SVM scope | Beginning with ONTAP 9.6, NVE supports SVM scope for external key  management only, not for Onboard Key Manager. MetroCluster is not  supported.

to:

SVM scope | Beginning with ONTAP 9.6, NVE supports SVM scope for external key  management only, not for Onboard Key Manager. MetroCluster is supported starting with ONTAP 9.8.

Thanks,
Dan Tulledge

**Comment by netapp-forry** [comment]
Thanks Dan -- we'll update this right away.
