### ISSUE TITLE
Add Commercial Solutions for Classified (CSfC) note in the cc-mode-enabled section

### ISSUE THREAD

**Issue by tulledge** [NetAppDocs/ontap#273]
Page: [Enable onboard key management in ONTAP 9.6 and later (NVE)](https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nve-task.html)

After this statement:
For NVE, if you set cc-mode-enabled=yes, volumes you create with the volume create and volume move start commands are automatically encrypted. For volume create, you need not specify -encrypt true. For volume move start, you need not specify -encrypt-destination true.

Add:
When configuring ONTAP data at rest encryption to meet the requirements for Commercial Solutions for Classified (CSfC), you must use NSE with NVE and the Onboard Key Manager is enabled in Common Criteria mode.  For more information on CSfC see: https://assets.netapp.com/m/128a1e9f4b5d663/original/Commercial-Solutions-for-Classified.pdf

**Comment by netapp-forry** [comment]
Thanks Dan -- we'll update the topic right away.
