### ISSUE TITLE
Please add a reference to HWU on page What version of ONTAP can I upgrade to?

### ISSUE THREAD

**Issue by lamandanetapp** [NetAppDocs/ontap#278]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

Requesting update for Elio token ID 124c6d959e4546e4a82e230b16f1b926 - Can we please add a reference on this page that customers should also consult the HWU / verify their platform information supports the version they're looking to upgrade to? (I.e. Yes - the version you can upgrade to varies based on what version they are currently on, but it also varies based on what platform they're currently on as well.)

**Comment by netapp-aherbin** [comment]
Thank you for your feedback.  We are looking into making the update.

Amanda

**Comment by netapp-aherbin** [comment]
We've added the suggested information and HWU link to the topic. Thank you.
