### ISSUE TITLE
Browser Tab Labeling

### ISSUE THREAD

**Issue by aholt123** [NetAppDocs/ontap#282]
Page: [ONTAP 9 Documentation](https://docs.netapp.com/us-en/ontap/index.html)

Right now, when I browse the ONTAP Documentation Center, the page titles don't display the specific topic title that I am viewing. Each page displays the identical title "ONTAP 9 Documentation Center". It makes it difficult to see at a glance what pages you have open and are viewing, especially when you have multiple tabs open. If I have multiple topics/tabs open for the Documentation Center, I have to click through each tab to find the specific topic I am looking for. For example, it would be helpful if the tab I am viewing was called "Expanding Aggregates", along side the topic titles of the other two pages I have open, "Minimum number of hot spares you should have", and "Considerations for sizing RAID groups".

**Comment by netapp-forry** [comment]
Hi Adam -- Thanks for contacting us.
Sorry, I'm not grasping the problem you're experiencing. Perhaps seeing it would help -- would you be willing to spend a few minutes on a Zoom call next week? I'm OOO Tue-Wed, but I'd be available Mon-Thu-Fri.

**Comment by netapp-forry** [comment]
@aholt123 - Can you provide more information about this issue?

**Comment by aholt123** [comment]
Please provide the initial request text here and I can update. Thanks.

Adam Holt

**Comment by netapp-forry** [comment]
Responded via NetApp email.

**Comment by netapp-forry** [comment]
Could not reproduce, no further info received. Please reopen if you can provide more info.
