### ISSUE TITLE
Docs for customers that can't use Active IQ

### ISSUE THREAD

**Issue by GlowingMoose** [NetAppDocs/ontap#283]
Page: [Upgrade ONTAP overview](https://docs.netapp.com/us-en/ontap/upgrade/index.html)

You need to add back all the documentation for customers that cannot use Active IQ. Why has all that documentation been removed!

**Comment by netapp-aherbin** [comment]
Hi,

The documentation for customers that cannot use Active IQ remains available.  In the upgrade content section there are two options:  one to "[Upgrade with Upgrade Advisor](https://docs.netapp.com/us-en/ontap/upgrade/task_plan_with_upgrade_advisor.html)" and one to upgrade "[Upgrade without Upgrade Advisor](https://docs.netapp.com/us-en/ontap/upgrade/task_plan_without_upgrade_advisor.html)".  If you don't have Active IQ, you should follow the stops to upgrade without Upgrade Advisor and then proceed to the third section which is "[What should I verify before I upgrade with or without Upgrade Advisor?](https://docs.netapp.com/us-en/ontap/upgrade/task_what_to_check_before_upgrade.html)"  

We are working to make the experience of finding needed content better.  Would you mind sharing how you came to the conclusion the content was not there?

Thanks for your valuable feedback!
Amanda

**Comment by netapp-aherbin** [comment]
Please feel free to reopen issue with additional information.  Closing for now as the documentation in question is available.
