### ISSUE TITLE
Missing a space

### ISSUE THREAD

**Issue by jgartrell-missional** [NetAppDocs/ontap#287]
Page: [Enable or disable AES encryption for Kerberos-based communication](https://docs.netapp.com/us-en/ontap/smb-admin/enable-disable-aes-encryption-kerberos-task.html)

anSVM  should be an SVM

Many thanks

**Comment by netapp-forry** [comment]
Thanks John -- We'll fix this ASAP.
@netapp-ahibbard -- When you fix the typo, please also change instances of "the CIFS server" to "the SMB server" to conform to current usage. However, leave all command references -- e.g. "vserver cifs security" -- as is, as the CLI has not change. Thanks!
