### ISSUE TITLE
Consider adding footnote for FIPS compliance and how it could affect access.

### ISSUE THREAD

**Issue by netapp-adlove** [NetAppDocs/ontap#292]
Page: [Enable SSH public key accounts](https://docs.netapp.com/us-en/ontap/authentication/enable-ssh-public-key-accounts-task.html)

A customer commented on this KB ( https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Unable_to_SSH_with_FIPS_enabled%2C_using_public_key_authentication ) the following:

"This answered my question directly. I only wish this was a footnote in the admin guide for the section about using public key authentication. this KB article was found only after 3hrs of Google"

They seem to have been referring to this document describing how to enable public key account. I suggest we link the customer to this kb, or add in our docs information describing FIPS compliance scenarios.

**Comment by netapp-forry** [comment]
Thanks Adrian - good suggestion, we'll look into this ASAP.

**Comment by netapp-forry** [comment]
Tracking in BURT 1448836.

**Comment by netapp-forry** [comment]
Updated two topics, fixed BURT.
https://docs.netapp.com/us-en/ontap/networking/configure_network_security_using_federal_information_processing_standards_@fips@.html
https://docs.netapp.com/us-en/ontap/authentication/enable-ssh-public-key-accounts-task.html
