### ISSUE TITLE
NVMe limits

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#295]
Page: [Considerations for FC-NVMe configurations](https://docs.netapp.com/us-en/ontap/san-config/fc-nvme-config-concept.html)

This page is client on the node limits. I believe NVMe is restricted to 4-node clusters or small. We just had a customer get burned by this limitation. We also have a limit of 8 SVMs, I think.

**Comment by netapp-forry** [comment]
Thanks again -- will investigate ASAP.

**Comment by netapp-aherbin** [comment]
Investigating with SAN TME.

**Comment by netapp-forry** [comment]
Corrections review by SME and added to topic, publication verified. Thanks again for your input!
