### ISSUE TITLE
SVMDR destination volume placement details requested

### ISSUE THREAD

**Issue by neilmaldy** [NetAppDocs/ontap#296]
Page: [Exclude volumes from SVM replication](https://docs.netapp.com/us-en/ontap/data-protection/exclude-volumes-svm-replication-task.html)

Could you please add a new section on SVMDR destination volume placement and include additional information and examples on using volume modify -vserver -volume -vserver-dr-protection unprotected and vserver modify -vserver -aggr-list to control volume placement on the destination?

**Comment by netapp-forry** [comment]
Thanks Neil -- we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks for bringing this up, Neil. I've added the following topics that should provide the additional information you wanted:

https://docs.netapp.com/us-en/ontap/data-protection/vol-placement-criteria-svm-dest-reference.html
https://docs.netapp.com/us-en/ontap/data-protection/specify-svmdr-vol-dest-aggr.html
