### ISSUE TITLE
Doc page doesn't contain additional cifs security options available in 9.6-9.8 (maybe earlier)

### ISSUE THREAD

**Issue by dalvenjah** [NetAppDocs/ontap#298]
Page: [Display information about CIFS server security settings](https://docs.netapp.com/us-en/ontap/smb-admin/display-server-security-settings-task.html)

Documentation page lists output for "vserver cifs security show"; but sample output (and documentation of settings) ends at "Is SMB Encryption Required"

OnTAP 9.6 adds the following output entries:
                        Client Session Security:                none
                SMB1 Enabled for DC Connections:               false
                SMB2 Enabled for DC Connections:      system-default
  LDAP Referral Enabled For AD LDAP connections:               false
               Use LDAPS for AD LDAP connection:               false

and OnTAP 9.8 adds the following:
      Encryption is required for DC Connections:               false

Would like some detail on these new 6 options - I can guess but would like to know the implications of each setting.

Thank you!

**Comment by netapp-forry** [comment]
Thanks for letting us know! I'll dig into this as soon as I'm back in the new year. Happy holidays!

**Comment by netapp-forry** [comment]
Topic updated with additional parameters displayed, publication verified.
To learn more about the individual settings, I'd suggest searching in the site. For example, if you search "channel binding ldap", your results will include the following topic, which describes the channel binding functionality:
   https://docs.netapp.com/us-en/ontap/nfs-config/using-ldap-concept.html
If you are already a NetApp customer, you can also consult the ONTAP Release Notes for an overview of file access features under Authentication and Windows enhancements:
   https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508

Thanks again for your input, much appreciated!
