### ISSUE TITLE
commands appear to be incorrect

### ISSUE THREAD

**Issue by jbeermannetapp** [NetAppDocs/ontap#302]
Page: [Configure FC adapters for target mode](https://docs.netapp.com/us-en/ontap/san-config/configure-fc-adapters-target-mode-task.html)

from a customer:
ubfs-lsf-cl2::*> node run -node ubfs-lsf-cl2n2 storage disable adapter -d 1c
Invalid host adapter "-d"
usage: disable [-f] adapter <name>
        disables and stops I/O traffic on adapters and switches

ubfs-lsf-cl2::*> node run -node ubfs-lsf-cl2n2 storage disable adapter 1c   
Disabling adapter 1c...

ubfs-lsf-cl2::*> system hardware unified-connect modify -t target 1c        

Error: "1c" is an invalid value for field "-node <nodename>"
       Valid choices in this command's context: ubfs-lsf-cl2n1, ubfs-lsf-cl2n2

ubfs-lsf-cl2::*> system hardware unified-connect modify -t target -node ubfs-lsf-cl2n2 -adapter 1c

Warning: FC-4 type on adapter 1d will also be changed to target.
Do you want to continue? {y|n}: y
Any changes will take effect after rebooting the system. Use the "system node reboot" command to reboot.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Jim -- we'll look into this ASAP.

**Comment by netapp-forry** [comment]
Verified corrections in published topic -- thanks again!
