### ISSUE TITLE
Recommending upgrade to latest patch level before upgrade to major release version

### ISSUE THREAD

**Issue by jjbusiness75** [NetAppDocs/ontap#303]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

Received this from a Support Delivery Manager after major downtime was had during an ONTAP upgrade. Would like consideration for the official documentation. 

Contact me for name of SDM for follow-up.

"If you are plaining an ONTAP upgrade from an old ONTAP version (like 9.1 or 9.3) to a newer version and the system is not in one of the latest Patches please do not upgrade directly to the next major version.
It is highly recommended to upgrade first to the latest Patch level in the same ONTAP family and only then go to the next Major version.
For example if your system is 9.1P9 and you are planning to go to 9.7 this is the recommendation path:
9.1P9 - > 9.1P20 -> 9.3 -> (multi-hop 9.5) -> 9.7.
And in all major version please use the latest patch level that is out.
This way will ensure that all the issues in the old version and where solved are implemented before moving to the next major version.
It can save downtime to the customers."

**Comment by netapp-forry** [comment]
Thanks JJ -- please contact me directly re. this issue -- thanks -- forry@netapp.com

**Comment by netapp-forry** [comment]
Opened BURT 1449946 for internal discussion.

**Comment by netapp-forry** [comment]
Topic updated with best practice guidance.
