### ISSUE TITLE
Why does text refer to Synchronous SnapMirror

### ISSUE THREAD

**Issue by nichollri** [NetAppDocs/ontap#305]
Page: [Restore the contents of a volume from a SnapMirror destination](https://docs.netapp.com/us-en/ontap/data-protection/restore-volume-snapvault-backup-task.html)

The documentation is discussing general Aysnc SnapMirror and restoring from a destination snapshot.  
This wording is confusing:

What you’ll need

To restore a volume from a **SnapMirror Synchronous destination** (supported beginning withONTAP 9.5), you must first delete and release the relationship.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Richard -- we'll look into this ASAP.
