### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by jsknair** [NetAppDocs/ontap#309]
Page: [Enable ONTAP S3 access for local FabricPool tiering](https://docs.netapp.com/us-en/ontap/s3-config/enable-ontap-s3-access-local-fabricpool-task.html)

The document has the word 'ipspace' misspelled as 'ispace' . Pls fix it.

**Comment by netapp-lenida** [comment]
Thank you for calling this typo to our attention. We'll fix it right away.
