### ISSUE TITLE
TOC doesn't match section heading

### ISSUE THREAD

**Issue by neilmaldy** [NetAppDocs/ontap#311]
Page: [Convert a directory to a qtree using a Windows client](https://docs.netapp.com/us-en/ontap/volumes/convert-directory-qtree-windows-client-task.html)

TOC says "logical space reportry..." but section is called "Convert a directory to a qtree using a Windows client"

**Comment by netapp-forry** [comment]
Thanks Neil -- you're right, of course, the sidebar TOC should match the topic title. We'll fix ASAP.
