### ISSUE TITLE
add space between username and hostname_or_IP

### ISSUE THREAD

**Issue by tmatejuk** [NetAppDocs/ontap#319]
Page: [Access the cluster by using SSH](https://docs.netapp.com/us-en/ontap/system-admin/access-cluster-ssh-task.html)

in 'Step 1'
second ssh command 'format' is
ssh -l usernamehostname_or_IP [command]

and should be ( space between username and hostname_or_IP )
ssh -l username hostname_or_IP [command]

**Comment by netapp-forry** [comment]
Thanks for calling this to our attention -- we'll fix it ASAP.
