### ISSUE TITLE
Missing information in steps

### ISSUE THREAD

**Issue by lacem** [NetAppDocs/ontap#320]
You cannot enable FIPS level key on a drive without first applying a data key. 
Please add a note to first ensure that drives are keyed with a data key id before applying FIPS key. 

Adding a FIPS key without a data key results in the drive showing "Part" for the mode. 

Sample from lab where DATA key is not applied:
fas8060-nse-rtp-1::*> storage encryption disk modify -disk 1.10.0 -fips-key-id 000000000000000002000000000001009e726b7f10e7532eb9a70f48695c3bd90000000000000000

Info: Starting modify on 1 disk on node fas8060-rtp-6b.
      View the status of the operation by using the "storage encryption disk show-status" command.

fas8060-nse-rtp-1::*> storage encryption disk show -fips
Disk     Mode FIPS-Compliance Key ID
-------- ---- ----------------------------------------------------------------
1.10.0   part 000000000000000002000000000001009E726B7F10E7532EB9A70F48695C3BD9

Also, you must be in advanced to apply FIPS level key. A message is displayed if you are not:

fas8060-nse-rtp-1::> storage encryption disk modify -disk * -fips-key-id 0x0
Error: command failed on disk "1.11.13": Setting the FIPS-compliance key to the manufacture secure ID is not allowed at this privilege level.
Warning: Do you want to continue running this command? {y|n}:

**Comment by netapp-forry** [comment]
Matt, thanks for letting us know -- I'll look into this and get back to you ASAP.

**Comment by lacem** [comment]
Hello Mark,

I stand corrected on the last bit regarding the priv level. You can set a key just not unlock without being in elevated privileges.

Workflow:

fas8060-nse-rtp-1::> storage encryption disk modify -disk 1.10.0 -fips-key-id 0x0

Error: command failed: Setting the FIPS-compliance key to the manufacture secure ID is not allowed at this privilege level.

fas8060-nse-rtp-1::> set adv

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

fas8060-nse-rtp-1::*> storage encryption disk modify -disk 1.10.0 -fips-key-id 0x0

Info: Starting modify on 1 disk on node fas8060-rtp-6b.
      View the status of the operation by using the "storage encryption disk show-status" command.

fas8060-nse-rtp-1::*> set admin

fas8060-nse-rtp-1::> storage encryption disk modify -disk 1.10.0 -fips-key-id 000000000000000002000000000001009e726b7f10e7532eb9a70f48695c3bd90000000000000000

Info: Starting modify on 1 disk on node fas8060-rtp-6b.
      View the status of the operation by using the "storage encryption disk show-status" command.


So I guess really all we need to make sure is a data key is set.



Matthew Lacey
Technical Support Engineer
M-F 0700 - 1600 EST

NetApp
984-209-7098 Direct Phone
***@***.******@***.***>

 For technical assistance on a new or existing case, please call:
* US & Canada 888-4-NETAPP
* EMEA/Europe  00-800-44-638277
* Asia/Pacific  800-8008-0800

You may also get Support on the Web at http://mysupport.netapp.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__mysupport.netapp.com&d=DwQGaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=l-Aqes3fHVCTcS6w__N4D4dJ8klgqT8gXFoh4hPy6Oo&m=uS2KaaXuVIE31Qf5W9Mx9Yy-cEqtMP0CQ3JvqbMiJiY&s=t-73NR5MreEy3VGnujiuOly5Wzo9kydSGo6CI34X2LE&e=>.

Everyone in the NetApp Technical Support Center is committed to providing the
highest level of customer satisfaction.  If you believe that the level of support
can be improved, please contact my manager, Chris Duke, at ***@***.******@***.***>.


[Welcome to Data Driven]

[Facebook]<https://urldefense.proofpoint.com/v2/url?u=https-3A__www.facebook.com_NetApp-3Ffref-3Dts&d=DwMGaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=l-Aqes3fHVCTcS6w__N4D4dJ8klgqT8gXFoh4hPy6Oo&m=uS2KaaXuVIE31Qf5W9Mx9Yy-cEqtMP0CQ3JvqbMiJiY&s=B3lEjgNXUEr4IrINhwMbl2hBhqOeQfTQrt4w5qYXJ1w&e=>[Twitter]<https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_NetApp&d=DwMGaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=l-Aqes3fHVCTcS6w__N4D4dJ8klgqT8gXFoh4hPy6Oo&m=uS2KaaXuVIE31Qf5W9Mx9Yy-cEqtMP0CQ3JvqbMiJiY&s=83fJD6ZpyowOpNTOHs6XCXxQGchCdRkT9sFJ-BAZ6qI&e=>
 #DataDriven
