### ISSUE TITLE
Changes for Automatic giveback commands

### ISSUE THREAD

**Issue by sdowling03** [NetAppDocs/ontap#322]
Page: [Automatic giveback commands](https://docs.netapp.com/us-en/ontap/high-availability/ha_automatic_giveback_commands.html)

There are just some contradictions on the following documentation page. The page correctly states:
"The -onreboot parameter applies to reboots and halt commands issued from ONTAP. When the -onreboot parameter is set to false, a takeover does not occur in the case of a node reboot. Therefore, automatic giveback cannot occur, regardless of whether the -auto-giveback parameter is set to true. A client disruption occurs."

But then the table has no/no for the Does automatic giveback occur collum when -onreboot true and -auto-giveback false. This is incorrect and is contradicting the above statement.

**Comment by netapp-forry** [comment]
Sean, thanks for calling this to our attention -- we'll fix it ASAP.
