### ISSUE TITLE
SM-BC is not SM-S

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#326]
Page: [Additional restrictions and limitations](https://docs.netapp.com/us-en/ontap/smbc/smbc_plan_additional_restrictions_and_limitations.html)

The documention for SM-BC, including the link above, is mixing up SM-S and SM-BC. This particular doc discusses limits for SM-S and I'm not sure it's correct for SM-BC.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Jeffrey -- we'll look into this ASAP.
