### ISSUE TITLE
Request precision regarding requirements for MetroCluster

### ISSUE THREAD

**Issue by jfmartin67** [NetAppDocs/ontap#329]
Page: [Enable external key management in ONTAP 9.6 and later (NVE)](https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-external-key-management-96-later-nve-task.html)

The text should mention something like this: In the case of a MetroCluster Configuration, it has to be configured and setup first before enabling KMIP servers.

**Comment by netapp-forry** [comment]
Jean-Francois, thanks for letting us know -- we'll look into this ASAP.

**Comment by netapp-folivia** [comment]
Hi! I read this page and found we do have a bullet point, ' You must configure the MetroCluster environment before the key manager is configured.' I'll close this issue but thanks for keeping a close eye on the docs!

**Comment by netapp-folivia** [comment]
Thanks, Jean-Francois. I understand perfectly now. I'll make the update and let you know here when it's live.

**Comment by netapp-folivia** [comment]
Hi Jean-Francois, we've updated the docs -- you can see the changes here: https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-external-key-management-96-later-nve-task.html Thanks!
