### ISSUE TITLE
add note: •	Release Note text: “Automatic firmware update functionality is currently unavailable. You must continue to download required firmware updates manually.”

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap#333]
Page: [Update firmware](https://docs.netapp.com/us-en/ontap/task_admin_update_firmware.html)

the feature is disabled from the support site. 

Re: CSD Non-Stop Ops: IMPORTANT! - KEY FEATURE MISSING from ONTAP Version 9.10.1

The driver for this delay was a Global Trade Compliance (GTC) review that happened after development on the primary feature was completed.  The result is that some changes were needed with AutoSupport On Demand Service (AODS) to validate two things: 
1.	Customer is not on an entity list (i.e. a company we’re blocked from business with by the government) 
2.	The request is not coming from an IP address in a country we’re prohibited from doing business

**Comment by netapp-forry** [comment]
Tracking this issue in internal email.
