### ISSUE TITLE
HTTP Error 404 File not found - when opening the anti-ransomware documentation from System Manager

### ISSUE THREAD

**Issue by tomerikko** [NetAppDocs/ontap#337]
In system Manager (i used 9.10.1RC1) there is a built-in search module in the middle of the top bar.
in this search module, if you search for anti, you will see a link to a documentation page called "anti-ransomware documentation", 
by clicking on this link you get to a page with this URL:
https://docs.netapp.com/us-en/ontap/security-anti-ransomware-overview-concept.html

but this page does not exist hence, you get a 404 HTTP error .
Please redirect this link the systems out there uses to the correct page.

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll fix this ASAP.
