### ISSUE TITLE
Facts not in evidence: creating audit directories in ONTAP

### ISSUE THREAD

**Issue by dplaflamme-ibx** [NetAppDocs/ontap#339]
Page: [How the ONTAP auditing process works](https://docs.netapp.com/us-en/ontap/nas-audit/auditing-process-concept.html)

This page refers casually to an audit directory needing to exist before auditing can be created but doesn't discuss how to create one, let alone if there are issues about choosing where to create one. That seems worth a hyperlink to an article on those nuances.

**Comment by netapp-forry** [comment]
Thanks for pointing this out -- I'll look into it ASAP.

**Comment by netapp-forry** [comment]
We have updated the topic mentioned above, and one additional one.
Planning an auditing configuration
 https://docs.netapp.com/us-en/ontap/nas-audit/plan-auditing-config-concept.html#parameters-common-to-all-auditing-configurations

From the latter topic: "Log destination path ... Specifies the directory where the converted audit logs are stored, typically a dedicated volume or qtree."

Your suggestion was welcome; apparently others have had questions about this before. From a community discussion:
https://community.netapp.com/t5/ONTAP-Discussions/How-to-create-a-destination-for-audit-logging-in-clustermode-NetApp-Release-8-3/m-p/125416

Thanks again for contacting us.
