### ISSUE TITLE
Man pages topic needs language and link improvements

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap#342]
Page: [ONTAP manual pages](https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html)

Few if any users refer to man pages as manual pages. Why not title this topic "ONTAP man pages?" This would imply fixing the file name as well for SEO purposes. Alternately, edit the topic title to say "ONTAP manual (man) pages" and make do.

Recommended re-write:

The ONTAP manual (man) pages explain how to use ONTAP CLI commands. Man pages are available at the ONTAP command line and  are available online in the ONTAP 9 Documentation Center.

Note that there are a few problems with the current wording of the second sentence:

1. The words "ONTAP command line" don't need a link, and I would argue that taking the user to a 9.10.1 man topic is odd/unhelpful. Remove the link.
2. The man pages are not on the Support Site, so the statement is factually inaccurate. Additionally, the link is malformed. It appears to be copied from the link in the Doc Center table of contents, which is not the standard described [here](http://docs.netapp.com/ontap-9/topic/com.netapp.ndc.help/GUID-16C1422D-6908-4ED2-A439-0B0C75A2807D.html).

**Comment by netapp-forry** [comment]
Thanks Adam -- we'll fix it ASAP.
