### ISSUE TITLE
Guidance needed for performance impact of the initial scan

### ISSUE THREAD

**Issue by MrObvious** [NetAppDocs/ontap#346]
Page: [Enable File System Analytics](https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html)

What do we recommend for the performance impact?

**Comment by netapp-ahibbard** [comment]
@MrObvious considerations for performance impact for File System Analytics are captured on [this page](https://docs.netapp.com/us-en/ontap/file-system-analytics/considerations-concept.html#peformance-considerations)

**Comment by MrObvious** [comment]
Thank you. Perhaps some guidance on how much jobs to start if customer wants to enable cluster wide? Feel free to ping me on Teams.

-Paul Stejskal

**Comment by netapp-ahibbard** [comment]
Closing this having added the link to the KB you shared Paul. Thanks for creating that.
