### ISSUE TITLE
Add 9.10.1 info

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#349]
Page: [Move a SnapLock volume](https://docs.netapp.com/us-en/ontap/snaplock/move-snaplock-volume-task.html)

Hello; for this page the third bullet is no longer applicable with ONTAP 9.10.1 and later:
"The destination aggregate must be the same SnapLock type as the SnapLock volume you want to move; either Compliance to Compliance or Enterprise to Enterprise."

Can we add a note or something to this effect? Maybe something like:
The SnapLock Unified Aggregates feature in ONTAP 9.10.1 and later removes this requirement.

Thanks!

**Comment by netapp-forry** [comment]
Thanks Joey -- we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks, Joey. I'll get this updated.

**Comment by netapp-lenida** [comment]
Thanks again Joey. I've added a bullet under the "What you'll need" section to call out the change in ONTAP 9.10.1.
