### ISSUE TITLE
DQP Link not working

### ISSUE THREAD

**Issue by jgartrell-missional** [NetAppDocs/ontap#352]
Page: [When you need to update the Disk Qualification Package](https://docs.netapp.com/us-en/ontap/upgrade/concept_when_you_need_to_update_the_disk_qualification_package.html)

I don't think it's on your end, but the link to https://mysupport.netapp.com/NOW/download/tools/diskqual/

takes me here (I was already logged in....)
https://mysupport.netapp.com/site/global/dashboard

Did I overlook something?

**Comment by netapp-forry** [comment]
Thanks for letting us know, John. I think it might just be a stale link in that topic, we'll look into fixing it ASAP.
@netapp-ahibbard - I believe we have the same issue in this topic as well:
https://docs.netapp.com/us-en/ontap/disks-aggregates/update-disk-qualification-package-concept.html

**Comment by netapp-ahibbard** [comment]
Both links have been updated to point to: https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip
