### ISSUE TITLE
Remove Sophos link

### ISSUE THREAD

**Issue by tulledge** [NetAppDocs/ontap#354]
Page: [Antivirus configuration overview](https://docs.netapp.com/us-en/ontap/antivirus/index.html)

Please remove the link to NetApp Technical Report 4309: Antivirus Solution for Clustered Data ONTAP Sophos  

Sophos is no longer supported.

Thanks,
Dan

**Comment by netapp-forry** [comment]
Thanks Dan -- we'll remove this ASAP.
