### ISSUE TITLE
NVMe limits on the Limits docs.

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#357]
Page: [Storage limits](https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html)

Could we get NVMe limits include on this page?

**Comment by netapp-forry** [comment]
Thanks Jeffrey - good idea - we'll look into this right away.

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @jfsinmsp - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by netapp-ahibbard** [comment]
@ntap-bmegan Please keep this open.
