### ISSUE TITLE
Incorrect limits

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap#358]
Page: [SnapMirror Business Continuity overview](https://docs.netapp.com/us-en/ontap/concept_san_smbc_overview.html)

The stated number of supported CGs and vols is incorrect as of 9.10.1.
For correct limits please refer to 
https://docs.netapp.com/us-en/ontap/smbc/smbc_plan_additional_restrictions_and_limitations.html#consistency-groups

It's important this information is kept consistent.

**Comment by netapp-forry** [comment]
Thanks for contacting us -- we'll address this issue ASAP.
