### ISSUE TITLE
missing vserver peer create command steps

### ISSUE THREAD

**Issue by rbaetz** [NetAppDocs/ontap#368]
Page: [Replicate an entire SVM configuration](https://docs.netapp.com/us-en/ontap/data-protection/replicate-entire-svm-config-task.html)

You forgot the need to peer the vservers with 'vserver peer create' command in all these SVM_DR options.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Rob -- we'll look into this right away.

**Comment by netapp-lenida** [comment]
Thanks, Rob. The topics do mention in the "What you'll need" section that cluster and SVM peering is required, bit I have also added a link to the documentation and added the peering step to the procedures.
