### ISSUE TITLE
Network diagram is wrong.

### ISSUE THREAD

**Issue by campbj70** [NetAppDocs/ontap#370]
Page: [Ways to configure iSCSI SAN hosts with single nodes](https://docs.netapp.com/us-en/ontap/san-config/configure-iscsi-san-hosts-single-nodes-reference.html)

In the "Multi-network single-node configurations" diagram, Host 2 is shown as having 2 connection both going to the left switch. The other 2 hosts have a connection to each of the two switches. This configuration is for a fully redundant solution so Host2 should also have a connection to each of the two switches and not only the left switch.
![image](https://user-images.githubusercontent.com/99951397/154639156-d96b8e30-43c5-433e-9d17-9a0bd515473a.png)

**Comment by netapp-chandaj** [comment]
@netapp-forry : Updated graphic attached for review
![scrn-en-drw-iscsi-multinw-singlen](https://user-images.githubusercontent.com/66023260/154932992-5f354c33-a26f-4ba8-a384-e278ae5a62e8.gif)
.

**Comment by campbj70** [comment]
Perfect.


Regards.

Jamie


James Campbell
Technical Consultant
[cid:Also_7a0c802e-71d6-4cb3-9ca6-b017c03ff3c41.png]

ALSO Schweiz AG
Meierhofstrasse 5
CH-6032 Emmen

Phone:  +41 41 266 29 61
***@***.***
www.also.ch


[cid:LinkedIn2_7bc761e2-9391-403a-8b8a-dfa4b2166c8c1.jpg]<https://www.linkedin.com/company/alsogroup/> [cid:Twitter2_7312c582-f712-42b9-9cd9-798680196c301.jpg] <https://twitter.com/alsoschweiz?lang=de>  [cid:FaceBook2_f2b7c9e3-b7ca-4c9d-9633-61da53cc94b41.jpg] <https://www.facebook.com/ALSOSchweiz>

Notice: The information contained in this message is intended only for use of the individual(s) named above and may contain confidential, proprietary or legally privileged information. No confidentiality or privilege is waived or lost by any mistransmission. If you are not the intended recipient of this message you are hereby notified that you must not use, disseminate, copy it in any form or take any action in reliance of it. If you have received this message in error, please delete it and any copies of it and notify the sender immediately.

**Comment by netapp-forry** [comment]
Confirming, looks good Chanda - please go ahead and publish - thanks!

**Comment by netapp-chandaj** [comment]
The updated graphic has been published:
https://docs.netapp.com/us-en/ontap/san-config/configure-iscsi-san-hosts-single-nodes-reference.html#multi-network-single-node-configurations
