### ISSUE TITLE
Add automatic snapshot information to ransomware protection guide

### ISSUE THREAD

**Issue by ntapmattt** [NetAppDocs/ontap#371]
Page: [Anti-ransomware use cases and considerations](https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html)

In the ransomware protection guide we need to explain the timing of how the automatic snapshtos work when there is ransomware detected and when there is not.  I was thinking this could go in the section "Anti-ransomware use cases and considerations."  Here are the details of what we need to cover.

In order to obtain the best possible recovery point, the on box anti-ransomware feature takes a snapshot as soon as the file contents being written look suspicious.  However, the anti-ransomware feature does not immediately flag an alert.  Analytics need to run and confirm that the activity is actually suspected ransomware before generating an alert.  This process could take up to 60 minutes.  If the analytics determines the activity is not suspicious then an alert is not generated, but the automatically created snapshot remains present on the file system for a minimum of two days.

**Comment by netapp-forry** [comment]
Confirmed updated text in published topic -- thanks again for your input!
