### ISSUE TITLE
BURT 1457333 

### ISSUE THREAD

**Issue by netapp-TimMcGue** [NetAppDocs/ontap#373]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

Once BURT 1457333 gets fixed this list could get an update for 9.6 to 9.10.1 updates.

**Comment by netapp-forry** [comment]
Thanks Tim - an update is in the works, I'll keep you posted.
