### ISSUE TITLE
IDR not Supported on FabricPool aggrs with !none tiering policy

### ISSUE THREAD

**Issue by MrObvious** [NetAppDocs/ontap#374]
Page: [Determine how much data in a volume is inactive by using inactive data reporting](https://docs.netapp.com/us-en/ontap/fabricpool/determine-data-inactive-reporting-task.html)

It is not clearly documented that I can tell, but IDR isn't supported on FabricPool enabled volumes (tiering policy != none). See section 2.5 of 9.8 FP TOI for more details.

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks again for bringing this to our attention. The topic has been updated: 

https://docs.netapp.com/us-en/ontap/fabricpool/determine-data-inactive-reporting-task.html
