### ISSUE TITLE
Inconsistent documentation for supported remote URLs

### ISSUE THREAD

**Issue by kevinh-netapp** [NetAppDocs/ontap#379]
Page: [Commands for managing configuration backup schedules](https://docs.netapp.com/us-en/ontap/system-admin/commands-manage-config-backup-schedules-reference.html)

"system configuration backup settings" command documentation lists "HTTP, HTTPS, or FTP" as supported:
https://docs.netapp.com/us-en/ontap/system-admin/commands-manage-config-backup-schedules-reference.html

 

"system configuration backup" command documentation lists "FTP, HTTP, HTTPS, TFTP, or FTPS" as supported:

https://docs.netapp.com/us-en/ontap/system-admin/commands-manage-config-backup-files-reference.html

 

After review, it appears that TFTP and FTPS are indeed supported for both types of commands, so there is an inconsistency that should be addressed.

**Comment by netapp-forry** [comment]
Thanks Kevin -- we'll fix ASAP.

**Comment by kevinh-netapp** [comment]
Thanks! Can we get the man pages updated as well?  Can that be done on the documentation side directly or does it need to be addressed in ONTAP first?

**Comment by netapp-ahibbard** [comment]
@kevinh-netapp Thanks for raising this. The changes have been implemented in the documentation. 
For the manual pages, I've filed BURT 1460189. Please make any notes there.
