### ISSUE TITLE
Clarify SVM where account is created

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#385]
Page: [Create a SnapLock security administrator account](https://docs.netapp.com/us-en/ontap/snaplock/create-snaplock-security-administrator-account-task.html)

Hello!
On this page we say "The snaplock role is associated with the cluster SVM, unlike the vsadmin-snaplock role, which is associated with the data SVM."

We should say "admin SVM" rather than "cluster SVM". So perhaps:
"The snaplock role is associated with the admin SVM, unlike the vsadmin-snaplock role, which is associated with the data SVM."

Also, for the example on this page
"
The following command enables the SVM administrator account SnapLockAdmin with the predefined snaplock role to access SVM2 using a password:

cluster1::> security login create -vserver SVM2 -user-or-group-name SnapLockAdmin -application ssh -authmethod password -role snaplock
"

We use a generic example of a data SVM, but the proper SVM would be "cluster1", the admin SVM. So perhaps:
"
The following command enables the SVM administrator account SnapLockAdmin with the predefined snaplock role to access admin SVM cluster1 using a password:

cluster1::> security login create -vserver cluster1 -user-or-group-name SnapLockAdmin -application ssh -authmethod password -role snaplock
"

Let me know if the changes make sense.
Thanks!

**Comment by netapp-forry** [comment]
Thanks Joey - we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks again for the feedback, Joey. The topic has been updated.
