### ISSUE TITLE
NFS Not supported

### ISSUE THREAD

**Issue by jgartrell-missional** [NetAppDocs/ontap#387]
Page: [Virus scanning](https://docs.netapp.com/us-en/ontap/concepts/virus-scanning-concept.html)

The article states CIFS/SMB is supported.
Can we make it explict that NFS is not supported?  For on-access vscan.

**Comment by netapp-forry** [comment]
Thanks John -- I'll update the topic ASAP.

**Comment by netapp-forry** [comment]
Topic updated and published. Also updated this topic with the same correction:
[About NetApp virus scanning](https://docs.netapp.com/us-en/ontap/antivirus/file-protection-virus-scanning-concept.html)
