### ISSUE TITLE
SnapMirror SVM

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#395]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

Currently working with a customer who is using SnapMirror SVM who is in a jam with a mismatch of versions in ONTAP.  I know we have a warning about version independence with that technology, but that's a bit easy to miss and understand the impact of.  My suggestion is that we have a chart specific to SnapMirror SVM that calls out the specifics and another for SnapMirror SVM involving CVO since it sounds like the rules are different for that combination.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Tim -- we'll look into this and get back to you ASAP.

**Comment by TimMcGue** [comment]
Thanks very much!  While looking at this page, I might also make another suggestion.  The DP style transfers have been deprecated and currently that table is at the top.  I would suggest moving that one to the bottom and keeping the XDP and SVMDR charts towards the top.

**Comment by netapp-forry** [comment]
Thanks Tim, good idea, makes sense.
And while I have you on the line ... what would you say if we:
- Reverse the order of ONTAP releases, starting with most recent top and left?
   I'm thinking that the source and destination releases most customers are interested in are 9.6 and later. Reversing
   the order would make them easier to find.
- Remove 8.* rows and columns
   The highest we support are 8.2->9.0 and 8.3->9.1. Are you aware of any customers using these configurations? 
   Would there be any negative effects in removing those rows and columns?

**Comment by TimMcGue** [comment]
I love the idea of putting the most recent releases at the top of the charts!  That will make things much more user friendly even with the complex data.

So I'd say the challenge is the end of self support for removing those older versions - https://mysupport.netapp.com/site/info/version-support

8.2 has reached end of self support so that can definitely go.  But we've got another month or so for 8.3 so maybe that one needs to stick around a bit (even though to your point that is very rare).

**Comment by netapp-lenida** [comment]
Hi Tim, we've made several improvements to the compatibility matrix, and we will continue to improve it as time allows. I'm going to close this issue, but some additional work will be coming soon. In the meantime, we have reserved the order of the releases and removed some of the releases that are no longer supported. Thanks again for your feedback.

**Comment by TimMcGue** [comment]
Thanks so much!
