### ISSUE TITLE
Please clarify the threshold option

### ISSUE THREAD

**Issue by wardwouts** [NetAppDocs/ontap#396]
Page: [Create a volume efficiency policy to run efficiency operations](https://docs.netapp.com/us-en/ontap/volumes/create-efficiency-policy-task.html)

To me this is not clear:
```
You can run deduplication or data compression operations at a scheduled time, or by creating a schedule with a specific duration, or by specifying a threshold percentage, which waits for the new data to exceed the specified percentage and then triggers the deduplication or data compression operation. This threshold value is the percentage of the total number of blocks used in the volume. You can obtain the total number of blocks used from the df command output.
```
Is the threshold triggering on total data usage (the output of `df`), or on new data usage?

Say I set a threshold for 20% and I start with a volume that is 50% filled. Will the trigger hit at 70%, or will it never hit because the volume is already using more than 20% from the start?

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @wardwouts - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by wardwouts** [comment]
Please improve the documentation before closing the issue automatically.

**Comment by netapp-forry** [comment]
Thanks for your reply -- we will keep this issue open until we have addressed your issue.
My apologies for the delay, we hope to have an answer soon.

**Comment by netapp-forry** [comment]
@ntap-bmegan - Please keep this open.

**Comment by netapp-forry** [comment]
Tracking internally with BURT 1373065.

**Comment by netapp-forry** [comment]
My apologies for the delay. We have updated the topic to address your question. Please let us know if you have further questions about this or any other topic, and thanks again for contacting us.

**Comment by wardwouts** [comment]
Much better. Thanks
