### ISSUE TITLE
Incorrect command

### ISSUE THREAD

**Issue by wnichola-ntap** [NetAppDocs/ontap#399]
Page: [Enable or disable oplocks on existing SMB shares](https://docs.netapp.com/us-en/ontap/smb-admin/enable-disable-oplocks-existing-shares-task.html)

The page has "vserver share properties", but the command is "vserver cifs share properties".

Ref:
nas-cm99::> version
NetApp Release 9.9.1P7: Sat Jan 29 01:25:00 UTC 2022

nas-cm99::> vserver share?

Error: "share" is not a recognized command

nas-cm99::> vserver cifs share?
  share>                      Manage CIFS shares

Man page reference:
https://docs.netapp.com/us-en/ontap/smb-admin/commands-manage-shares-reference.html

**Comment by netapp-forry** [comment]
Thanks very much for letting us know -- we'll fix this ASAP.

**Comment by netapp-ahibbard** [comment]
This has been corrected on [Enable or disable oplocks on existing SMB shares](https://docs.netapp.com/us-en/ontap/smb-admin/enable-disable-oplocks-existing-shares-task.html). Thank you!
