### ISSUE TITLE
Remove "s" in "to avoids"

### ISSUE THREAD

**Issue by netapp-rlithman** [NetAppDocs/ontap#402]
Page: [Prepare to use the ONTAP Mediator](https://docs.netapp.com/us-en/ontap/smbc/smbc_plan_preparing_to_use_the_ontap_mediator.html)

It coordinates automated failover when a failure is detected and helps to _avoids_ split-brain scenarios when each cluster simultaneously tries to establish control as the primary cluster.

Thanks! 
Rachel

**Comment by netapp-ahibbard** [comment]
Thanks Rachel! This has been fixed
