### ISSUE TITLE
Need to specify a difference between TSSE volumes & non-TSSE volumes

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/ontap#404]
Page: [Run efficiency operations manually on existing data](https://docs.netapp.com/us-en/ontap/volumes/run-efficiency-operations-manual-existing-data-task.html)

This statement should only be true for non-TSSE volumes (thin-provisioned volumes prior to ONTAP 9.8):
When you run data compression on existing data, by default the data compression operation skips the data blocks that are shared by deduplication and the data blocks that are locked by Snapshot copies. If you choose to run data compression on shared blocks, then optimization is turned off and the fingerprint information is captured and used for sharing again. You can change the default behavior of data compression when compressing existing data.

WIth TSSE volumes in ONTAP 9.8, the background scanner will compress data blocks that are shared by the active file system & snapshot copies.

We should be referencing what happens with TSSE volumes & non-TSSE volumes.

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks again. The topic has been updated.
