### ISSUE TITLE
Native Storage? ONTAP Edge -> ONTAP Select?

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap#405]
Page: [Storage limits](https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html)

Hi All,

Please define "Native Storage" and what the difference is to "Storage Array".
I'm just guessing here: FlexArray, maybe? But what possible impact would that have on WAFL limits...???
All sorts of "model-dependent" info, except for root-vol size... I've got no idea what it could be.
It's literally **defined nowhere in the documentation**.

Also: Since 9.0 "ONTAP Edge" is called **"ONTAP Select"**. Please use "Edge" only when referring to pre-9.0.

While you're at it, you might want to add information regarding **FlexGroup** volumes.

Sebastian
NAI (NetApp Authorized Instructor)

**Comment by netapp-forry** [comment]
Thanks for letting us know, Sebastian -- we'll look into this ASAP.
