### ISSUE TITLE
Use dedicated ports where possible.

### ISSUE THREAD

**Issue by lowest21** [NetAppDocs/ontap#407]
Page: [Considerations for iSCSI configurations overview](https://docs.netapp.com/us-en/ontap/san-config/iscsi-config-concept.html)

I feel we should direct people to use dedicated iSCSI ports where possible and allow MPIO at the client end to deal with any path failures. I don't believe interface groups are a good fit with iSCSI and they should only be used when unavoidable, I.E. when there are no available ports to dedicate to iSCSI.

**Comment by lowest21** [comment]
Obviously vLANs and LIFs would need to be created on top of the dedicated ports.

**Comment by netapp-forry** [comment]
Thanks for calling our attention to this -- we'll investigate ASAP.

**Comment by netapp-barbe** [comment]
Thanks - Looking into it!

**Comment by netapp-forry** [comment]
Greetings,
After some internal consultation, we are not clear about what problem would be addressed by your proposed solution to recommend dedicated iSCSI ports. 
Would you be willing to discuss the matter further with NetApp staff? If so, please contact me directly via email: Mark Forry – 
forry@netapp.com
Thanks much.

**Comment by netapp-forry** [comment]
Hi again -- I'll close this issue, but if you'd like to discuss this matter with NetApp staff, please let me know and I'll reopen. 
Thanks much – Mark Forry – forry@netapp.com
