### ISSUE TITLE
Not able to view shares even from Administrator user 

### ISSUE THREAD

**Issue by harinaresh** [NetAppDocs/ontap#408]
Page: [View information about SMB shares using the MMC](https://docs.netapp.com/us-en/ontap/smb-admin/view-shares-mmc-task.html)

Even from Administrator user, i am not ale to view the SMB shares of the SVM. I am getting below error.
![image](https://user-images.githubusercontent.com/97676609/158376695-659ab4f0-d546-4c98-a330-9949cf89fac8.png)

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll investigate ASAP.

**Comment by netapp-forry** [comment]
Hello Harinaresh - In the topic you cited, there is a link to an FAQ. The FAQ includes a link to this KB:
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Connecting_CIFS_shares_via_MMC_results_in_error_'You_do_not_have_permissions_to_see_list_of_shares_for_Windows_client'
Are you able to access this KB? Did it help?

**Comment by harinaresh** [comment]
I am able to access the KB link Connecting CIFS shares via MMC results in error 'You do not have permissions to see list of shares for Windows client' - NetApp Knowledge Base<https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Connecting_CIFS_shares_via_MMC_results_in_error_'You_do_not_have_permissions_to_see_list_of_shares_for_Windows_client'>.
But it does not help because I am using this MMC to view the shares provided Azure NetApp files (Azure cloud). And I do not have access to the ONTAP present in Azure cloud. All I can do is to make the domain user part of  Domain Admin group  on AD (as mentioned in the above link). But that is not helping.

The other workaround mentioned in above link is to  add local BUILTIN\Administrators group to the user but that is not possible as I do not have access to ONTAP (present in azure cloud) as mentioned above.


Thanks,
Hari

**Comment by netapp-forry** [comment]
Thanks for that clarification. I am not familiar with Azure NetApp Files, so I would suggest you consult the ANF documentation to see if you can find a solution:
   https://docs.microsoft.com/en-us/azure/azure-netapp-files/
I see that there is an ANF FAQ with caveats about ANF:
   https://docs.microsoft.com/en-us/azure/azure-netapp-files/faq-smb#can-i-manage-smb-shares-sessions-and-open-files-through-microsoft-management-console-mmc

If in these documents you're not able to find a solution, I would recommend that you contact NetApp Support.

**Comment by netapp-forry** [comment]
Hello Hari -- I hope you were able to find a solution in the Azure NetApp Files documentation or with NetApp Support. Thanks again for contacting us.
