### ISSUE TITLE
need to add - ABE does not hide the share, it only hides the folders/files created under it, based on the access permissions.

### ISSUE THREAD

**Issue by allardrc** [NetAppDocs/ontap#411]
Page: [Provide folder security on shares with access-based enumeration overview](https://docs.netapp.com/us-en/ontap/smb-admin/provide-security-access-based-enumeration-task.html)

The document does not specify that ABE does not hide the share, it only hides the folders/files created under it, based on the access permissions.

**Comment by netapp-forry** [comment]
Thanks Bob -- we'll look into this ASAP.

**Comment by netapp-forry** [comment]
Added the following text to the topic:
"That is, the share itself would be visible to all users, but files and folders within the share could be displayed to or hidden from designated users."
Thanks again for calling this to our attention.
