### ISSUE TITLE
Need to add text to the page

### ISSUE THREAD

**Issue by allardrc** [NetAppDocs/ontap#412]
Page: [Provide folder security on shares with access-based enumeration overview](https://docs.netapp.com/us-en/ontap/smb-admin/provide-security-access-based-enumeration-task.html)

Need to add 
ABE does not hide the share, it only hides the folders/files created under it, based on the access permissions.

**Comment by netapp-forry** [comment]
Dup of [#411](https://github.com/NetAppDocs/ontap/issues/411)
