### ISSUE TITLE
Removing the security and compliance bundle language from on-box anti-ransomware.

### ISSUE THREAD

**Issue by ntapmattt** [NetAppDocs/ontap#419]
Page: [Enable anti-ransomware](https://docs.netapp.com/us-en/ontap/anti-ransomware/enable-task.html)

We need to remove all reference to the security and compliance bundle from this doc: https://docs.netapp.com/us-en/ontap/pdfs/sidebar/Ransomware_protection.pdf

It currently exists on page 4 and 6.  The text we are replacing is:

What you’ll need
• The Multi-tenant Encryption Key Management (MT_EK_MGMT) license installed from the security and
compliance bundle.

We are replacing it with this text:

What you’ll need
The Multi-tenant Encryption Key Management (MT_EK_MGMT) license installed for ONTAP 9.10.1.

**Comment by netapp-forry** [comment]
Thanks Matt - I'll address this ASAP.

**Comment by ntapmattt** [comment]
Thanks Mark.

I learned this doc needs another update with respect to mentioning that FlexCache is not supported.  In fact, FlexCache volumes are supported on the origin but not the cache.

FlexCache volumes mirror what’s on the origin and the origin volume already support On Box anti-ransomware, so I’ll request the doc be updated to specify this.

So, the way it reads now is incorrect.  Are you able to make this update at the same time or do you need another GitHub ticket on it?

Thanks,

-Matt

From: Mark Forry ***@***.***>
Reply-To: NetAppDocs/ontap ***@***.***>
Date: Tuesday, March 22, 2022 at 4:46 AM
To: NetAppDocs/ontap ***@***.***>
Cc: "Trudewind, Matt" ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/ontap] Removing the security and compliance bundle language from on-box anti-ransomware. (Issue #419)

NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Thanks Matt - I'll address this ASAP.

**Comment by netapp-forry** [comment]
Confirmed publication of the following topics:
- licensing correction
  https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html
  https://docs.netapp.com/us-en/ontap/anti-ransomware/enable-task.html
  https://docs.netapp.com/us-en/ontap/anti-ransomware/enable-default-task.html
- FlexCache support caveat
  https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html
  https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html
