### ISSUE TITLE
We don't support snapshot restore on a pre-conversion snapshot 

### ISSUE THREAD

**Issue by jsknair** [NetAppDocs/ontap#422]
Page: [Supported and unsupported configurations for FlexGroup volumes](https://docs.netapp.com/us-en/ontap/flexgroup/supported-unsupported-config-concept.html)

The following statement under "Features supported beginning with ONTAP 9.8" is incorrect and must be removed. 

Restoring "pre-conversion" Snapshot copies to a FlexGroup volume

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention. I'll look into this as soon as possible.

**Comment by netapp-lenida** [comment]
The topic has been updated. Thanks again.
