### ISSUE TITLE
link broken. get 404 file not found

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap#426]
Page: [Root-data partitioning](https://docs.netapp.com/us-en/ontap/task_dp_root_data_partitioning.html)

the link doesnt work [Disk and aggregates management](https://docs.netapp.com/us-en/disks-aggregates/index.html).

- get 404 error 

404

File not found

The site configured at this address does not contain the requested file.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Logan.
Reviewing the topic, it seems pretty lightweight; we're considering moving the useful sentence elsewhere and removing the topic.
Could you please tell us how you found this topic? Thanks again.

**Comment by netapp-ahibbard** [comment]
Thanks for reporting this. This has been updated to redirect to more relevant content
