### ISSUE TITLE
Command syntax error 

### ISSUE THREAD

**Issue by ankkitraj4** [NetAppDocs/ontap#427]
Page: [Enable Telnet or RSH access to the cluster](https://docs.netapp.com/us-en/ontap/system-admin/enable-telnet-rsh-access-cluster-task.html)

The command 
Cluster::>system services firewall policy clone -policy mgmt -new-policy-name policy-name
Should have a -destination-policy instead of -new-policy-name 

The correct syntax can be found on ontap docs below.
https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-cmpr-930%2Fsystem__services__firewall__policy__clone.html

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll fix this ASAP.

**Comment by netapp-ahibbard** [comment]
Thanks. The fix has just been published.
