### ISSUE TITLE
Need to change example to correct method (broadcast-domain modify)

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#432]
Page: [Check the MTU network setting on the storage system](https://docs.netapp.com/us-en/ontap/performance-admin/check-network-settings-task.html)

As the page states, any port in a broadcast domain needs to be use "broadcast-domain modify" to change MTU. 
But, the example still uses "network port modify" (the ONTAP 8.3 way).
Please change the example to use the right modify command. i.e.
network port broadcast-domain modify -ipspace <IPspace> -broadcast-domain <broadcast-domain> -mtu <desired_value>

**Comment by netapp-forry** [comment]
Thanks Andris - we'll fix this ASAP.

**Comment by netapp-barbe** [comment]
Will do, thanks all

**Comment by netapp-barbe** [comment]
Done, thank you for the feedback
https://docs.netapp.com/us-en/ontap/performance-admin/check-network-settings-task.html
