### ISSUE TITLE
This section seems incomplete?

### ISSUE THREAD

**Issue by MrObvious** [NetAppDocs/ontap#433]
Page: [Event and performance monitoring](https://docs.netapp.com/us-en/ontap/event-performance-monitoring/index.html)

All,

We have been working on quite a few KBs about performance over the last 2 years (with KCS), and was wondering if there were more plans to build this out? Perhaps the documentation and KBs can be tied together?

**Comment by netapp-forry** [comment]
Thanks for this input. We're working on a related issue internally, please contact me directly for details.
Thanks -- Mark Forry
forry@netapp.com

**Comment by netapp-forry** [comment]
Tracking this issue internally with BURT 1453025.
