### ISSUE TITLE
Improper page title/procedure

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/ontap#435]
Page: [Delete one or more existing Snapshot copies from a volume](https://docs.netapp.com/us-en/ontap/san-admin/delete-all-existing-snapshot-copies-volume-task.html)

The page title and description says "Delete _one or more_ existing Snapshot copies from a volume"

The page URL says "_delete all_"

The actual process on the page only describes deleting all the snapshots. 

Either the title of the page or the procedures should be brought into line with each other. Preferably update the content to show how to delete individual/some snapshots as well as deleting all. 

Thanks,
Judson

**Comment by netapp-forry** [comment]
Thanks Judson - we'll fix this ASAP.

**Comment by netapp-forry** [comment]
Hi Judson - I've added content to the page you cited, with instructions for deleting single, multiple, or all Snapshot copies. Good suggestion, I agree that this is clearer.
Changing the URL is a bit more complicated, but I'll look into it. Meanwhile, I'll close this issue, with our thanks to you.
