### ISSUE TITLE
Recovery procedure

### ISSUE THREAD

**Issue by toshiki-mukaeda** [NetAppDocs/ontap#436]
Page: [Respond to abnormal activity.](https://docs.netapp.com/us-en/ontap/anti-ransomware/respond-abnormal-task.html)
Potential Ransomware Attack
Respond to the attack and restore protected data. Then click Update and Clear Suspect File Types to record your decision and resume normal anti-ransomware monitoring.

This will mis-lead the recovery procedure.  According to this document, administrator will restore data first, but after restore from snapshot, there is no indicate the potential attack.  The admin should click the "Update and Clear Suspect File Types" first, then recover from snapshot.

**Comment by netapp-forry** [comment]
Thank you Toshiki-san -- I'll look into this ASAP.

**Comment by netapp-forry** [comment]
Hello Toshiki-san,
We have updated the recovery procedure topic that you mentioned, noting that the step to clear suspect file types is not necessary if a volume snap restore is being performed.
Also, please note that as of ONTAP 9.11.1, there are new commands available for managing ARW Snapshot copies:
   https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-shapshot-options-task.html
Thanks again for contacting us.
