### ISSUE TITLE
Document update for CVO- NVE with Azure key vault

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#437]
Page: [Manage keys with Azure Key Vault or Google Cloud KMS](https://docs.netapp.com/us-en/ontap/encryption-at-rest/manage-keys-azure-google-task.html)

(Adding details from an internal email)

While working with Engineering, we found that this is not a bug, but just a missing configuration steps, I am adding the steps we took to get this configured successfully in CVO, will you be able to incorporate this to our documentations please?

Once the external azure key-manager is enabled using the command below, we were getting errors:
security key-manager external azure enable -vserver svm_deepcvo -client-id ea7140ef-92e7-4e3b-b370-192d1301eb19  -tenant-id 890df2fb-c027-40fc-88ad-7dc5308deacc -name https://akvdeep.vault.azure.net/ -key-id https://akvdeep.vault.azure.net/keys/key1/
So we had to do two checks and configurations: Check Route, DNS and Azure key vault permissions for the App registration

1.	Setup DNS for the Data Vserver, I think by default there is no DNS added for Data vServer:

deepcvo::*> dns create -domains nd0kqg11cufetbgowtyquwd5id.jx.internal.cloudapp.net -name-servers 168.63.129.16 -vserver svm_deepcvo
Warning: Only one DNS server is configured. Configure more than one DNS server to avoid a single-point-of-failure.

2.	Access policies for the App registration:
 
![image](https://user-images.githubusercontent.com/18287750/161087102-550c4d26-8940-4fd3-aee8-b0a76421f719.png)

Give the full Key permissions, Secret permissions, and certificate permissions to the application  from AKV access policies ( Do not forget to save the access policies, once its applied)

Result:
deepcvo::*> vol create nve_test -encrypt true -aggregate aggr1
[Job 27] Job succeeded: Successful
deepcvo::*> security key-manager external azure check
Vserver: svm_deepcvo
Node: deepcvo-01
Category: service_reachability
              Status: OK
Category: ekmip_server
              Status: OK
Category: kms_wrapped_key_status
              Status: OK
3 entries were displayed.

**Comment by netapp-forry** [comment]
Thanks Ben -- we'll look into this ASAP.
