### ISSUE TITLE
The article is missing the issue expected after the Link and the mediator are down

### ISSUE THREAD

**Issue by kadaNtap** [NetAppDocs/ontap#439]
Page: [Link between Site B and Mediator down and Site A down](https://docs.netapp.com/us-en/ontap/smbc/smbc_troubleshoot_link_between_site_b_and_mediator_down.html)

The solution describes how to resume I/O but there is no indication in the article that an I/O disruption will occur in that scenario.

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll look into this ASAP.

**Comment by kadaNtap** [comment]
Sorry, I meant the following article https://docs.netapp.com/us-en/ontap/smbc/smbc_troubleshoot_link_between_site_a_and_mediator_down.html but my request still applies to this one as well.
I will create a new request
