### ISSUE TITLE
Stray apostrope

### ISSUE THREAD

**Issue by clintsanderson** [NetAppDocs/ontap#444]
Page: [Replace SSL certificates](https://docs.netapp.com/us-en/ontap/encryption-at-rest/replace-ssl-certificates-task.html)

Looks like there is a stray apostrophe at the end of this command:
Install the new KMIP server-ca certificate:
security certificate install -type server-ca -vserver <>`

**Comment by netapp-forry** [comment]
Thanks Clint -- we'll fix this ASAP.

**Comment by netapp-ahibbard** [comment]
Thanks @clintsanderson . I've just merged the fix
