### ISSUE TITLE
Incorrect wording for FlexCache/Snapmirror support

### ISSUE THREAD

**Issue by ntap-christoh** [NetAppDocs/ontap#445]
https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

In the "SnapMirror Asynchronous relationships" part of the table, there are 3 bullets that contradict each other.  The most important piece is that FlexCache volumes can be created against SnapMirror primary volumes, and starting in ONTAP 9.8, against SnapMirror secondary volumes.    The bullet mentioning that FlexCache volumes can't be a primary or secondary volume is sort-of redundant, but if we are to keep it, it definitely shouldn't be the first bullet.

**Comment by netapp-forry** [comment]
Thanks Chris -- we'll fix this ASAP.

**Comment by elliott-ecton** [comment]
This is still incorrect. Is there an ETA on getting this fixed? 9.11.1 has gone RC already

**Comment by netapp-lenida** [comment]
Hi Chris, sorry for getting back to you on this so late. I am working on an update now.

**Comment by netapp-lenida** [comment]
This issue should now be fixed. Thanks again for bringing it to our attention.
