### ISSUE TITLE
Missing cli session privilege instructions

### ISSUE THREAD

**Issue by kevinh-netapp** [NetAppDocs/ontap#449]
Page: [Restore the node configuration using a configuration backup file](https://docs.netapp.com/us-en/ontap/system-admin/restore-node-config-backup-file-task.html)

This page is missing instructions for changing the session privilege (The asterisk in the examples show that either adv or diag privileges are enabled).  Based on the commands it looks like the advanced privilege level is needed.  The cluster level recovery instructions appear to include these instructions but I am not seeing them for this node level section. Example:

https://docs.netapp.com/us-en/ontap/system-admin/restore-cluster-config-from-existing-task.html

Thanks!

**Comment by netapp-ahibbard** [comment]
@kevinh-netapp Thanks for catching this. You're correct, this command requires the advanced privilege. We will correct
