### ISSUE TITLE
Add point "set -expiry-time not supported"

### ISSUE THREAD

**Issue by ReneMeier** [NetAppDocs/ontap#453]
Page: [Considerations for creating a SnapVault backup relationship and a unified data protection relationship for FlexGroup volumes](https://docs.netapp.com/us-en/ontap/flexgroup/snapvault-backup-concept.html)

Please add the point that the option expiry-time for a snapshot is also not supported on a flexgroup volume

snapshot modify -vserver svm1 -volume svm1_nas_001 -snapshot daily_1900.2022-04-06_1900 -expiry-time "05/15/2022 13:00:00"
 Error: command failed: The "-expiry-time" parameter is not supported for FlexGroup volumes..

**Comment by netapp-forry** [comment]
Thanks for letting us know, Rene -- we'll address this ASAP.

**Comment by netapp-lenida** [comment]
Thanks again for bringing this to our attention, Rene. The topic has been updated.
