### ISSUE TITLE
CG does not really support any FlexVol relationship as shown in the diagram

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/ontap#456]
Page: [Consistency groups overview](https://docs.netapp.com/us-en/ontap/consistency-groups/index.html)

If the diagram being shown (pasted below) is depicting remote protection of the CG, you cannot setup a remote relationship for any FlexVol volume.  I can create a consistency group for a NAS volume which would be a local protection on the primary/source system, but when you attempt to setup the remote relationship, an error message is displayed in System Manager that a SM-BC relationship cannot be created because the volumes in the CG are NAS volumes and SM-BC only works with SAN volumes.

There should be better clarity in the documentation on the use of a CG for NAS volumes to be for local snapshots only with no remote replication capable.

![](https://docs.netapp.com/us-en/ontap/media/consistency-group-single-diagram.gif)

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll look into this ASAP.

**Comment by netapp-ahibbard** [comment]
The documentation -- in particular the Protection section which delineates between remote and local protection -- has been updated to clarify this. Thanks for your comment!
