### ISSUE TITLE
migrate from 8.3 docs how to shutdown a single node in a 2 node cluster

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap#457]
Page: [Shut down a node](https://docs.netapp.com/us-en/ontap/system-admin/shut-down-node-task.html)

**old 8.3 ref:** https://library.netapp.com/ecmdocs/ECMP12465455/html/GUID-DFAB972D-1F50-412B-A1DB-C7FC5A80163D.html

- not sure why this is not in the new ontap 9 docs. i realize its not a common task but it is very impactful if not done properly. 
- there are plans (https://jira.ngage.netapp.com/browse/KDA-591) to move how to shutdown procedures from kb to IE. in the meantime we should first move the 2 node config procedure first or link to the kb.

**kb**  we have a kb as well : https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_halt_a_single_node_without_takeover_in_a_two-node__ONTAP_cluster

thank you

**Comment by netapp-lenida** [comment]
Hi Logan, 

I believe the information you're looking for is here: 

https://docs.netapp.com/us-en/ontap/high-availability/ha_manual_takeover.html#moving-epsilon-for-certain-manually-initiated-takeovers

**Comment by loganbaez** [comment]
Hello Lenida,

Those are steps for a takeover. My question relates to halting 1 node out of a 2 node only cluster.

Thanks for checking

-logan

**Comment by netapp-ahibbard** [comment]
This topic has been moved into the ONTAP 9 documentation: https://docs.netapp.com/us-en/ontap/high-availability/halt-reboot-node-wo-takeover-task.html

**Comment by netapp-ehoffman** [comment]
Relates to https://jira.ngage.netapp.com/browse/KDA-591
