### ISSUE TITLE
Please add a caution "for user or group type rules at the volume level, qtree parameter should contain "".".

### ISSUE THREAD

**Issue by yumiyaz** [NetAppDocs/ontap#459]
Page: [How default quotas work](https://docs.netapp.com/us-en/ontap/volumes/default-quotas-concept.html)

The customer requests to add "Please add a caution for user or group type rules at the volume level, -qtree parameter should contain "". " to this doc because he couldn't understand it from this doc.
This caution is quoted from the following command reference.

volume quota policy rule create
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-970/volume__quota__policy__rule__create.html

-qtree<qtree name> - Qtree Name
 This parameter specifies the name of the qtree to which the quota rule applies. This parameter is not applicable for tree type rules.
 For user or group type rules at the volume level, this parameter should contain "".

**Comment by netapp-forry** [comment]
Thanks very much for letting us know -- we'll add a caveat after the following bullet item ASAP.

- When you create a quota using the volume quota policy rule create command, setting the -target parameter to an empty string ("") creates a default quota.

**Comment by netapp-ahibbard** [comment]
Thanks for raising this issue. The document has been amended with this clarification
