### ISSUE TITLE
Enhance with commands on how to use volume recovery queue

### ISSUE THREAD

**Issue by clintsanderson** [NetAppDocs/ontap#460]
Page: [Protection against accidental volume deletion](https://docs.netapp.com/us-en/ontap/volumes/protection-accidental-volume-deletion-concept.html)

This KB has some suggestions:
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue

**Comment by netapp-forry** [comment]
Thanks for letting us know, Clint -- we'll look into this ASAP.

**Comment by netapp-forry** [comment]
Hi Clint,
Apologies for the slow response here.
I see that the text of the doc topic and the KB are identical except for the two bullets. Just to confirm: would you like me to copy the two bullets into the doc topic? I can also add a pointer to the topic that discusses the System Manager capability.
Please let me know what you think -- when I hear back from you, I'll make the updates and let you review.
Thanks -- Mark

**Comment by netapp-forry** [comment]
Added KB link to topic, verified publication. Thanks again for letting us know!
