### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#461]
Page: [Update a load-sharing mirror relationship](https://docs.netapp.com/us-en/ontap/data-protection/update-load-sharing-mirror-set-task.html)

The following BURT changed the behavior of ONTAP where this update is done automatically during volume creation or mounts:
https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/635790

**Comment by netapp-forry** [comment]
Thanks Tim -- we'll address this ASAP.
