### ISSUE TITLE
Clarify that disabling SMB2 disables both SMB 3.0 and SMB 3.1

### ISSUE THREAD

**Issue by wnichola-ntap** [NetAppDocs/ontap#464]
Page: [Available SMB server options](https://docs.netapp.com/us-en/ontap/smb-admin/server-options-reference.html)

To ensure there is no room for interpretation, could this be adjusted to say 3.X instead of 3.0?

Enabling or disabling SMB 2.x
SMB 2.0 is the minimum SMB version that supports LIF failover. If you disable SMB 2.x, ONTAP also automatically disables SMB 3.0.
SMB 2.0 is supported only on SVMs. The option is enabled by default on SVMs

We can see that it definitely disables both 3.0 and 3.1 along with 2.0:
`nas-cm910::*> version
NetApp Release 9.10.1: Sat Jan 15 15:04:44 UTC 2022

nas-cm910::*> cifs options modify -vserver toddhoward -smb2-enabled false
Warning: Disabling the SMB 2.0 protocol will disconnect all SMB 2.0, SMB 3.0 and SMB 3.1 clients.
Do you want to continue? {y|n}: y

Warning: When SMB 2.0 was disabled for Vserver "toddhoward", the fake open feature was also disabled.  If you re-enable SMB 2.0 and want to enable fake open, specify "-is-fake-open-enabled true" with "-smb2-enabled true".
         When SMB 2.0 was disabled for Vserver "toddhoward", the Large MTU feature was also disabled.  If you re-enable SMB 2.0 and want to enable Large MTU, specify "-is-large-mtu-enabled true" with "-smb2-enabled true".

         When SMB 3.0 was disabled for Vserver "toddhoward", the SMB 3.1 and copy offload and multichannel features were also disabled. If you re-enable SMB 3.0 and want to enable these features, specify "-smb31-enabled true -copy-offload-enabled true -is-multichannel-enabled true" with
         "-smb3-enabled true".

nas-cm910::*> cifs options show -vserver toddhoward -fields smb2-enabled,smb3-enabled,smb31-enabled
vserver    smb2-enabled smb3-enabled smb31-enabled
---------- ------------ ------------ -------------
toddhoward false        false        false`

**Comment by netapp-forry** [comment]
Thanks for letting us know, Nichola - we'll fix this ASAP.
