### ISSUE TITLE
The doc contridicts itself

### ISSUE THREAD

**Issue by richnetapp** [NetAppDocs/ontap#465]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

multi-stage
If a direct or direct multi-hop path is not available for your non-adjacent target release, you must first upgrade to a supported intermediate release, and then upgrade to the target release. **For example, if you are currently running 9.7 and you want to upgrade to 9.10.1, you must complete a multi-stage upgrade: first from 9.7 to 9.9.1, and then from 9.9.1 to 9.10.1.**

But the table shows you can perform either a multi-stage upgrade or a direct multi-hop.   Which is correct?
<html><body>

9.7 | 9.10.1 | direct multi-hop (ANDU only, requires images for 9.8 & 9.10.1P2 or later P release) otherwise multi-stage (via 9.9.1)
-- | -- | --

</body>
</html>

**Comment by netapp-forry** [comment]
Thanks for letting us know, Rich. I believe the table is correct, but I'll verify and get back to you.

**Comment by richnetapp** [comment]
Hey Mark,

Great – thanks..  I just happened to look at it today when A SAM asked me a question about a specific 9.7 to 910.1 upgrade…

Rich

Rich Haynes
Technical Program Manager
SAM Center of Excellence (SCOE)
NCDA, NCIE-SAN

NetApp
315-699-0068 Direct Phone
315-436-2024 Mobile Phone
***@***.******@***.***>

***@***.***



[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>    [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>     [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>     [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>

**Comment by netapp-forry** [comment]
Review draft approved and scheduled for publication next week.
