### ISSUE TITLE
The NetApp NVMe documentation has an error.

### ISSUE THREAD

**Issue by jdaecher** [NetAppDocs/ontap#466]
Page: [NVMe namespaces considerations](https://docs.netapp.com/us-en/ontap/san-admin/nvme-namespaces-considerations-concept.html)

The NetApp NVMe documentation has an error.
The document named: Set up namespaces for NVMe
Available on this link https://docs.netapp.com/us-en/ontap/pdfs/sidebar/Set_up_namespaces_for_NVMe.pdf
On page 3 (or Content Page 1) it states:
Resizing: You cannot increase or decrease the size of a namespace.
 
But according to the NetApp ONTAP release notes, this is now supported starting with ONTAP 9.10.1
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
Page 39
NVMe namespace
You can use the ONTAP CLI to increase or decrease the size of a
namespace. You and use System Manager to increase the size of a
namespace. links: not yet available
Resizing a namespace
ONTAP 9.10.1

**Comment by netapp-forry** [comment]
Thanks for letting us know, Jens -- we'll look into this ASAP.

**Comment by netapp-ahibbard** [comment]
Thanks for catching this! The doc has been updated
