### ISSUE TITLE
Master License Key Link Incorrect

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/ontap#469]
Page: [Prerequisites](https://docs.netapp.com/us-en/ontap/smbc/smbc_plan_prerequisites.html)

The link referenced for the Master License Keys (https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/) is not correct and lands you on the main dashboard at the NetApp Support Site.

This is the correct link to go directly to the Master License Key section: https://mysupport.netapp.com/site/systems/master-license-keys

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll fix this ASAP.

**Comment by netapp-ahibbard** [comment]
Thanks for catching this! The link has been updated to point to the correct destination
