### ISSUE TITLE
Link customer bulletin page to this document

### ISSUE THREAD

**Issue by emile-bodin** [NetAppDocs/ontap#472]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

We need information on this page on the latest available ONTAP release, like in https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2

That can be either via a link or include the relevant information in this document.

**Comment by netapp-forry** [comment]
Thanks Emile - good idea - I'll incorporate this info into the topic ASAP.
