### ISSUE TITLE
Include commands to download software to the controller

### ISSUE THREAD

**Issue by jarrah31** [NetAppDocs/ontap#476]
Page: [Manual disruptive upgrade using the CLI](https://docs.netapp.com/us-en/ontap/upgrade/task_updating_an_ontap_cluster_disruptively.html)

If I use `cluster image package get`, the imported software version doesn't show up in `system image show`. You have to use `system node image update * -package` instead.

Please could you include the `system node image update` command in the guide to help those following this process?

**Comment by netapp-ahibbard** [comment]
Thanks for letting us know -- we'll look into this ASAP.

**Comment by netapp-forry** [comment]
Hello Jarrah,
I apologize for the delay in responding.
The command you mentioned -- system node image update * -package -- is in fact documented in the following topic:
Download and install the ONTAP software image
https://docs.netapp.com/us-en/ontap/upgrade/task_download_and_install_ontap_software_image.html#for-manual-upgrades

In the manual upgrade topic you cited, the doc states that "You must have satisfied preparation requirements." This is accurate, but apparently it wasn't helpful to you. I plan to update the manual update topic to refer to the topic about downloading and installing the ONTAP software image.

Would this have helped in your case? Please let me know if this resolves your issue.

Thanks again for contacting us -- Regards -- Mark Forry

**Comment by netapp-forry** [comment]
Republished topic with link to information about using the system node image update command. Please let us know if you have further comments -- thanks again for contacting us.

**Comment by jarrah31** [comment]
Hi Mark,
Thank you very much for your help, adding the link to the manual download instructions is a great solution and very much helps clarify which commands should be used to download the software in advance of following the guide.
