### ISSUE TITLE
FabricPool support for SnapLock Enterprise is a PVR-Key supported feature. 

### ISSUE THREAD

**Issue by jsknair** [NetAppDocs/ontap#478]
Page: [What SnapLock is](https://docs.netapp.com/us-en/ontap/snaplock/snaplock-concept.html)

This document implies the SnapLock Enterprise support for FabricPool is on by default.
This is a PVR-key supported feature and needs an FPVR and not enabled without it.

**Comment by netapp-lenida** [comment]
Thanks again for letting us know about this issue. The topic has been updated.
