### ISSUE TITLE
The advanced mode isn't allowed to "unpartition" command.

### ISSUE THREAD

**Issue by yumiyaz** [NetAppDocs/ontap#481]
Page: [Sanitize a disk](https://docs.netapp.com/us-en/ontap/disks-aggregates/sanitize-disk-maintenance-mode-task.html)

I tested "sanitize" command for this document.
However, the following message appeared.

aff200-dal-1a*> disk unpartition 1.0.10
disk unpartition: command is allowed only in diag mode.

Could you check the privilege of the command?

**Comment by netapp-ahibbard** [comment]
@yumiyaz Thanks for identifying this issue. disk partition commands are only available at the diag level and should be performed only under NetApp Support supervision. It is highly recommended that you contact NetApp Support before you proceed.
We will update the doc accordingly.
