### ISSUE TITLE
Document FsxN Support

### ISSUE THREAD

**Issue by mimitche** [NetAppDocs/ontap#492]
Page: [Supported and unsupported features for FlexCache volumes](https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html)

On this page CVO (Cloud Volumes ONTAP) is specifically called out as supported.  Can the official support status of FlexCache on FsxN be added as well?

(FlexCache does work on FsxN as long as it is setup via CLI or API.)

**Comment by netapp-forry** [comment]
Thanks for contacting us -- we'll look into this ASAP.

**Comment by netapp-forry** [comment]
Please contact Amazon using the Feedback function of the doc site to request updates to FSx documentation. 
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html
