### ISSUE TITLE
404 on the link {https://docs.netapp.com/us-en/ontap/encryption-at-rest/encryption-at-rest/return-seds-unprotected-mode-task.html}

### ISSUE THREAD

**Issue by calvinwonghk** [NetAppDocs/ontap#500]
Page: [Replace a FIPS drive or SED](https://docs.netapp.com/us-en/ontap/encryption-at-rest/replace-self-encrypting-disk-task.html)

need update, thx!

If an HA pair is using [encrypting SAS or NVMe drives (SED, NSE, FIPS)](https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html), you must follow the instructions in the topic [Returning a FIPS drive or SED to unprotected mode](https://docs.netapp.com/us-en/ontap/encryption-at-rest/encryption-at-rest/return-seds-unprotected-mode-task.html) for all drives within the HA pair prior to initializing the system (boot options 4 or 9). Failure to do this may result in future data loss if the drives are repurposed.

**Comment by netapp-ahibbard** [comment]
@calvinwonghk - Thanks for sharing this. We will fix immediately.
