### ISSUE TITLE
Add maxdir and maxfile topics from TR guide to Docs. 

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap#502]
Page: [Cautions for increasing the maximum directory size for FlexVol volumes](https://docs.netapp.com/us-en/ontap/volumes/cautions-increasing-maximum-directory-size-concept.html)

This is a topic that comes up alot for customers. this should be covered in ONTAP concepts. The following TR guide covers both topics from a-z. 

https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf

**Comment by netapp-forry** [comment]
Thanks Logan - we'll look into this ASAP.

**Comment by netapp-forry** [comment]
Moving discussion and resolution to https://jira.ngage.netapp.com/browse/KDA-1448.
