### ISSUE TITLE
wrong picture

### ISSUE THREAD

**Issue by UweRoos** [NetAppDocs/ontap#504]
Page: [SVM disaster recovery workflow](https://docs.netapp.com/us-en/ontap/data-protection/svm-disaster-recovery-workflow-concept.html)

The picture does not show what's written in the text:
To recover from a disaster and serve data from the destination SVM, you must activate the destination SVM. Activating the destination SVM involves stopping scheduled SnapMirror transfers, aborting ongoing SnapMirror transfers, breaking the replication relationship, stopping the source SVM, and starting the destination SVM.

Regards,
Uwe.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Uwe - we'll look into this as soon as possible.
