### ISSUE TITLE
Update for SnapLock with ONTAP 9.10.1

### ISSUE THREAD

**Issue by polotski** [NetAppDocs/ontap#505]
Page: [Commit Snapshot copies to WORM](https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html)

Hi Team,

with ONTAP 9.10.1 we introduced the possibility to have SnapLock as well as non-SnapLock volumes on the same aggregate. However, the above referenced documentation does not mention this yet. Could this be updated please?
In the "Create a SnapLock aggregate" section of the online documentation, this change is already visible:
[Create a SnapLock aggregate](https://docs.netapp.com/us-en/ontap/snaplock/create-snaplock-aggregate-task.html)

Best Regards
Jörg

joerg.wolfinger@netapp.com

**Comment by netapp-forry** [comment]
Thanks for letting us know, Jörg -- we'll look into this as soon as possible.

**Comment by netapp-lenida** [comment]
This issue has been fixed in this topic in the note in Step 3. Thanks again for letting us know.
