### ISSUE TITLE
Release Notes link broken

### ISSUE THREAD

**Issue by rallard** [NetAppDocs/ontap#508]
Page: [ONTAP 9 Documentation](https://docs.netapp.com/us-en/ontap/index.html)

**Comment by netapp-ahibbard** [comment]
@rallard - Thanks for opening the issue. We've tested the link, and it seems that you are encountering a registration issue. The instructions on the registration page may be helpful to you:

Sign-in with the email address on your NetApp account. The password will be either (a) a One Time Passcode (OTP) that will be sent to your email address, or (b) your password to your organization.* Read our [FAQ](https://kb.netapp.com/Advice_and_Troubleshooting/Miscellaneous/FAQs_for_NetApp_adoption_of_MS_Azure_AD_B2C_for_login) or get [help](https://mysupport.netapp.com/site/help).
Existing users: If you have not done so already, please [pre-register](https://mysupport.netapp.com/site/user/registration) now
New users: Please [register](https://mysupport.netapp.com/site/user/registration)
NetApp employees: Sign-in with [username]@netapp.com
*If your organization is federated with NetApp
