### ISSUE TITLE
Minimum OS requirement

### ISSUE THREAD

**Issue by simonpie** [NetAppDocs/ontap#510]
Page: [Trigger scheduled migration and tiering](https://docs.netapp.com/us-en/ontap/fabricpool/trigger-scheduled-migration-tiering-task.html)

Hello,

I believe this behaviour is available starting in 9.8.x.  It is definitely not available in 9.7.

**Comment by netapp-lenida** [comment]
Thanks for letting us know about this @simonpie. I'll update the topic as soon as possible.

**Comment by netapp-lenida** [comment]
The topic has been updated to include the release in which this feature was introduced. Closing the issue.
