### ISSUE TITLE
Add limitations of the client match field

### ISSUE THREAD

**Issue by aknetapp** [NetAppDocs/ontap#512]
Page: [How export rules work](https://docs.netapp.com/us-en/ontap/smb-admin/export-rules-concept.html)

does it make sense to add the info from https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What's_the_max_limit_of_characters_that_can_be_defined_in_%22clientmatch%22_field_of_%22export-policy_rule%22%3F here?

**Comment by netapp-forry** [comment]
Thanks Andy -- I'll look into this ASAP.

**Comment by netapp-forry** [comment]
Updated the topic you cited in the SMB content, also the following identical topic in the NFS content:
   https://docs.netapp.com/us-en/ontap/nfs-admin/export-rules-concept.html
At some point, we'll explore removing this redundancy.

It would probably be good to add this character limit to the man page.
