### ISSUE TITLE
Clone splitting

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#524]
Page: [Use FlexClone volumes to create efficient copies of your FlexVol volumes overview](https://docs.netapp.com/us-en/ontap/volumes/flexclone-efficient-copies-concept.html)

This page is wrong when it states "As a result, the FlexClone volume becomes an independent FlexVol volume with its own disk space, instead of sharing disk space with its parent" and that's a critical error. Since 9.5 (maybe 9.4) a clone split does *not* copy data. the split volume continues to share space with the original.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Jeffrey -- we'll fix this ASAP.

**Comment by netapp-lenida** [comment]
The topic has been updated to the following: 
"You can also split a FlexClone volume from its parent volume. Beginning with ONTAP 9.4, for non-guaranteed volumes on AFF systems, the split operation for FlexClone volumes shares the physical blocks and does not copy the data. Therefore, splitting of FlexClone volumes on AFF systems is faster than the FlexClone splitting operation in other FAS systems in ONTAP 9.4 and later releases."
Thanks again for bringing this to our attention.
