### ISSUE TITLE
Not Secure" (HTTP) NetApp Docs URL 

### ISSUE THREAD

**Issue by Dariukuss** [NetAppDocs/ontap#528]
Page: [ONTAP 9 Documentation](https://docs.netapp.com/us-en/ontap/index.html)

Hello team, 

I seeing there is "Not Secure" (HTTP) so it wont be great to check the status of the certificates, 

![image](https://user-images.githubusercontent.com/45126082/172127958-933880d1-a4bf-4fc9-89b3-d9f31e1bdfc1.png)

Just in case !! 

Dario

**Comment by netapp-forry** [comment]
Thanks for letting us know, Dario -- we'll look into this as soon as possible.

**Comment by Dariukuss** [comment]
Hey !! 

Okay seems fair enough - that's exactly why: 

![image](https://user-images.githubusercontent.com/45126082/172178262-bbb55b47-9830-4d39-afe8-ab7cadfad486.png)

Second link of this google search: 
https://www.google.com/search?q=neatpp+volume+quota&rlz=1C1ONGR_esES1001ES1002&oq=neatpp+volume+quota+&aqs=chrome..69i57.7004j0j7&sourceid=chrome&ie=UTF-8

I entered via that link - and went directly to HTTP. 

Thanks for the quick responsed - I was thinking maybe some cert expired - but its clear now. 

BR and thanks !! 

Dario

**Comment by netapp-forry** [comment]
Thanks again, Dario, for letting us know about this issue with HTTP/HTTPS display. I'll close the content issue, but do feel free to contact us again if you have content questions or problems.
