### ISSUE TITLE
Is supported the anti-ransomware on CVO 9.11.1 ?

### ISSUE THREAD

**Issue by netapptakayuki** [NetAppDocs/ontap#530]
Page: [Anti-ransomware use cases and considerations](https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html)

The 9.11.1RC1 of Cloud Volumes ONTAP is released now. But the anti-ransomware license is unlicensed in CVO instance.
Is this anti-ransomware function of CVO supported ?

**Comment by netapp-forry** [comment]
Thank you for contacting us, Takayuki-san. 
I believe this is a question for the product manager. I'll close this issue and open an email discussion with him.
