### ISSUE TITLE
Missing modifier in example for SLAG

### ISSUE THREAD

**Issue by ntap-christoh** [NetAppDocs/ontap#533]
Page: [Configure Storage-Level Access Guard](https://docs.netapp.com/us-en/ontap/smb-admin/configure-storage-level-access-guard-task.html)

I believe there is a typo in step 10.
Apply the Storage-Level Access Guard security policy by using the vserver security file-directory policy apply command.

vserver security file-directory apply -vserver vs1 -policy-name policy1

The job to apply the security policy is scheduled.

It's mentioned to use the vserver security file-directory **policy** apply command, but the example shows a command without the vserver security file-directory **policy** piece.  I believe the example should show as follows:

vserver security file-directory policy apply -vserver vs1 -policy-name policy1

**Comment by ntap-christoh** [comment]
It may actually be the other way around.  The current example may be correct, but the description may not be correct.

**Comment by netapp-forry** [comment]
Hi Chris -- Thanks for letting us know. It appears that the step text "vserver security file-directory policy apply" is incorrect, it should be "vserver security file-directory apply" as in the example. This is per the man page:
   https://docs.netapp.com/us-en/ontap-cli-9111//vserver-security-file-directory-apply.html
We'll fix it ASAP.
