### ISSUE TITLE
Add FIPS 140-2 validation info to network management guide

### ISSUE THREAD

**Issue by ntapmattt** [NetAppDocs/ontap#537]
Page: [Configure IP security (IPsec) over wire encryption](https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html)

A statement about FIPS 140-2 validation needs to be added to the network management guide.  It can be similar to the following.

"Staring in ONTAP 9.9.1 and later the encryption algorithms used by IPsec are FIPS 140-2 validated as they are generated by the NetApp Cryptographic Module in ONTAP which carries the FIPS 140-2 validation."

**Comment by netapp-forry** [comment]
Thanks for letting us know, Matt -- we'll update this ASAP.

@netapp-barbe: Heads up that Andrew will be making this change.

**Comment by ntapmattt** [comment]
Awesome.  Thanks.

-Matt

From: Andrew Hibbard ***@***.***>
Reply-To: NetAppDocs/ontap ***@***.***>
Date: Tuesday, June 14, 2022 at 3:58 PM
To: NetAppDocs/ontap ***@***.***>
Cc: "Trudewind, Matt" ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/ontap] Add FIPS 140-2 validation info to network management guide (Issue #537)

NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Closed #537<https://github.com/NetAppDocs/ontap/issues/537> as completed.
