### ISSUE TITLE
SCSI-3 reservations?

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#540]
Page: [Additional restrictions and limitations](https://docs.netapp.com/us-en/ontap/smbc/smbc_plan_additional_restrictions_and_limitations.html)

I don't see anything in our documentation about SCSI-3 reservations being unsupported with SM-BC. That's a major omission. We have a customer who just learned about this now. Can you check to see where this is described?

**Comment by netapp-forry** [comment]
Thanks for letting us know, Jeff -- we'll look into this ASAP.

**Comment by netapp-ahibbard** [comment]
Thanks Jeff. This has been updated in the [SM-BC docs](https://docs.netapp.com/us-en/smbc/smbc_plan_prerequisites.adoc)
