### ISSUE TITLE
Add warning/note about 9.10.1 extended retention feature

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#543]
Page: [Set the retention time overview](https://docs.netapp.com/us-en/ontap/snaplock/set-retention-period-task.html)

Here we say you can set retention longer in 9.10.1:
"Beginning with ONTAP 9.10.1, you can set a retention time up to October 26, 3058 and a retention period up to 100 years. When you extend retention dates, older policies are converted automatically. In ONTAP 9.9.1 and earlier releases, unless you set the default retention period to infinite, the maximum supported retention time is January 19 2071 (GMT)."

But what we don't say is that you can't replicate a 9.10.1 volume with the new extended retention to a destination on an earlier ONTAP release. We should mention this.

Could we add something to this like: "When establishing a SnapMirror relationship with a SnapLock source volume using a retention date later than January 19th 2071 (GMT), the destination cluster must be running ONTAP 9.10.1 or later or the SnapMirror transfer will fail."

**Comment by netapp-lenida** [comment]
Thanks for letting us know about this, Joey! I'll make this update ASAP.

**Comment by netapp-lenida** [comment]
The topic has been updated. Thanks again Joey!
