### ISSUE TITLE
Update to docs

### ISSUE THREAD

**Issue by sdowling03** [NetAppDocs/ontap#544]
Page: [Convert a FlexVol volume to a FlexGroup volume](https://docs.netapp.com/us-en/ontap/flexgroup/convert-flexvol-volume-task.html)

The line "You cannot convert a FlexGroup volume back to a FlexVol volume. If you want to do so, you should contact support." is misleading as it cannot be converted back to a FlexVol. The following KB and linked TR documents this:
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Can_you_convert_a_Flexgroup_to_a_Flexvol

It also is included in the PDF version here which may also need to be updated:
https://docs.netapp.com/us-en/ontap/pdfs/sidebar/Convert_FlexVol_volumes_to_FlexGroup_volumes.pdf

**Comment by netapp-forry** [comment]
Thanks for letting us know, Sean -- I'll look into this ASAP.

**Comment by netapp-forry** [comment]
We have corrected the text in this topic -- thanks again for letting us know.
