### ISSUE TITLE
Question for System wipeout 

### ISSUE THREAD

**Issue by flp-advanced** [NetAppDocs/ontap#548]
Page: [Fast zeroing of drives](https://docs.netapp.com/us-en/ontap/disks-aggregates/fast-zeroing-drives-concept.html)

Is option 4, Clean configuration and initialize all disks, with fast zeroing as reliable as the old method oder do i have to sanitize all the disks manualy afterwards?

**Comment by netapp-forry** [comment]
Thanks for contacting us. I'll do some research, then get back to you ASAP.

**Comment by netapp-forry** [comment]
Greetings -- I hope my response addressed your question. If not, please let us know -- thanks.
