### ISSUE TITLE
Potentially incorrect data in support table - Throughput floors & SVM

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/ontap#552]
Page: [Guarantee throughput with QoS overview](https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html)

The table at https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#supported-workloads-for-throughput-floors lists SVM and claims that throughput floors are supported for SVMs with Ontap 9.8. It seems this is incorrect, see the following output from an Ontap 9.11.1 cluster with a clear error message that this is not supported:

```
trinidad::> version
NetApp Release 9.11.1RC1: Wed Apr 27 06:57:10 UTC 2022

trinidad::> vserver modify -vserver svm_hland -qos-policy-group test

Error: command failed: Invalid QoS policy group specified "test". The specified QoS policy group has a min-throughput value set. Data Vservers are not
       supported by a policy group with a min-throughput value set.

trinidad::>
```

Can you please validate the document statement and correct the table of this is indeed not supported?

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll look into this ASAP.

**Comment by netapp-thomi** [comment]
BURT opened for tracking purposes:   BURT 1488888

**Comment by netapp-thomi** [comment]
The documentation topic referred to above has been updated to show that throughput floors are not supported for data servers (SVMs).  Thank you for pointing out the discrepancy.
Thanks,
Thom
