### ISSUE TITLE
Incorrect steps

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#559]
Page: [Transition an existing FlexGroup SnapMirror relationship to SVM DR](https://docs.netapp.com/us-en/ontap/flexgroup/transition-snapmirror-relationship-svm-dr-task.html)

The steps in this page are incorrect. In both step 2, 3, and 5 we have examples of volume-level relationships, not SVMDR. While I'm at it, some of the steps could use some re-wording. Here are my suggestions.

For step 2:
"
Create the FlexGroup SVM DR SnapMirror relationship. Use the same SnapMirror policy which is configured on the FlexGroup volume SnapMirror relationships:
snapmirror create -destination-path dest_svm: -source-path src_svm: -identity-preserve true -policy MirrorAllSnapshots
"

For step 3:
"
Verify the relationship is broken off: snapmirror show -destination-path dest_svm: -source-path src_svm:
"
(the example output  is fine)

For step 5:
"
Resynchronize the SVM SnapMirror relationship: snapmirror resync -destination-path dest_svm: -source-path src_svm:
"
(the example output is fine here)

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention, Joey. I'll update this information right away.

**Comment by netapp-joey** [comment]
Thanks as always, Lenida.

I forgot one thing. For step 2, can we add the following note? This is mentioned in the FlexVol docs so we should mention it here for FlexGroups too.
"You must use the `-identity-preserve true` option of the `snapmirror create` command when you create your replication relationship."

Thanks!

**Comment by netapp-lenida** [comment]
Will do! Thank you.

**Comment by netapp-lenida** [comment]
This issue has been addressed.
