### ISSUE TITLE
AFF specific content and inaccurate 7-mode transition reference 

### ISSUE THREAD

**Issue by beckylelliott** [NetAppDocs/ontap#561]
Page: [Inline storage efficiency enabled by default on AFF systems](https://docs.netapp.com/us-en/ontap/volumes/inline-storage-efficiency-enablement-aff-concept.html)

This section appears to be AFF specific.  However,  the table lists an option that should only pertain ONLY to FAS systems. 
AFF are too modern to have ran 7-mode ONTAP.  Listing 7-mode transition under volume conditions for storage efficiencies enabled for AFF adds unnecessary confusion. 

Under volume conditions: "ONTAP 7-Mode transition to clustered ONTAP" appears.  7-Mode pre-dated AFF systems by years.   AFF systems are too recent to have transitioned from 7-Mode to CDOT.  

 
![image](https://user-images.githubusercontent.com/23369195/176905434-4b3eb756-078b-4555-ac72-39395d749c54.png)

**Comment by netapp-forry** [comment]
Thanks for letting us know, Becky -- we'll look into this ASAP.

**Comment by netapp-forry** [comment]
Hi Becky - apologies for the delay.

I read that row as saying that volumes that were transitioned from 7-mode systems are supported for storage efficiency features on AFF systems. So the transitioned volume could conceivably have been copied from a FAS to an AFF system. 

Does that sound right to you? If so, we can leave the row as is. If not, I'll need to find an SME who would know.

**Comment by netapp-forry** [comment]
Hi Becky -- Please let me know if you'd like me to pursue this issue further -- thanks.
