### ISSUE TITLE
SyncMirroRemote and Default options don't appear on cli

### ISSUE THREAD

**Issue by dom123dom** [NetAppDocs/ontap#563]
Page: [Check throughput and latency between nodes](https://docs.netapp.com/us-en/ontap/performance-admin/measure-latency-throughput-nodes-task.html)

When running this command on ONTAP 9.9.1P8 only the below options are available, is this document out of date or is there another reason the other commands are missing?

AsyncMirrorLocal   
AsyncMirrorRemote
RemoteDataTransfer

I'm specifically wanting to test SyncMirrorRemote which is listed in the documentation as an available option but does not appear in the command at the cli. 

Thanks

**Comment by netapp-thomi** [comment]
Hi,
The current man pages for 9.7 through 9.11.1 list the following options for the "-session-type" parameter of the "network test-path" command:
-----------------------------------------------
-session-type {AsyncMirrorLocal|AsyncMirrorRemote|RemoteDataTransfer} - Type of Session to Test
The session type parameter is used to mimic the application settings used. A session consists of multiple TCP connections.

AsyncMirrorLocal: settings used by SnapMirror between nodes in the same cluster
AsyncMirrorRemote: settings used by SnapMirror between nodes in different clusters
RemoteDataTransfer: settings used by Data ONTAP for remote data access between nodes in the same cluster

The default session-type is AsyncMirrorRemote.
-----------------------------------------------------

It appears that the ONTAP documentation is incorrect.  There are no options called "SyncMirrorRemote" or "Default".
However, I will try to verify the list of options with a subject matter expert in Development.  

Links to man pages:
ONTAP 9.7           https://docs.netapp.com/us-en/ontap-cli-97/network-test-path.html
ONTAP 9.8           https://docs.netapp.com/us-en/ontap-cli-98/network-test-path.html
ONTAP 9.9.1        https://docs.netapp.com/us-en/ontap-cli-991/network-test-path.html
ONTAP 9.10.1      https://docs.netapp.com/us-en/ontap-cli-9101/network-test-path.html
ONTAP 9.11.1      https://docs.netapp.com/us-en/ontap-cli-9111/network-test-path.html

Thanks,
Thom

**Comment by netapp-thomi** [comment]
Hello, dom123dom, 
Thanks for pointing out the discrepancy in the ONTAP documentation.  The topic you referenced has been updated to show only three session types, which is consistent with the ONTAP man pages and the functionality of the system.  
Thank you for your comment and helping us keep the documentation up-to-date, complete, and accurate.
Thom
