### ISSUE TITLE
Missing link in the Upgrade OS section

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap#564]
Page: [Install or upgrade the ONTAP Mediator service](https://docs.netapp.com/us-en/ontap/mediator/index.html)

In the document there is a line stating "You can use the following link for information about setting up a repository." but there is no link, which customers can use.

**Comment by netapp-forry** [comment]
Thanks Viktor -- we'll look into this ASAP.

**Comment by netapp-ahibbard** [comment]
Thanks again for raising this Viktor. This reference to a link should not have been there and was removed.
