### ISSUE TITLE
What is the disk requirements? any link?

### ISSUE THREAD

**Issue by calvinwonghk** [NetAppDocs/ontap#565]
Page: [Install or upgrade the ONTAP Mediator service](https://docs.netapp.com/us-en/ontap/mediator/index.html)

**Comment by ntap-bmegan** [comment]
@netapp-ahibbard - Is this work complete? If not, can you provide an estimate?

**Comment by ntap-bmegan** [comment]
This issue will be closed on **mon 14 nov** due to lack of activity within the last 90 days. @calvinwonghk - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

FYI @jenatnetapp, @netapp-ehoffman
