### ISSUE TITLE
Command not available in Ontap 9

### ISSUE THREAD

**Issue by santhas-cell** [NetAppDocs/ontap#567]
cluster::> system health cluster-switch

Error: "cluster-switch" is not a recognized command
cluster::> set adv

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

cluster::*> system health cluster

Error: "cluster" is not a recognized command
cluster::*> system health cluster-switch

Error: "cluster-switch" is not a recognized command

cluster::*> version
NetApp Release 9.9.1P6: Tue Dec 21 13:38:22 UTC 2021

**Comment by netapp-ahibbard** [comment]
Thanks @santhas-cell. We will look into this ASAP

**Comment by netapp-ahibbard** [comment]
The topic that mentions this is [Verify the monitoring of cluster and management network switches](https://docs.netapp.com/us-en/ontap/system-admin/verify-monitor-cluster-management-network-switches-task.html)

**Comment by netapp-barbe** [comment]
Thank you, I will look into this issue and update the documentation accordingly.

**Comment by andris-ntap** [comment]
With ONTAP 9.8 and later, where support for multiple types of Ethernet switches has been introduced (cluster, storage, MCC-IP, shared), the CLI command syntax was changed.  Generally, "system cluster-switch" moved to "system switch ethernet".

ONTAP 9.7 man page: https://docs.netapp.com/us-en/ontap-cli-97/system-cluster-switch-show.html
ONTAP 9.8 man page: https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-show.html

ONTAP 9 Release Notes: https://library.netapp.com/ecm/ecm_get_file/ECMLP2492508

**Comment by netapp-iseult** [comment]
The documentation has been updated and we can close this issue.
