### ISSUE TITLE
Page retirement request - Enable or disable access-based enumeration from a Windows client

### ISSUE THREAD

**Issue by mark-beaupre** [NetAppDocs/ontap#568]
Page: [Enable or disable access-based enumeration from a Windows client](https://docs.netapp.com/us-en/ontap/smb-admin/enable-disable-access-based-enumeration-client-task.html)

The abecmd utility is no longer available in new versions of Windows Server and Windows clients. This utility shipped with WIndows Server 2008 which hit end of support January 14, 2020.

https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2008

This page should be retired.

**Comment by netapp-ahibbard** [comment]
Thanks for bringing this to our attention Mark. We will address ASAP.
