### ISSUE TITLE
change "node_mgmt_ip" to "cluster"

### ISSUE THREAD

**Issue by pdiddens** [NetAppDocs/ontap#569]
Page: [Move a SnapLock volume](https://docs.netapp.com/us-en/ontap/snaplock/move-snaplock-volume-task.html)

"Using a secure connection, log in to the ONTAP cluster management LIF:

ssh snaplock_user@node_mgmt_ip"

cluster management lif is mentioned but ssh into node-mgmt? Would'nt cluster make more sense to be consistent?

**Comment by netapp-ahibbard** [comment]
Thanks for bringing this to our awareness. We'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks @pdiddens, cluster management LIF does make more sense. I've updated the topic.
