### ISSUE TITLE
CLI syntax changes for ONTAP 9.8+ and remove dead content

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#579]
Page: [Commands for monitoring the health of your system](https://docs.netapp.com/us-en/ontap/system-admin/commands-monitor-health-system-reference.html)

See GitHub with more details about the CLI changes: https://github.com/NetAppDocs/ontap/issues/567

This content should be removed - it's about very EOVS ONTAP versions...
**Downgrade software versions between minor releases**

When downgrading a cluster from Data ONTAP 8.2.1 to Data ONTAP 8.2, ONTAP clears the history of deleted switches. It also sets the Model column to OTHER if a switch that it automatically discovers is not supported for health monitoring.

**Comment by andris-ntap** [comment]
You should also **remove** these two commands, entirely.  Nobody should be checking or changing the polling interval.

<html><body>


Display the interval in which the health monitor polls switches to gather information | system cluster-switch polling-interval show
-- | --
Modify the interval in which the health monitor polls switches to gather information.   This command is available at the advanced privilege level. | system cluster-switch polling-interval modify


</body>
</html>

**Comment by netapp-iseult** [comment]
The suggested updates to the "Commands for monitoring the health of your system" topic have been published.
