### ISSUE TITLE
Correct range for default retention period is 0-100 when specified in years

### ISSUE THREAD

**Issue by lido-alexion** [NetAppDocs/ontap#581]
Page: [Set the default retention period](https://docs.netapp.com/us-en/ontap/snaplock/set-default-retention-period-task.html)

I think the correct range for default retention period is 0-100 when specified in years (and not 0-70).

**Comment by netapp-lenida** [comment]
Let me check on this, but I think @lido-alexion is referring to this change introduced in ONTAP 9.10.1: 
https://docs.netapp.com/us-en/ontap/snaplock/set-retention-period-task.html#about-retention-period-and-retention-time

**Comment by netapp-lenida** [comment]
I have updated the maximum retention period to 100 years with a note that the value changed in ONTAP 9.10.1.
