### ISSUE TITLE
Could you please change the expression of a sentence?

### ISSUE THREAD

**Issue by yumiyaz** [NetAppDocs/ontap#582]
Page: [Provision a FlexGroup volume automatically](https://docs.netapp.com/us-en/ontap/flexgroup/provision-automatically-task.html)

Could you please change the following sentence?
The customer misunderstood this setting which is the design and he thought it isn't able to change settings.

Original : 
"The FlexGroup volume is created with the volume space guarantee except on AFF systems. For AFF systems, the FlexGroup volume is created with the none space guarantee."

To :
"Volume space guarantee default setting is the following. The FlexGroup volume is created with the volume space guarantee except on AFF systems. For AFF systems, the FlexGroup volume is created with the none space guarantee. "

I confirmed the following command reference.
volume create
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-970/volume__create.html

|[-space-guarantee| -s {none|volume}] - Space Guarantee Style
	This optionally specifies the space guarantee style for the volume. A value of volume reserves space on the aggregates for the entire volume. A value of none reserves no space on the aggregates, meaning that writes can fail if an aggregate runs out of space. Because CIFS does not handle out-of-space conditions, do not use the value none if the volume is accessible to CIFS clients. The default setting for the volumes on All Flash FAS systems is none, otherwise the default setting is volume. The file setting is no longer supported.

**Comment by netapp-lenida** [comment]
Thank you @yumiyaz for bringing this to our attention. We will look at this topic right away.

**Comment by netapp-lenida** [comment]
Thank you @yumiyaz for bringing this to our attention. We will look at this topic right away.

**Comment by netapp-lenida** [comment]
Thanks again @yumiyaz. I have updated the topic.
