### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap#586]
Page: [Get AutoSupport message descriptions](https://docs.netapp.com/us-en/ontap/system-admin/get-autosupport-message-descriptions-task.html)

Page is no longer available.

You can get a similar AutoSupport/callhome list with a syslog translator query.  (e.g. 9.10.1)
https://mysupport.netapp.com/site/bugs-online/syslog-translator?product=ontap&version=9.10.1&syslog=callhome

**Comment by netapp-ahibbard** [comment]
Thanks for making us aware of this Logan. We will resolve this today.

**Comment by andris-ntap** [comment]
Please check ALL docs for this obsolete URL and update with something like this...

The descriptions of the AutoSupport messages that you receive are available through the ONTAP - Syslog Translator page.
Steps

1. Go to the [ONTAP - Syslog Translator](https://mysupport.netapp.com/site/bugs-online/syslog-translator) page.
2. On the ONTAP Syslog Translator page under RELEASE, specify your major version of ONTAP, enter **callhome** under SEARCH STRING and then click **Translate**.
