### ISSUE TITLE
Is Requirements for setting up FPolicy section complete?

### ISSUE THREAD

**Issue by jgartrell-missional** [NetAppDocs/ontap#587]
Page: [Requirements, considerations, and best practices for configuring FPolicy](https://docs.netapp.com/us-en/ontap/nas-audit/requirements-best-practices-fpolicy-concept.html)

Do we have any other requirements?
firewall policies or service-policy for newer versions on ONTAP?

Many thanks!

**Comment by netapp-forry** [comment]
Thanks for the heads-up, John -- we'll look into this ASAP.

**Comment by netapp-forry** [comment]
Hi John -- As you suggested, there are new networking capabilities for FPolicy in ONTAP 9.8 and later:
LIFs and service policies in ONTAP 9.6 and later
https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html#client-side-lif-service
Service: data-fpolicy-client
"Beginning with ONTAP 9.8, ONTAP provides client service for outbound FPolicy connections."

I'll consult with SMEs about updating the topic you mentioned -- thanks again for contacting us.

Tracking internal discussion in BURT 1495284.

**Comment by netapp-forry** [comment]
Hi John,
Sorry for the delay. We've updated the FPolicy topic with the following note:
Beginning with ONTAP 9.8, ONTAP provides a client LIF service for outbound FPolicy connections with the addition of the data-fpolicy-client service. [Learn more about LIFs and service policies](https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html).
The updated firewall policy content is as noted earlier in this thread.
Thanks again for contacting us!
