### ISSUE TITLE
Command is incorrect for onboard key manager

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/ontap#588]
Page: [Assign a data authentication key to a FIPS drive or SED (onboard key management)](https://docs.netapp.com/us-en/ontap/encryption-at-rest/assign-authentication-keys-seds-onboard-task.html)

'security key-manager query -key-type NSE-AK' does not work with onboard key-manager
The correct command is 'security key-manager key show'
(-key-type not supported with security key-manager key show)

**Comment by netapp-ahibbard** [comment]
@jhubert-netapp - Thanks for making us aware of this. I've updated the doc with the "security key-manager **key** query" command as it is not deprecated and both `security key-manager query` and `security key-manager key show` are deprecated.
