### ISSUE TITLE
Potentially confusing parameter description in object store server create command

### ISSUE THREAD

**Issue by kevinh-netapp** [NetAppDocs/ontap#591]
Page: [Create the S3 object store server](https://docs.netapp.com/us-en/ontap/s3-config/create-s3-object-store-server-task.html)

The use of "ca_cert_name" in the" vserver object-store-server create" command on this page has led some users to incorrectly specify a "server-ca" type certificate instead of the "server" type that is needed to allow connections to the object store server after it is created.  See the KB below for additional information:

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/HTTPS_connection_to_ONTAP_S3_server_fails_with_Connection_was_closed_before_we_received_a_valid_response_from_endpoint_URL

It may be a good idea to change "ca_cert_name" to just "cert_name" or even "server_cert_name" to help prevent users from specifying an incorrect certificate if they are not on an ONTAP version that has the fix for Bug 1414174 (mentioned in the KB).

**Comment by netapp-forry** [comment]
Thanks for letting us know, Kevin -- I'll update the topic ASAP.

**Comment by netapp-forry** [comment]
Moving discussion to BURT 1501598 and closing.
