### ISSUE TITLE
Conflicting language around "Sync mode of operation"

### ISSUE THREAD

**Issue by netappacook** [NetAppDocs/ontap#593]
Page: [SnapMirror Synchronous disaster recovery basics](https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html)

Under "Modes of Operation",  the following sentence conflicts with statements in TR-4733 dated May 2022.

"In Sync mode, **an I/O to primary storage is first replicated to secondary storage. Then the I/O is written to primary storage,** and acknowledgment is sent to the application that issued the I/O. "

On page 8 of TR-4733, it states: "In Synchronous mode, application I/O operations **are sent in parallel to the primary and secondary** storage systems."

The difference here is a serial process versus a parallel process.  What is the correct language?

**Comment by netapp-forry** [comment]
Thanks for letting us know, Adam -- we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks again for your feedback, Adam. After checking with Engineering, I have changed the topic you reference to match the TR.
