### ISSUE TITLE
ONTAP 9 doc center

### ISSUE THREAD

**Issue by y2luie03** [NetAppDocs/ontap#595]
Page: [Disassociate a volume efficiency policy from a volume](https://docs.netapp.com/us-en/ontap/volumes/disassociate-volume-efficiency-policy-task.html)

Hi Team,

I'd like to request the old documentation pages be put back in place with the exact commands available for each individual ONTAP release and the arguments/flags for the commands.  
These new pages are helpful still but the old documentation was better more thorough and better suited for our new hires that are on boarding.  
My request is to make both the old and new ONTAP 9 doc pages available for review and use by our customers and our new hires.  A few customers have also asked for the old documentation pages from a few weeks ago to be posted again.
There are also several typos in the new documentation:
example on this page:  https://docs.netapp.com/us-en/ontap/volumes/disassociate-volume-efficiency-policy-task.html?q=volume+efficiency+policy+modi

"Once you disassociate a volume efficiency policy, you have it trigger it manually." 
-This should probably read "you have to trigger it manually"

Can we make both of the ONTAP 9 doc center documents available?

Additional note: the search function in the new document does not work as well as the old one, a lot more guessing which link you might want to go to instead of getting you to the exact command you're already plugging in to the search.

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll investigate ASAP.

**Comment by netapp-forry** [comment]
Current status of this issue:

- We have fixed the typo that you noted; thanks for bringing it to our attention.

- Regarding "Can we make both of the ONTAP 9 doc center documents available?"
As you are aware, we changed our publication platform; all content has been migrated to the new site and the old Doc Center site was retired, it is no longer available. In the process of migrating content, almost all of the existing content was brought into the new platform. It's possible that there were errors, but the only content that was deliberately excluded was obsolete and/or incorrect.
- - I would therefore request that if you are aware of content that is missing, please let us know and we will investigate and restore if appropriate. Likewise, if you find a topic that is incorrect, incomplete, or ambiguous, please let us know in a new GitHub issue.

- Regarding search, two notes:
-- If you are looking for an exact string, you can use double-quotes to search for an exact string.
-- If you are looking for specific commands, please be aware that man pages are now in a separate site:
    https://docs.netapp.com/us-en/ontap-cli-9111/index.html

Thanks again for your comments on these issues. I will close this issue, but please do contact us if you have further questions or discover problems.
