### ISSUE TITLE
Vserver API missing vserver parameter

### ISSUE THREAD

**Issue by cyang-catalogicsoftware** [NetAppDocs/ontap#597]
/servlets/netapp.servlets.admin.XMLrequest_filer
Vserver API missing vserver parameter
can  you help me

**Comment by netapp-forry** [comment]
Thanks for contacting us -- we are looking into your query and will respond ASAP.

**Comment by cyang-catalogicsoftware** [comment]
This is my configuration

![image](https://user-images.githubusercontent.com/101167617/181484878-28bd5bf6-f38a-46a2-923d-50d048651b57.png)

**Comment by cyang-catalogicsoftware** [comment]
I don't know which parameter is missing

**Comment by cyang-catalogicsoftware** [comment]
can  you  help  me

**Comment by netapp-forry** [comment]
Hello cyang -- thanks for contacting us. We are trying to locate a person who is qualified to respond to your query. We'll get back to you as soon as possible.

**Comment by netapp-forry** [comment]
Could you please let us know what product and version you are using?

**Comment by cyang-catalogicsoftware** [comment]
ONTAPSELECT9.9.1_NODAR.ova
