### ISSUE TITLE
Question about MetroCluster configurations line in Supported and unsupported features with SnapLock matrix.

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/ontap#600]
Page: [What SnapLock is](https://docs.netapp.com/us-en/ontap/snaplock/snaplock-concept.html)

To whom it may concern,
I'd like to ask about Question about MetroCluster configurations row in Supported and unsupported features with SnapLock matrix.

MetroCluster configurations row in the matrix, "SnapLock Compliance or Enterpris are suppported ~" was written.

But I think this note mentioned about both of Compliance and Enterprise although it was written in Compliance column. 

And Yes or No should be written in the Compliance cell at first and add comment if it needed.

Cloud you please confirm what is the correct and modify this MetroCluster configuration row.
I guess both of Compliance and Enterprise was yes and some limitation should be noted.
Best regards,

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention. We'll look into it as soon as possible.

**Comment by netapp-lenida** [comment]
Thanks again, Ibukiyama-san. I have updated the MetroCluster section to make the SnapLock support information clearer.
