### ISSUE TITLE
"to prevent the code path that detects the contradiction from being executed."

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#604]
Page: [Additional restrictions and limitations](https://docs.netapp.com/us-en/ontap/smbc/smbc_plan_additional_restrictions_and_limitations.html)

What does "to prevent the code path that detects the contradiction from being executed" mean in this document? That paragraph makes no sense to me. Either there's a typo, or we need to explain further what this means.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Jeffrey -- we'll look into this ASAP.

**Comment by netapp-ahibbard** [comment]
This has been clarified. Thanks for making us aware of this.
