### ISSUE TITLE
Broken Link?

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#606]
Page: [Data protection overview with System Manager](https://docs.netapp.com/us-en/ontap/concept_dp_overview.html)

The link to "Managing data protection" seems to load the same page...not actually going to any pre-9.8 documentation.

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention, Tony. I'm looking into this now.

**Comment by netapp-lenida** [comment]
The broken link has been updated. Thanks again, Tony.
