### ISSUE TITLE
Is maintenance mode an alternative option?

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#609]
Page: [Return a FIPS drive or SED to unprotected mode](https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html)

This page details well about performing this required task within ONTAP.  However, from a recent case (2009234100) we almost were unable to boot into ONTAP to perform this task.  It appears that through  maintenance mode the "disk encrypt" command has options to rekey; however, we don't have this documented anywhere I can find and the details I'm finding from engineering is relatively spares.  

Therefore the ask here is can we check with engineering for a method to perform the same return to unprotected mode using a combination of maintenance mode commands successfully?

**Comment by netapp-forry** [comment]
Thanks for letting us know, Tim -- we'll look into this right away.

**Comment by netapp-ahibbard** [comment]
Thanks for bringing this up Tim. We've added maintenance mode instructions to the doc.
