### ISSUE TITLE
Suggested link change in "Key concepts" topic

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/ontap#61]
Page: [Key concepts](https://docs.netapp.com/us-en/ontap/concept_key_ontap.html)

Instead of linking to https://docs.netapp.com/us-en/ontap/concept_get_more_information.html, I'd recommend linking to the "Concepts Guide" in the Doc Center (http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-concepts/home.html).

In my mind, that is the most relevant next level of detail document.

**Comment by netapp-aherbin** [comment]
Thank you for your feedback.  The content owner is in agreement with your suggestion and the change has been posted.
