### ISSUE TITLE
Missing dash (-) in the volume show "is-qtree-caching-enabled" option. 

### ISSUE THREAD

**Issue by wilcoxc26149** [NetAppDocs/ontap#614]
Page: [Disable qtree functionality in FlexGroup volumes before reverting](https://docs.netapp.com/us-en/ontap/revert/task_disabling_qtrees_in_flexgroup_volumes_before_reverting.html)

Missing the dash for "-is-qtree-caching-enabled" option.
For ONTAP 9.6 or later, use: volume show is-qtree-caching-enabled true

Tested on AFF700s ONTAP 9.13.0
xxxxxx::*> volume show **is-qtree-caching-enabled true**

Error: Invalid character '-' in volume name. It can have '_' and alphanumeric characters.

xxxxxxx::*> volume show **-is-qtree-caching-enabled true**
There are no entries matching your query.

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll look into this right away.

**Comment by netapp-lenida** [comment]
Thanks @wilcoxc26149 for bringing this to our attention. The documentation has been updated.
