### ISSUE TITLE
"-peer cluster" should be "-peer-cluster"

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#616]
Page: [Create a FlexCache volume](https://docs.netapp.com/us-en/ontap/flexcache/create-volume-task.html)

![image](https://user-images.githubusercontent.com/18287750/183428669-45f1e20c-13d2-4599-8a11-730d9b1abbb9.png)

At step 2.b.

It should be ‘-peer-cluster’ and not ‘-peer cluster’

**Comment by netapp-forry** [comment]
Thanks Ben -- we'll fix this ASAP.
