### ISSUE TITLE
add link to kb on how to unpartition

### ISSUE THREAD

**Issue by loganbaez** [NetAppDocs/ontap#621]
Page: [Sanitize a disk](https://docs.netapp.com/us-en/ontap/disks-aggregates/sanitize-disk-maintenance-mode-task.html)

- **step 4 under Node shell method**

we can link to this kb. it has been made public recently. 
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP

also. we should move the partition check before dropping down to node shell or adive they have to go back to cluster shell after enabling option to sanitize.

**Comment by netapp-ahibbard** [comment]
Thanks Logan. The steps have been reordered and the KB added
