### ISSUE TITLE
Do we support MacOS?

### ISSUE THREAD

**Issue by jgartrell-missional** [NetAppDocs/ontap#624]
Page: [ONTAP platforms](https://docs.netapp.com/us-en/ontap/concepts/introducing-data-management-software-concept.html)

Good afternoon, the image mentions Unix, Windows, Linux, Virtualized.

Is MacOS supported?  And if so, it would be nice to get it added to that image.

**Comment by netapp-ahibbard** [comment]
Thanks @jgartrell-missional . We are looking into this.

**Comment by netapp-forry** [comment]
Hi John,
Although I was not able to find an official “ONTAP supports MacOS” statement, the NetApp ONTAP PowerShell Toolkit supports MacOS and there are numerous KBs and blog articles discussion MacOS client issues. So I think we can safely conclude that MacOS clients are supported. We will open a BURT to update the graphic (we'll cc you) and republish ASAP.

Thanks again for letting us know.
