### ISSUE TITLE
Dead link to obsolete Cloud Insights doc page.

### ISSUE THREAD

**Issue by netapp-alavoie** [NetAppDocs/ontap#634]
Page: [Add a connection to the cloud](https://docs.netapp.com/us-en/ontap/task_add_connection_to_cloud.html)

**Comment by netapp-alavoie** [comment]
Looks like the link to Cloud Insights documentation at the bottom of this page points to a page that was removed as being obsolete.  

I recommend pointing it instead to:
https://docs.netapp.com/us-en/cloudinsights/task_dc_na_cloud_connection.html

**Comment by netapp-forry** [comment]
Thanks Tony -- we'll correct this ASAP.

**Comment by netapp-ahibbard** [comment]
Thanks. The link destination has been updated
