### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by massa007** [NetAppDocs/ontap#635]
Page: [Configure NetApp Volume Encryption overview](https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html)

"The keys are deleted the entire aggregate is deleted." --> "The keys are deleted if the entire aggregate is deleted."

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll fix this ASAP.

**Comment by netapp-ahibbard** [comment]
Thanks @massa007 . We've update the documentation.
