### ISSUE TITLE
Weird typo in Google search results for OKM

### ISSUE THREAD

**Issue by juliantap** [NetAppDocs/ontap#646]
Page: [Enable onboard key management in ONTAP 9.6 and later](https://docs.netapp.com/us-en/ontap/encryption-at-rest/enable-onboard-key-management-96-later-nse-task.html)

When I did a Google search for "onboard key manager" using Edge, I got the following as the top result. The acronym is incorrect. It says "OCM" instead of "OKM". But, I have no idea what generates that text and don't find it when I search for the string in this topic or anywhere on docs.netapp.com. This typo doesn't seem to exist when I perform the same search using Firefox. In Firefox, it's correctly identified as OKM in all results.

This is obviously not high-priority, might be generated by some 3rd-party Edge tool we can't control, and is probably just a rabbit hole. Sorry if it does nothing but generate angst! But it does make it look like it's a typo that we own so I wanted to point it out.

![image](https://user-images.githubusercontent.com/83591660/187093995-85b1904d-1593-445f-8f2c-ef24d230fc02.png)

**Comment by netapp-forry** [comment]
Hi Julia -- Thanks for letting us know. I confirmed that the string "OCM" is not in the repository, so there's no action for us to take. I will ask the tools team about it.
