### ISSUE TITLE
How do I delete a file

### ISSUE THREAD

**Issue by tshefi** [NetAppDocs/ontap#649]
Page: [Delete files and directories rapidly on the cluster](https://docs.netapp.com/us-en/ontap/flexgroup/fast-directory-delete-asynchronous-task.html)

While following this guide, I was able to successfully delete a folder which resided under my NFS share, via this command:
ntap2554openstack::*> volume file async-delete start -vserver rhos_ci_cinder_glance -volume vol_glance -path tshefi/
[Job 231553] Job is queued: Asynchronous directory delete job. 

Great  tshefi/ folder vanished, however I'd also like to delete files from that share,
as the title suggests we can now "Delete files and directories",
I can't seem to guess the correct -path format for a file.

Lets assume the share originally looked like this:
$ ll vol_glance/
total 0
-rw-r--r--. 1 stack stack 0 Aug 31 11:52 file1.txt
-rw-r--r--. 1 stack stack 0 Aug 31 11:52 file2.txt
drwxr-xr-x. 2 stack stack 6 Aug 31 11:52 tshefi   -> this folder was removed, 

How do I delete file1.txt from the share?  

This command doesn't seem to work:
ntap2554openstack::*> volume file async-delete start -vserver rhos_ci_cinder_glance -volume vol_glance -path file1.txt 

Error: command failed: entry doesn't exist

Using  -path /file1.txt doesn't work either, nor do any other options I could think of.
Please consider adding an additional example of a file path/deletion to the existing folder example. 

Thank you very much
Tzach

**Comment by netapp-forry** [comment]
Thanks for letting us know, Tzach - we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks again for bringing this to our attention, Tzach. The title incorrectly stated that both files and directories can be deleted. The title is now updated to show that only directories can be deleted.
