### ISSUE TITLE
Please add links to labs for sales prospects and current NetApp customers

### ISSUE THREAD

**Issue by lanson-netapp** [NetAppDocs/ontap#656]
Page: [Security and data encryption](https://docs.netapp.com/us-en/ontap/security-encryption/index.html)

[Try the Securing ONTAP with Zero Trust Hands-On Lab (for existing customers)](https://handsonlabs.netapp.com/catalog)
[Try NetApp products with a test Drive (for new customers)](https://www.netapp.com/test-drives)

**Comment by netapp-forry** [comment]
Thanks again -- will discuss and get back to you.

**Comment by lanson-netapp** [comment]
This has been done before:
![2022-09-07_13-19-50](https://user-images.githubusercontent.com/112093682/188940657-7ca39135-b32c-4e80-ab34-11b6c8ec6505.png)

**Comment by netapp-forry** [comment]
Right you are -- thanks! We'll pursue this soon.
