### ISSUE TITLE
AD FS 3.0 Auto Certificate Rollover TokenSignature

### ISSUE THREAD

**Issue by mod25** [NetAppDocs/ontap#657]
Will Ontap 9.3 saml config automatic update new cert from https://ADFS/FederationMetadata/2007-06/FederationMetadata.xml or do i have to manualy update on ontap cli with command [security saml-sp].

Thank you

**Comment by netapp-forry** [comment]
Greetings -- Thanks for contacting us.

I'm not seeing anything about SAML certificate updates in the current SAML topic:
https://docs.netapp.com/us-en/ontap/authentication/configure-saml-authentication-task.html

I did find a KnowledgeBase (KB) article: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/ONTAP_System_Manager/System_Manager_SAML_Authentication_Resolution_Guide

If this is not sufficient to resolve your issue, I suggest you contact NetApp Support.
