### ISSUE TITLE
Warning about converting already full volumes.

### ISSUE THREAD

**Issue by JesterThew** [NetAppDocs/ontap#665]
Page: [Convert a FlexVol volume to a FlexGroup volume](https://docs.netapp.com/us-en/ontap/flexgroup/convert-flexvol-volume-task.html)

This task should come with a warning about the dangers of converting an already full volume and ending up with a full constituent.
From the Best Practices TR (link below) page 177.

"Also, if you have a FlexVol volume that is already very large (80–100TB) and already very full (80–90%),
you should copy the data rather than convert, because the converted FlexGroup volume has a very large,
very full member volume. This might create performance issues and does not fully resolve your capacity
issues, particularly if that dataset contains files that grow over time."

https://www.netapp.com/media/12385-tr4571.pdf

**Comment by netapp-forry** [comment]
Thanks for letting us know, Jester -- we'll look into this as soon as possible.

**Comment by netapp-lenida** [comment]
Thanks again for your feedback @JesterThew. The topic has been updated.
