### ISSUE TITLE
Update to ONTAP 9 release notes

### ISSUE THREAD

**Issue by sdowling03** [NetAppDocs/ontap#670]
Page: [ONTAP 9 Documentation](https://docs.netapp.com/us-en/ontap/index.html)

Hi Docs Team,

I have a customer that hit an issue where his EMS messages stopped sending to their Syslog server after a 9.8 update due to the management-ems LIF service being added to an Intercluster LIF that did not have a route to their Syslog server. We have removed the service now, and it is now working again. The issue is documented in the public report here, and Engineering has deemed it not to be a bug and has outlined the workaround:
https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1470250

The customer is now requesting that we add it to the release notes and the PDF in the update adviser to make them aware of the possible issue before updating. Perhaps this can be added to the Upgrade cautions section. 

Latest release notes: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508

**Comment by netapp-forry** [comment]
Thanks for letting us know, Sean -- we're looking into this now.

**Comment by netapp-forry** [comment]
Tracking internally, BURT 1505681.

**Comment by netapp-aherbin** [comment]
Sean,

The following topic has been added to the post-upgrade checks in the ONTAP documentation and a note is being added to the release notes linking to this topic.

https://docs.netapp.com/us-en/ontap/upgrade/remove-ems-lif-service-task.html

Thank you for your feedback!
