### ISSUE TITLE
flexcache prepopulate start fails due to lack of explanation

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#673]
Page: [Prepopulate a FlexCache volume](https://docs.netapp.com/us-en/ontap/flexcache/prepopulate-volume-task.html)

> volume flexcache prepopulate -cache-vserver vserver_name -cache-volume -path-list path_list -is-recursion true|false

It doesn't explain what to specify for this ”-path-list” argument.
The sample states the following,

> This example includes a single directory path for prepopulation:
> cluster1::*> flexcache prepopulate start -cache-vserver vs2 -cache-volume fg_cachevol_1 -path-list /dir1
>   (volume flexcache prepopulate start)
> [JobId 207]: FlexCache prepopulate job queued.

What do you mean by directory path?
If it is SMB, is it the path directory of the SMB file share name?
Is it the full path of the junction path mounted on the SVM?
Is it the full path including FlexVolume name? 
Is it a path name that can be checked with the df command (e.g. /vol/flexvol_name)?

Also, since there is no description in the following manual, I do not know what to specify. And I've been trying too, but I couldn't get this command to work.
https://docs.netapp.com/us-en/ontap-cli-9111//volume-flexcache-prepopulate-start.html#parameters

cluster2::*> volume flexcache prepopulate start -cache-volume fctestvol1 -cache-vserver svm2 -path-list /testvol1/dir2/forAA/folder11/test999

Error: command failed: Path(s) "/testvol1/dir2/forAA/folder11/test999" does not
       exist in origin volume "testvol1" in Vserver "svm1".

**Comment by netapp-forry** [comment]
Thanks for pointing out this issue -- we'll look into it as soon as possible.

**Comment by netapp-lenida** [comment]
@netapp-forry, this seems to be in reference to the man page.

**Comment by netapp-lenida** [comment]
Thanks for your feedback @kanitani. I will add more examples to the documentation.

**Comment by netapp-lenida** [comment]
I'm awaiting a response to an email I sent to a TME about this issue on Monday. Still awaiting a response. Will update ASAP.

**Comment by netapp-lenida** [comment]
Closing this issue since I am unable to make any further progress after contacting Engineering.

**Comment by kanitani** [comment]
Which team did you contact?
