### ISSUE TITLE
FlexClone Volume Move Consideration 

### ISSUE THREAD

**Issue by sitww** [NetAppDocs/ontap#674]
Bullet point 2 states - You can move FlexClone volumes from one aggregate to another aggregate on the same node or another node in the same SVM without splitting. I have not been able to achieve this.

**Comment by netapp-lenida** [comment]
Thanks @sitww. I've reached out to our SMEs and received some clarification for the bullet text in question in https://docs.netapp.com/us-en/ontap/volumes/recommendations-moving-concept.html#flexclone-volume-considerations-and-recommendations. We will update the information as soon as possible.

**Comment by netapp-lenida** [comment]
I've added some additional clarification to the second bullet point in the FlexClone volume considerations and recommendations section. Thanks again for contacting us.
