### ISSUE TITLE
Update readonly with additional information on "security login password"

### ISSUE THREAD

**Issue by netapp-norbertt** [NetAppDocs/ontap#682]
Hello team,

On page: [Predefined roles for cluster administrators](https://docs.netapp.com/us-en/ontap/authentication/predefined-roles-cluster-administrators-concept.html) there is a description for the readonly role mentioning it is allowed to execute "security login password" with access level all. This can be understood the way that user with role "readonly" is able to execute the command with all parameters, e.g.: 

    security login password -username admin

and thus change the password for admin as well. In reality this is not possible:

    mctsyscl1::> security login password -username admin

    Error: not authorized to change this password.
           command failed: not authorized for that command

    mctsyscl1::> 

and the user with "readonly" role is able to change it's own password only. This is nicely described in [Predefined roles for SVM administrators](https://docs.netapp.com/us-en/ontap/authentication/predefined-roles-svm-administrators-concept.html) for role "vsadmin-readonly":

    Managing own user account local password and key information

Can you please add a similar comment into [Predefined roles for cluster administrators](https://docs.netapp.com/us-en/ontap/authentication/predefined-roles-cluster-administrators-concept.html)  for readonly role?

Thanks!

**Comment by netapp-forry** [comment]
Thanks for letting us know, Norbert -- we'll fix this ASAP.

**Comment by netapp-aherbin** [comment]
The topic has bee updated to reflect that the readonly role is allowed to execute "security login password" for managing own user account local password and key information only as reflected in the example topci.

Thank you for feedback!
