### ISSUE TITLE
Please include the details discussed in burt 1487459 to this doc. Thanks

### ISSUE THREAD

**Issue by jsknair** [NetAppDocs/ontap#683]
Page: [How a quota report accounts for disk space and file usage](https://docs.netapp.com/us-en/ontap/volumes/quota-report-accounts-disk-space-file-usage-concept.html)

**Comment by netapp-ahibbard** [comment]
Thanks for reporting this @jsknair . We will look into this ASAP

**Comment by netapp-mdavidson** [comment]
Closing out, link to updated page: https://docs.netapp.com/us-en/ontap/volumes/space-display-quota-report-unix-client-concept.html#how-a-quota-report-accounts-for-disk-space-and-file-usage
