### ISSUE TITLE
Unclear ONTAP version which needs to go through the latest patch release

### ISSUE THREAD

**Issue by toshiki-mukaeda** [NetAppDocs/ontap#685]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)
If you are planning an ONTAP upgrade from an older ONTAP version (such as 9.3), it is a best practice to upgrade first to the latest patch release in the same ONTAP release family and only then upgrade to the next supported major release. 

"an older ONTAP version" is ambiguous.  9.3 is recommended for upgrade first to the latest patch, but how about 9.5 or 9.7?
Please specify exact ONTAP version or is it recommended for out of full support version.

**Comment by netapp-aherbin** [comment]
Thank you for your feedback.  We will look into this right away.

**Comment by netapp-aherbin** [comment]
Toshiki,  

No matter what version of ONTAP you are running, it is best practice to upgrade to latest patch release of your current version before performing an upgrade to another release.  We agree with your point that "an older ONTAP version" is ambiguous and  will remove this phrase.  

Please let me know if you need further clarification.

Thanks again for your comment.

**Comment by netapp-aherbin** [comment]
The update has been posted.  Thanks again for your feedback.  Feel free to reach out if there are additional concerns.
