### ISSUE TITLE
e0m typo - should be e0M

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#686]
Page: [Configure NetApp hardware-based encryption overview](https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html)

Typo:  e0m should be e0M

Otherwise, you should use port **e0m** for communication with key management servers.

**Comment by netapp-ahibbard** [comment]
Thanks @andris-ntap . We will get this fixed ASAP

**Comment by netapp-ahibbard** [comment]
Thanks Andris. The doc has been updated
