### ISSUE TITLE
Minor Tweaks 

### ISSUE THREAD

**Issue by TheFalldog** [NetAppDocs/ontap#688]
Page: [Manage administrator approval groups](https://docs.netapp.com/us-en/ontap/multi-admin-verify/manage-groups-task.html)

Hey there, a couple of pedantic tweaks for y'all...

_security multi-admin-verify approval-group create [ -vserver svm_name] -name group_name -approvers approver1[,approver2…] [-email address1], address1…​]_

The -email section seems to be missing an opening bracket. 

_security multi-admin-verify approval-group show -instance_

In my testing the following output represents the command without the -instance flag. 

Cheers!

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll fix this ASAP.

**Comment by netapp-forry** [comment]
The corrected topic has been published -- thanks again for contacting us and sorry for the delay.
