### ISSUE TITLE
Add first step -  take the LUN offline

### ISSUE THREAD

**Issue by ErikMaier** [NetAppDocs/ontap#689]
Page: [Enable space allocation for SCSI thinly provisioned LUNs](https://docs.netapp.com/us-en/ontap/san-admin/enable-space-allocation-scsi-thin-provisioned-luns-task.html)

Hello there,

I think we should add another step before the current first step, which should be

Bring the LUN offline -> lun modify -vserver vserver_name -volume volume_name -lun lun_name -state offline

Cheers

**Comment by netapp-forry** [comment]
Thanks for letting us know, Erik -- we'll look into this ASAP.

**Comment by netapp-aherbin** [comment]
Erik,

We've added the step to bring the LUN offline.  Thank you!

Amanda
