### ISSUE TITLE
Diag Command

### ISSUE THREAD

**Issue by tyler-espinoza** [NetAppDocs/ontap#691]
Page: [Delete a FlexCache relationship](https://docs.netapp.com/us-en/ontap/flexcache/delete-relationship-task.html)

Sorry if this is a duplicate, I forgot if I submitted it earlier...

This page lists the diag command "volume flexcache origin cleanup-cache-relationship". I was under the impression that diag commands should not be listed in public facing documentation. What's more is this only needs to be run if the "volume flexcache delete" command fails for some reason (verified against he internal man pages), which contradicts how this page simply lists it as the inherent 3rd step of deleting a FlexCache relationship. If it is determined that the "cleanup-cache-relationship" command needs to remain on this page for some reason, it's not mentioned that it's a diag command (and there isn't even a '*' character in the example prompt) so I predict that someone attempting to accomplish this workflow would encounter syntax errors and/or ONTAP reporting that the command does not exist.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Tyler -- we'll fix this ASAP.

**Comment by netapp-lenida** [comment]
Thanks again, Tyler. I've removed the diag command from this topic.
