### ISSUE TITLE
Incorrect guidelines -You can map a LUN to only one igroup.

### ISSUE THREAD

**Issue by Kristofer-NetApp** [NetAppDocs/ontap#693]
Page: [What to know before you create a LUN](https://docs.netapp.com/us-en/ontap/san-admin/lun-san-environments-concept.html)

Currently Document reads:

You can map a LUN to only one igroup.

When it should state:

'You can map a LUN only once to an igroup.'

**Comment by netapp-aherbin** [comment]
Hi Kristofer,

Thank you for you feedback.  

I think the intention of the statement is that you cannot map a LUN to 2 or more igroups at the same time.  Is that correct?

Also, are you saying that if a LUN is mapped to igroupA and the unmapped, it cannot be remapped to igroupA but can be mapped igroupB?

Amanda

**Comment by Kristofer-NetApp** [comment]
Hello Amanda,

Based on the way it reads now its stating to customers we only allow LUN 1 to be mapped to igroup A only.

In ONTAP we allow LUN 1 to be mapped to multiple igroups.   igroup A, igroup B, etc.

Originally the statement was made to make sure clients understand that they cannot map LUN 1 to igroup A 2 times in the original document this came from:

https://library.netapp.com/ecmdocs/ECMP1196995/html/GUID-D0FCDFC5-8FA3-4E7F-B844-2DE5098E068E.html

Kristofer Richert

**Comment by netapp-aherbin** [comment]
Updated as suggested:  You can map a LUN only once to an igroup.

Thank you!
