### ISSUE TITLE
ONTAP Select

### ISSUE THREAD

**Issue by ArnaudAlbertini** [NetAppDocs/ontap#701]
Page: [Plan your upgrade without Upgrade Advisor](https://docs.netapp.com/us-en/ontap/upgrade/task_plan_without_upgrade_advisor.html)

Hello, 

We don't specify the path for ONTAP Select upgrades.
We don't have ActiveIQ so it would be valid here and further up in the guide too.

I'm happy to clarify further if needed.

Thanks,
Arnaud

**Comment by netapp-forry** [comment]
Thanks for raising this issue, Arnaud -- we'll look into it ASAP.

**Comment by netapp-forry** [comment]
I'm seeing the following statement in the Select doc:
"Upgrade the ONTAP Select node using the standard ONTAP upgrade procedures with the ONTAP Select upgrade file."
https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html#general-procedure
(We can also provide a more direct pointer to the ONTAP upgrade content.)

Unless we have reason to doubt that, I'm inclined to update the following topic (where we mention CVO) to include a similar statement and pointer to this Select topic:
https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

@arnaud, what do you think?
@aherbin, your thoughts?

Thanks

**Comment by ArnaudAlbertini** [comment]
Hello Mark,

I found it confusing not to have a pointer with Select in the concept upgrade path.

There is no mention of ONTAP select in any page from the section : “Setup,Upgrade and revert ONTAP.”
We only differentiate for CVO and mention ON-Premise releases.

Does it mean we can use any upgrade path or method to upgrade an ONTAP Select ?


Thanks,
Arnaud

Arnaud Albertini
Support Account Manager

NetApp
+33 6 77650262
+33 1 49011786
***@***.******@***.***>


From: Mark Forry ***@***.***>
Date: Thursday, 17 November 2022 at 14:36
To: NetAppDocs/ontap ***@***.***>
Cc: Albertini, Arnaud ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/ontap] ONTAP Select (Issue #701)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



I'm seeing the following statement in the Select doc:
"Upgrade the ONTAP Select node using the standard ONTAP upgrade procedures with the ONTAP Select upgrade file."
https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html#general-procedure
(We can also provide a more direct pointer to the ONTAP upgrade content.)

Unless we have reason to doubt that, I'm inclined to update the following topic (where we mention CVO) to include a similar statement and pointer to this Select topic:
https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

@arnaud<https://github.com/arnaud>, what do you think?
@aherbin, your thoughts?

Thanks

**Comment by netapp-forry** [comment]
That's a totally reasonable question. According to the Select doc, the answer would be "yes, you can use any upgrade path or method to upgrade an ONTAP Select." However, I'd like us to verify this with the Select team before updating the ONTAP doc. When we get an answer, we'll advise here.

**Comment by netapp-aherbin** [comment]
Adding the following statement to  [ONTAP upgrade overview](https://docs.netapp.com/us-en/ontap/upgrade/index.html) and to to the topic on [Upgrade paths](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html) that Mark mentioned above.


“You can use these procedures to upgrade ONTAP and ONTAP select.  For more information on ONTAP select see [Upgrading the ONTAP Select nodes](https://docs.netapp.com/us-en/ontap-select/concept_adm_upgrading_nodes.html#general-procedure).”

Also updating the topic: [Download and install the ONTAP software image](https://docs.netapp.com/us-en/ontap/upgrade/task_download_and_install_ontap_software_image.html) to note that for ONTAP select the specific download in "ONTAP Select Node Upgrade."

Any concerns with this approach?

**Comment by netapp-aherbin** [comment]
These updates have been posted.  @ArnaudAlbertini  @netapp-forry Please comment if there are additional concerns.  If not, I'll close this issue shortly.

**Comment by netapp-forry** [comment]
No additional concerns from me -- looks good -- thanks!

**Comment by netapp-aherbin** [comment]
Closing this issue.
