### ISSUE TITLE
Wrong spelling

### ISSUE THREAD

**Issue by zhihongluo** [NetAppDocs/ontap#703]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

![image](https://user-images.githubusercontent.com/104557809/202403192-4451a42e-a973-4c4c-8e34-5bdcb5f5ebb8.png)

**Comment by netapp-forry** [comment]
Thanks for letting us know, Zhihong -- we'll fix this ASAP.

**Comment by netapp-aherbin** [comment]
Fixed.  Thanks for catching this!
