### ISSUE TITLE
[Action Needed]Description makes confused, need to be confirmed or modified

### ISSUE THREAD

**Issue by PolarLiu12** [NetAppDocs/ontap#704]
Page: [Convert from RAID-DP to RAID-TEC](https://docs.netapp.com/us-en/ontap/disks-aggregates/convert-raid-dp-tec-task.html)

Problem:

------------------------------------------
If you want the added protection of triple-parity, you can convert from RAID-DP to RAID-TEC. RAID-TEC is recommended if the size of the disks used in your local tier (aggregate) is greater than 4 TiB.

What you’ll need

The local tier (aggregate) that is to be converted must have a minimum of six disks.<<<***
------------------------------------------
For RAID-TEC, it must have a minimum of seven disks in every group, the description said "must have a minimum of six disks" which makes confused.

My understanding is that, 'If you want the added protection of triple-parity, excepts the thiry-prity disk, The local tier (aggregate) that is to be converted must have a minimum of six disks.', am I right?

Would you help to confirm is this a wrong description?
Or if not, would you like help to modify it to something easier to understand?

By the way, Japanese version also have same issue:

https://docs.netapp.com/ja-jp/ontap/disks-aggregates/convert-raid-dp-tec-task.html

Thanks!

Polar Liu
Technical Support Engineer
NetApp Technical Support Center
Email: [Polar.L@netapp.com](mailto:Polar.L@netapp.com)
Working Hours: Mon-to-Fri, ## 9：00 - # 18：00 (JST)

**Comment by netapp-barbe** [comment]
Thanks for raising this issue, Polar -- we'll look into it ASAP.

**Comment by netapp-forry** [comment]
Hi Polar,
You are correct, 7 disks are required. Checking in this Public Report:
   https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/948840
... I see the following error message:
   Unable to create root aggregate: 5 disks specified, but at least 7 disks are required for raid_tec
Hence the system-generated message shows the 7 disk requirement.
We'll fix this as soon as possible in the English version; the Japanese version might take a bit longer.
Thanks again for raising this issue.

**Comment by netapp-aherbin** [comment]
I'll take care of making this change.

**Comment by netapp-forry** [comment]
Confirming that the fixed topic has been updated and published.

@netapp-gudugunti -- passing this issue to you to respond to the localization issue.

**Comment by PolarLiu12** [comment]
Hi all, 

Thanks for your response!

Polar

**Comment by netapp-gudugunti** [comment]
@PolarLiu12 The content issue is fixed on the language pages. Closing the issue.
