### ISSUE TITLE
What about TCP?

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#708]
Page: [Configure a storage VM for NVMe](https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html)

The System Manager steps only mention enabling FC for NVMe. Do these same steps apply if you're using NVMe/TCP, or are different steps required?

**Comment by netapp-aherbin** [comment]
Thanks Ben.  

We'll verify this ASAP!
