### ISSUE TITLE
"with" or "within"?

### ISSUE THREAD

**Issue by netapp-rlithman** [NetAppDocs/ontap#71]
Under the topic “Balance load by moving LUNs” and the section "Move restrictions" under Day-to-day administration. I was wondering whether the word “with” should be “within” in the following statement:
•	A LUN cannot be moved to a qtree **with** the same volume.

**Comment by netapp-gregb** [comment]
Should be within. LUNs live inside volumes.

**Comment by netapp-aherbin** [comment]
Rachel, thank you for your feedback. This issue has been updated and is scheduled for posting on 12/201/19
