### ISSUE TITLE
Cloud Volumes Service for AWS

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#711]
Page: [ONTAP and the cloud overview](https://docs.netapp.com/us-en/ontap/cloud/index.html)

This page mentions _Cloud Volumes Service for AWS_. It should be replaced with _Amazon FSx for ONTAP_.

**Comment by netapp-aherbin** [comment]
Thanks Ben! We will update ASAP.

**Comment by netapp-aherbin** [comment]
The update has been posted.  Thanks again!
