### ISSUE TITLE
CVO releases marked with an asterisk

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/ontap#716]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

"The asterisk (*) after the release version indicates a Cloud Volumes ONTAP-only release."

It seems to me that the wrong versions are marked with an asterisk. Isn't it the case that all 9.x.1 version are CVO versions?

Thx
Holger

**Comment by netapp-forry** [comment]
Hello Holger, 
Thanks for contacting us.
Beginning with ONTAP 9.9.0:
- 9.x.0 are cloud-only releases, i.e. for Cloud Volumes ONTAP (CVO) systems
- 9.x.1 are general releases, i.e. for on-premises and CVO systems

Does that address your question?

**Comment by kholger** [comment]
Hi Mark,

Thanks for the clarification. I raised it up as it also created confusion on customer site if 9.x.1 could be used for CVO.
Would it be possible to add the info you shared to this section?

Thanks
Holger

**Comment by netapp-forry** [comment]
Thanks Holger -- good to know. I agree, it would be good to add some clarifying text, here and elsewhere.
@netapp-lenida -- let's add a sentence saying something like "9.x.1 releases can be installed on both on-premises and Cloud Volumes ONTAP systems."

**Comment by kholger** [comment]
Much appreciated. Thank you!

**Comment by netapp-lenida** [comment]
Thanks again @kholger for bringing this to our attention. The text has been updated. I hope this removes any confusion that you and others were experiencing.
