### ISSUE TITLE
Documentation doesn't match options within System Manager

### ISSUE THREAD

**Issue by jarrah31** [NetAppDocs/ontap#717]
Page: [Serve data from a SnapMirror destination](https://docs.netapp.com/us-en/ontap/task_dp_serve_data_from_destination.html)
Hello,

I'm using ONTAP 9.11.1P3 and I'm testing SVM DR via System Manager using the instructions found in this guide.

I've noticed that this page doesn't cover the instructions for activating an SVM DR destination, but instead focuses on the menu options for a volume SnapMirror relationship (e.g. Pause and Break do not appear in the menu for an SVM SnapMirror). 

The previous page titled "Configure storage VM disaster recovery" caters for SVM DR, so it's confusing when the next page talks about volumes.

The next page to mention Storage VMs is called "Reactivate a source storage VM", so the System Manager documentation is missing the whole "Serve data from an SVM DR Destination" process that the CLI section has.

The CLI steps for this is very well documented (https://docs.netapp.com/us-en/ontap/data-protection/make-svm-destination-volumes-writeable-task.html), so could the System Manager guide for an end-to-end SVM DR process be improved upon please?

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll look into this as soon as possible.

**Comment by netapp-lenida** [comment]
I'm looking into this. Thank you!

**Comment by jarrah31** [comment]
Thanks Lenida

**Comment by netapp-lenida** [comment]
I'm looking into this. Thank you!

**Comment by netapp-lenida** [comment]
Thanks again for bringing this to our attention. I worked with one of our SMEs to document the correct steps for the missing topic. You can find it here: https://docs.netapp.com/us-en/ontap/task-dp-serve-data-from-dest-svm.html.

**Comment by jarrah31** [comment]
Thank you Lenida!
