### ISSUE TITLE
Where can I find the documentation for older ONTAP releases?

### ISSUE THREAD

**Issue by pixelchrome** [NetAppDocs/ontap#719]
Hi,
I am for the documentation of older ONTAP Releases. Pre 9.12 in my specific case for 9.7.

Where can I find that for these pages

https://docs.netapp.com/us-en/ontap/nas-audit/requirements-best-practices-fpolicy-concept.html
https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html

BR

**Comment by netapp-forry** [comment]
Thanks for raising this issue, Harald -- we'll get back to you as soon as possible.

**Comment by netapp-barbe** [comment]
After consultation with our LIF policy expert, the specified link is valid, even for ONTAP 9.7. The major distinction is that the data-fpolicy-client service is not available in ONTAP 9.6, which means outbound fpolicy connections might be established using any LIF in the admin vserver.

In terms of the service policy reference, that topic should be valid, even if some of the services it references are flagged as not existing until a particular release (such as ONTAP 9.11.1). The conceptual overview in that topic is still valid relative to the ONTAP 9.7 release.

Please reach out if you have further questions. In the meantime, I will close this issue.
