### ISSUE TITLE
The summary is missing for this page

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#72]
Page: [Enable new features by adding license keys](https://docs.netapp.com/us-en/ontap/task_admin_enable_new_features.html)

I noticed that a summary was missing when using the search. Only a <> shows up as the description for this page.

**Comment by netapp-bcammett** [comment]
![license](https://user-images.githubusercontent.com/18287750/71192962-44345180-2257-11ea-91e4-72a2ef257e87.gif)

**Comment by netapp-aherbin** [comment]
Thank you Ben.  A summary has been added and is being published now.
