### ISSUE TITLE
Add note for MetroCluster configurations to use same certificates 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap#722]
Page: [Install SSL certificates on the cluster](https://docs.netapp.com/us-en/ontap/encryption-at-rest/install-ssl-certificates-hardware-task.html)

Hello everyone, 

Following up on a recent burt 1513842 - https://burtview.netapp.com/burts/1513842. Can we add a note for MetroCluster setups that both clusters should either have same certificates or use one certificate on both sides, so that drives can be properly access in switchover: 

https://burtview.netapp.com/burts/1513842#Notes_jcomen_MonNov2810:06:40EST2022

Otherwise, we might get into trouble when disk ownership is moved the the other cluster in switchover, but it can't properly access they keys used.

**Comment by netapp-forry** [comment]
Thanks for contacting us, Viktor. Further discussion can be conducted in email and via a Jira ticket.
    https://jira.ngage.netapp.com/browse/ONTAPDOC-726
Moving this issue to ontap-internal and closing.
