### ISSUE TITLE
Update note for DP matrix

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#724]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

Since 9.12.1 is out in RC now, can we clarify this note in the "SnapMirror DR relationships" section?
"DP-type mirrors cannot be initialized beginning with ONTAP 9.11.1 and will be completely deprecated in a future release. For more information, see Deprecation of data protection SnapMirror relationships."

Suggestion:
"DP-type mirrors cannot be initialized beginning with ONTAP 9.11.1 and are completely deprecated in ONTAP 9.12.1. For more information, see Deprecation of data protection SnapMirror relationships."

**Comment by netapp-lenida** [comment]
Makes sense to me. I'll update the topic ASAP. Thanks, Joey.

**Comment by netapp-lenida** [comment]
Makes sense to me. I'll update the topic ASAP. Thanks, Joey.

**Comment by netapp-lenida** [comment]
Thanks again, Joey. I've updated the topic.
