### ISSUE TITLE
Are IC LIFs really needed on the remote cluster?

### ISSUE THREAD

**Issue by Myer** [NetAppDocs/ontap#727]
Page: [Enable ONTAP S3 access for remote FabricPool tiering](https://docs.netapp.com/us-en/ontap/s3-config/enable-ontap-s3-access-remote-fabricpool-task.html)

Nowhere else this requirement (IC LIFs on the destination) is mentioned. In all the other docs - when using ONTAP S3 as the FabricPool target - it always says:
- use IC LIFs on the source cluster (S3 client)
- use S3 data LIFs inside the S3 SVM on the destination cluster (S3 server)

Please clarify how the source FabricPool cluster actually communicates with the ONTAP S3 server.

**Comment by netapp-forry** [comment]
Thanks for raising this issue -- we'll look into it ASAP.

**Comment by netapp-forry** [comment]
Hello Myer,
Apologies for the delay in responding. I'm looking into this issue; however I'm not finding the doc you cited in the bullet list. Could you please point me to that topic?
Thanks much -- Mark

**Comment by netapp-forry** [comment]
Hello again,
I just confirmed with one of the engineers that an IC LIF is not required on the destination cluster. I'll update this topic and related FabricPool topics ASAP.
Regards -- Mark

**Comment by Myer** [comment]
Hi Mark,

it's about this sentence: "Intercluster LIFs must be configured on both local and remote clusters, although cluster peering is not required."
On the page which I linked to in the first post.

As you confirmed the part that intercluster LIFs are required on "remote clusters" is wrong.

**Comment by netapp-forry** [comment]
Topic updated per your observation -- thanks again for contacting us.
