### ISSUE TITLE
update support for LUN on SnapLock volume on SnapVault destination

### ISSUE THREAD

**Issue by manoharvk** [NetAppDocs/ontap#730]
Page: [Commit Snapshot copies to WORM](https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html)

From ONTAP 9.9.0 onwards, LUNs on a SnapLock volume is supported only in the case of LockVault (SnapLock for SnapVault) relationships where a snapshot of a non-SnapLock source volume is replicated and locked on a SnapLock destination. Such a snapshot can contain LUNs.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Manohar -- we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks again Manohar. The topic now includes the following information:

Beginning with ONTAP 9.9.0, LUNs on a SnapLock volume are supported in SnapLock only for SnapVault relationships where a Snapshot copy of a non-SnapLock source volume is replicated and locked on a SnapLock destination. These Snapshot copies can contain LUNs.
