### ISSUE TITLE
Mention SnapCenter is not supported

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#731]
Page: [Tamperproof Snapshot copy locking overview](https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html)

Multiple customers are reading this page and immediately asking if SnapCenter can support tamperproof snapshots. It's not, and we need to make that clear before customers proceed with implementation of this feature and discover it's not compatible.

**Comment by netapp-lenida** [comment]
Thanks, Jeffrey. I'm updating this now.

**Comment by netapp-lenida** [comment]
The topic has been updated to include SnapCenter in the list of unsupported features.
