### ISSUE TITLE
Cloning

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#732]
Page: [Tamperproof Snapshot copy locking overview](https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html)

We also need an update on this doc about whether volume-clone and file-clone will work with a snapshot which has an expiry time.

**Comment by netapp-lenida** [comment]
Thanks again, Jeffrey. I've sent a message to Engineering and will update the topic as soon as I hear back.

**Comment by netapp-lenida** [comment]
Sorry for not following up until now. Volume clone and file clone will work on a locked Snapshot copy. These have been added to the list of supported features. Thanks again.
