### ISSUE TITLE
Doccument change for the following page

### ISSUE THREAD

**Issue by sdowling03** [NetAppDocs/ontap#733]
Page: [Create the S3 object store server](https://docs.netapp.com/us-en/ontap/s3-config/create-s3-object-store-server-task.html)

Hi Docs Team,

would it be possible to make the following change to the documentation here, as it's very misleading? I just had a call with the customer, and I agree that the wording here leads to customers using the incorrect certificate. Here is the line with the misleading info:

Create the S3 server:
vserver object-store-server create -vserver svm_name -object-store-server s3_server_fqdn **-certificate-name ca_cert_name** -comment text [additional_options]

The line here in bold advises the customers to use the ca_cert_name. But here, we should be using the s3_server_name.

Here is what I would correct it to:
Create the S3 server:
vserver object-store-server create -vserver svm_name -object-store-server s3_server_fqdn **-certificate-name s3_server_name** -comment text [additional_options]

He also had one suggestion for an image in the FabricPool best practices in ONTAP 9.11.1 available at https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf
He mentioned that John Lantz sent him a better image, so maybe this will be updated, as John is the author of the TR. Here is the new image on page 36:
![image](https://user-images.githubusercontent.com/97728958/206723706-26be9784-7a07-4904-a7e1-3f8839dd3260.png)

**Comment by netapp-forry** [comment]
See discussion in email.

**Comment by netapp-forry** [comment]
Fix verified in the topic noted above, and John has been advised in email.
Marking this closed -- thanks again, Sean!
