### ISSUE TITLE
Please include a description for the "Reserved" metric and other capacity labels on this page

### ISSUE THREAD

**Issue by averageguyx** [NetAppDocs/ontap#734]
Page: [Monitor capacity in System Manager](https://docs.netapp.com/us-en/ontap/concept_capacity_measurements_in_sm.html)

In the following screenshot, "Physical Used", Reserved" and "Available" are in the screenshot.  On the document that explains this, the only Physical used, Physical used %, Logical used and Logical used % are explained.  There are more labels on this screenshot that need definitions.

![image](https://user-images.githubusercontent.com/49987703/207099866-82c0394b-8681-4fce-af6c-557fca92466e.png)

**Comment by netapp-thomi** [comment]
Hi averageguyx,
Thanks for your comment.  You're right; those labels need some explanation.  I'll look into this and update the file.
Thanks for helping us keep our documentation useful and up-to-date.
Thom Illingworth
Senior Technical Writer
NetApp Information Engineering

**Comment by netapp-thomi** [comment]
Additional information has been added to this topic to explain the labels on the System Manager UI.
Refer to [Capacity measurement terms](https://docs.netapp.com/us-en/ontap/concepts/capacity-measurements-in-sm-concept.html#cap-measurement-terms)

**Comment by netapp-thomi** [comment]
Hi Chanda,
Thanks for the reminder.  I closed #734 and #856
Thanks,
Thom



Thom Illingworth

Information Engineering (IE) Content Services


________________________________
