### ISSUE TITLE
Proxy server requirements for adding a connection to the cloud - NEEDS TO BE ADDED

### ISSUE THREAD

**Issue by bruce-johnson** [NetAppDocs/ontap#735]
Page: [Add a connection to the cloud](https://docs.netapp.com/us-en/ontap/fabricpool/add-connection-to-cloud-task.html)

Customers using a proxy server MUST ensure that the URL https://example.com is accessible from the proxy server. 

If it is not accessible, customers will receive a non-helpful general and confusing error in the GUI which reads " THe HTTP Proxy configuration is not valid"

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/ONTAP_System_Manager/'HTTP_Proxy_configuration_is_not_valid'_message_received_when_adding_a_connection_in_System_Manager

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention, Bruce. I'll update the topic as soon as possible.

**Comment by netapp-lenida** [comment]
The topic has been updated with a note that the URL hhtps://example.com must be accessible to the proxy server. Thanks again for bringing this to our attention.
