### ISSUE TITLE
confusing sequence of VServer start stop actions

### ISSUE THREAD

**Issue by Rorari** [NetAppDocs/ontap#737]
Page: [Reactivate the original source volume](https://docs.netapp.com/us-en/ontap/data-protection/reactivate-original-source-volume-task.html)
First the VServer from Source Cluster is stopped and then the VServer from Destination Cluster is started. This makes no sense to me.

**Comment by netapp-forry** [comment]
Thanks for your comment, Rorari -- we'll look into this ASAP.
