### ISSUE TITLE
This document needs clarity

### ISSUE THREAD

**Issue by jsknair** [NetAppDocs/ontap#739]
Page: [Enable Autonomous Ransomware Protection by default in new volumes](https://docs.netapp.com/us-en/ontap/anti-ransomware/enable-default-task.html)

This document talks about enabling ARP at the SVM level will help the new volumes arp enabled by default, we have an unhappy but big customer complaining that 'the doc does not clearly say when enabling the ARP at the SVM level, it does not enable ARP for the pre-existing volume'. 

Can we please capture that information clearly in this document? 

Thanks,

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll fix this ASAP.

**Comment by netapp-forry** [comment]
The corrected version has been published -- thanks again for contacting us!
