### ISSUE TITLE
FIPS compliance heading needs fixing

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#744]
Page: [Support for industry-standard network technologies](https://docs.netapp.com/us-en/ontap/concepts/support-industry-standard-technologies-concept.html)

Just a minor formatting issue with the **FIPS compliance** heading and section.

**Comment by netapp-forry** [comment]
Thanks Andris -- we'll fix ASAP.

**Comment by netapp-ahibbard** [comment]
Thanks Andris. Doc has been updated
