### ISSUE TITLE
Incorrect upgrade paths suggested 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/ontap#746]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

Hello everyone, 

In the table here there are suggestions that ONTAP 9,8 can be directly upgraded to 9.10.1 and 9.11.1, which doesn't really seems to be the case in MetroCluster IP configs due to https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1455547. 

I assume that might be possible in a normal cluster, but can we update the docs, so that there is no confusion and people don't get stuck in the middle of ANDUs? 

Thanks!

**Comment by netapp-ahibbard** [comment]
Thanks for reporting this Viktor. We will look into it ASAP

**Comment by viktorpenev** [comment]
Hi Andrew,

Thanks for the update. The title might be a bit harsh, but some of those are just not applicable for every type of config/systems we have.

Best regards,

Viktor Penev
Technical Support Engineer
Technical Support Center

NetApp
***@***.******@***.***>

[A close up of a logo  Description automatically generated]<https://www.netapp.com/us/index.aspx>


[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>

**Comment by netapp-forry** [comment]
@netapp-aherbin and @netapp-folivia: Please take a look at Viktor's comments, and investigate:

- If we need to update this topic to include MCC info.
- Whether a note is needed in the MCC doc set.
- Whether there are other MCC-related upgrade issues.

Thanks.

**Comment by netapp-aherbin** [comment]
I've investigated and updated the upgrade topic.  This issue is specific to select platforms and  does not indicate other MCC-related upgrade issues.  @netapp-folivia please confirm if this has impact the MCC doc set.  Let me know if you have questions.

**Comment by netapp-folivia** [comment]
Thanks, Amanda. I'll try to get confirmation on this today.

**Comment by andris-ntap** [comment]
Any updates?

**Comment by netapp-aoife** [comment]
Hi all, I've confirmed that this issue does not have an impact on the MCC doc set. Closing this as completed.
