### ISSUE TITLE
Article validity ends at ONTAP 9.9.1

### ISSUE THREAD

**Issue by pmeidell** [NetAppDocs/ontap#747]
Page: [Remove ownership from a disk](https://docs.netapp.com/us-en/ontap/disks-aggregates/remove-ownership-disk-task.html)

Starting with ONTAP 9.10.1 the options to the commands in step 4
-root
-data
are not valid.

This article needs to be updated so that it applies to all current ONTAP releases.

**Comment by netapp-ahibbard** [comment]
Thanks @pmeidell . We will look into this asap.

**Comment by netapp-thomi** [comment]
Opened jira issue ONTAPDOC-791 to track progress of fix.

**Comment by netapp-thomi** [comment]
Verified that the fix has been merged into the public repo.
