### ISSUE TITLE
Step 3 missing guidance for SVM-DR w/identity-preserve: true

### ISSUE THREAD

**Issue by blueboy31** [NetAppDocs/ontap#748]
Page: [Convert a FlexVol volume to a FlexGroup volume within an SVM-DR relationship](https://docs.netapp.com/us-en/ontap/flexgroup/convert-flexvol-svm-dr-relationship-task.html)

Running the check in step 3 of this document yields:
`Error: command failed: This operation is not permitted on a Vserver that is configured as the destination for identity preserve Vserver DR.`

Unknown if this indicates that the volume is ready for conversion.

**Comment by netapp-ahibbard** [comment]
Thanks for reporting this. We will investigate ASAP

**Comment by netapp-lenida** [comment]
Thanks @blueboy31. I've updated the information in the step with some additional information that I hope will make it clearer how you should proceed. It now reads as follows:

"From the destination SVM, verify that the FlexVol volume is ready for conversion:

volume conversion start -vserver svm_name -volume vol_name -check-only true

If this command generates any errors other than "This is a destination SVMDR volume," you can take the appropriate corrective action, run the command again, and continue the conversion."

I'm closing this now, but feel free to add any other feedback you might have for this issue.
