### ISSUE TITLE
Found a duplicate sentence in this page

### ISSUE THREAD

**Issue by NicolasErMo** [NetAppDocs/ontap#749]
Page: [How export policies are used with SMB access](https://docs.netapp.com/us-en/ontap/smb-admin/export-policies-access-concept.html)

Hi Team,

I see in this document a duplicate sentence:

“You associate exactly one export policy with each volume to configure client access to the volume. Each SVM can contain multiple export policies. This enables you to do the following for SVMs with multiple volumes:
•	Assign different export policies to each volume of the SVM for individual client access control to each volume in the SVM.
•	Assign the same export policy to multiple volumes of the SVM for identical client access control without having to create a new export policy for each volume.
”

If I am not wrong, would it be possible to remove the duplicate one?

**Comment by netapp-forry** [comment]
Thanks for letting us know, Nicholas -- we'll fix this ASAP. Happy New Year!

**Comment by NicolasErMo** [comment]
Thank you.

Happy New Year 😊

Regards,
Nicolas ERARD-MOTHES
Technical Support Engineer
Technical Support Centre

NetApp
***@***.******@***.***>

For technical assistance on a new or existing case, please call:
US & Canada 888-4-NETAPP // EMEA/Europe  00-800-44-638277 // Asia/Pacific  800-8008-0800
You may also get Support on the Web at http://mysupport.netapp.com<http://mysupport.netapp.com/>

[A picture containing drawing  Description automatically generated]<https://www.netapp.com/>


[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>

**Comment by netapp-forry** [comment]
Update published.
