### ISSUE TITLE
Cluster HA and Boot Menu

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#750]
Page: [Remove nodes from the cluster](https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html)

Hello doc team!  We had a customer ask today about unjoining 2 nodes from a 4 node cluster if that would automatically enable cluster HA on the two remaining nodes.  I think it does.  Someone else thought it didn't.  We couldn't find any engineering documentation to say for certain either way so figured maybe it was an opportunity to document what it really does.  As a note this is what the cluster ha command is - https://docs.netapp.com/us-en/ontap-cli-9121//cluster-ha-show.html.

The other thing just looking through the doc, Step 5b at the bottom has option 4 from the boot menu.  Which is certainly fine.  We do have options 9b/9c that can be done as well.  Maybe that complicates things too much, especially since that requires 9a first.  The real key there is we want people to wipe the configuration which option 4 gets done.  Anyway, color this second request with a very light color of request!   Also, here is the boot menu doc - https://docs.netapp.com/us-en/ontap/system-admin/manage-node-boot-menu-task.html

**Comment by netapp-forry** [comment]
Thanks for letting us know, Tim -- we'll look into this ASAP. Happy New Year!

**Comment by netapp-aherbin** [comment]
@netapp-chandaj we have confirmed that HA is automatically enabled on a 4-node cluster when 2 nodes unjoin.  We are confirming if this is true for all of ONTAP 9 or if it was enabled in a specific release.

**Comment by netapp-aherbin** [comment]
Confirmed that HA is enabled by default on remaining 2 nodes and that this is applicable to all versions of ONTAP 9.  Topic updated.

@TimMcGue for the second lightly colored request, we try to give one the customer one "happy" path even if there are various options.  Option 9a/b/c seems a bit more complicated, so we'll leave option 4.  But if you want to discuss further or feel strongly about publishing both, shot me an email.

Thanks,
Amanda

**Comment by TimMcGue** [comment]
@netapp-aherbin  thanks much for the deep research and great effort here!
