### ISSUE TITLE
ARP supportability in Cloud environments

### ISSUE THREAD

**Issue by toshiki-mukaeda** [NetAppDocs/ontap#753]
Page: [Autonomous Ransomware Protection use cases and considerations](https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html)

Cloud you describe clearly that ARP supportability under cloud environment?   
ARP is not supported on "CVO in AWS" or "FSx for NetApp ONTAP".
-----
ARP is not currently available in the following Cloud Volumes ONTAP environments:

- Amazon FSx
- Azure
- Google Cloud

**Comment by netapp-forry** [comment]
Thank you for alerting us, Toshiki-san. We have confirmed in email that AWS should be added to the list, I'll make that change ASAP.

**Comment by netapp-forry** [comment]
Update published.
