### ISSUE TITLE
Selective LUN Mapping and node to execute commands

### ISSUE THREAD

**Issue by TimMcGue** [NetAppDocs/ontap#755]
Page: [Remove nodes from the cluster](https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html)

We previously opened BURT 1279032 for an engineering request change.  Engineering has closed that BURT and won't fix.  So I'm hoping we can include the reason for the BURT in documentation.  

ONTAP supports Selective LUN Mapping - https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html.  That keeps a list of nodes available for the LUNs.  The cluster unjoin itself does not check for those LUN mappings are not in place for the nodes being removed.  So say you have node 1, 2, 3, and 4.  If SLM is configured for nodes 1 and 2, then you remove nodes 1 and 2, the clients will lose access to those LUNs even though the volumes were moved over to nodes 3 and 4.

Therefore, the request.  Can we document to make sure the Selective LUN Mapping has had the nodes to be unjoined removed?  Thankfully you already have great doc on how to do that - https://docs.netapp.com/us-en/ontap/san-admin/modify-slm-reporting-nodes-task.html.  

Second part.  The unjoin or remove-node command needs to be executed from a different node in the cluster than the one being unjoined.  Can we give the readers some direction as to login via the remote node management LIF or to login to the cluster-management LIF that has been re-homed to one of the remaining nodes?

Here's what happens if you try to run it from the same node that is being removed:

aff300-2n-rtp-4::*> system node show local -fields node
node
-------------
aff300-rtp-4a

aff300-2n-rtp-4::*> cluster remove-node -node aff300-rtp-4a

Error: command failed: Cannot remove a node on which the remove-node command is
       invoked. Please connect to any other node in the cluster to remove this
       node.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Tim -- we'll look into this ASAP.

**Comment by TimMcGue** [comment]
Thanks so much for the quick work - that looks great!

**Comment by netapp-aherbin** [comment]
Updates are posted.  Thanks!
