### ISSUE TITLE
Provide more detail on aggregate full alerts

### ISSUE THREAD

**Issue by luddite516** [NetAppDocs/ontap#756]
Page: [Address aggregate fullness and overallocation alerts](https://docs.netapp.com/us-en/ontap/volumes/aggregate-fullness-overallocation-alerts-concept.html)
This page does not specify the names of the EMS events which are used to alert.  It would be helpful to have hte specific event names so that they can be included in event filters and notifications.

**Comment by netapp-forry** [comment]
Thanks for letting us know -- we'll look into this ASAP.

**Comment by netapp-forry** [comment]
Tracking internally as ONTAPDOC-799.

**Comment by netapp-ehoffman** [comment]
This request for content enhancement is in the team's backlog and now being tracked internally,
