### ISSUE TITLE
Conceptual overview and diagram of how an IPSec Client and ONTAP interact alongside the storage protocols

### ISSUE THREAD

**Issue by Sawall10** [NetAppDocs/ontap#758]
Page: [Configure IP security (IPsec) over wire encryption](https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html)

Customer feedback: 
RE: NetApp Log # 2009422906
"I think NetApp would go well documenting something of an overview of how client setup would work at a high level,  might save questions like this.   Maybe something stating that strongswan connects and that you feel that the IPSec connection will come up before the remote mounting meaning the mounts are transparent on boot,  if that is what your labs are showing of course."

The customer's original question: "From a conceptual point of view I was wondering how the connection might happen with regard to bringing up the NFS or the ISCSI. Is it that the IPSec connection somehow does the mounting of share after a successful connection?"

Request:
I think this documentation would benefit from a conceptual overview and diagram of how an IPSec Client and ONTAP interact alongside the storage protocols to avoid confusion. I suspect people are mistaken that the IPSec Client is used to establish the mount for iSCSI/NFS.

Cheers,
Shane Wall

**Comment by netapp-forry** [comment]
Thanks, Shane -- interesting and worthwhile suggestion -- we'll look into this ASAP.

**Comment by netapp-ehoffman** [comment]
Closing this issue, and tracking via Jira: https://jira.ngage.netapp.com/browse/ONTAPDOC-895
Shane, we'll work on getting you access.
