### ISSUE TITLE
please include information on Entitlement requirements?

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap#760]
Page: [Update firmware](https://docs.netapp.com/us-en/ontap/task_admin_update_firmware.html)

AIQEXPERT or AIQADVISOR are required for this to work.  can we have this updated so customers and internal user be aware of this?

Please include this in BOLD/HIGHLIGHT - also links to how to check your entitlements?

**Comment by netapp-forry** [comment]
Thanks for contacting us, Eric -- good point -- we'll update the topic ASAP.

**Comment by ericd-netapp** [comment]
correction.  Please add  AIQUPGRADE as another entitlement that qualifies.

**Comment by netapp-thomi** [comment]
Thanks for the update, Eric.   We're on it!

**Comment by ericd-netapp** [comment]
Additionally please note that Disk Qualification Package (DQP) are NOT included in automatic updates.

please remove all references to such.

thanks!

**Comment by netapp-thomi** [comment]
All changes were made and tracked in ONTAPDOC-819
