### ISSUE TITLE
Does Anti-Ransomware protection supports ONTAP Select?

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#762]
Page: [Autonomous Ransomware Protection use cases and considerations](https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html)

Does this representation "all on-premises ONTAP systems" include ONTAP Select?

**Comment by netapp-forry** [comment]
Thanks for the question, Kan-san -- I'll look into it and get back to you ASAP.

**Comment by netapp-forry** [comment]
The topic has been updated: "ARP is not currently available for ONTAP Select."
Thanks again for calling this to our attention.
