### ISSUE TITLE
Cloud you please consider to add reason why it's reccommend to "not use" auto FlexGroup rebalancing.

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/ontap#763]
Page: [Rebalance FlexGroup volumes](https://docs.netapp.com/us-en/ontap/flexgroup/manage-flexgroup-rebalance-task.html)

To whom it may concern,

My customer asked me why recommended "not use flexgroup auto FlexGroup rebalancing"  after converting from FlexVol to FlexGroup Volume? 

=====================================================================
FlexVol to FlexGroup conversion
It is recommended that you do not use automatic FlexGroup rebalancing after a FlexVol to FlexGroup conversion. Instead, you can use the disruptive retroactive file move feature available in ONTAP 9.10.1 and later, by entering the volume rebalance file-move command. For command syntax, see the volume rebalance file-move start man page.
=====================================================================

I can't find reason on docs or any other materials.
So,  Cloud you please consider to add reason of why recommended "not use flexgroup auto FlexGroup rebalancing" for explanation?

Best regards,

**Comment by netapp-forry** [comment]
Thanks for contacting us -- good question -- we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks for the suggestion @imasafum. I've added the following explanation to the topic:

Rebalancing with the non-disruptive retroactive file move feature can degrade performance when moving large numbers of files, like when you perform a FlexVol to FlexGroup conversion, and as much as 50 to 85% of the data on the FlexVol volume is moved to a new constituent.
