### ISSUE TITLE
Customer reported that the minimum specs may have changed

### ISSUE THREAD

**Issue by bdeloure** [NetAppDocs/ontap#764]
Page: [Create an audit log](https://docs.netapp.com/us-en/ontap/snaplock/create-audit-log-task.html)

We had a customer who is running ONTAP 9.10.1P4 and knows about this limitation "_The minimum default retention period for audit log files is six months._"

They took one of our 9.11.1 labs in Hands-on Labs and discovered that the lab with ONTAP 9.11.1 appears to have now have no minimum period.  Looking through the release notes for 9.11.1 there is mention of System Manager management of SnapLock being added, and abilities to set these values in System Manager, but no mention of changes to minimums and nothing in the release notes specific to SnapLock audit log minimums.

Our labs use GA releases of ONTAP running on virtual machines and tend to behave the same as running on hardware for these types of settings.

Opening this issue to have someone research to see if the documentation page needs to be updated for the newest ONTAP release in terms of SnapLock audit log minimum retention values.

**Comment by bdeloure** [comment]
Our labs uses GA releases of ONTAP running on virtual machines and tend to behave the same as running on hardware for these types of settings.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Brian -- we'll investigate ASAP.

**Comment by netapp-lenida** [comment]
Hi Brian,
I checked with engineering regarding this question. This is the response I received:

>>> I assume, the customer looked at the SnapLock configuration setting of the log volume and it showed the default retention period setting as “min”. If so, this is expected. The default-retention-period setting that is specified during SnapLock log volume creation is for the audit log files created within the SnapLock volume and not for the volume itself. 

This sounds like there has not been a change to the default retention for audit logs, but if this response doesn't appear accurate, perhaps you can share a few more details about what the customer experienced.

**Comment by bdeloure** [comment]
If there were not changes, then perhaps the confusion might be coming from this page also: https://docs.netapp.com/us-en/ontap/snaplock/set-retention-period-task.html  There is a doc under Configure SnapLock that is titled retention time for the volume, but it looks like that doc is about retention period and retention time for the volume, then there is a separate mention of retention in the Create an audit log.  I can see how this is confusing.  Maybe warning note in the audit log retention doc pointing to the retention for the volume. Although I'm pretty sure the customer knew what he was talking about and was setting the retention period using the example command for the audit log and comparing it to the older ONTAP release.

**Comment by bdeloure** [comment]
This is exactly what he reported:
"The minimum default retention period for audit log files is six months says the documentation. But in my lab environment that is running on 9.11.1 I can define lower periods then six months, however in our production environment that is running on 9.10.1P4 I can not define periods lower then six months."

**Comment by netapp-lenida** [comment]
Thanks for sending the additional details. I'll forward this to the engineering team and I'll let you know what I hear back.

**Comment by netapp-lenida** [comment]
Closing this issue now. The minimum retention period for audit log files has not changed, however, I did add a pointer to the topic that explains about volume retention.

**Comment by bdeloure** [comment]
Lenida, Thanks.  I think you need to change the link it is broken now and I think it is going to .htm but it should be ".html"
