### ISSUE TITLE
Root SVM volume with a space guarantee set to "volume" can be added to FabricPool.

### ISSUE THREAD

**Issue by KalinTM** [NetAppDocs/ontap#765]
Page: [Considerations and requirements for using FabricPool](https://docs.netapp.com/us-en/ontap/fabricpool/requirements-concept.html)

In the Functionality or features not supported by FabricPool section of this article there is a line indicating that a volume with a space guarantee set to anything other than "none" will not allow the owning aggregate to be added to FabricPool. A data aggregate containing a root SVM volume with a space guarantee set to "volume" can be added to FabricPool. This has been reproduced in a VSIM a few times now.

**Comment by netapp-lenida** [comment]
Thanks again for bringing this to our attention, Kalin. I'm updating the documentation to the following: 

With the exception of root SVM volumes and CIFS audit staging volumes, FabricPool does not support attaching a cloud tier to an aggregate that contains volumes using a space guarantee other than `none`. For example, a volume using a space guarantee of `volume` (`-space-guarantee` `volume`) is not supported.

**Comment by netapp-lenida** [comment]
The topic has been updated.
