### ISSUE TITLE
NVMe/FC support with MetroCluster

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap#770]
Page: [SAN configurations in a MetroCluster environment](https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html)

Please change the following:
"MetroCluster configurations do not support front-end NVMe host connectivity"

This has been changed as of ONTAP 9.12.1 - see here:
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
page 52

Cheers, Niels

**Comment by netapp-forry** [comment]
Thanks for letting us know, Niels -- we'll update this ASAP.

**Comment by netapp-folivia** [comment]
HI Niels,

We have added support for ONTAP 9.12.1 and revised this section: https://docs.netapp.com/us-en/ontap/san-admin/san-config-mcc-concept.html

Thanks for your feedback!

Best,
Olivia
