### ISSUE TITLE
ARP: SnapMirror support

### ISSUE THREAD

**Issue by pdiddens** [NetAppDocs/ontap#774]
Page: [Autonomous Ransomware Protection use cases and considerations](https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html)

"Unsupported volume types:
[...]
SnapMirror-protected volumes (ONTAP 9.11.1 and earlier releases)"

I think this needs some clarification: SnapMirror is supported with 9.10.1 and later but retaining training data for ARP was implemented in 9.12.1. After failing over to SnapMirror destination or doing a reverse sync with ONTAP pre 9.12.1, ARP needs to be put into learning mode.

**Comment by netapp-forry** [comment]
Hi Patrick,

Thanks for calling out this lack of clarity.

A little further down in the topic, you'll see this subsection:
https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html#snapmirror-and-arp-interoperability 

I think that an appropriate update would be to remove the bullet above and add the following paragraph to the SnapMirror subsection:

"In ONTAP 9.10.1 and 9.11.1 systems where ARP is enabled, when the SnapMirror destination volume is converted to RW, ARP is not automatically enabled on the RW-converted destination volume. Rather, ARP must be put into learning mode again. "

I'll start an email thread with SMEs to confirm.
