### ISSUE TITLE
Is disk sanitization supported with Snaplock?

### ISSUE THREAD

**Issue by psauerbi** [NetAppDocs/ontap#778]
Page: [When disk sanitization cannot be performed](https://docs.netapp.com/us-en/ontap/disks-aggregates/sanitization-not-performed-concept.html)

A customer is asking me if disk sanitization is supported with Snaplock. I think it is not working with Snaplock Compliance?
Would be great is we could add this if its correct.

**Comment by netapp-forry** [comment]
Thanks for contacting us, Patrick -- we'll look into this ASAP.

**Comment by netapp-lenida** [comment]
Hi Patrick, 
After checking with product management and engineering, here is the response I received:

>>>  As I understand, to run disk sanitization, the disk needs to be a spare disk. Any disk which is part of an aggregate cannot be sanitized until all volumes and aggregates that the disk is part of is deleted (volumes can be moved and aggregates deleted) and the disk is marked as spare. So the question of being able to sanitize SnapLock disks should not arise. Let me know if I am missing anything.

So disk sanitation does not appear to be a feature that we need/should document for SnapLock. I'm closing this issue, but please let us know if you still have questions.
