### ISSUE TITLE
Throttle units are Bits not Bytes, and Vol Move docs are incorrect.

### ISSUE THREAD

**Issue by MrObvious** [NetAppDocs/ontap#779]
Page: [Use SnapMirror global throttling](https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-global-throttling-concept.html)

First, the "B" needs capitalized as it isn't Megabits/sec (Mb/s) but Megabytes/sec (MB/s). Second the line saying this isn't affected for vol move isn't true per burt 1379902. I tested in a lab myself and shared the results with Glase and Nathaniel.
<html><body>
<div class="paragraph">
<p>For example, if the outgoing throttle is set to 100 Mbps, each node 
in the cluster will have the outgoing bandwidth set to 100 Mbps. If 
global throttling is disabled, it is disabled on all nodes.</p>
</div>
<div class="admonitionblock note">

  | The throttle has no effect on volume move transfers or  load-sharing mirror transfers. Although data transfer rates are often  expressed in bits per second (bps), the throttle values must be entered  in kilobytes per second (KBps).
-- | --

</div>
</body>
</html>

Thanks 
- Paul Stejskal

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention, Paul. We'll look into this as soon as possible.

**Comment by netapp-lenida** [comment]
Transferring this issue to Jira ONTAPDOC-835.
