### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by pydonny** [NetAppDocs/ontap#781]
Page: [How ONTAP enables dynamic home directories](https://docs.netapp.com/us-en/ontap/smb-admin/dynamic-home-directories-concept.html)

It would be great if there was a matrix that says this is available or not available on all the different platforms, not just specific to this page. i.e. ANF, FSxN, CVO, CVS, AFF etc. 

Thanks

**Comment by netapp-forry** [comment]
Thanks for your query, Donald -- I'll look into this and get back to you ASAP.

**Comment by netapp-aherbin** [comment]
@netapp-chandaj I'll update the issue when I have more info.

**Comment by netapp-aherbin** [comment]
Moving to Jira (ONTAPDOC-1172) for internal tracking.
