### ISSUE TITLE
error in cli command

### ISSUE THREAD

**Issue by aydinpr** [NetAppDocs/ontap#783]
Page: [Verify all LIFS are on home ports after upgrade](https://docs.netapp.com/us-en/ontap/upgrade/task_enabling_and_reverting_lifs_to_home_ports_post_upgrade.html)

Replace

Display the status of all LIFs: network interface show -fields home-ports,curr-port

With

Display the status of all LIFs: network interface show -fields home-port,curr-port

**Comment by netapp-forry** [comment]
Thanks for letting us know, Aydin -- we'll fix this ASAP.

**Comment by netapp-aherbin** [comment]
The topic is updated with the correction.  Thank you!
