### ISSUE TITLE
Support for Fabricpool + FlexGroup + SVM-DR is included with 9.12.1

### ISSUE THREAD

**Issue by dammers** [NetAppDocs/ontap#786]
Page: [Supported and unsupported configurations for FlexGroup volumes](https://docs.netapp.com/us-en/ontap/flexgroup/supported-unsupported-config-concept.html)

Please refer to https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf

John Lantz: Updated for 9.12.1.
Support for SVM migrate. Support for FabricPool, FlexGroup,
and SVM-DR working in conjunction.
Note: Prior to 9.12.1, any two of these features worked
together, but not all three in conjunction.

**Comment by netapp-forry** [comment]
Thanks for letting us know, Robin -- we'll update this topic ASAP.

**Comment by netapp-lenida** [comment]
Thanks again, Robin. The topic has been updated.
