### ISSUE TITLE
Add information about local-identity and remote-identity options for ipsec policy for PSK auth

### ISSUE THREAD

**Issue by alikulov** [NetAppDocs/ontap#787]
Page: [Configure IP security (IPsec) over wire encryption](https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html)

According to documentation there is no need to have local and remote identities configured for PSK policy, but it doesn't work without these options. And there is KB mentioning these options for PSK auth.

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/Enabling_an_IPSEC_connection_fails_with_%22Payload_has_an_unknown_value%3A_4%22

**Comment by netapp-forry** [comment]
Thanks for letting us know, Arthur -- we'll look into this ASAP.

**Comment by netapp-barbe** [comment]
in progress, resolving open question

**Comment by netapp-ranuk** [comment]
Hi @alikulov We have appended additional information to provide more clarity about the remote and local identities, Please see [here](https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html).
