### ISSUE TITLE
Fan-out SnapMirror relationships supported after 9.9.1

### ISSUE THREAD

**Issue by zhimingCN** [NetAppDocs/ontap#789]
Page: [Convert a FlexVol volume SnapMirror relationship to a FlexGroup volume SnapMirror relationship](https://docs.netapp.com/us-en/ontap/flexgroup/convert-flexvol-snapmirror-relationship-task.html)

Hello Team,

Could anyone help to modify the document, cause after 9.9.1 fan-out is supported for flexgroup.

>Fan-out SnapMirror relationships are not supported for FlexGroup volumes. (Original)
to
>Fan-out SnapMirror relationships are not supported for FlexGroup volumes before ONTAP 9.9.1.

Considerations for creating SnapMirror cascade and fanout relationships for FlexGroups (01/27/2022)
https://docs.netapp.com/us-en/ontap/flexgroup/create-snapmirror-cascade-fanout-reference.html

Best regards
zhiming

**Comment by netapp-lenida** [comment]
Thanks for letting us know, Zhiming. We'll update the doc ASAP.

**Comment by netapp-lenida** [comment]
Thanks again. The topic has been updated:

The source FlexVol volume in the SnapMirror relationship must not be the source volume for multiple SnapMirror relationships.

Beginning with ONTAP 9.9.1, fanout SnapMirror relationships are supported for FlexGroup volumes. For more information, see
https://docs.netapp.com/us-en/ontap/flexgroup/create-snapmirror-cascade-fanout-reference.html#considerations-for-creating-cascading-relationships.
