### ISSUE TITLE
Correction: Create CGs with new "volumes" should say new "LUNs"

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#793]
Page: [Configure a single consistency group](https://docs.netapp.com/us-en/ontap/consistency-groups/configure-task.html)

The first sub-title: "Create a consistency group with new volumes" should read "Create...with new LUNs" since you cannot create a consistency group with new volumes...only new LUNs.

**Comment by netapp-ahibbard** [comment]
Thanks @tansley-netapp . We will get this fixed asap

**Comment by netapp-ahibbard** [comment]
Docs have been updated. Thanks again for reporting this.
