### ISSUE TITLE
We need to add the sync-snapmirror is not supported for FlexGroups yet. 

### ISSUE THREAD

**Issue by jsknair** [NetAppDocs/ontap#794]
Page: [Supported and unsupported configurations for FlexGroup volumes](https://docs.netapp.com/us-en/ontap/flexgroup/supported-unsupported-config-concept.html)

**Comment by netapp-ahibbard** [comment]
Thanks @jsknair . We will update ASAP

**Comment by netapp-lenida** [comment]
Hi @jsknair, thanks for pointing this out. The Synchronous SnapMirror documentation lists FlexGroup volumes as unsupported:
https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html#unsupported-features
However, I will add this to the unsupported data protection features section in this topic.

**Comment by netapp-lenida** [comment]
The topic has been updated to include Synchronous SnapMirror in the list of unsupported data protection features.
