### ISSUE TITLE
Update the information regarding batch upgrade LIF migrations for 9.8 and above.

### ISSUE THREAD

**Issue by netapp-norbertt** [NetAppDocs/ontap#796]
Page: [Automated nondisruptive ONTAP upgrade using the CLI](https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_cli.html)

Contains:

  When a set of nodes is upgraded during a batch upgrade, the LIFs are migrated to the HA partner nodes.

According to page: [Verifying the LIF failover configuration](https://docs.netapp.com/us-en/ontap/upgrade/task_verifying_the_lif_failover_configuration.html)

   In ONTAP 9.8 and later, if the batch method is used, LIFs are migrated to the other batch group.

Can you please correct this?

Thanks!

**Comment by netapp-aherbin** [comment]
Thanks you! We'll look into this ASAP!

**Comment by netapp-aherbin** [comment]
Thank you @netapp-norbertt!  I've updated the topic with the information for 9.7 and earlier and for 9.8 and later.
