### ISSUE TITLE
Manage licenses overview (cluster administrators only) dead link

### ISSUE THREAD

**Issue by kevinh-netapp** [NetAppDocs/ontap#799]
Page: [Update firmware](https://docs.netapp.com/us-en/ontap/task_admin_update_firmware.html)

The link with the text "[Manage licenses overview (cluster administrators only)](https://docs.netapp.com/system-admin/manage-licenses-concept.html)" seems to be dead.

**Comment by netapp-aherbin** [comment]
Thank you Kevin! We'll get this fixed ASAP!

**Comment by netapp-thomi** [comment]
17 FEB 2023:  Thom verified that this issue has been corrected in the external documentation repository.
