### ISSUE TITLE
Correct max network latency for ONTAP 9.12.1

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#802]
Page: [SVM data mobility overview](https://docs.netapp.com/us-en/ontap/svm-migrate/index.html)

Supported configurations table:

Last row: ONTAP 9.12.1 now supports up to 10ms of max network latency.

**Comment by netapp-lenida** [comment]
Thanks, Tony! I'll get this updated ASAO.

**Comment by tansley-netapp** [comment]
I just got an email from Andrew that it was fixed


Thanks,

Tony Ansley
ONTAP Technical Marketing Engineer
NetApp

Mobile:   512.565.8644
Email:     ***@***.******@***.***>


From: Lenida Vorwerk ***@***.***>
Date: Monday, February 6, 2023 at 3:10 PM
To: NetAppDocs/ontap ***@***.***>
Cc: Ansley, Tony ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/ontap] Correct max network latency for ONTAP 9.12.1 (Issue #802)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Thanks, Tony! I'll get this updated ASAO.

**Comment by tansley-netapp** [comment]
Nevermind…that was a different ask. Timing of notifications made me think it was the same.😊

Thanks,

Tony Ansley
ONTAP Technical Marketing Engineer
NetApp

Mobile:   512.565.8644
Email:     ***@***.******@***.***>


From: Ansley, Tony ***@***.***>
Date: Monday, February 6, 2023 at 3:10 PM
To: NetAppDocs/ontap ***@***.***>, NetAppDocs/ontap ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [NetAppDocs/ontap] Correct max network latency for ONTAP 9.12.1 (Issue #802)
I just got an email from Andrew that it was fixed


Thanks,

Tony Ansley
ONTAP Technical Marketing Engineer
NetApp

Mobile:   512.565.8644
Email:     ***@***.******@***.***>


From: Lenida Vorwerk ***@***.***>
Date: Monday, February 6, 2023 at 3:10 PM
To: NetAppDocs/ontap ***@***.***>
Cc: Ansley, Tony ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/ontap] Correct max network latency for ONTAP 9.12.1 (Issue #802)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.




Thanks, Tony! I'll get this updated ASAO.

**Comment by netapp-lenida** [comment]
Thanks again, Tony. The max network latency has been updated to 10ms for ONTAP 9.12.1.
