### ISSUE TITLE
Not sure why this is included in the SM-S "unsupported" lists

### ISSUE THREAD

**Issue by averageguyx** [NetAppDocs/ontap#804]
Page: [SnapMirror Synchronous disaster recovery basics](https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html)

The below "limitation" of SAN & NAS access to the same volume is not an SM-S limitation, but a general ONTAP restriction.  It is unsupported to have both SAN & NAS access to the same volume regardless of whether SM, SM-S or anything else is configured for the volume.

_Mixed SAN and NAS access
The primary volume of a SnapMirror Synchronous relationship can either serve NAS data or SAN data. Both SAN and NAS access from the primary volume of a SnapMirror Synchronous relationship is not supported._

**Comment by netapp-lenida** [comment]
Thanks for bringing this to our attention. We will make this clarification as soon as possible.

**Comment by netapp-lenida** [comment]
Thanks again for pointing this out. The bullet has been removed since it's not a restriction that's specific to SnapMirror Synchronous.
