### ISSUE TITLE
SM-BC deployment workflow needs to add a task to install Mediator CA certificate in ONTAP

### ISSUE THREAD

**Issue by netapp-jyhshing** [NetAppDocs/ontap#805]
Page: [High level deployment workflow](https://docs.netapp.com/us-en/ontap/smbc/smbc_install_high_level_deployment_workflow.html)

The Mediator cannot be initialized in ONTAP without proper CA certificate.
Please add a step to install the Mediator CA certificate before the step of "Initialize the ONTAP Mediator".

Here is the relevant information and example for performing the step.

1. Find the Mediator CA certificate from the Mediator Linux VM/host software installation location. 

cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config

[root@ontap-mediator server_config]# cat ca.crt
-----BEGIN CERTIFICATE-----
MIIFxTCCA62gAwIBAgIJANhtjk6HFCiOMA0GCSqGSIb3DQEBCwUAMHgxFTATBgNV
BAoMDE5ldEFwcCwgSW5jLjELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3Ju
…
p+jdg5bG61cxkuvbRm7ykFbih1b88/Sgu5XJg2KRhjdISF98I81N+Fo=
-----END CERTIFICATE-----

2. Add the Mediator CA certificate to ONTAP from ONTAP CLI. Paste the CA certificate obtained from the Mediator when prompted. 

aff-a250-b::> security certificate install -type server-ca -vserver aff-a250-b
 
Please enter Certificate: Press <Enter> when done
-----BEGIN CERTIFICATE-----                      
MIIFxTCCA62gAwIBAgIJANhtjk6HFCiOMA0GCSqGSIb3DQEBCwUAMHgxFTATBgNV
BAoMDE5ldEFwcCwgSW5jLjELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3Ju
…
p+jdg5bG61cxkuvbRm7ykFbih1b88/Sgu5XJg2KRhjdISF98I81N+Fo=
-----END CERTIFICATE-----
 
 
You should keep a copy of the CA-signed digital certificate for future reference.
 
The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: D86D8E4E8714288E
 
The certificate's generated name for reference: ONTAPMediatorCA
 
aff-a250-b::>

**Comment by netapp-ahibbard** [comment]
Thanks @netapp-jyhshing and sorry for the delayed response. The page has been updated to refer users to a more in-depth Mediator installation workflow which includes the information you've outlined: https://docs.netapp.com/us-en/ontap/mediator/verify-code-signature-task.html
