### ISSUE TITLE
add example output at the end?

### ISSUE THREAD

**Issue by RSGtheSSE** [NetAppDocs/ontap#812]
Page: [Return a FIPS drive or SED to unprotected mode](https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html)

Could we add some example output to the end of this document after running the maintenance mode rekey commands?  Not exactly sure what to expect and am having a hard time trying to determine whether or not the commands were successful.

**Comment by netapp-ahibbard** [comment]
Thanks @RSGtheSSE . We will update ASAP

**Comment by netapp-ahibbard** [comment]
Thanks for this request. The docs have been updated with sample output.
