### ISSUE TITLE
encrypt root volumes? yes or no?

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/ontap#814]
Page: [Configure NetApp Volume Encryption overview](https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html)

There is a bullet point on this page that says:
In addition to data volumes, NAE supports encryption of SVM root volumes and the MetroCluster metadata volume. NAE does not support encryption of the root volume.

So which is it?  Does "NAE supports encryption of SVM root volumes" or "NAE does not support encryption of the root volume"?  It can't be both!

**Comment by netapp-aherbin** [comment]
Thank you for letting us  know about this.  We'll look into it ASAP.

**Comment by netapp-ahibbard** [comment]
@NA-Scott - The statement is correct as is: NAE supports encryption of SVM root volumes; NAE does not support encryption of the root volume. The SVM root volume and the (node) root volume are different. There is more information about SVM root volumes and node root volumes on the [Volumes, qtrees, files, and LUNs concept page](https://docs.netapp.com/us-en/ontap/concepts/volumes-qtrees-files-luns-concept.html)
