### ISSUE TITLE
Remove the line which talk about FPolicy SDK. 

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#824]
Page: [What synchronous and asynchronous notifications are](https://docs.netapp.com/us-en/ontap/nas-audit/synchronous-asynchronous-notifications-concept.html)

This is a customer-facing document we shouldn't have a reference to FPolicy SDK as that is offered only to partners.

**Comment by netapp-ehoffman** [comment]
Thanks Nikhita! We'll update as soon as possible.
Ed

**Comment by Nikhita-13** [comment]
Do we have an update on when this would be addressed ?

**Comment by netapp-ehoffman** [comment]
Amanda, can you implement this in the next public merge?

**Comment by netapp-aherbin** [comment]
Done.
