### ISSUE TITLE
Apply retention period during manual Snapshot copy creation

### ISSUE THREAD

**Issue by jbnetapp** [NetAppDocs/ontap#825]
Page: [Lock a Snapshot copy for protection against ransomware attacks](https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html)

In section Apply retention period during manual Snapshot copy creation the option should be -snaplock-expiry-time and not -expiry-time.

**Comment by netapp-lenida** [comment]
Thanks again, Jerome. The topic has been updated with the correct command option: -snaplock-expiry-time.
