### ISSUE TITLE
MetroCluster support of NVMe-oF

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap#827]
Page: [All SAN Array configuration limits and support](https://docs.netapp.com/us-en/ontap/asa/support-limitations.html)

MetroCluster configurations *DO* support NVMe-oF - specifically NVMe/FCP as of 9.12.1. NVMe/TCP is still NOT supported.

**Comment by nlsntap** [comment]
I just noticed that further down the page support for NVMe/FCP on MC-IP is listed. So there is conflicting information on this page. The statement atz the bottom is correct, the one at the top needs some rewording, needs to point to the statement below or get removed.

**Comment by netapp-aherbin** [comment]
Thank you for pointing this out.  We'll look into it ASAP. 

Amanda

**Comment by netapp-aherbin** [comment]
The topic is updated.  Thanks again!
