### ISSUE TITLE
Add S3 GCP support for Cloud Volumes ONTAP

### ISSUE THREAD

**Issue by netapp-driley** [NetAppDocs/ontap#828]
Page: [ONTAP version support for S3 object storage](https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html)

Hi - Can you please add S3 GCP support under the S3 support with Cloud Volumes ONTAP table (see below)? The S3 GCP support was [added to Cloud Volumes ONTAP in November](https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html#ontap-s3-license-in-gcp).
![image](https://user-images.githubusercontent.com/18422994/221894251-2e874020-5f85-4ed5-a442-a11dbffc8625.png)

**Comment by netapp-ehoffman** [comment]
From Don: Just to follow up on this item, it looks like one of the ONTAP S3 pages was updated to reflect the Google S3 support (https://docs.netapp.com/us-en/ontap/s3-config/ontap-s3-interoperability-concept.html). We just need to also update [the ONTAP version support for S3 object storage page](https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html).

The engineer for this item was Galina Tseitlin and the product manager is Tamir Berg. George Buslovitch escalated the item and is requesting the change. 

If you need anything else, please let me know.
