### ISSUE TITLE
The description for each page should be reviewed

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#83]
Page: [ONTAP System Manager docs](https://docs.netapp.com/us-en/ontap/index.html)

Search results show that many pages have the following for a page description: <>

Others don't start with a capital letter, while others don't end in a period.

![image](https://user-images.githubusercontent.com/18287750/77103982-9ff6ae00-69f1-11ea-9448-19f3b6c0899e.png)

**Comment by netapp-aherbin** [comment]
Ben thank you for your feedback.  I've check each topic in the repo and added summaries where needed.
