### ISSUE TITLE
Copy DACL warning from "Configure and apply audit policies..." to this page

### ISSUE THREAD

**Issue by netapp-adlove** [NetAppDocs/ontap#830]
Page: [Apply security policies](https://docs.netapp.com/us-en/ontap/smb-admin/apply-security-policies-audit-task.html)

Hello Doc Team,

The warning below should be included on the apply security policies page:

"When an audit policy and associated SACLs are applied, any existing  DACLs are overwritten. You should review existing security policies  before creating and applying new ones."

Users should be aware that applying "security policies" will wipe any existing DACLs from the affected files and folders. The warning does currently exist in our documents at the link below, however due to the online docs structure, the warning is hidden multiple levels/pages above where the warning is most needed; when policies are about to be applied.

-- | --

This warning comes from the "Configure and apply audit policies..." doc page located here:
https://docs.netapp.com/us-en/ontap/smb-admin/configure-apply-audit-policies-ntfs-files-folders-task.html

-- | --

Additionally, our current page has a typo. Please add a space to "SVMsis" so it reads "SVMs is"

"Applying an audit policy to SVMsis the last step in creating and applying NTFS ACLs to files or folders."

**Comment by netapp-aherbin** [comment]
Thank you.  We will look into it and respond ASAP.

**Comment by netapp-mdavidson** [comment]
Updates to page complete. Closing out.
