### ISSUE TITLE
Apply DACL warning to this page

### ISSUE THREAD

**Issue by netapp-adlove** [NetAppDocs/ontap#831]
Page: [Apply security policies](https://docs.netapp.com/us-en/ontap/smb-admin/apply-security-policies-file-task.html)

Hello Doc Team,

The warning below should be included on the apply security policies page:

"When a security policy and its associated DACLs are applied, any existing DACLs are overwritten. You should review existing security policies before creating and applying new ones."

Users should be aware that applying "security policies" will wipe any existing DACLs from the affected files and folders. This means the command replaces existing DACLs with the new ones defined in the security policy/security descriptor.

**Comment by netapp-mdavidson** [comment]
Updates to page complete. Closing out.
