### ISSUE TITLE
Link Directly to ONTAP 9 Download page

### ISSUE THREAD

**Issue by kevinh-netapp** [NetAppDocs/ontap#833]
Page: [Download and install the ONTAP software image](https://docs.netapp.com/us-en/ontap/upgrade/task_download_and_install_ontap_software_image.html)

Instead of just linking to the Software Downloads page of the support site, can we link directly to the ONTAP 9 download page?  https://mysupport.netapp.com/site/products/all/details/ontap9/downloads-tab

**Comment by netapp-aherbin** [comment]
Hi Kevin,

Yes we can do this.

I'll update ASAP.

Amanda

**Comment by kevinh-netapp** [comment]
Thank you Amanda!

**Comment by netapp-aherbin** [comment]
The link is updated and posted.  Thanks again.
