### ISSUE TITLE
Clarify break step as optional

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#835]
Page: [Delete a volume replication relationship](https://docs.netapp.com/us-en/ontap/data-protection/delete-volume-replication-relationship-task.html)

It's not necessary to break a SnapMirror unless you need the volume read/write. Can we clarify this here?
Perhaps:
2. (Optional) Break the replication relationship if you require the destination volume to be a read/write volume. This step is not needed if you plan to delete the destination volume or if you don't need the destination volume read/write.

snapmirror break -source-path SVM:volume|cluster://SVM/volume, …​ -destination-path SVM:volume|cluster://SVM/volume, …​

cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst

**Comment by netapp-lenida** [comment]
Thanks for the suggestion, Joey. I'll update the topic ASAP.

**Comment by netapp-lenida** [comment]
Thanks for the feedback, Joey. I've updated the topic to make this step optional.
