### ISSUE TITLE
Topic needs corrections/clarifications with CLI due to ONTAP version changes

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#837]
Page: [Mixed version requirements](https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html)

As background info...
With ONTAP 9.4+, we changed the (priv: advanced) CLI abruptly:
cluster unjoin -> cluster remove-node  
Burt 1107597 [KB.0 CSI Setup Simplicity] implement cluster remove-node command 

ONTAP 9.2 marked “cluster join” as deprecated. In ONTAP 9.4, “cluster join” was made into a hidden alias.
cluster join -> cluster add-node
Burt 1111073 [KB.0 CSI Setup Simplicity] Infrastructure for cluster add node

Typo: -skip-lastlow-version-node check should be -skip-last-low-version-node-check

Suggested text (and changed "unjoin" to "remove")

In this case, you should upgrade the nodes that do support the later version of ONTAP, then remove the nodes that do not support the version of ONTAP you are upgrading to using the advanced privilege cluster remove-node -skip-last-low-version-node-check command.

Suggested handling of text by general changing "join" -> "add". Remove old "join" command.

Beginning with ONTAP 9.3, by default, you cannot add new nodes to the cluster that are running a version of ONTAP that is different from the version running on the existing nodes.

You might also need to enter a mixed version state for a technical refresh or an interrupted upgrade. In such cases you can override ONTAP default behavior and add nodes of a different version using the following advanced privilege command:

-     cluster add-node -allow-mixed-version-join

**Comment by netapp-aherbin** [comment]
Thanks Andris,

I'll work on getting this updated as soon as possible.

Amanda

**Comment by andris-ntap** [comment]
Looks good... Ship it!
