### ISSUE TITLE
panicked takeover has different behavior for LIF migration

### ISSUE THREAD

**Issue by zhuolin-shen** [NetAppDocs/ontap#838]
Page: [How automatic takeover and giveback works](https://docs.netapp.com/us-en/ontap/high-availability/ha_how_automatic_takeover_and_giveback_works.html)

"What happens during takeover" section only describes user-initiated takeover.
Customer cannot refer to it for a panicked takeover scenario, because LIF migration will not occur before takeover begins but after  takeover completes which means over 60 seconds or more service outage.
(Related burt# 1127799)
Could you please add the panicked takeover scenario along with LIF migration's difference to the document?

**Comment by netapp-aherbin** [comment]
Moving to Jira 1171 for internal tracking.
@zhuolin-shen I will keep you updated via email on progress.
