### ISSUE TITLE
Clarification of "Data protection for S3 NAS buckets"

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#839]
Page: [S3 multiprotocol overview](https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html)

Can we add a note of some kind that clearly states that SnapMirror Synchronous is not compatible with S3 multiprotocol?

Maybe state that the only supported SnapMirror replication is SVM-DR (which I think is intimated by the link at the end of this section, but I am not sure if that is clear.

Also, in the section "How S3 multiprotocol works", third paragraph, last sentence should read "The credentials of the SMB/NFS **_users_** will be used..." It currently sase "uses".

**Comment by netapp-aherbin** [comment]
Thank you.  We will look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks for the suggestion, Tony. I'm taking a look.

**Comment by tansley-netapp** [comment]
Lenida,

Engineering is asking that this clarification be provided…so not sure how much of a “suggestion” it is 😃 😃

Thanks for the quick response. Let me know if you need anything from me.

Thanks,

Tony Ansley
ONTAP Technical Marketing Engineer
NetApp

Mobile:   512.565.8644
Email:     ***@***.******@***.***>


From: Lenida Vorwerk ***@***.***>
Date: Monday, March 13, 2023 at 9:54 AM
To: NetAppDocs/ontap ***@***.***>
Cc: Ansley, Tony ***@***.***>, Author ***@***.***>
Subject: Re: [NetAppDocs/ontap] Clarification of "Data protection for S3 NAS buckets" (Issue #839)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Thanks for the suggestion, Tony. I'm taking a look.

**Comment by netapp-lenida** [comment]
Thanks again, Tony. The topic has been updated.
