### ISSUE TITLE
Remove link to McAfee guide 

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#840]
Page: [Antivirus configuration overview](https://docs.netapp.com/us-en/ontap/antivirus/index.html)
The McAfee guide is pointing to a version that talks about their old product which is now EOL. Please remove the link and replace that with the following - Trellix (formerly McAfee), review the partner website for documentation: https://docs.trellix.com/bundle?labelkey=prod-endpoint-security-storage-protection&labelkey=prod-endpoint-security-storage-protection-v2-3-x&labelkey=prod-endpoint-security-storage-protection-v2-2-x&labelkey=prod-endpoint-security-storage-protection-v2-1-x&labelkey=prod-endpoint-security-storage-protection-v2-0-x

**Comment by netapp-aherbin** [comment]
@Nikhita-13 There is no link to the McAfee guide on this page.  There is a link to the NetApp TR for McAfee.  Are you referring to a link inside the TR?

**Comment by netapp-ehoffman** [comment]
I spoke with Nikhita this morning, so can advise: we should delete this item from the Related Info section:
[NetApp Technical Report 4286: Antivirus Solution for Clustered Data ONTAP McAfee](http://www.netapp.com/us/media/tr-4286.pdf)

and add a new one:
[Trellix (formerly McAfee) Endpoint Security Storage Protection]
(hhttps://docs.trellix.com/bundle?labelkey=prod-endpoint-security-storage-protection&labelkey=prod-endpoint-security-storage-protection-v2-3-x&labelkey=prod-endpoint-security-storage-protection-v2-2-x&labelkey=prod-endpoint-security-storage-protection-v2-1-x&labelkey=prod-endpoint-security-storage-protection-v2-0-x)

**Comment by Nikhita-13** [comment]
What Ed said is correct. But the link in his comment has an error: the correct link to the Trellix website is -

https://docs.trellix.com/bundle?labelkey=prod-endpoint-security-storage-protection&labelkey=prod-endpoint-security-storage-protection-v2-3-x&labelkey=prod-endpoint-security-storage-protection-v2-2-x&labelkey=prod-endpoint-security-storage-protection-v2-1-x&labelkey=prod-endpoint-security-storage-protection-v2-0-x
