### ISSUE TITLE
Broken link in the document

### ISSUE THREAD

**Issue by debabrac** [NetAppDocs/ontap#842]
Page: [SnapMirror Cloud backups to object storage](https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html)

In the below section
Multiple 3rd party backup partners who offer support for SnapMirror Cloud replication. Participating vendors are available on the [NetApp blog](https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html#https://www.netapp.com/blog/new-backup-architecture-snapdiff-v3/).

The link is redirecting to open the same page NetApp Blog. Please check

**Comment by netapp-ahibbard** [comment]
Thanks for reporting this @debabrac . We will have this fixed asap.

**Comment by netapp-ahibbard** [comment]
The link has been fixed to direct to the correct location. Thanks again for reporting this
