### ISSUE TITLE
Document motd escape codes

### ISSUE THREAD

**Issue by rscheff** [NetAppDocs/ontap#846]
Page: [Manage the MOTD](https://docs.netapp.com/us-en/ontap/system-admin/manage-motd-reference.html)

The example of the motd text gives some hints, that special escape codes can be used to print infomation around the system and session, as well as last logins and currently logged on session.

however, our documentation doesn't provide a comprehensive list of what these options are (or point to some external documentation, where this would be listed).

Someone has already found these possibilities:
https://community.netapp.com/t5/ONTAP-Discussions/How-to-configure-dynamic-content-in-MOTD-banner/td-p/164659

\n=<node-name>, 
\b=empty line, 
\d=<date>, 
\f=0, 
\l=/dev/pts/1, 
\m=<processor-architecture>, , 
\o=<domain-name>, 
\r=<ontap-version>,
\s=Data ONTAP, 
\t=23:20:54 UTC, 
\u=<some unknown number>, 
\v=<netapp-version-and-date>

\L=last login time, 
\N=logged in as <who>, 
\C=<cluster-management-name>, 
\I=<cluster-management-IP>, 
\O=<domain-name>, 
\U=number-of-users-currently-logged-in, 
\W=<node name and logged in time and IP address of user

**Comment by netapp-aherbin** [comment]
Thank you! We'll look into this.

**Comment by netapp-aherbin** [comment]
@rscheff the following list is provided in the **[security login motd modify](https://docs.netapp.com/us-en/ontap-cli-9131//security-login-motd-modify.html#parameters)** command page.  All the options you listed above are here except for \f.  

I'll add a link to the command page for reference and reach out to ENG regarding the \f option.  Are you looking for additional information, or does this cover it?

The message may contain dynamically generated content using the following escape sequences:

\\ - A single backlash character.
\b - No output: supported for compatibility with Linux only.
\C - Cluster name.
\d - Current date as set on the login node.
\t - Current time as set on the login node.
\I - Incoming LIF IP address (prints 'console' for a console login).
\l - Login device name (prints 'console' for a console login).
\L - Last login for the user on any node in the cluster.
\m - Machine architecture.
\n - Node or data Vserver name.
\N - Name of user logging in.
\o - Same as \O. Provided for Linux compatibility.
\O - DNS domain name of the node. Note that the output is dependent on the network configuration and may be empty.
\r - Software release number.
\s - Operating system name.
\u - Number of active clustershell sessions on the local node. For the cluster admin: all clustershell users. For the data Vserver admin: only active sessions for that data Vserver.
\U - Same as \u, but has 'user' or 'users' appended.
\v - Effective cluster version string.
\W - Active sessions across the cluster for the user logging in ('who').
