### ISSUE TITLE
Support for Flash Pool incorrect

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#847]
Page: [SVM data mobility overview](https://docs.netapp.com/us-en/ontap/svm-migrate/index.html)

With the added support as of ONTAP 9.12.1 for "FAS Hybrid" arrays (aggregates), the Unsupported Features list at bottom of the page needs to be updated to remove "Flash Pool" from the list.

Tony Ansley

**Comment by netapp-lenida** [comment]
Flash Pool has been removed from the list of unsupported features. Thank you!
