### ISSUE TITLE
Add new step 2. 

### ISSUE THREAD

**Issue by lacem** [NetAppDocs/ontap#849]
Page: [Remove nodes from the cluster](https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html)

Suggesting to add a line about epsilon before marking a node ineligible. 

This can be step 2 and then just bump the remaining steps down:

-A node that holds epsilon cannot be marked as ineligible and should be modified first before setting eligibility 

The command to do this is:
::> set advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: Y
::*> cluster modify -node <NODE> -eligibility false

**Comment by netapp-aherbin** [comment]
Thanks! We'll look into ASAP.

@lacem are you internal to NetApp?

**Comment by lacem** [comment]
Yes I am. I work in customer support.
________________________________

**Comment by netapp-aherbin** [comment]
@lacem I've added steps 2/2a to the topic.  Please verify if the issue can be closed.

Thanks!
Amanda

**Comment by netapp-aherbin** [comment]
@lacem closing this issue.  Please let me know if any further updates are needed.  Thank you
