### ISSUE TITLE
ONTAP 9.13.0 information is missing to be used with Cloud Volumes ONTAP

### ISSUE THREAD

**Issue by anee04** [NetAppDocs/ontap#851]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

**Comment by netapp-lenida** [comment]
Thanks @anee04. The ONTAP 9.13.0 information has been added to the Unified Replication table in this topic.

**Comment by anee04** [comment]
Thank you Lenida for the quick turn-around!
