### ISSUE TITLE
option -data-services data-s3-server - is this needed during SVM create.

### ISSUE THREAD

**Issue by anee04** [NetAppDocs/ontap#852]
Page: [Create an SVM for S3](https://docs.netapp.com/us-en/ontap/s3-config/create-svm-s3-task.html)

-data-services data-s3-server option - is this needed during SVM create ?

Reference KB:

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_set_up_ONTAP_S3_as_object_store_for_FabricPool_on_remote_cluster_using_HTTPs

step 4

Reason:

Customer had an existing SVM and did not create a service policy with data services enabled and was trying to add a bucket from system manager as system manager lists the SVM and gets error s3 service needs to be configured which is valid.

**Comment by netapp-ehoffman** [comment]
@anee04 , we'll be opening a Jira issue to track this feedback. If you have a NetApp ID, please share it so we can include you on that issue.

**Comment by netapp-ehoffman** [comment]
This issue is now being tracked in Jira:
https://jira.ngage.netapp.com/browse/ONTAPDOC-957

**Comment by anee04** [comment]
Netapp id = anee@netapp.com

Thanks for the JIRA link, added myself to JIRA watchers list.

**Comment by netapp-ehoffman** [comment]
Closing this issue, tracking in Jira.
