### ISSUE TITLE
Need to incorporate the lack of support for SMB change notify

### ISSUE THREAD

**Issue by mpittman-netapp** [NetAppDocs/ontap#853]
Page: [Supported and unsupported features for FlexCache volumes](https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html)

I was not sure of the best way to accomplish this, so I figured I would just submit this feedback and we can talk through it, if needed.  Please let me know your thoughts.

**Comment by netapp-ehoffman** [comment]
Thanks for the feedback. Please share your NTAP short name and we'll follow up via email to begin discussions.
Ed

**Comment by netapp-lenida** [comment]
Thanks for reaching out, Michael. I'll email you and we can discuss more how to update this.

**Comment by netapp-lenida** [comment]
The topic has been updated. Thanks again for bringing this to our attention.
