### ISSUE TITLE
dashboard under storage -> Storage VMs

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/ontap#856]
Page: [Monitor capacity in System Manager](https://docs.netapp.com/us-en/ontap/task_admin_monitor_capacity_in_sm.html)

Team,

 there is another dashboard that talks about Capacity. 
 i.e storage --> Storage VMs.  can we get a clarity of how the capacity information is being presented here and how is this different from the one we see under "Dashboard"?

**Comment by sabarig84** [comment]
any update on this pls?

**Comment by netapp-thomi** [comment]
Additional information was added to the topic to explain the labels in the capacity charts:   Refer to 
[Capacity measurement terms](https://docs.netapp.com/us-en/ontap/concepts/capacity-measurements-in-sm-concept.html#cap-measurement-terms)
