### ISSUE TITLE
I would like to get the following section on this page revamped 'Best practices and recommendations when setting up FPolicy'

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#860]
Page: [Requirements, considerations, and best practices for configuring FPolicy](https://docs.netapp.com/us-en/ontap/nas-audit/requirements-best-practices-fpolicy-concept.html)

I have referenced the word doc below consisting of the draft content that I would like to review and publish under this section 'Best practices and recommendations when setting up FPolicy'

https://netapp-my.sharepoint.com/:w:/p/nikhitag/EV42wgakspJKokp4x5v0x1gB6xqymcTaI9DP2SpM76lhfA?e=d6JDah

**Comment by netapp-aherbin** [comment]
@netapp-pcarriga please reassign this as appropriate.

**Comment by Nikhita-13** [comment]
Hello Team, 

By when we would incorporate these best practices in the documentation?

**Comment by netapp-pcarriga** [comment]
Hi @Nikhita-13 - The updates are in progress and I will prioritize publication ASAP.

**Comment by netapp-pcarriga** [comment]
Hi @Nikhita-13 - These updates are now published. Thanks.
