### ISSUE TITLE
Best Practice for Mediator

### ISSUE THREAD

**Issue by kadaNtap** [NetAppDocs/ontap#862]
Page: [Summary of deployment best practices](https://docs.netapp.com/us-en/ontap/smbc/smbc_plan_summary_of_deployment_best_practices.html)

Under Mediator section for best practices, we need to add the following bullet point

- ONTAP Mediator must be installed in a third failure domain, separate from the two ONTAP clusters.

**Comment by netapp-ahibbard** [comment]
Thanks @kadaNtap - this has been updated: https://docs.netapp.com/us-en/ontap/smbc/smbc_plan_prerequisites.html
