### ISSUE TITLE
small edit on deleting volumes and aggregrates - root volumes and aggregates can't be deleted...

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap#863]
Maybe we can just add a clarifying note that Node Root Volumes and Aggregates can't be deleted.   On the bullet points in the "Before you begin" section could something like this....

All non root-volumes have been [moved] from aggregates owned by the node.

All non root-aggregates have been [deleted] from the node.

Page: [Remove nodes from the cluster](https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html)

**Comment by netapp-aherbin** [comment]
Thanks Eric,

I'll work with  you to get this updated.

Amanda

**Comment by netapp-aherbin** [comment]
@ericd-netapp are you suggesting that we update the following 2 bullets:

- All volumes have been moved or deleted from the aggregates owned by the node -> All non-root volumes have been moved from aggregates owned by the node.
- All aggregates have been deleted from the node -> All non-root aggregates have been deleted from the node

Amanda

**Comment by ericd-netapp** [comment]
Looks good!

-Eric
323.388.7727

**Comment by netapp-aherbin** [comment]
Updated posted.  Thank you.
