### ISSUE TITLE
Incorrect command in example

### ISSUE THREAD

**Issue by mark-MetroSys** [NetAppDocs/ontap#864]
Page: [Stop or start the CIFS server](https://docs.netapp.com/us-en/ontap/smb-admin/stop-start-server-task.html)

Example omitted cifs from the start command.

Currently reads: "cluster1::> vserver start -vserver vs1"

Should read "cluster1::> vserver cifs start -vserver vs1"

**Comment by netapp-aherbin** [comment]
Thanks Mark. 

We'll get this updated ASAP.

Amanda

**Comment by netapp-aherbin** [comment]
Updated.  Thank you.
