### ISSUE TITLE
Different information for direct multi-hop.

### ISSUE THREAD

**Issue by cuiguoxing** [NetAppDocs/ontap#866]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

For ONTAP9.1 upgrade to 9.12. 
- 9.7 → 9.9.1
- 9.9.1 → 9.12.1

But on ONTAP 9.7 upgrade to 9.12 shows
direct multi-hop (requires images for 9.8 & 9.12.1)

This will give people a wrong image, such as upgrade from 9.1 unable to use direct multi-hop.

Can you make it same information?

Thanks,

Allen

**Comment by netapp-aherbin** [comment]
Thanks I will look into this update ASAP!

**Comment by netapp-aherbin** [comment]
Thanks Allen.  We've updated the 9.1 paths to go directly from 9.7 to 9.12.1 with direct multi-hop.
