### ISSUE TITLE
page does not mention disabling mount root only which leads to failures.

### ISSUE THREAD

**Issue by markb1netapp** [NetAppDocs/ontap#868]
Page: [Enable access for Windows NFS clients](https://docs.netapp.com/us-en/ontap/nfs-admin/enable-access-windows-nfs-clients-task.html)

Take a look at the following KB article:
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Mount_failure_with_Network_Error_53_on_Native_Windows_NFS_clients

Note that clients are unable to mount due to windows mounting NFS from non privileged ports (>1024).

So this doc needs to include disabling mount root only
::> vserver nfs modify -vserver <vserver_name> -mount-rootonly disabled

**Comment by netapp-barbe** [comment]
Mairead, please work on this GH issue

**Comment by netapp-maireadn** [comment]
HI Barb, will do. Thanks, Mairead

**Comment by netapp-maireadn** [comment]
in progress

**Comment by netapp-maireadn** [comment]
Thanks @markb1netapp for taking the time to provide feedback.
I've updated the documentation and it should be live in the next 24 hours.
I modified the command to this:
vserver nfs modify -vserver svm_name -v3-ms-dos-client enabled -mount-rootonly disabled
Mairead

**Comment by netapp-maireadn** [comment]
Closing this GitHub issue now
