### ISSUE TITLE
Missing dns-zone name in example

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#870]
Page: [Create a DNS load balancing zone](https://docs.netapp.com/us-en/ontap/networking/create_a_dns_load_balancing_zone.html)

The command example appears to be missing the dns-zone name (storage.company.com)?

The following example demonstrates how to create a DNS load balancing zone named storage.company.com while creating the LIF lif1:

network interface create -vserver vs0 -lif lif1 -home-node node1
-home-port e0c -address 192.0.2.129 -netmask 255.255.255.128 -dns-zone  <<<<<<?

**Comment by netapp-aherbin** [comment]
Thanks, we'll get this updated ASAP.

**Comment by netapp-aherbin** [comment]
Updated.  Thank you.
