### ISSUE TITLE
Remove the comments about having to manually enable AES "After the Destination Becomes Read-Write)

### ISSUE THREAD

**Issue by jpick-66** [NetAppDocs/ontap#873]
Page: [Enable or disable AES encryption for Kerberos-based communication](https://docs.netapp.com/us-en/ontap/smb-admin/enable-disable-aes-encryption-kerberos-task.html)

About this task
Beginning with ONTAP 9.12.1, AES encryption is enabled and disabled using the -advertised-enc-types option, which allows you to specify the encryption types advertised to the AD KDC. The default setting is rc4 and des, but when an AES type is specified, AES encryption is enabled. You can also use the option to explicitly disable the weaker RC4 and DES encryption types. In earlier ONTAP releases, you must use the -is-aes-encryption-enabled option to enable and disable AES encryption, and encryption types cannot be specified.

To enhance security, the storage virtual machine (SVM) changes its machine account password in the AD each time the AES security option is modified. Changing the password might require administrative AD credentials for the organizational unit (OU) that contains the machine account.

If an SVM is configured as a disaster recovery destination where the identity is not preserved (the -identity-preserve option is set to false in the SnapMirror configuration), the non-default SMB server security settings are not replicated to the destination. If you have enabled AES encryption on the source SVM, you must manually enable it on the destination SVM.

**Comment by netapp-ahibbard** [comment]
Thanks for opening this. I'll look into it ASAP. If you have a NetApp ID, please let us know your short name in case we need to reach out with any questions.

**Comment by jpick-66** [comment]
Hello Andrew.  My contact information is: ***@***.******@***.***>

Thx for looking into this.

-jon

**Comment by netapp-ahibbard** [comment]
The topic has been updated
