### ISSUE TITLE
can we add some note stated that this procedure is "Non-Disruptive"?

### ISSUE THREAD

**Issue by ericd-netapp** [NetAppDocs/ontap#875]
Page: [Assign a data authentication key to a FIPS drive or SED (external key management)](https://docs.netapp.com/us-en/ontap/encryption-at-rest/assign-authentication-keys-seds-external-task.html)

**Comment by ericd-netapp** [comment]
ALso, cna it be changed here too:  https://docs.netapp.com/us-en/ontap/encryption-at-rest/assign-fips-140-2-authentication-key-task.html

**Comment by netapp-ahibbard** [comment]
Thanks @ericd-netapp . The docs have been updated
