### ISSUE TITLE
Typo / ERROR

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap#877]
Page: [RDMA overview](https://docs.netapp.com/us-en/ontap/concepts/rdma-concept.html)

"you may want to take advantage of ONTAP’s _Read_ Direct Memory Access (RDMA) offerings"

should be:

"you may want to take advantage of ONTAP’s **Remote** Direct Memory Access (RDMA) offerings"

**Comment by netapp-ahibbard** [comment]
Thanks @SPGoetze . This has been fixed.
