### ISSUE TITLE
Suggestion for enhancement

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap#878]
Page: [RDMA overview](https://docs.netapp.com/us-en/ontap/concepts/rdma-concept.html)

Since you **do** mention the back-end (Cluster Interconnect), why not also mention the RoCEv2 based connectivity between

- Controllers and NVMe-Shelves
- DR-Partners in a MCC-IP

After all, RoCE means RDMA over Converged Ethernet...

**Comment by netapp-ahibbard** [comment]
Thanks for the suggestions. The docs have been updated.
