### ISSUE TITLE
The lead paragraph includes hard returns

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#88]
Page: [Encrypt stored data using self-encrypting drives](https://docs.netapp.com/us-en/ontap/task_security_encrypt_stored_data_hw.html)

**Comment by netapp-aherbin** [comment]
Ben thanks for your feedback.  The hard returns have been removed.

**Comment by netapp-aherbin** [comment]
Ben thanks for your feedback.  The hard returns have been removed.
