### ISSUE TITLE
erroneous listing of unsupported command for MAV

### ISSUE THREAD

**Issue by valuial** [NetAppDocs/ontap#880]
Page: [Multi-admin verification overview](https://docs.netapp.com/us-en/ontap/multi-admin-verify/index.html)

Hi Team,

I have a partner trying to set up MAV at their customers, who has a "last-resort" system using snaplock. They want to lock down any snaplock modifications using MAV so are trying to lock the command "volume snaplock modify", which is listed on the overview section of the [multi-admin-verify](https://docs.netapp.com/us-en/ontap/multi-admin-verify/index.html#how-multi-admin-verification-works) documentation.

When they tried to configure the command they got an ONTAP error message stating that the command is not supported with MAV. I was able to replicate this in Labondemand for both ONTAP 9.11.1 and ONTAP 9.12.1.

In the [Manage protected operation rules](https://docs.netapp.com/us-en/ontap/multi-admin-verify/manage-rules-task.html) section, there is a second table with supported commands. The same as in the overview section with the exception of the "volume snaplock modify" command.

I highly suspect the second table in the Manage protected operation rules section is the correct one.
Please correct the overview section table to only include actually supported commands.

Thank you.

Freundliche Grüße/ Kind Regards

Boris Moddemann
Technical Engineer
NetApp Partner Solution Center EMEA

**Comment by netapp-aherbin** [comment]
The table has been updated.  Thanks again.

**Comment by netapp-lenida** [comment]
I'll fix the topic to specify which release supports this command. Support for the "volume snaplock modify" command was added in ONTAP 9.13.1.
