### ISSUE TITLE
SVM-DR interop table does not include cloud releases

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#882]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

The matrix posted here and what we document in our internal Field Portal docs are not the same.  Can we update the public docs to reflect the table in this PPTX: https://fieldportal.netapp.com/content/729273

**Comment by netapp-aherbin** [comment]
Thank you! We will look into this ASAP.

**Comment by netapp-lenida** [comment]
Thanks for your help, Tony. The tables should include cloud releases now.
