### ISSUE TITLE
FAS22xx is obsolete - remove related text

### ISSUE THREAD

**Issue by andris-ntap** [NetAppDocs/ontap#883]
Page: [Network cabling guidelines](https://docs.netapp.com/us-en/ontap/networking/network_cabling_guidelines.html)

FAS22xx is obsolete. Remove the **bold text** shown below:

There should always be two or more cluster connections to each node. **, but nodes on FAS22xx systems can be configured with a single 10-GbE cluster port.**

Extra bonus points for removing similar verbiage in other areas of the doc set.

**Comment by netapp-ehoffman** [comment]
Let's transition this to a Jira issue for further discussion.

**Comment by netapp-aherbin** [comment]
Done. Moved to Issue 1007 for tracking and internal discussion.
