### ISSUE TITLE
Document searchability

### ISSUE THREAD

**Issue by DocPoulson** [NetAppDocs/ontap#887]
Page: [Verify enabled SMB versions](https://docs.netapp.com/us-en/ontap/smb-config/verify-enabled-versions-task.html)

To improve searchability of this page, add the following question to this page: "can SMB1 still be enabled in ONTAP 9?"

**Comment by netapp-aherbin** [comment]
@DocPoulson thank you for your feedback.  We are investigating how to improve the searchability of this content.  We are moving this to an internal issue (ONTAPDOC-1170) for tracking.  Are you internal to NetApp?

**Comment by netapp-aherbin** [comment]
Tracking internally - closing
