### ISSUE TITLE
NFS Trunking support missing from Release notes

### ISSUE THREAD

**Issue by Sawall10** [NetAppDocs/ontap#889]
Page: [ONTAP release notes](https://docs.netapp.com/us-en/ontap/release-notes.html)
https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508

This page links to ONTAP® 9 Release Notes (April 11, 2023).

I was expecting to see a mention of NFS Session Trunking support in the release notes for 9.12.1. Can you please advise?

**Comment by netapp-ehoffman** [comment]
Hi Shane, thanks for reaching out. Can you let us know if you are a NetApp employee? (And if so, please share your short name.)
-Ed

**Comment by Sawall10** [comment]
I am

***@***.***


Shane Wall



NetApp

+61 416 105 711 Mobile Phone

***@***.******@***.***>

________________________________

**Comment by netapp-ehoffman** [comment]
Addressed via internal communication
