### ISSUE TITLE
Where did the section about fabricpool go?

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#890]
Page: [Lock a Snapshot copy for protection against ransomware attacks](https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html)

This page used to have a section about fabricpool interaction, why was that removed?

**Comment by netapp-lenida** [comment]
Hi Joey, I'm replying to you over email.

**Comment by netapp-lenida** [comment]
Followed up over email.
