### ISSUE TITLE
Additional Navigation Needed

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/ontap#893]
Page: [Upgrade ONTAP overview](https://docs.netapp.com/us-en/ontap/upgrade/index.html)

Micro-rant... sorry.

I have an iPhone 13 mini, I do not have (easy) access to the navigation pane on the left (visible on a desktop/large screen).
Would be really helpful to have a link at the bottom that would lead me to the "next" page (similarly, a link to the "back" page) would make the site and specifically this page alot more useful.

This is the upgrade page, looking to figure out what my next steps needs to be.

Thanks for listening.
Respectfully,

**Comment by netapp-aherbin** [comment]
Thank you for the feedback.  

@ntap-bmegan can you advise on this?

**Comment by ntap-bmegan** [comment]
I've logged this request. 

As it's not something that can be implemented by the ONTAP content team - this requires changes to the publishing system - I'm closing the issue. (Moving the issue to the private dev repo would render it unreachable by @louvipi.)
