### ISSUE TITLE
What is VDR Setup

### ISSUE THREAD

**Issue by rbaetz** [NetAppDocs/ontap#895]
Page: [Features that do not support volume rehost](https://docs.netapp.com/us-en/ontap/volumes/features-supported-volume-rehost-concept.html)

You do not define or explain what VDR is and this acronym is not used anywhere else in docs.netapp.com.

Also, please include SVM_DR if it is part of the not supported features or give how-to page for SVM_DR snapmirror.

**Comment by netapp-aherbin** [comment]
Thank you for the feedback.  We will address this as soon as possible.

**Comment by netapp-lenida** [comment]
Hi Robert, thanks for bringing this to our attention. After researching, it appears that VDR stands for vserver DR. I will update the topic with the correct terminology, SVM DR.

**Comment by netapp-lenida** [comment]
Hi Robert, thanks for bringing this to our attention. After researching, it appears that VDR stands for vserver DR. I will update the topic with the correct terminology, SVM DR.

**Comment by netapp-lenida** [comment]
VDR has been chanced to SVM DR. Thanks again for bringing this to our attention.
