### ISSUE TITLE
Section "Windows NFSv3 clients do not support the network status monitor (NSM) protocol" obsolete

### ISSUE THREAD

**Issue by ReneMeier** [NetAppDocs/ontap#896]
Page: [Enable access for Windows NFS clients](https://docs.netapp.com/us-en/ontap/nfs-admin/enable-access-windows-nfs-clients-task.html)

Based on the article "Network File System overview" at https://learn.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview in section "nfs-version-3-continuous-availability" the block mentionend in the titel is obsolete.

**Comment by netapp-aherbin** [comment]
@ReneMeier thank you for the feedback.

Could you provide more clarity on what you've identified as obsolete?  I don't see a reference to "nfs-version-3-continuous-availability" in the page or the article linked above.

**Comment by ReneMeier** [comment]
https://docs.netapp.com/us-en/ontap/nfs-admin/enable-access-windows-nfs-clients-task.html

***@***.***


https://learn.microsoft.com/en-us/windows-server/storage/nfs/nfs-overview

***@***.***

***@***.***

**Comment by netapp-aherbin** [comment]
@ReneMeier please be more specific about the update you are requesting.  What block?
