### ISSUE TITLE
It's not clear why there are two sets of steps on this page

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#90]
Page: [Recover deleted volumes](https://docs.netapp.com/us-en/ontap/task_admin_recover_deleted_volumes.html)

**Comment by netapp-aherbin** [comment]
Ben, thank you for your feedback. I've reached out to the writer of this topic and will post an update soon.

**Comment by netapp-forry** [comment]
Issue addressed earlier per commit comment.
