### ISSUE TITLE
MAV for snapshot locking 

### ISSUE THREAD

**Issue by assefasam** [NetAppDocs/ontap#901]
Page: [Lock a Snapshot copy for protection against ransomware attacks](https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html)

One of our clients would like to know if MAV can be implemented when snapshot locking is turned on to avoid someone accidentally locking snapshots for a long time.  Perhaps some limit on how far in the future a snapshot can be locked.  As an example, if someone is locking a snapshot for more than a year, it requires a secondary admin to sign off on it.

Is there something like that available for this feature.

**Comment by netapp-lenida** [comment]
Hi Samuel, I'll send you a separate email. Thanks

**Comment by netapp-lenida** [comment]
Replied over offline email.
