### ISSUE TITLE
Incorrect link for TRs

### ISSUE THREAD

**Issue by louvipi** [NetAppDocs/ontap#902]
Page: [Antivirus configuration overview](https://docs.netapp.com/us-en/ontap/antivirus/index.html)

Links to TRs are not working, page not found.
https://www.netapp.com/us/media/tr-4304.pdf
and
http://www.netapp.com/us/media/tr-4312.pdf  (The one I really care about).

Does anyone "own" these TR's these days?  These TR's really need an update.  Version 1.0.5 (and really 1.0.6) of the ONTAP AV Connector is out, and we know use REST API's instead of ZAPI calls.

Feel free to message me internally on Teams.

**Comment by louvipi** [comment]
John Gartrell

**Comment by netapp-aherbin** [comment]
@louvipi I just sent you an email.  We can work from there and I'll update the issue once things are resolved.

**Comment by netapp-aherbin** [comment]
The links to both TRs are resolving.  Thank you for your feedback.  I'll follow up on the email thread regarding TR update/ownership.
