### ISSUE TITLE
Please update the 'direct' method message

### ISSUE THREAD

**Issue by pascaldewild** [NetAppDocs/ontap#903]
Page: [What version of ONTAP can I upgrade to?](https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html)

At this moment, it states under the 'Note' in the direct description, you can upgrade 'by three versions' beginning with 9.11.1... However, the table underneath suggests/shows you can do a direct upgrade from 9.8 -> 9.12.1, which would allow you to upgrade 'four versions'. 

Please verify this is actually the case, and if so, please update the 'Note' underneath the Direct upgrade path...

>> Note: Beginning with ONTAP 9.11.1, software images support upgrading directly to releases that are three releases higher than the running release. For example, you can use the direct upgrade path from 9.8 to 9.11.1.

**Comment by netapp-aherbin** [comment]
Thank you for the feedback.  We will address this as soon as possible.

**Comment by netapp-aherbin** [comment]
Yes direct upgrade from 9.8 to 9.12.1 is valid, allowing four versions.  We've updated the note.
