### ISSUE TITLE
Notes are incorrectly formatted

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#91]
Page: [Search, filter, and sort any object or operation](https://docs.netapp.com/us-en/ontap/task_admin_search_filter_sort.html)

Page: [Secure client access with Kerberos](https://docs.netapp.com/us-en/ontap/task_nas_secure_client_access_with_kerberos.html)

Page: [Clone volumes and LUNs for testing](https://docs.netapp.com/us-en/ontap/task_admin_clone_data.html)

See the Contributor's Guide for details: https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html

**Comment by netapp-aherbin** [comment]
Ben, thanks for your feedback.  The formatting for the notes has been corrected.
