### ISSUE TITLE
why is the content after the graphic in a single-cell table?

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/ontap#911]
Page: [ONTAP platforms](https://docs.netapp.com/us-en/ontap/concepts/introducing-data-management-software-concept.html)

**Comment by netapp-aherbin** [comment]
@ntap-bmegan I can see no reason why it was coded this way.  I'll update in my next hot-fix.

Amanda

**Comment by netapp-aherbin** [comment]
Updated posted.
