### ISSUE TITLE
Add note about minimum schdules

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#912]
Page: [Create a replication job schedule](https://docs.netapp.com/us-en/ontap/data-protection/create-replication-job-schedule-task.html)

Can we please add a note to this page about the minimum supported schedules for volume SnapMirror?
e.g.:
Note: The minimum supported schedule (RPO) for FlexVol volumes in a volume SnapMirror relationship is 5 minutes. The minimum supported schedule (RPO) for FlexGroup volumes in a volume SnapMirror relationship is 30 minutes.

Note that I'm also submitting an issue for SVMDR separately. This page is under volume replication so I feel we should only mention those limits here and the SVMDR limits on that page.

**Comment by netapp-lenida** [comment]
Thanks Joey, the note has been added.
