### ISSUE TITLE
Add minimum supported schedules to step 3

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#913]
Page: [Replicate an entire SVM configuration](https://docs.netapp.com/us-en/ontap/data-protection/replicate-entire-svm-config-task.html)

Can we please add a note to this page about the minimum supported schedules for SVM SnapMirror? This would fit in step 3. E.g.:

Note: The minimum supported schedule (RPO) for FlexVol volumes in an SVM SnapMirror relationship is 15 minutes. The minimum supported schedule (RPO) for FlexGroup volumes in an SVM SnapMirror relationship is 30 minutes.

Thanks!

**Comment by netapp-joey** [comment]
Because of the way the documentation is organized, we will also need this note on the following page's Step 3:
https://docs.netapp.com/us-en/ontap/data-protection/exclude-lifs-svm-replication-task.html
https://docs.netapp.com/us-en/ontap/data-protection/exclude-network-name-service-svm-replication-task.html

Thanks for the help

**Comment by netapp-lenida** [comment]
Thanks, Joey. I'll update the documentation as soon as possible.

**Comment by netapp-lenida** [comment]
The three topics have been updated.
