### ISSUE TITLE
procedures to enable access to the repositories missing for RHEL 9

### ISSUE THREAD

**Issue by nlsntap** [NetAppDocs/ontap#914]
Page: [Enable access to the repositories](https://docs.netapp.com/us-en/ontap/mediator/enable-access-repos-task.html)

Now that Mediator is supported with RHEL 9, the  procedures to enable access to the repositories needs to be added for RHEL 9, too.

**Comment by netapp-thomi** [comment]
Hello nlsntap,
Thank you for your suggestion.   The information has been included in an updated topic on the repository:
https://docs.netapp.com/us-en/ontap/mediator/enable-access-repos-task.html

Thanks for helping us keep the ONTAP documentation updated and accurate.

Thom
