### ISSUE TITLE
verbage change regarding when lookups would be case-sensitive

### ISSUE THREAD

**Issue by tkapla** [NetAppDocs/ontap#915]
Page: [Case-sensitivity of file and directory names in a multiprotocol environment](https://docs.netapp.com/us-en/ontap/nfs-admin/case-sensitivity-file-directory-multiprotocol-concept.html)

current statement: If you have enabled or modified character mapping using the Vserver CIFS character-mapping commands, a normally case-insensitive Windows lookup becomes case-sensitive.

recommended statement: If a character mapping has been created using the Vserver CIFS character-mapping commands, a Windows lookup that would normally be case-insensitive can become case-sensitive. This means that filename lookups will only be case-sensitive if the character mapping has been created and the filename is using that character mapping.

**Comment by tkapla** [comment]
Hello, is there any update on this request

**Comment by netapp-mdavidson** [comment]
Hi @tkapla - the note for case sensitivity has been updated on this page. Closing ticket out.
