### ISSUE TITLE
remove snaplock

### ISSUE THREAD

**Issue by saschape** [NetAppDocs/ontap#917]
Page: [Cloud WORM storage](https://docs.netapp.com/us-en/ontap/cloud/snaplock-worm-storage-concept.html)

remove the name snaplock from the link and the title on the left.
add explanation how privilege delete works with "Cloud WORM storage"

**Comment by saschape** [comment]
Thanks...one more thing:
Most of the German Customers require that WORM Technology is certified by KPMG.
https://kpmg.com/de/en/home.html

Because of the new Naming, "Cloud Worm Storage" looks like a "new" product for KPMG and does not have this certification. So here is the question... Can we link "Cloud Worm Storage" to the "Snaplock" Technology in the official Documentation? is that sufficient for KPMG?
...or do we need an additional KPMG certification anyway?

Thanks
Sascha

With kind regards

Sascha Petrovski
Azure Cloud Solutions Architect
Mobile: +49 151 120 55 921
Email: sascha.petrovski@netapp.com

**Comment by netapp-lenida** [comment]
Topic and sidebar have been updated. Sascha, please reply to the email I sent you earlier if you have any other issues. Closing this issue.
