### ISSUE TITLE
Add a new page to ONTAP S3 documents

### ISSUE THREAD

**Issue by harshitmarwah1** [NetAppDocs/ontap#919]
Page: [S3 object storage management](https://docs.netapp.com/us-en/ontap/object-storage-management/index.html)

Hello Team,

I'm from product team for ONTAP S3 and would like to add new page to docs.metapp.com w.r.t. compatible 3rd party application which supports object storage.

**Comment by netapp-aherbin** [comment]
Moving to internal Jira issue (1048) for discussion and tracking.  Inlcuded @harshitmarwah1 on issue for questions/updates.
