### ISSUE TITLE
Unified replication relationships table

### ISSUE THREAD

**Issue by pdiddens** [NetAppDocs/ontap#921]
Page: [Compatible ONTAP versions for SnapMirror relationships](https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html)

It would be easier to read if unified replication relationships were shown bi-directional in the table itself. The hint how to read the table can easily be missed.

**Comment by netapp-lenida** [comment]
This was fixed.
