### ISSUE TITLE
"Supported features" table has an error on the "SMB protocol" row

### ISSUE THREAD

**Issue by jshoucair** [NetAppDocs/ontap#925]
Page: [SVM data mobility overview](https://docs.netapp.com/us-en/ontap/svm-migrate/index.html)

I believe "SMB Protocol" is intended to be it's own row, but begins in the "Additional information" column of the "NFS v4.0" row.

**Comment by netapp-lenida** [comment]
Thanks for letting us know. I'll make sure this is fixed.

**Comment by netapp-lenida** [comment]
Thanks again for bringing this to our attention. The table has been fixed.
