### ISSUE TITLE
This Page is not updated for quite some releases and it needs to be fixed.

### ISSUE THREAD

**Issue by jaintap** [NetAppDocs/ontap#926]
Page: [Considerations for FC-NVMe configurations](https://docs.netapp.com/us-en/ontap/san-config/fc-nvme-config-concept.html)

Supported configurations:

NVMe is supported on AFF platforms that have 32G FC ports --> NVMe is Supported on AFF,ASA and C Series Platforms that have 32G FC Ports

You can set up your FC-NVMe configuration with single nodes or HA pairs using a single fabric or multifabric.

NVMe is supported on 4-node clusters or smaller. --> NVMe is supported cluster upto 12node.

NVMe can be the only data protocol on the storage virtual machine (SVM) --> This needs to be remvoed.

Up to 8 NVMe SVMs are supported per cluster. --> There is no such restriction now and it is removed.

FC-NVMe can be the only data protocol on data LIFs.

LUNs and namespaces cannot be mixed on the same volume. --> This restriction is no longer there.

You should configure one management LIF for every SVM supporting SAN.

The use of heterogeneous FC switch fabrics is not supported, except in the case of embedded blade switches.

Specific exceptions are listed on the [NetApp Interoperability Matrix Tool](https://mysupport.netapp.com/matrix).

Cascade, partial mesh, full mesh, core-edge, and director fabrics are all industry-standard methods of connecting FC switches to a fabric, and all are supported.

A fabric can consist of one or multiple switches, and the storage controllers can be connected to multiple switches.
=====

**Comment by netapp-aherbin** [comment]
Moving this to internal tracking (ontapdoc 1109) while awaiting response for additional information from @jaintap
