### ISSUE TITLE
Replace Symantec TR link with the Symantec Documentation Link shared in description. 

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#929]
Page: [Antivirus configuration overview](https://docs.netapp.com/us-en/ontap/antivirus/index.html)
Replace [NetApp Technical Report 4304: Antivirus Solution for Clustered Data ONTAP Symantec](http://www.netapp.com/us/media/tr-4304.pdf) link with the following link that redirects customers to Symantec website:
https://techdocs.broadcom.com/us/en/symantec-security-software/endpoint-security-and-management/symantec-protection-engine/9-0-0.html)

**Comment by netapp-aherbin** [comment]
Hi Nikhita,

I'll get this updated.

Amanda

**Comment by netapp-aherbin** [comment]
The update is posted.  Thank you.
