### ISSUE TITLE
Requirement: "All nodes in the source cluster must be running the same ONTAP version"

### ISSUE THREAD

**Issue by ChristopherRegerNetApp** [NetAppDocs/ontap#932]
Page: [SVM data mobility overview](https://docs.netapp.com/us-en/ontap/svm-migrate/index.html)

Currently the document says this about the source:

"All nodes in the source cluster must be running the same ONTAP version"

This is also true for the destination cluster. Without specifying both source and destination, it looks like destination cluster could be in a mixed cluster mode

**Comment by netapp-aherbin** [comment]
Hi @ChristopherRegerNetApp, I received your PR for this change as will.  Update is in progress.

Thanks,
Amanda

**Comment by ChristopherRegerNetApp** [comment]
You're welcome! Thank you for the quick response!
