### ISSUE TITLE
arw options for node vserver?

### ISSUE THREAD

**Issue by basola55** [NetAppDocs/ontap#934]
### Page URL

https://docs.netapp.com/us-en/ontap/anti-ransomware/modify-automatic-shapshot-options-task.html

### Page title

Modify options for automatic Snapshot copies

### Summary

we tried to customize the options on a cifs vserver. this did not work. we found out that these options are only available on the node vservers. can you please add a note to the doc that these options can only be customized on node vservers!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @basola55 . The documentation has been updated
