### ISSUE TITLE
Review statements about Tamper-proof Audit Logging

### ISSUE THREAD

**Issue by jasondkessler** [NetAppDocs/ontap#935]
### Page URL

https://docs.netapp.com/us-en/ontap/system-admin/ontap-implements-audit-logging-concept.html

### Page title

How ONTAP implements audit logging

### Summary

I believe the statements about tamper-proof audit logging are incorrect.  Please review and modify as required.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Created Jira (ONTAPDOC-1054) for internal discussion and tracking.  @jasondkessler I've tagged you in the issue.  Moving discussion there.
