### ISSUE TITLE
S3 SnapMirror also for Google Cloud and AWS?

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap#938]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-snapmirror/index.html

### Page title

S3 SnapMirror overview

### Summary

Only Cloud Volumes ONTAP for Azure is explicitly mentioned as a possible target.

Are you sure, that Google Cloud and AWS are not also possibilities, since we CAN configure ONTAP S3 buckets there?
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html#ontap-s3-license-in-google-cloud
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html#ontap-s3-license-in-aws

If it's not possible, I'd appreciate a reason, because I'm teaching this stuff and am asked by my students about it...

Greetings from Vienna

Sebastian

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mdavidson** [comment]
Hi @SPGoetze - the table on this page has been updated with the version support info for Cloud Volumes ONTAP for Azure, AWS, and Google Cloud. Closing this ticket out.
