### ISSUE TITLE
Discrepancy in XDP matrix

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#939]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html

### Page title

Compatible ONTAP versions for SnapMirror relationships

### Summary

![matrix](https://github.com/NetAppDocs/ontap/assets/61209037/a3fc7c8f-5f92-4fe9-94c8-e44e59c6ae0b)

9.11.1 and 9.5 should be a No. In the matrix currently, it's a No in one space but a Yes in another. We should change the Yes to a No.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for catching that error, Joey. I'll fix it ASAP.

**Comment by netapp-lenida** [comment]
The table has been updated.
