### ISSUE TITLE
regarding "How automatic Snapshot copies work when ransomware is detected"

### ISSUE THREAD

**Issue by zhuolin-shen** [NetAppDocs/ontap#940]
### Page URL

https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html

### Page title

Autonomous Ransomware Protection use cases and considerations

### Summary

-----Original Message-----
From: Shen, Zhuolin
Sent: Thursday, May 25, 2023 15:02
To: '[doccomments@netapp.com](mailto:doccomments@netapp.com)' <[doccomments@netapp.com](mailto:doccomments@netapp.com)>
Subject: docs_feedback: https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html#arp-performance-and-frequency-considerations

After the modification on 05/19/2023, this document page deleted the whole contents below.

How automatic Snapshot copies work when ransomware is detected In order to obtain the best possible recovery point, ARP creates an automatic Snapshot copy as soon as it detects abnormal file activity.
However, ARP does not immediately flag an alert; rather, analytics need to run and confirm that the suspicious activity matches a ransomware profile before generating an alert. This process could take up to 60 minutes.
If the analytics determines the activity is not suspicious, then an alert is not generated, but the automatically created Snapshot copy remains present on the file system for a minimum of two days.

Regarding this change, customer has following queries below :
1) what is the reason for deleting this whole paragraph?
2) Does the time lag of "This process could take up to 60 minutes." get changed?

Could you please help to confirm and provided the related information?

Thank you for your cooperation in advance.
Regards,
Zhuolin Shen

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@netapp-ahibbard see the following [commit](https://github.com/NetAppDocs/ontap-internal/commit/4652f15ce864129d4b0d641e8e164bfe7b9c8db9) for reference.

**Comment by netapp-ahibbard** [comment]
Hi @zhuolin-shen - This information was moved to the overview page of the ARP documentation with additional information added about how ARP snapshots work: https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html#threat-assessment-and-arp-snapshots
