### ISSUE TITLE
Example for tamperproof snapshots 

### ISSUE THREAD

**Issue by pdiddens** [NetAppDocs/ontap#941]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/snapshot-lock-concept.html

### Page title

Lock a Snapshot copy for protection against ransomware attacks

### Summary

cluster1> volume snapshot policy create -policy policy_name -enabled true -schedule1 5min -count1 5 -retention-period1 "1 months"

This configuration will result in 288 snapshots per day and will effectively stop working after 1023 snapshots.

Wouldn't it make more sense to have a 25 minutes or 30 minutes retention period and explain the interaction of retention period and snapshot count or rotation.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
The example has been updated as follows:

cluster1> volume snapshot policy create -policy policy_name -enabled true -schedule1 hourly -count1 24 -retention-period1 "1 days"

Closing this issue. Thank you!
