### ISSUE TITLE
Table formatting

### ISSUE THREAD

**Issue by simonhazell** [NetAppDocs/ontap#946]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html

### Page title

Compatible ONTAP versions for SnapMirror relationships

### Summary

It looks like a recent update to this page has affect the table formatting. AT least 3 tables are showing in a non-table format

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
The table formatting has been fixed.  Thank you.
