### ISSUE TITLE
Tables are not diaplayed correctly

### ISSUE THREAD

**Issue by mmmguapo** [NetAppDocs/ontap#948]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html

### Page title

Compatible ONTAP versions for SnapMirror relationships

### Summary

Compatibility Table not readable - please fix.

For SVM DR for SVM migration:* Replication is supported in a single direction from an earlier version of ONTAP to a later version of ONTAP; for example, from ONTAP 9.11.1 to ONTAP 9.12.* The ONTAP version on the target cluster must be no more than 2 versions newer, as shown in the table below.* Replication is not supported for long-term data protection use cases.The asterisk (*) after the release version indicates a cloud-only release.
--

| | 9.3 | 9.4 | 9.5 | 9.6 | 9.7 | 9.8 | 9.9.0* | 9.9.1 | 9.10.0* | 9.10.1 | 9.11.0* | 9.11.1 | 9.12.0* | 9.12.1 | 9.13.0* | 9.13.1 | 9.3 | Yes | Yes | Yes | | | | | | | | | | | | | | 9.4 | | Yes | Yes | Yes | | | | | | | | | | | | | 9.5 | | | Yes | Yes | Yes | | | | | | | | | | | | 9.6 | | | | Yes | Yes | Yes | | | | | | | | | | | 9.7 | | | | | Yes | Yes | Yes | | | | | | | | | | 9.8 | | | | | | Yes | Yes | Yes | | | | | | | | | 9.9.0* | | | | | | | Yes | Yes | Yes | | | | | | | | 9.9.1 | | | | | | | | Yes | Yes | Yes | | | | | | | 9.10.0* | | | | | | | | | Yes | Yes | Yes | | | | | | 9.10.1 | | | | | | | | | | Yes | Yes | Yes | | | | | 9.11.0* | | | | | | | | | | | Yes | Yes | Yes | | | | 9.11.1 | | | | | | | | | | | | Yes | Yes | Yes | | | 9.12.0* | | | | | | | | | | | | | Yes | Yes | Yes | | 9.12.1 | | | | | | | | | | | | | | Yes | Yes | Yes | 9.13.0* | | | | | | | | | | | | | | | Yes | Yes | 9.13.1 | | | | | | | | | | | | | | | | Yes</p></div><br class="Apple-interchange-newline">
</body>
</html>

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Fixed.  Thank you.
