### ISSUE TITLE
Some Array models can fan-out to 16 destinations.

### ISSUE THREAD

**Issue by tansley-netapp** [NetAppDocs/ontap#949]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/limitations-mirror-relationships-concept.html

### Page title

SnapMirror limitations

### Summary

Bullet item "You can fan out to maximum of eight destination volumes..." needs to be updated.
A700 and higher models can support 16 destinations.

Would it makes sense to mention "...up to either 8 or 16 destination, depending on array model. Refer to HWU for model-specific limits."???

Tony Ansley

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for letting me know, Tony. It would definitely help if we add a link to Hardware Universe along with the additional necessary updates. I'll work on this as soon as I can.

**Comment by netapp-lenida** [comment]
Thanks again, Tony. The topic has been updated as follows:

Depending on the array model, you can fan out a maximum of eight or sixteen destination volumes from a single source volume. See the [Hardware Universe](https://hwu.netapp.com/) to learn details for your specific configuration.
