### ISSUE TITLE
Export policies

### ISSUE THREAD

**Issue by JCarberr** [NetAppDocs/ontap#95]
Page: [Manage access using export policies](https://docs.netapp.com/us-en/ontap/task_nas_provision_export_policies.html)

How do you FIND / VIEW / EDIT Export Policies in the new System Manager? (Without first knowing the volume the export is attached to?)

**Comment by netapp-forry** [comment]
James, first my apologies for the ridiculously slow response.
If I'm understanding correctly, you want to use System Manager to see all export policies that are in effect for a given cluster? I believe you can do so, but you do have to first select an NFS-enable Storage VM. Then under the Settings tab, scroll down to the Policies section, where you'll see an Export Policies tile. Is this what you were looking for? If so, I hope this resolves your issue.
If not, please let me know more and I'll follow up with the System Manager Eng team.
Thanks for letting us know.

**Comment by netapp-forry** [comment]
James, please let us know if you have further questions or if this response did not address your issue -- thanks.
