### ISSUE TITLE
Cloud Volumes ONTAP supportability

### ISSUE THREAD

**Issue by pablogarciaarevalo** [NetAppDocs/ontap#953]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-snapmirror/index.html

### Page title

S3 SnapMirror overview

### Summary

Based on my internal conversation with the product manager, Cloud Volumes ONTAP (on AWS, Azure and Google) supports both S3 snapmirror options: Supports active mirrors and takeover and Supports backup and restore

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mdavidson** [comment]
Hi @pablogarciaarevalo - the table on this page has been updated. It now includes the version support info for Cloud Volumes ONTAP for Azure, AWS, and Google Cloud. Closing this ticket.
