### ISSUE TITLE
Request for explicit ONTAP version

### ISSUE THREAD

**Issue by mochizukifumihito** [NetAppDocs/ontap#955]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_considerations_for_snaplock.html

### Page title

Upgrade considerations for SnapLock

### Summary

The customer concerning for this document on their upgrading ONTAP plan.
Would you please specify the kernel version for “if these are qualified as bad SnapLock releases or if SnapLock is disabled in those releases"?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@mochizukifumihito thank you for your inquiry.  This consideration pre-dates all current releases.  There are currently no ONTAP 9 kernel versions that qualify as bad SnapLock releases or in which SnapLock is disabled.   

Therefore we are removing this content and will track future releases to document this in ONTAP 9 if needed.
