### ISSUE TITLE
Clone splitting does not result in data movement. 

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#956]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/split-flexclone-from-parent-task.html

### Page title

Split a FlexClone volume from its parent volume

### Summary

This sentence is incorrect "Splitting a FlexClone volume from its parent volume consumes free space from the containing aggregate." I see there's more clarification later, but the clarification about 9.4 is incorrect as well. 

Splitting a clone does not copy data. Splitting a clone may result in reservation of more space in the aggregate, but there is no data movement as of 9.4. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-thomi** [comment]
The content of the documentation currently reflects the requested changes.  Thanks for helping us keep the documentation accurate and up to date.

**Comment by jfsinmsp** [comment]
This isn't complete yet. The lead is still very incorrect. 

If you want a read-write FlexClone volume to have its own disk space rather than using that of its parent volume, you can split the FlexClone volume from its parent volume. Because this operation creates a copy of the data that is currently shared between the parent volume and the FlexClone volume, the operation can take some time to complete.
