### ISSUE TITLE
Large LUNs and large volumes Section needs to be updated

### ISSUE THREAD

**Issue by Nikhita-13** [NetAppDocs/ontap#958]
### Page URL

https://docs.netapp.com/us-en/ontap/smbc/smbc_plan_prerequisites.html

### Page title

Prerequisites

### Summary

The Large LUNs and large volumes section need to be updated. Starting with, the ONTAP 9.12.1P2 release, Large LUN, and large volume support are available with all platforms not just ASA. Pg 35 https://www.netapp.com/media/10680-tr4080.pdf

**The revised statement I think should be** 

- For ONTAP release 9.12.1 P2 and later, SMBC supports Large LUNs and large volumes greater than 100TB on All SAN Arrays (ASA) and All Flash Array (AFF). 
- For ONTAP releases below 9.12.1 P2 and above ONTAP 9.8, Large LUNs and large volumes greater than 100TB are supported only on All SAN Arrays. 

The warning should now look like this:
For ONTAP Releases 9.12.1P2 and later, You must ensure that both the primary and secondary clusters are either All SAN Arrays or All Flash Array, and that they both have ONTAP 9.12.1 P2 or later installed. If the secondary cluster is running a version earlier than ONTAP 9.12.1P2 or if the Array type is not the same as Primary cluster, the synchronous relationship can go out of sync if the primary volume grows larger than 100 TB.

For Releases below ONTAP 9.12.1P2 and above ONTAP 9.8, You must ensure that both the primary and secondary clusters are All SAN Arrays, and that they both have ONTAP 9.8 or later installed. If the secondary cluster is running a version earlier than ONTAP 9.8 or if it is not an All SAN Array, the synchronous relationship can go out of sync if the primary volume grows larger than 100 TB.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, Nikhita, I'll update the topic ASAP.

**Comment by netapp-ahibbard** [comment]
Thanks @Nikhita-13 . This has been updated.
