### ISSUE TITLE
Missing NVMe/TCP LIF info

### ISSUE THREAD

**Issue by netapp-bingen** [NetAppDocs/ontap#962]
### Page URL

https://docs.netapp.com/us-en/ontap/san-admin/configure-nvme-lif-task.html

### Page title

Configure an NVMe LIF

### Summary

This page only has info for Fibre Channel and is missing steps for NVMe/TCP.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Hi @netapp-bingen 

I'll update the command to include the nvme-tcp option as follows.  I'll also add a note that nvme-tcp is available for 9.10.1 and later.

network interface create -vserver SVM_name -lif LIF_name -role LIF_role -data-protocol {fc-nvme|nvme-tcp}  -home-node home_node -home-port home_port

Sound good? Or do we need anything else?

**Comment by netapp-bingen** [comment]
That should be fine.

**Comment by netapp-bingen** [comment]
I might need to file a separate request, but one other thing is that I can't find anywhere in the docs where we mention that the NVMe/TCP LIFs are listening for discovery on port 8009. Is that something that can be worked in?

**Comment by netapp-aherbin** [comment]
No need to file a separate request.  I'll work on it.

**Comment by netapp-aherbin** [comment]
@netapp-bingen I've also updated the topic to indicate that:

After creation, NVMe/TCP LIFs listen for discovery on port 8009.

Let me know if anything else is needed.

Amanda
