### ISSUE TITLE
Clarify ONTAP Version mixing support

### ISSUE THREAD

**Issue by ace-en** [NetAppDocs/ontap#963]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

### Page title

What version of ONTAP can I upgrade to?

### Summary

This matrix is also used for determining which versions of ONTAP can be mixed in the same cluster for migration purposes. Can we add some documentation to this page to explain this?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@ace-en are you internal to NetApp?

**Comment by ace-en** [comment]
I am!

Keith Aasen
Sr. Manager, ONTAP Customer Product Management
Customer Communications

NetApp
250-217-2996 Direct Phone
***@***.******@***.***>

[signature_4239528745]


***@***.***<https://www.facebook.com/NetApp>   ***@***.*** <https://www.instagram.com/netapp/>    ***@***.*** <https://www.youtube.com/netapp>    ***@***.*** <https://www.linkedin.com/company/netapp/>    ***@***.*** <https://twitter.com/NetApp>




From: Amanda Stroman ***@***.***>
Date: Wednesday, June 14, 2023 at 12:20 PM
To: NetAppDocs/ontap ***@***.***>
Cc: Aasen, Keith ***@***.***>, Mention ***@***.***>
Subject: Re: [NetAppDocs/ontap] Clarify ONTAP Version mixing support (Issue #963)
NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.



@ace-en<https://github.com/ace-en> are you internal to NetApp?

**Comment by netapp-aherbin** [comment]
Great...moving to internal discussion.
