### ISSUE TITLE
Large LUN support

### ISSUE THREAD

**Issue by simonhazell** [NetAppDocs/ontap#967]
### Page URL

https://docs.netapp.com/us-en/ontap/san-admin/resize-lun-task.html

### Page title

Resize a LUN

### Summary

Hi. Shouldn't this be updated to reflect large LUN support in 9.12.1P2 for FAS and AFF not just ASA (see the ONTAP release notes)
And also the last section has a reference to SnapDrive for Windows. This should really SnapCenter (assuming its has this capability) which i think is does

Thanks
Simmon

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Updated.  Thank you.
