### ISSUE TITLE
Add ONTAP 9.12.1 revert path

### ISSUE THREAD

**Issue by gmogil** [NetAppDocs/ontap#968]
### Page URL

https://docs.netapp.com/us-en/ontap/revert/concept_revert_paths.html

### Page title

Revert paths

### Summary

Hi Team,

Could you please add 9.12.1 to the revert path table?

Thank you!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
The revert paths have been added.  Thank you.
