### ISSUE TITLE
Sidebar title doesn't match the scope of the page

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#972]
### Page URL

https://docs.netapp.com/us-en/ontap/encryption-at-rest/manage-keys-azure-google-task.html

### Page title

Manage keys with a cloud provider

### Summary

The sidebar title for this page is "Manage keys with Azure or Google Cloud key managements services" but the page also covers AWS. I would suggest updating the sidebar title to match the page title: "Manage keys with a cloud provider"

![image](https://github.com/NetAppDocs/ontap/assets/18287750/40765858-cd4c-4c78-9e4c-6fd13dc1887e)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Updated.  Thanks!
