### ISSUE TITLE
The documentation about unsupported features for FlexCache is missing additional information and I don't understand what "No" means.

### ISSUE THREAD

**Issue by kanitani** [NetAppDocs/ontap#979]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/supported-unsupported-features-concept.html

### Page title

Supported and unsupported features for FlexCache volumes

### Summary

![image](https://github.com/NetAppDocs/ontap/assets/68621663/b951f752-3671-476e-90ed-7d07b55fb5a4)

It is described that FlexCache volumes do not support Qtree and Quotas.
However, this description is inaccurate, so please be more specific about not supporting it.

Example:
a) Qtrees configured at origin volume cannot be accessed via FlexCache volume.
b) If you create Qtrees on the origin side, that information is reflected in the cache volume and can be accessed, but you cannot create Qtrees from the cache side.

Could you add an explanation for Quota as well?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kanitani** [comment]
Regarding the quota, for reference, when I set a capacity hard limit on the origin side, even if I accessed the volume via FlexCache volume, it was not possible to write more data than the hard limit.

**Comment by netapp-lenida** [comment]
Thanks @kanitani. I'll check with the FlexCache group to get the appropriate descriptions.

**Comment by netapp-lenida** [comment]
Thanks again. The descriptions for quotas and qtrees have been updated.

**Comment by kanitani** [comment]
Lenida,

It is not changed for Quota.
![image](https://github.com/NetAppDocs/ontap/assets/68621663/5e84ebb4-8954-470d-b47f-21ab3857d989)

Please write it correctly.
