### ISSUE TITLE
Prerequisites for cluster peering missing Cipher requirement

### ISSUE THREAD

**Issue by kdcherif** [NetAppDocs/ontap#980]
### Page URL

https://docs.netapp.com/us-en/ontap/peering/prerequisites-cluster-peering-reference.html

### Page title

Prerequisites for cluster peering

### Summary

Starting with ONTAP 9.6, cluster peer encryption provides TLS 1.2 AES-256 GCM encryption support for data replication.
"PSK-AES256-GCM-SHA384" security ciphers are required for cluster peering to work even if encryption is disabled.  

The above information should be included in this page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ahibbard** [comment]
Thanks @kdcherif . We've published this update.
