### ISSUE TITLE
Regarding the command -> cluster2::> snapmirror show -expand

### ISSUE THREAD

**Issue by omriok** [NetAppDocs/ontap#981]
### Page URL

https://docs.netapp.com/us-en/ontap/flexgroup/monitor-snapmirror-data-transfers-task.html

### Page title

Monitor SnapMirror data transfers for FlexGroup volumes

### Summary

The command "snapmirror show -expand" will be effective when running via diagnostic privilege.

 cluster2::> set diag
 cluster2::*> snapmirror show -expand

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for contacting us, Omri. I have sent you a reply in email.

**Comment by netapp-lenida** [comment]
Closing this issue and tracking internally.
