### ISSUE TITLE
Add schedule caveat to section about asynchronous SnapMirror

### ISSUE THREAD

**Issue by netapp-joey** [NetAppDocs/ontap#982]
### Page URL

https://docs.netapp.com/us-en/ontap/consistency-groups/protect-task.html

### Page title

Protect a consistency group

### Summary

Under "Configure asynchronous SnapMirror protection" and the sub-section "Steps", we should add a note about the minimum supported schedule (30min) for step 4.

Something like:
"
System Manager auto-fills source-side information. Select the appropriate cluster and storage VM for the destination. Select a protection policy. Ensure that Initialize relationship is checked.

When selecting an asynchronous policy, you have the option to Override Transfer Schedule.

Note: The minimum supported schedule (RPO) for consistency groups with asynchronous SnapMirror is 30 minutes.
"
Thanks!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, Joey. I'll look into this.

**Comment by netapp-lenida** [comment]
The topic has been updated.
