### ISSUE TITLE
volume flexcache connection-status show

### ISSUE THREAD

**Issue by simonhazell** [NetAppDocs/ontap#983]
### Page URL

https://docs.netapp.com/us-en/ontap/flexcache/view-connection-status-origin-task.html

### Page title

View the connection status of a FlexCache relationship

### Summary

Hi - i think this is a diag command. Well, it is in 9.11.1 when i tried it in LOD
Thanks
Simon

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks Simon. I'll look into this.

**Comment by netapp-lenida** [comment]
Since we do not document diag commands, the topic has been removed.

**Comment by simonhazell** [comment]
It would be useful for someone to document this command in a KB article. Its a very useful command and helped me in my first flexcache project
