### ISSUE TITLE
Provide information on how to disable UEFI secure boot if the customer does not need it enabled per security policy

### ISSUE THREAD

**Issue by netapp-adlove** [NetAppDocs/ontap#984]
### Page URL

https://docs.netapp.com/us-en/ontap/mediator/install-mediator-pkg-task.html

### Page title

Install the ONTAP Mediator installation package

### Summary

Hello Docs team,

I would like to bring your attention to 2 issues on this docs page.

The information as provided in the docs is applicable and is valid, however it goes about providing instructions that not every customer will need nor want to implement, as an easier option exists. The easiest way to install the ONTAP mediator on a UEFI secure boot enabled linux VM or physical machine is to just disable the secure boot setting on the VM/machine side. With it disabled, there is no need to configure the mediator and SCST to work with UEFI secure boot. Please either link to the following KB, or provide users/customers information within the docs page itself that tells customers how to disable UEFI on their respective system.

https://kb.netapp.com/onprem/ontap/metrocluster/MEDIATOR_installation_failed_to_start_the_service

Solution
Go to the Physical machine BIOS setting and disable "UEFI SecureBoot"
Disable the "Safe Start" (vSphere 6.x) or "Secure Boot" (vSphere 7.x) option in the VMWare settings for the VM

---

Secondly, given that the UEFI setting can be a showstopper for installation, I recommend putting the information about UEFI within the steps itself in the docs page. Both a NetApp PS installer and I missed the information about UEFI on the page because it is not a part of the steps. 

When the information is in the steps section, it illustrates that the information provided is needed in some fashion for a successful installation. Currently it is in the "About this task" section, which does not properly illustrate the full importance of the UEFI secure boot setting notice. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-thomi** [comment]
The work for this issue is being tracked in ONTAPDOC-1165

**Comment by netapp-thomi** [comment]
It is not recommended to disable the security of a system to make the installation simpler.  However, we are examining the procedure to determine how to improve the flow of the steps and include information as you suggested in part 2 of your comment.

**Comment by netapp-thomi** [comment]
Hi netapp-adlove.   Thank you for bringing this issue to our attention.  The changes you recommended have been made to the topics.
