### ISSUE TITLE
Does SVM DR really  be supported when source SVMs containing S3 NAS buckets ?

### ISSUE THREAD

**Issue by yanw113** [NetAppDocs/ontap#986]
### Page URL

https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html

### Page title

S3 multiprotocol overview

### Summary

I have a question about “you can replicate source SVMs containing S3 NAS buckets using SVM DR”,  according to my lab testing result, only volume snapmirror is supported rather than SVM DR if source SVMs containing S3 NAS buckets.

Could someone or a team double-confirm it?  Is the following description accurate?

Data protection for S3 NAS buckets
S3 NAS “buckets” are simply mappings of NAS data for S3 clients, they are not standard S3 buckets. Therefore, there is no need to protect S3 NAS buckets using NetApp S3 SnapMirror functionality. Instead, **you can replicate source SVMs containing S3 NAS buckets using SVM DR,** a standard SnapMirror data protection relationship with destination SVMs. SVM DR is the only supported SnapMirror replication method with S3 multiprotocol. SnapMirror Synchronous is not supported.

Below is my lab info and test result, for your reference:

Src:
cluster1::> version
NetApp Release Yellowdog__9.12.1: Tue Jan 31 19:19:43 UTC 2023
cluster1::> bucket show -vserver yanw
  (vserver object-store-server bucket show)
Vserver     Bucket          Type     Volume            Size       Encryption Role       NAS Path
----------- --------------- -------- ----------------- ---------- ---------- ---------- ----------
yanw        bucket1         nas      nasvol            -          false      -          /nasvol

Dest:

cluster2::> version
NetApp Release Yellowdog__9.12.1: Tue Jan 31 19:19:43 UTC 2023
cluster2::> snapmirror create -source-path yanw: -destination-path yanw_dr:
Error: command failed: A Vserver DR relationship between Vserver "yanw" and
       Vserver "yanw_dr" is not supported because Vserver"yanw" contains either
       an object store server, object store policy, object store user or object
       store bucket.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, Yan. I have confirmed that you can use asynchronous SnapMirror, but SVM DR is not supported, I will update the topic.

**Comment by netapp-lenida** [comment]
Thanks, Yan. I have confirmed that you can use asynchronous SnapMirror, but SVM DR is not supported, The topic has been updated.
