### ISSUE TITLE
Warning for Bug 1455547 "Upgrade from ONTAP 9.8 to 9.10.1 fails on FAS2750, FAS500f, AFF A220, or AFF A250 MetroCluster systems"

### ISSUE THREAD

**Issue by amadorloureiro** [NetAppDocs/ontap#988]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html

### Page title

What version of ONTAP can I upgrade to?

### Summary

Should this https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1455547 be mentioned as an exception and warning for the particular update mentined here? 

More information at https://kb.netapp.com/onprem/ontap/metrocluster/Node_stuck_in_%22Waiting_for_reservations_to_clear%22_during_upgrade

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Hi @amadorloureiro the ANDU upgrade path for 9.8 to 9.10.1 already has a note that MCC IP on the platforms mentioned cannot perform a direct upgrade.  These platforms must upgrade to 9.9.1 first then to 9.10.1.  

I will add this same note to the Manual paths as well.

**Comment by netapp-aherbin** [comment]
The note has also been added to the manual paths.
