### ISSUE TITLE
Version warnings and evidently we're translating documentation into English?

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#989]
### Page URL

https://docs.netapp.com/us-en/ontap/smbc/index.html

### Page title

Overview

### Summary

I'm getting warnings as shown below plastered all over various documentation links.

A newer release of this product is available.
English is provided using machine translation for your convenience. English precedes English for any inconsistencies.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
@jfsinmsp I think this issue has been resolved.  Please take a look from your browser and let us know if you are still seeing the message.

**Comment by ntap-bmegan** [comment]
This has been corrected.
