### ISSUE TITLE
default != enabled

### ISSUE THREAD

**Issue by jfsinmsp** [NetAppDocs/ontap#990]
### Page URL

https://docs.netapp.com/us-en/ontap/volumes/set-efficiency-mode-task.html

### Page title

Set storage efficiency mode during volume creation

### Summary

This page is entitled "Create a new volume with efficiency mode enabled" and then it instructs the user to set efficiency to default. Shouldn't it be set to 'efficient'?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks for letting us know the topic was confusing. I've reworded the information in this topic to make it clearer.
