### ISSUE TITLE
Snapmirror ports

### ISSUE THREAD

**Issue by kholger** [NetAppDocs/ontap#991]
### Page URL

https://docs.netapp.com/us-en/ontap/peering/prerequisites-cluster-peering-reference.html

### Page title

Prerequisites for cluster peering

### Summary

Hi,

Is it correct that port 10000/TCP and ICMP is required for snapmirror?
I've done multiple migrations just with 11104-11105/TCP open between IC LIFs, where all other ports and ICMP was blocked.

Afaik, 10000/TCP is used for NDMP.

Thx

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @nikhilamn, thank you for bringing this to our attention. I'll investigate and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @kholger, thanks again for your feedback. I've verified that we can remove port 10000 and have updated the documentation accordingly.
