### ISSUE TITLE
list unsupported config changes

### ISSUE THREAD

**Issue by sabarig84** [NetAppDocs/ontap#992]
### Page URL

https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html

### Page title

Mixed version ONTAP clusters

### Summary

While the cluster is in a mixed version state, you should not **enter any commands that alter the cluster operation or configuration except as necessary to satisfy the upgrade requirements**. To facilitate controller upgrade activities, volume move operations while in a mixed version ONTAP cluster are supported.

is it possible to call out some of those config changes or commands so one can take caution? the line seems to be very generic ....

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
We've added examples for additional clarification.
