### ISSUE TITLE
LSM information is not consistent between this document and Best practices document

### ISSUE THREAD

**Issue by josevtome** [NetAppDocs/ontap#993]
### Page URL

https://docs.netapp.com/us-en/ontap/data-protection/create-load-sharing-mirror-task.html

### Page title

Create and initializing load-sharing mirror relationships

### Summary

For the creation of the LSM, this document states that: "For a two-node cluster, you should create the LSM on the partner of the node with the SVM root volume."

In the TR-4015 - SnapMirror Best Practices, it states that LSM is not suitable for single HA clusters, and it should be configured for multiple HA pair clusters, configuring the LSM between the node with the root volume and another node from a different HA pair.

My customer provided feedback that this is confusing as both documents state something different. Can this information be validated and corrected wherever it makes more sense?

Appreciate any feedback.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
Thanks, Jose. I'll look into this as soon as I can.

**Comment by netapp-lenida** [comment]
I can't find the text you mentioned from TR-4015 https://www.netapp.com/pdf.html?item=/media/17229-tr4015.pdf, but one of the TMEs is checking into it.

**Comment by netapp-lenida** [comment]
The documentation has been updated to match the TR. Thanks for your feedback and your patience!
