### ISSUE TITLE
A FlexGroup volume contains a FabricPool configuration is supported with ONTAP 9.12.1 or later

### ISSUE THREAD

**Issue by zhuolin-shen** [NetAppDocs/ontap#995]
### Page URL

https://docs.netapp.com/us-en/ontap/flexgroup/create-svm-disaster-recovery-relationship-task.html

### Page title

Create an SVM disaster recovery relationship for FlexGroup volumes

### Summary

The same info below should be reflected in DP section, however, the current page keeps the old info of releases earlier than ONTAP 9.12.1
=====
https://docs.netapp.com/us-en/ontap/flexgroup/supported-unsupported-config-concept.html#features-supported-beginning-with-ontap-9-13-1

FabricPool, FlexGroup, and SVM DR working in conjunction. (In releases earlier than ONTAP 9.12.1, any two of these features worked together, but not all three in conjunction.)  <-----------

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
The topic has been updated. Thanks again for your feedback.
