### ISSUE TITLE
Remove hyphen in step 8.

### ISSUE THREAD

**Issue by netapp-norbertt** [NetAppDocs/ontap#996]
### Page URL

https://docs.netapp.com/us-en/ontap/smb-admin/configure-storage-level-access-guard-task.html

### Page title

Configure Storage-Level Access Guard

### Summary

Currently the step 8 contains:

    vserver security file-directory policy-task add

correct one is:

    vserver security file-directory policy task add

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aherbin** [comment]
Updated.  Thank you.
