### ISSUE TITLE
This page doesn't show up in the sidebar

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/ontap#997]
### Page URL

https://docs.netapp.com/us-en/ontap/snaplock/implement-privileged-delete-functionality-task.html

### Page title

Delete Enterprise-mode WORM files

### Summary

I was googling and stumbled on this page. It doesn't show up in the sidebar.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-lenida** [comment]
This topic is no longer needed because it is now located here:
 https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html#delete-enterprise-mode-worm-files
 I apparently missed it when I reorganized the content a few months ago, so I'll remove it. Thanks for letting me know!

**Comment by netapp-lenida** [comment]
The topic has been removed and will now redirect to the new location.
