### ISSUE TITLE
Deprecation of TLS 1.0 & 1.1 does not appear listed in ONTAP 9.12 release notes

### ISSUE THREAD

**Issue by cwaltham** [NetAppDocs/ontap#999]
### Page URL

https://docs.netapp.com/us-en/ontap/release-notes.html

### Page title

ONTAP release notes

### Summary

As the title suggests, it appears that TLS versions 1.0 and 1.1 have been removed from ONTAP 9.12.1 (and possibly 9.12.0, although I don't have the ability to test that version). I've looked through the "big" release notes[1] and I can't find any mentions of older versions of TLS being removed.

Thanks,

Chris
Sr. Product Manager, FSx for NetApp ONTAP

[1] https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-ehoffman** [comment]
@cwaltham , thank you for reaching out on this. We've checked internally and plan to add the following to the ONTAP Release Notes. In summary, these versions of TLS are disabled by default, but can be enabled by admininstrators.


ONTAP 9.8 - TLS 1.0 disabled by default	TLS 1.0 is disabled by default for new installations of ONTAP.  

Systems that are upgraded to ONTAP 9.8 and later that already have TLS 1.0 enabled are not affected as the upgrade will leave TLS 1.0 in an enabled state. When disabled by default, TLS 1.0 can be manually enabled as needed.	 

ONTAP 9.12.0 - TLS 1.1 disabled by default	TLS 1.1 is disabled by default for new installations of ONTAP.  

Systems that are upgraded to ONTAP 9.12.0 and later that already have TLS 1.1 enabled are not affected as the upgrade will leave TLS 1.1 in an enabled state.  When disabled by default, TLS 1.1 can be manually enabled as needed.

**Comment by netapp-ehoffman** [comment]
Updates published to ONTAP Release Notes 14 July 2023.
